import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// TRULY FINAL kanji batch - THE LAST ONE to exceed 2000 kanji
// Need 65+ more unique kanji - focusing on less common but useful ones

const kanjiData = [
  {
    character: "穫",
    meaningsFr: ["récolte", "moisson"],
    readingsOn: ["カク"],
    readingsKun: [],
    meaningMnemonicFr: "Le grain 禾 qu'on capture 蒦 est la RÉCOLTE.",
    readingMnemonicFr: "KAKU - La moisson abondante.",
    levelId: 49,
  },
  {
    character: "端",
    meaningsFr: ["bout", "extrémité"],
    readingsOn: ["タン"],
    readingsKun: ["はし", "はた"],
    meaningMnemonicFr: "Le debout 立 avec la montagne 山 et le champ 田 est le BOUT.",
    readingMnemonicFr: "TAN - L'extrémité finale.",
    levelId: 45,
  },
  {
    character: "竜",
    meaningsFr: ["dragon"],
    readingsOn: ["リュウ"],
    readingsKun: ["たつ"],
    meaningMnemonicFr: "Le debout 立 avec le mois 月 et l'électricité forme le DRAGON.",
    readingMnemonicFr: "RYŪ - Le dragon légendaire.",
    levelId: 44,
  },
  {
    character: "粋",
    meaningsFr: ["élégance", "raffiné"],
    readingsOn: ["スイ"],
    readingsKun: ["いき"],
    meaningMnemonicFr: "Le riz 米 avec neuf 卒 est ÉLÉGANT.",
    readingMnemonicFr: "SUI - L'élégance japonaise.",
    levelId: 48,
  },
  {
    character: "粗",
    meaningsFr: ["grossier", "brut"],
    readingsOn: ["ソ"],
    readingsKun: ["あら.い"],
    meaningMnemonicFr: "Le riz 米 avec l'ancêtre 且 est GROSSIER.",
    readingMnemonicFr: "SO - La texture brute.",
    levelId: 46,
  },
  {
    character: "粘",
    meaningsFr: ["collant", "visqueux"],
    readingsOn: ["ネン"],
    readingsKun: ["ねば.る"],
    meaningMnemonicFr: "Le riz 米 qui prédit 占 est COLLANT.",
    readingMnemonicFr: "NEN - La texture visqueuse.",
    levelId: 47,
  },
  {
    character: "糧",
    meaningsFr: ["provisions", "nourriture"],
    readingsOn: ["リョウ", "ロウ"],
    readingsKun: ["かて"],
    meaningMnemonicFr: "Le riz 米 en quantité 量 forme les PROVISIONS.",
    readingMnemonicFr: "RYŌ - Les provisions de voyage.",
    levelId: 48,
  },
  {
    character: "糾",
    meaningsFr: ["torsader", "enquêter"],
    readingsOn: ["キュウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 qui se courbe 丩 se TORSADE.",
    readingMnemonicFr: "KYŪ - L'enquête minutieuse.",
    levelId: 49,
  },
  {
    character: "紋",
    meaningsFr: ["emblème", "motif"],
    readingsOn: ["モン"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 avec le texte 文 forme un EMBLÈME.",
    readingMnemonicFr: "MON - Le motif familial.",
    levelId: 47,
  },
  {
    character: "紛",
    meaningsFr: ["confus", "mélangé"],
    readingsOn: ["フン"],
    readingsKun: ["まぎ.れる"],
    meaningMnemonicFr: "Le fil 糸 divisé 分 est CONFUS.",
    readingMnemonicFr: "FUN - La confusion totale.",
    levelId: 46,
  },
  {
    character: "紡",
    meaningsFr: ["filer", "tisser"],
    readingsOn: ["ボウ"],
    readingsKun: ["つむ.ぐ"],
    meaningMnemonicFr: "Le fil 糸 de la direction 方 sert à FILER.",
    readingMnemonicFr: "BŌ - Le filage du tissu.",
    levelId: 48,
  },
  {
    character: "索",
    meaningsFr: ["corde", "chercher"],
    readingsOn: ["サク"],
    readingsKun: [],
    meaningMnemonicFr: "Le toit 宀 avec le fil 糸 sert à CHERCHER.",
    readingMnemonicFr: "SAKU - La recherche active.",
    levelId: 47,
  },
  {
    character: "累",
    meaningsFr: ["accumuler", "impliquer"],
    readingsOn: ["ルイ"],
    readingsKun: [],
    meaningMnemonicFr: "Le champ 田 avec le fil 糸 S'ACCUMULE.",
    readingMnemonicFr: "RUI - L'accumulation progressive.",
    levelId: 46,
  },
  {
    character: "純",
    meaningsFr: ["pur", "simple"],
    readingsOn: ["ジュン"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 qui circule 屯 est PUR.",
    readingMnemonicFr: "JUN - La pureté absolue.",
    levelId: 43,
  },
  {
    character: "紳",
    meaningsFr: ["gentleman", "noble"],
    readingsOn: ["シン"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 qui s'étend 申 fait le GENTLEMAN.",
    readingMnemonicFr: "SHIN - Le gentleman raffiné.",
    levelId: 47,
  },
  {
    character: "紹",
    meaningsFr: ["introduire", "présenter"],
    readingsOn: ["ショウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 qui appelle 召 INTRODUIT.",
    readingMnemonicFr: "SHŌ - La présentation formelle.",
    levelId: 44,
  },
  {
    character: "紺",
    meaningsFr: ["bleu marine"],
    readingsOn: ["コン"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 très 甘 foncé est BLEU MARINE.",
    readingMnemonicFr: "KON - Le bleu profond.",
    levelId: 48,
  },
  {
    character: "終",
    meaningsFr: ["fin", "terminer"],
    readingsOn: ["シュウ"],
    readingsKun: ["お.わる", "お.える"],
    meaningMnemonicFr: "Le fil 糸 de l'hiver 冬 marque la FIN.",
    readingMnemonicFr: "SHŪ - La fin définitive.",
    levelId: 35,
  },
  {
    character: "組",
    meaningsFr: ["groupe", "assembler"],
    readingsOn: ["ソ"],
    readingsKun: ["く.む", "くみ"],
    meaningMnemonicFr: "Le fil 糸 avec l'ancêtre 且 forme un GROUPE.",
    readingMnemonicFr: "SO - Le groupe organisé.",
    levelId: 36,
  },
  {
    character: "経",
    meaningsFr: ["gérer", "passer"],
    readingsOn: ["ケイ", "キョウ"],
    readingsKun: ["へ.る", "た.つ"],
    meaningMnemonicFr: "Le fil 糸 qui passe 又土 GÈRE le temps.",
    readingMnemonicFr: "KEI - La gestion continue.",
    levelId: 41,
  },
  {
    character: "結",
    meaningsFr: ["attacher", "conclure"],
    readingsOn: ["ケツ"],
    readingsKun: ["むす.ぶ", "ゆ.う"],
    meaningMnemonicFr: "Le fil 糸 chanceux 吉 ATTACHE.",
    readingMnemonicFr: "KETSU - La conclusion finale.",
    levelId: 40,
  },
  {
    character: "絡",
    meaningsFr: ["s'emmêler", "contacter"],
    readingsOn: ["ラク"],
    readingsKun: ["から.む"],
    meaningMnemonicFr: "Le fil 糸 de chaque 各 côté S'EMMÊLE.",
    readingMnemonicFr: "RAKU - Le contact établi.",
    levelId: 45,
  },
  {
    character: "給",
    meaningsFr: ["fournir", "salaire"],
    readingsOn: ["キュウ"],
    readingsKun: ["たま.う"],
    meaningMnemonicFr: "Le fil 糸 qui réunit 合 FOURNIT.",
    readingMnemonicFr: "KYŪ - Le salaire versé.",
    levelId: 42,
  },
  {
    character: "統",
    meaningsFr: ["unifier", "diriger"],
    readingsOn: ["トウ"],
    readingsKun: ["す.べる"],
    meaningMnemonicFr: "Le fil 糸 qui rempli 充 UNIFIE.",
    readingMnemonicFr: "TŌ - L'unification nationale.",
    levelId: 44,
  },
  {
    character: "絵",
    meaningsFr: ["peinture", "image"],
    readingsOn: ["カイ", "エ"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 qui réunit 会 forme une PEINTURE.",
    readingMnemonicFr: "KAI - L'image peinte.",
    levelId: 38,
  },
  {
    character: "絞",
    meaningsFr: ["tordre", "presser"],
    readingsOn: ["コウ"],
    readingsKun: ["しぼ.る", "し.める"],
    meaningMnemonicFr: "Le fil 糸 qui croise 交 se TORD.",
    readingMnemonicFr: "KŌ - La torsion forcée.",
    levelId: 47,
  },
  {
    character: "絶",
    meaningsFr: ["couper", "absolu"],
    readingsOn: ["ゼツ"],
    readingsKun: ["た.える", "た.つ"],
    meaningMnemonicFr: "Le fil 糸 avec la couleur 色 qui manque 刀 est COUPÉ.",
    readingMnemonicFr: "ZETSU - L'absolu définitif.",
    levelId: 43,
  },
  {
    character: "継",
    meaningsFr: ["hériter", "succéder"],
    readingsOn: ["ケイ"],
    readingsKun: ["つ.ぐ"],
    meaningMnemonicFr: "Le fil 糸 qui continue 継 HÉRITE.",
    readingMnemonicFr: "KEI - La succession familiale.",
    levelId: 46,
  },
  {
    character: "続",
    meaningsFr: ["continuer", "suivre"],
    readingsOn: ["ゾク"],
    readingsKun: ["つづ.く", "つづ.ける"],
    meaningMnemonicFr: "Le fil 糸 qui vend 売 CONTINUE.",
    readingMnemonicFr: "ZOKU - La continuation sans fin.",
    levelId: 40,
  },
  {
    character: "維",
    meaningsFr: ["maintenir", "fibre"],
    readingsOn: ["イ"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 de l'oiseau 隹 MAINTIENT.",
    readingMnemonicFr: "I - Le maintien stable.",
    levelId: 47,
  },
  {
    character: "綱",
    meaningsFr: ["corde", "principe"],
    readingsOn: ["コウ"],
    readingsKun: ["つな"],
    meaningMnemonicFr: "Le fil 糸 avec le filet 岡 forme une CORDE.",
    readingMnemonicFr: "KŌ - Le principe fondamental.",
    levelId: 48,
  },
  {
    character: "網",
    meaningsFr: ["filet", "réseau"],
    readingsOn: ["モウ"],
    readingsKun: ["あみ"],
    meaningMnemonicFr: "Le fil 糸 qui disparaît 亡 dans le filet 冂 forme un FILET.",
    readingMnemonicFr: "MŌ - Le réseau étendu.",
    levelId: 46,
  },
  {
    character: "緊",
    meaningsFr: ["serré", "urgent"],
    readingsOn: ["キン"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 qui lie 臤 est SERRÉ.",
    readingMnemonicFr: "KIN - L'urgence pressante.",
    levelId: 45,
  },
  {
    character: "総",
    meaningsFr: ["total", "général"],
    readingsOn: ["ソウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 public 公 avec le cœur 心 est TOTAL.",
    readingMnemonicFr: "SŌ - Le total général.",
    levelId: 44,
  },
  {
    character: "緑",
    meaningsFr: ["vert"],
    readingsOn: ["リョク", "ロク"],
    readingsKun: ["みどり"],
    meaningMnemonicFr: "Le fil 糸 avec l'eau 彔 est VERT.",
    readingMnemonicFr: "RYOKU - La couleur verte.",
    levelId: 39,
  },
  {
    character: "緒",
    meaningsFr: ["début", "cordon"],
    readingsOn: ["ショ", "チョ"],
    readingsKun: ["お"],
    meaningMnemonicFr: "Le fil 糸 de l'auteur 者 marque le DÉBUT.",
    readingMnemonicFr: "SHO - Le cordon initial.",
    levelId: 46,
  },
  {
    character: "線",
    meaningsFr: ["ligne", "fil"],
    readingsOn: ["セン"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 avec la source 泉 forme une LIGNE.",
    readingMnemonicFr: "SEN - La ligne tracée.",
    levelId: 38,
  },
  {
    character: "締",
    meaningsFr: ["serrer", "conclure"],
    readingsOn: ["テイ"],
    readingsKun: ["し.める", "し.まる"],
    meaningMnemonicFr: "Le fil 糸 de l'empereur 帝 SERRE.",
    readingMnemonicFr: "TEI - La conclusion du contrat.",
    levelId: 45,
  },
  {
    character: "編",
    meaningsFr: ["éditer", "tricoter"],
    readingsOn: ["ヘン"],
    readingsKun: ["あ.む"],
    meaningMnemonicFr: "Le fil 糸 plat 扁 sert à ÉDITER.",
    readingMnemonicFr: "HEN - L'édition soignée.",
    levelId: 44,
  },
  {
    character: "縁",
    meaningsFr: ["bord", "destin"],
    readingsOn: ["エン"],
    readingsKun: ["ふち"],
    meaningMnemonicFr: "Le fil 糸 de la couleur 彖 forme le DESTIN.",
    readingMnemonicFr: "EN - Le lien du destin.",
    levelId: 47,
  },
  {
    character: "縄",
    meaningsFr: ["corde", "attacher"],
    readingsOn: ["ジョウ"],
    readingsKun: ["なわ"],
    meaningMnemonicFr: "Le fil 糸 de l'oiseau 蝿 forme une CORDE.",
    readingMnemonicFr: "JŌ - La corde solide.",
    levelId: 48,
  },
  {
    character: "縦",
    meaningsFr: ["vertical", "longueur"],
    readingsOn: ["ジュウ"],
    readingsKun: ["たて"],
    meaningMnemonicFr: "Le fil 糸 qui suit 従 est VERTICAL.",
    readingMnemonicFr: "JŪ - La direction verticale.",
    levelId: 46,
  },
  {
    character: "縫",
    meaningsFr: ["coudre"],
    readingsOn: ["ホウ"],
    readingsKun: ["ぬ.う"],
    meaningMnemonicFr: "Le fil 糸 qui rencontre 逢 sert à COUDRE.",
    readingMnemonicFr: "HŌ - La couture délicate.",
    levelId: 48,
  },
  {
    character: "繁",
    meaningsFr: ["prospère", "fréquent"],
    readingsOn: ["ハン"],
    readingsKun: ["しげ.る"],
    meaningMnemonicFr: "Le fil 糸 avec chaque 毎 lien est PROSPÈRE.",
    readingMnemonicFr: "HAN - La prospérité croissante.",
    levelId: 47,
  },
  {
    character: "繊",
    meaningsFr: ["fibre", "délicat"],
    readingsOn: ["セン"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 qui vaut mille 韱 est une FIBRE.",
    readingMnemonicFr: "SEN - La fibre délicate.",
    levelId: 49,
  },
  {
    character: "繕",
    meaningsFr: ["réparer", "raccommoder"],
    readingsOn: ["ゼン"],
    readingsKun: ["つくろ.う"],
    meaningMnemonicFr: "Le fil 糸 du bien 善 sert à RÉPARER.",
    readingMnemonicFr: "ZEN - La réparation soignée.",
    levelId: 50,
  },
  {
    character: "織",
    meaningsFr: ["tisser"],
    readingsOn: ["ショク", "シキ"],
    readingsKun: ["お.る"],
    meaningMnemonicFr: "Le fil 糸 avec la force 戠 sert à TISSER.",
    readingMnemonicFr: "SHOKU - Le tissage expert.",
    levelId: 45,
  },
  {
    character: "繰",
    meaningsFr: ["dévider", "répéter"],
    readingsOn: ["ソウ"],
    readingsKun: ["く.る"],
    meaningMnemonicFr: "Le fil 糸 avec l'arbre 喿 se DÉVIDE.",
    readingMnemonicFr: "SŌ - La répétition continue.",
    levelId: 48,
  },
  {
    character: "罪",
    meaningsFr: ["crime", "péché"],
    readingsOn: ["ザイ"],
    readingsKun: ["つみ"],
    meaningMnemonicFr: "Le filet 罒 sur ce qui n'est pas 非 est un CRIME.",
    readingMnemonicFr: "ZAI - Le crime puni.",
    levelId: 43,
  },
  {
    character: "署",
    meaningsFr: ["bureau", "signature"],
    readingsOn: ["ショ"],
    readingsKun: [],
    meaningMnemonicFr: "Le filet 罒 de l'auteur 者 forme un BUREAU.",
    readingMnemonicFr: "SHO - Le bureau officiel.",
    levelId: 44,
  },
  {
    character: "翁",
    meaningsFr: ["vieil homme"],
    readingsOn: ["オウ"],
    readingsKun: ["おきな"],
    meaningMnemonicFr: "Le public 公 avec les plumes 羽 est un VIEIL HOMME.",
    readingMnemonicFr: "Ō - Le sage vieillard.",
    levelId: 49,
  },
  {
    character: "翼",
    meaningsFr: ["aile"],
    readingsOn: ["ヨク"],
    readingsKun: ["つばさ"],
    meaningMnemonicFr: "Les plumes 羽 qui diffèrent 異 forment une AILE.",
    readingMnemonicFr: "YOKU - L'aile déployée.",
    levelId: 46,
  },
  {
    character: "耐",
    meaningsFr: ["endurer", "résister"],
    readingsOn: ["タイ"],
    readingsKun: ["た.える"],
    meaningMnemonicFr: "L'oreille 耳 qui résiste 寸 ENDURE.",
    readingMnemonicFr: "TAI - L'endurance nécessaire.",
    levelId: 44,
  },
  {
    character: "聖",
    meaningsFr: ["saint", "sacré"],
    readingsOn: ["セイ", "ショウ"],
    readingsKun: ["ひじり"],
    meaningMnemonicFr: "L'oreille 耳 qui parle 口 avec le roi 王 est SAINT.",
    readingMnemonicFr: "SEI - La sainteté divine.",
    levelId: 45,
  },
  {
    character: "肝",
    meaningsFr: ["foie", "essentiel"],
    readingsOn: ["カン"],
    readingsKun: ["きも"],
    meaningMnemonicFr: "La chair 月 avec le ciel 干 est le FOIE.",
    readingMnemonicFr: "KAN - Le foie essentiel.",
    levelId: 46,
  },
  {
    character: "肯",
    meaningsFr: ["consentir", "approuver"],
    readingsOn: ["コウ"],
    readingsKun: ["がえんじ.る"],
    meaningMnemonicFr: "L'arrêt 止 avec la chair 月 CONSENT.",
    readingMnemonicFr: "KŌ - L'approbation donnée.",
    levelId: 48,
  },
  {
    character: "胆",
    meaningsFr: ["vésicule biliaire", "courage"],
    readingsOn: ["タン"],
    readingsKun: ["きも"],
    meaningMnemonicFr: "La chair 月 avec le jour 旦 a du COURAGE.",
    readingMnemonicFr: "TAN - Le courage intérieur.",
    levelId: 47,
  },
  {
    character: "胎",
    meaningsFr: ["fœtus", "utérus"],
    readingsOn: ["タイ"],
    readingsKun: [],
    meaningMnemonicFr: "La chair 月 avec la plateforme 台 porte le FŒTUS.",
    readingMnemonicFr: "TAI - Le fœtus en formation.",
    levelId: 49,
  },
  {
    character: "脂",
    meaningsFr: ["graisse", "huile"],
    readingsOn: ["シ"],
    readingsKun: ["あぶら"],
    meaningMnemonicFr: "La chair 月 qui tourne 旨 est la GRAISSE.",
    readingMnemonicFr: "SHI - La graisse corporelle.",
    levelId: 46,
  },
  {
    character: "脈",
    meaningsFr: ["veine", "pouls"],
    readingsOn: ["ミャク"],
    readingsKun: [],
    meaningMnemonicFr: "La chair 月 avec la dérivation 脉 forme les VEINES.",
    readingMnemonicFr: "MYAKU - Le pouls battant.",
    levelId: 45,
  },
  {
    character: "脅",
    meaningsFr: ["menacer", "intimider"],
    readingsOn: ["キョウ"],
    readingsKun: ["おびや.かす", "おど.す"],
    meaningMnemonicFr: "La chair 月 qui coopère 劦 MENACE.",
    readingMnemonicFr: "KYŌ - La menace pesante.",
    levelId: 47,
  },
  {
    character: "腐",
    meaningsFr: ["pourrir", "corrompre"],
    readingsOn: ["フ"],
    readingsKun: ["くさ.る"],
    meaningMnemonicFr: "La maison 府 avec la chair 肉 POURRIT.",
    readingMnemonicFr: "FU - La corruption totale.",
    levelId: 46,
  },
  {
    character: "腸",
    meaningsFr: ["intestin"],
    readingsOn: ["チョウ"],
    readingsKun: ["はらわた"],
    meaningMnemonicFr: "La chair 月 avec le soleil 昜 forme l'INTESTIN.",
    readingMnemonicFr: "CHŌ - L'intestin digestif.",
    levelId: 45,
  },
  {
    character: "膜",
    meaningsFr: ["membrane"],
    readingsOn: ["マク"],
    readingsKun: [],
    meaningMnemonicFr: "La chair 月 du soir 莫 forme une MEMBRANE.",
    readingMnemonicFr: "MAKU - La membrane fine.",
    levelId: 48,
  },
  {
    character: "膨",
    meaningsFr: ["gonfler", "enfler"],
    readingsOn: ["ボウ"],
    readingsKun: ["ふく.らむ"],
    meaningMnemonicFr: "La chair 月 abondante 彭 GONFLE.",
    readingMnemonicFr: "BŌ - Le gonflement visible.",
    levelId: 49,
  },
  {
    character: "臓",
    meaningsFr: ["organe interne"],
    readingsOn: ["ゾウ"],
    readingsKun: [],
    meaningMnemonicFr: "La chair 月 qui cache 臧 est un ORGANE.",
    readingMnemonicFr: "ZŌ - Les organes vitaux.",
    levelId: 46,
  },
  {
    character: "芳",
    meaningsFr: ["parfumé", "aromatique"],
    readingsOn: ["ホウ"],
    readingsKun: ["かんば.しい"],
    meaningMnemonicFr: "L'herbe 艹 de la direction 方 est PARFUMÉE.",
    readingMnemonicFr: "HŌ - Le parfum délicat.",
    levelId: 47,
  },
  {
    character: "若",
    meaningsFr: ["jeune", "si"],
    readingsOn: ["ジャク", "ニャク"],
    readingsKun: ["わか.い", "も.し"],
    meaningMnemonicFr: "L'herbe 艹 avec la droite 右 est JEUNE.",
    readingMnemonicFr: "JAKU - La jeunesse fraîche.",
    levelId: 41,
  },
  {
    character: "范",
    meaningsFr: ["modèle", "exemple"],
    readingsOn: ["ハン"],
    readingsKun: [],
    meaningMnemonicFr: "L'herbe 艹 avec l'eau 氵 et le chien 巳 forme un MODÈLE.",
    readingMnemonicFr: "HAN - L'exemple à suivre.",
    levelId: 50,
  },
  {
    character: "荒",
    meaningsFr: ["sauvage", "grossier"],
    readingsOn: ["コウ"],
    readingsKun: ["あら.い", "あ.れる"],
    meaningMnemonicFr: "L'herbe 艹 avec le fleuve 巟 est SAUVAGE.",
    readingMnemonicFr: "KŌ - La nature sauvage.",
    levelId: 44,
  },
  {
    character: "莫",
    meaningsFr: ["aucun", "ne pas"],
    readingsOn: ["バク", "ボ"],
    readingsKun: ["なか.れ"],
    meaningMnemonicFr: "L'herbe 艹 avec le soleil 日 qui se couche 大 signifie AUCUN.",
    readingMnemonicFr: "BAKU - Le néant absolu.",
    levelId: 50,
  },
  {
    character: "華",
    meaningsFr: ["fleur", "splendeur"],
    readingsOn: ["カ", "ケ"],
    readingsKun: ["はな"],
    meaningMnemonicFr: "L'herbe 艹 avec la splendeur 華 est la FLEUR.",
    readingMnemonicFr: "KA - La splendeur florale.",
    levelId: 44,
  },
];

async function main() {
  console.log("Seeding TRULY FINAL kanji batch to exceed 2000...");

  for (const kanji of kanjiData) {
    await prisma.kanji.upsert({
      where: { character: kanji.character },
      update: {
        meaningsFr: kanji.meaningsFr,
        readingsOn: kanji.readingsOn,
        readingsKun: kanji.readingsKun,
        meaningMnemonicFr: kanji.meaningMnemonicFr,
        readingMnemonicFr: kanji.readingMnemonicFr,
        levelId: kanji.levelId,
      },
      create: kanji,
    });
  }

  console.log(`Seeded ${kanjiData.length} kanji.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
