import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ULTIMATE FINAL batch - targeting 55 unique kanji to exceed 2000

const kanjiData = [
  {
    character: "葬",
    meaningsFr: ["enterrer", "funérailles"],
    readingsOn: ["ソウ"],
    readingsKun: ["ほうむ.る"],
    meaningMnemonicFr: "L'herbe 艹 de la mort 死 avec les mains 廾 ENTERRE.",
    readingMnemonicFr: "SŌ - Les funérailles solennelles.",
    levelId: 48,
  },
  {
    character: "蒸",
    meaningsFr: ["vapeur", "cuire à la vapeur"],
    readingsOn: ["ジョウ"],
    readingsKun: ["む.す", "む.れる"],
    meaningMnemonicFr: "L'herbe 艹 avec les grains 烝 fait de la VAPEUR.",
    readingMnemonicFr: "JŌ - La cuisson vapeur.",
    levelId: 45,
  },
  {
    character: "蓋",
    meaningsFr: ["couvercle", "couvrir"],
    readingsOn: ["ガイ"],
    readingsKun: ["ふた"],
    meaningMnemonicFr: "L'herbe 艹 avec le plat 盍 forme un COUVERCLE.",
    readingMnemonicFr: "GAI - Le couvercle fermé.",
    levelId: 49,
  },
  {
    character: "薄",
    meaningsFr: ["mince", "léger"],
    readingsOn: ["ハク"],
    readingsKun: ["うす.い"],
    meaningMnemonicFr: "L'herbe 艹 avec le plat 溥 est MINCE.",
    readingMnemonicFr: "HAKU - La minceur délicate.",
    levelId: 46,
  },
  {
    character: "薦",
    meaningsFr: ["recommander"],
    readingsOn: ["セン"],
    readingsKun: ["すす.める"],
    meaningMnemonicFr: "L'herbe 艹 avec l'oiseau 薦 RECOMMANDE.",
    readingMnemonicFr: "SEN - La recommandation sincère.",
    levelId: 48,
  },
  {
    character: "薪",
    meaningsFr: ["bois de chauffage"],
    readingsOn: ["シン"],
    readingsKun: ["たきぎ"],
    meaningMnemonicFr: "L'herbe 艹 avec le nouveau 新 est du BOIS DE CHAUFFAGE.",
    readingMnemonicFr: "SHIN - Le bois pour le feu.",
    levelId: 49,
  },
  {
    character: "薬",
    meaningsFr: ["médicament", "drogue"],
    readingsOn: ["ヤク"],
    readingsKun: ["くすり"],
    meaningMnemonicFr: "L'herbe 艹 avec la musique 楽 est un MÉDICAMENT.",
    readingMnemonicFr: "YAKU - Le médicament guérisseur.",
    levelId: 40,
  },
  {
    character: "藩",
    meaningsFr: ["clan", "fief"],
    readingsOn: ["ハン"],
    readingsKun: [],
    meaningMnemonicFr: "L'herbe 艹 avec la clôture 潘 forme un CLAN.",
    readingMnemonicFr: "HAN - Le clan féodal.",
    levelId: 50,
  },
  {
    character: "藻",
    meaningsFr: ["algue"],
    readingsOn: ["ソウ"],
    readingsKun: ["も"],
    meaningMnemonicFr: "L'herbe 艹 avec le bain 澡 est une ALGUE.",
    readingMnemonicFr: "SŌ - L'algue marine.",
    levelId: 50,
  },
  {
    character: "衆",
    meaningsFr: ["foule", "masses"],
    readingsOn: ["シュウ", "シュ"],
    readingsKun: [],
    meaningMnemonicFr: "Le sang 血 avec les gens 众 forme la FOULE.",
    readingMnemonicFr: "SHŪ - Les masses populaires.",
    levelId: 45,
  },
  {
    character: "衝",
    meaningsFr: ["collision", "choc"],
    readingsOn: ["ショウ"],
    readingsKun: ["つ.く"],
    meaningMnemonicFr: "La rue 行 avec le poids 重 cause une COLLISION.",
    readingMnemonicFr: "SHŌ - Le choc violent.",
    levelId: 47,
  },
  {
    character: "衰",
    meaningsFr: ["décliner", "affaiblir"],
    readingsOn: ["スイ"],
    readingsKun: ["おとろ.える"],
    meaningMnemonicFr: "Le vêtement 衣 avec le centre 中 qui se coupe DÉCLINE.",
    readingMnemonicFr: "SUI - Le déclin inévitable.",
    levelId: 47,
  },
  {
    character: "袋",
    meaningsFr: ["sac", "poche"],
    readingsOn: ["タイ"],
    readingsKun: ["ふくろ"],
    meaningMnemonicFr: "Le vêtement 衣 qui remplace 代 est un SAC.",
    readingMnemonicFr: "TAI - Le sac pratique.",
    levelId: 44,
  },
  {
    character: "裁",
    meaningsFr: ["couper", "juger"],
    readingsOn: ["サイ"],
    readingsKun: ["た.つ", "さば.く"],
    meaningMnemonicFr: "Le vêtement 衣 que la lance 戈 COUPE.",
    readingMnemonicFr: "SAI - Le jugement rendu.",
    levelId: 45,
  },
  {
    character: "裂",
    meaningsFr: ["déchirer", "fendre"],
    readingsOn: ["レツ"],
    readingsKun: ["さ.く"],
    meaningMnemonicFr: "Le vêtement 衣 qui s'aligne 列 se DÉCHIRE.",
    readingMnemonicFr: "RETSU - La déchirure nette.",
    levelId: 47,
  },
  {
    character: "裕",
    meaningsFr: ["abondance", "richesse"],
    readingsOn: ["ユウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le vêtement 衤 avec la vallée 谷 montre l'ABONDANCE.",
    readingMnemonicFr: "YŪ - La richesse matérielle.",
    levelId: 46,
  },
  {
    character: "補",
    meaningsFr: ["supplément", "compléter"],
    readingsOn: ["ホ"],
    readingsKun: ["おぎな.う"],
    meaningMnemonicFr: "Le vêtement 衤 avec le plat 甫 COMPLÈTE.",
    readingMnemonicFr: "HO - Le complément nécessaire.",
    levelId: 44,
  },
  {
    character: "裸",
    meaningsFr: ["nu", "dénudé"],
    readingsOn: ["ラ"],
    readingsKun: ["はだか"],
    meaningMnemonicFr: "Le vêtement 衤 avec le fruit 果 est NU.",
    readingMnemonicFr: "RA - La nudité totale.",
    levelId: 47,
  },
  {
    character: "製",
    meaningsFr: ["fabriquer", "manufacture"],
    readingsOn: ["セイ"],
    readingsKun: [],
    meaningMnemonicFr: "Le couteau 制 avec le vêtement 衣 FABRIQUE.",
    readingMnemonicFr: "SEI - La fabrication industrielle.",
    levelId: 43,
  },
  {
    character: "襟",
    meaningsFr: ["col", "revers"],
    readingsOn: ["キン"],
    readingsKun: ["えり"],
    meaningMnemonicFr: "Le vêtement 衤 avec l'interdit 禁 forme le COL.",
    readingMnemonicFr: "KIN - Le col du vêtement.",
    levelId: 49,
  },
  {
    character: "覆",
    meaningsFr: ["couvrir", "renverser"],
    readingsOn: ["フク"],
    readingsKun: ["おお.う", "くつがえ.す"],
    meaningMnemonicFr: "L'ouest 覀 avec le retour 復 COUVRE.",
    readingMnemonicFr: "FUKU - Le renversement soudain.",
    levelId: 48,
  },
  {
    character: "覇",
    meaningsFr: ["hégémonie", "champion"],
    readingsOn: ["ハ"],
    readingsKun: [],
    meaningMnemonicFr: "L'ouest 覀 avec la révolution 革 montre l'HÉGÉMONIE.",
    readingMnemonicFr: "HA - La domination totale.",
    levelId: 50,
  },
  {
    character: "触",
    meaningsFr: ["toucher", "contact"],
    readingsOn: ["ショク"],
    readingsKun: ["ふ.れる", "さわ.る"],
    meaningMnemonicFr: "La corne 角 avec l'insecte 虫 TOUCHE.",
    readingMnemonicFr: "SHOKU - Le contact physique.",
    levelId: 44,
  },
  {
    character: "訂",
    meaningsFr: ["corriger", "réviser"],
    readingsOn: ["テイ"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 en forme de T 丁 CORRIGENT.",
    readingMnemonicFr: "TEI - La correction minutieuse.",
    levelId: 46,
  },
  {
    character: "訃",
    meaningsFr: ["avis de décès"],
    readingsOn: ["フ"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 qui ne sont pas 卜 sont un AVIS DE DÉCÈS.",
    readingMnemonicFr: "FU - L'annonce funèbre.",
    levelId: 52,
  },
  {
    character: "討",
    meaningsFr: ["discuter", "attaquer"],
    readingsOn: ["トウ"],
    readingsKun: ["う.つ"],
    meaningMnemonicFr: "Les paroles 言 avec la main 寸 DISCUTENT.",
    readingMnemonicFr: "TŌ - La discussion critique.",
    levelId: 45,
  },
  {
    character: "訓",
    meaningsFr: ["instruction", "lecture kun"],
    readingsOn: ["クン"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 du fleuve 川 sont une INSTRUCTION.",
    readingMnemonicFr: "KUN - La lecture japonaise.",
    levelId: 44,
  },
  {
    character: "訟",
    meaningsFr: ["procès", "litige"],
    readingsOn: ["ショウ"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 publiques 公 forment un PROCÈS.",
    readingMnemonicFr: "SHŌ - Le litige juridique.",
    levelId: 49,
  },
  {
    character: "託",
    meaningsFr: ["confier", "charger"],
    readingsOn: ["タク"],
    readingsKun: ["かこつ.ける"],
    meaningMnemonicFr: "Les paroles 言 qui libèrent 乇 CONFIENT.",
    readingMnemonicFr: "TAKU - La confiance accordée.",
    levelId: 46,
  },
  {
    character: "診",
    meaningsFr: ["examiner", "diagnostiquer"],
    readingsOn: ["シン"],
    readingsKun: ["み.る"],
    meaningMnemonicFr: "Les paroles 言 qui vérifient 㐱 EXAMINENT.",
    readingMnemonicFr: "SHIN - Le diagnostic médical.",
    levelId: 44,
  },
  {
    character: "註",
    meaningsFr: ["annotation", "note"],
    readingsOn: ["チュウ"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 du maître 主 sont une ANNOTATION.",
    readingMnemonicFr: "CHŪ - La note explicative.",
    levelId: 50,
  },
  {
    character: "詠",
    meaningsFr: ["réciter", "composer des poèmes"],
    readingsOn: ["エイ"],
    readingsKun: ["よ.む"],
    meaningMnemonicFr: "Les paroles 言 éternelles 永 RÉCITENT.",
    readingMnemonicFr: "EI - La récitation poétique.",
    levelId: 48,
  },
  {
    character: "詮",
    meaningsFr: ["explication", "investigation"],
    readingsOn: ["セン"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 complètes 全 forment une EXPLICATION.",
    readingMnemonicFr: "SEN - L'investigation approfondie.",
    levelId: 50,
  },
  {
    character: "詰",
    meaningsFr: ["remplir", "serrer"],
    readingsOn: ["キツ"],
    readingsKun: ["つ.める", "つ.まる"],
    meaningMnemonicFr: "Les paroles 言 chanceux 吉 REMPLISSENT.",
    readingMnemonicFr: "KITSU - Le remplissage complet.",
    levelId: 45,
  },
  {
    character: "誉",
    meaningsFr: ["honneur", "gloire"],
    readingsOn: ["ヨ"],
    readingsKun: ["ほま.れ"],
    meaningMnemonicFr: "Les paroles 言 qui élèvent 興 apportent l'HONNEUR.",
    readingMnemonicFr: "YO - La gloire méritée.",
    levelId: 47,
  },
  {
    character: "誓",
    meaningsFr: ["serment", "jurer"],
    readingsOn: ["セイ"],
    readingsKun: ["ちか.う"],
    meaningMnemonicFr: "Les paroles 言 de la rupture 折 forment un SERMENT.",
    readingMnemonicFr: "SEI - Le serment solennel.",
    levelId: 46,
  },
  {
    character: "誘",
    meaningsFr: ["inviter", "séduire"],
    readingsOn: ["ユウ"],
    readingsKun: ["さそ.う"],
    meaningMnemonicFr: "Les paroles 言 qui guident 秀 INVITENT.",
    readingMnemonicFr: "YŪ - L'invitation séduisante.",
    levelId: 45,
  },
  {
    character: "語",
    meaningsFr: ["langue", "parler"],
    readingsOn: ["ゴ"],
    readingsKun: ["かた.る", "かた.らう"],
    meaningMnemonicFr: "Les paroles 言 qui m'appartiennent 吾 forment la LANGUE.",
    readingMnemonicFr: "GO - La langue parlée.",
    levelId: 35,
  },
  {
    character: "誤",
    meaningsFr: ["erreur", "se tromper"],
    readingsOn: ["ゴ"],
    readingsKun: ["あやま.る"],
    meaningMnemonicFr: "Les paroles 言 qui m'appartiennent 呉 sont une ERREUR.",
    readingMnemonicFr: "GO - L'erreur regrettable.",
    levelId: 44,
  },
  {
    character: "説",
    meaningsFr: ["expliquer", "théorie"],
    readingsOn: ["セツ", "ゼイ"],
    readingsKun: ["と.く"],
    meaningMnemonicFr: "Les paroles 言 qui libèrent 兌 EXPLIQUENT.",
    readingMnemonicFr: "SETSU - L'explication claire.",
    levelId: 41,
  },
  {
    character: "請",
    meaningsFr: ["demander", "inviter"],
    readingsOn: ["セイ", "シン"],
    readingsKun: ["こ.う", "う.ける"],
    meaningMnemonicFr: "Les paroles 言 pures 青 DEMANDENT.",
    readingMnemonicFr: "SEI - La demande formelle.",
    levelId: 44,
  },
  {
    character: "諾",
    meaningsFr: ["consentir", "approuver"],
    readingsOn: ["ダク"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 de la droite 若 CONSENTENT.",
    readingMnemonicFr: "DAKU - L'approbation donnée.",
    levelId: 47,
  },
  {
    character: "課",
    meaningsFr: ["section", "leçon"],
    readingsOn: ["カ"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 avec le fruit 果 forment une LEÇON.",
    readingMnemonicFr: "KA - La section d'étude.",
    levelId: 42,
  },
  {
    character: "調",
    meaningsFr: ["enquêter", "ton"],
    readingsOn: ["チョウ"],
    readingsKun: ["しら.べる", "ととの.う"],
    meaningMnemonicFr: "Les paroles 言 du matin 周 ENQUÊTENT.",
    readingMnemonicFr: "CHŌ - L'enquête approfondie.",
    levelId: 41,
  },
  {
    character: "談",
    meaningsFr: ["parler", "discussion"],
    readingsOn: ["ダン"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 qui brûlent 炎 forment une DISCUSSION.",
    readingMnemonicFr: "DAN - La discussion animée.",
    levelId: 43,
  },
  {
    character: "諸",
    meaningsFr: ["divers", "plusieurs"],
    readingsOn: ["ショ"],
    readingsKun: ["もろ"],
    meaningMnemonicFr: "Les paroles 言 de l'auteur 者 sont DIVERSES.",
    readingMnemonicFr: "SHO - Les éléments divers.",
    levelId: 46,
  },
  {
    character: "論",
    meaningsFr: ["théorie", "discuter"],
    readingsOn: ["ロン"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 organisées 侖 forment une THÉORIE.",
    readingMnemonicFr: "RON - La discussion théorique.",
    levelId: 42,
  },
  {
    character: "諦",
    meaningsFr: ["abandonner", "résigner"],
    readingsOn: ["テイ"],
    readingsKun: ["あきら.める"],
    meaningMnemonicFr: "Les paroles 言 de l'empereur 帝 ABANDONNENT.",
    readingMnemonicFr: "TEI - La résignation acceptée.",
    levelId: 48,
  },
  {
    character: "諧",
    meaningsFr: ["harmonie", "accord"],
    readingsOn: ["カイ"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 de tous 皆 créent l'HARMONIE.",
    readingMnemonicFr: "KAI - L'accord parfait.",
    levelId: 49,
  },
  {
    character: "謙",
    meaningsFr: ["modeste", "humble"],
    readingsOn: ["ケン"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 combinées 兼 sont MODESTES.",
    readingMnemonicFr: "KEN - L'humilité sincère.",
    levelId: 47,
  },
  {
    character: "講",
    meaningsFr: ["conférence", "lecture"],
    readingsOn: ["コウ"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 structurées 構 forment une CONFÉRENCE.",
    readingMnemonicFr: "KŌ - La conférence donnée.",
    levelId: 44,
  },
  {
    character: "識",
    meaningsFr: ["connaissance", "reconnaître"],
    readingsOn: ["シキ"],
    readingsKun: ["し.る"],
    meaningMnemonicFr: "Les paroles 言 avec la force 戠 forment la CONNAISSANCE.",
    readingMnemonicFr: "SHIKI - La conscience éveillée.",
    levelId: 43,
  },
  {
    character: "警",
    meaningsFr: ["avertir", "police"],
    readingsOn: ["ケイ"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 qui respectent 敬 AVERTISSENT.",
    readingMnemonicFr: "KEI - L'avertissement de la police.",
    levelId: 45,
  },
  {
    character: "議",
    meaningsFr: ["délibérer", "discussion"],
    readingsOn: ["ギ"],
    readingsKun: [],
    meaningMnemonicFr: "Les paroles 言 de justice 義 DÉLIBÈRENT.",
    readingMnemonicFr: "GI - La délibération politique.",
    levelId: 43,
  },
  {
    character: "譲",
    meaningsFr: ["céder", "transférer"],
    readingsOn: ["ジョウ"],
    readingsKun: ["ゆず.る"],
    meaningMnemonicFr: "Les paroles 言 qui cèdent 襄 TRANSFÈRENT.",
    readingMnemonicFr: "JŌ - La cession volontaire.",
    levelId: 47,
  },
];

async function main() {
  console.log("Seeding ULTIMATE FINAL kanji batch to exceed 2000...");

  for (const kanji of kanjiData) {
    await prisma.kanji.upsert({
      where: { character: kanji.character },
      update: {
        meaningsFr: kanji.meaningsFr,
        readingsOn: kanji.readingsOn,
        readingsKun: kanji.readingsKun,
        meaningMnemonicFr: kanji.meaningMnemonicFr,
        readingMnemonicFr: kanji.readingMnemonicFr,
        levelId: kanji.levelId,
      },
      create: kanji,
    });
  }

  console.log(`Seeded ${kanjiData.length} kanji.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
