import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Vocabulary supplement for levels 56-60
// Adding ~40 words per level to bring expert levels to ~90 words
// Focus: N1 literary, archaic, and sophisticated vocabulary

const vocabularyData = [
  // Level 56 - N1 Literary vocabulary
  { word: "応変", meaningsFr: ["Adaptation", "Flexibilité"], readings: ["おうへん"], mnemonicFr: "L'ADAPTATION aux circonstances.", levelId: 56 },
  { word: "変幻", meaningsFr: ["Transformation", "Métamorphose"], readings: ["へんげん"], mnemonicFr: "Une MÉTAMORPHOSE constante.", levelId: 56 },
  { word: "自在", meaningsFr: ["Libre", "Sans contrainte"], readings: ["じざい"], mnemonicFr: "Se mouvoir LIBREMENT.", levelId: 56 },
  { word: "融通", meaningsFr: ["Flexibilité", "Souplesse"], readings: ["ゆうずう"], mnemonicFr: "La SOUPLESSE dans les affaires.", levelId: 56 },
  { word: "折衷", meaningsFr: ["Compromis", "Éclectisme"], readings: ["せっちゅう"], mnemonicFr: "Un COMPROMIS élégant.", levelId: 56 },
  { word: "調和", meaningsFr: ["Harmonie"], readings: ["ちょうわ"], mnemonicFr: "L'HARMONIE des couleurs.", levelId: 56 },
  { word: "均整", meaningsFr: ["Symétrie", "Équilibre"], readings: ["きんせい"], mnemonicFr: "La SYMÉTRIE parfaite.", levelId: 56 },
  { word: "整然", meaningsFr: ["Ordonné", "Méthodique"], readings: ["せいぜん"], mnemonicFr: "Une disposition ORDONNÉE.", levelId: 56 },
  { word: "秩序", meaningsFr: ["Ordre", "Discipline"], readings: ["ちつじょ"], mnemonicFr: "L'ORDRE social.", levelId: 56 },
  { word: "体系", meaningsFr: ["Système", "Organisation"], readings: ["たいけい"], mnemonicFr: "Un SYSTÈME cohérent.", levelId: 56 },
  { word: "系統", meaningsFr: ["Système", "Lignée"], readings: ["けいとう"], mnemonicFr: "La LIGNÉE artistique.", levelId: 56 },
  { word: "脈絡", meaningsFr: ["Contexte", "Cohérence"], readings: ["みゃくらく"], mnemonicFr: "Le CONTEXTE de l'histoire.", levelId: 56 },
  { word: "筋道", meaningsFr: ["Logique", "Raisonnement"], readings: ["すじみち"], mnemonicFr: "La LOGIQUE du discours.", levelId: 56 },
  { word: "道理", meaningsFr: ["Raison", "Justice"], readings: ["どうり"], mnemonicFr: "La RAISON l'emporte.", levelId: 56 },
  { word: "条理", meaningsFr: ["Logique", "Raison"], readings: ["じょうり"], mnemonicFr: "La LOGIQUE des choses.", levelId: 56 },
  { word: "摂理", meaningsFr: ["Providence"], readings: ["せつり"], mnemonicFr: "La PROVIDENCE divine.", levelId: 56 },
  { word: "天理", meaningsFr: ["Loi naturelle"], readings: ["てんり"], mnemonicFr: "La LOI NATURELLE.", levelId: 56 },
  { word: "天命", meaningsFr: ["Destin", "Mission"], readings: ["てんめい"], mnemonicFr: "Le DESTIN tracé.", levelId: 56 },
  { word: "運命", meaningsFr: ["Destin"], readings: ["うんめい"], mnemonicFr: "Le DESTIN inéluctable.", levelId: 56 },
  { word: "宿命", meaningsFr: ["Fatalité"], readings: ["しゅくめい"], mnemonicFr: "La FATALITÉ acceptée.", levelId: 56 },
  { word: "因縁", meaningsFr: ["Karma", "Destin"], readings: ["いんねん"], mnemonicFr: "Le KARMA des vies passées.", levelId: 56 },
  { word: "業", meaningsFr: ["Karma", "Acte"], readings: ["ごう"], mnemonicFr: "Le KARMA accumulé.", levelId: 56 },
  { word: "縁起", meaningsFr: ["Présage", "Origine"], readings: ["えんぎ"], mnemonicFr: "Un bon PRÉSAGE.", levelId: 56 },
  { word: "吉兆", meaningsFr: ["Bon présage"], readings: ["きっちょう"], mnemonicFr: "Un BON PRÉSAGE.", levelId: 56 },
  { word: "凶兆", meaningsFr: ["Mauvais présage"], readings: ["きょうちょう"], mnemonicFr: "Un MAUVAIS PRÉSAGE.", levelId: 56 },
  { word: "予兆", meaningsFr: ["Signe avant-coureur"], readings: ["よちょう"], mnemonicFr: "Un SIGNE AVANT-COUREUR.", levelId: 56 },
  { word: "兆候", meaningsFr: ["Signe", "Symptôme"], readings: ["ちょうこう"], mnemonicFr: "Les SIGNES de changement.", levelId: 56 },
  { word: "徴候", meaningsFr: ["Symptôme", "Indice"], readings: ["ちょうこう"], mnemonicFr: "Les SYMPTÔMES de la maladie.", levelId: 56 },
  { word: "前兆", meaningsFr: ["Présage"], readings: ["ぜんちょう"], mnemonicFr: "Le PRÉSAGE du désastre.", levelId: 56 },
  { word: "瑞兆", meaningsFr: ["Bon augure"], readings: ["ずいちょう"], mnemonicFr: "Un BON AUGURE.", levelId: 56 },
  { word: "端緒", meaningsFr: ["Début", "Commencement"], readings: ["たんちょ"], mnemonicFr: "Le DÉBUT de l'enquête.", levelId: 56 },
  { word: "発端", meaningsFr: ["Origine", "Début"], readings: ["ほったん"], mnemonicFr: "L'ORIGINE de l'incident.", levelId: 56 },
  { word: "契機", meaningsFr: ["Occasion", "Catalyseur"], readings: ["けいき"], mnemonicFr: "Le CATALYSEUR du changement.", levelId: 56 },
  { word: "動機", meaningsFr: ["Motif", "Mobile"], readings: ["どうき"], mnemonicFr: "Le MOTIF du crime.", levelId: 56 },
  { word: "誘因", meaningsFr: ["Facteur déclencheur"], readings: ["ゆういん"], mnemonicFr: "Le FACTEUR DÉCLENCHEUR.", levelId: 56 },
  { word: "要因", meaningsFr: ["Facteur", "Cause"], readings: ["よういん"], mnemonicFr: "Le FACTEUR principal.", levelId: 56 },
  { word: "主因", meaningsFr: ["Cause principale"], readings: ["しゅいん"], mnemonicFr: "La CAUSE PRINCIPALE.", levelId: 56 },
  { word: "遠因", meaningsFr: ["Cause lointaine"], readings: ["えんいん"], mnemonicFr: "La CAUSE LOINTAINE.", levelId: 56 },
  { word: "近因", meaningsFr: ["Cause immédiate"], readings: ["きんいん"], mnemonicFr: "La CAUSE IMMÉDIATE.", levelId: 56 },
  { word: "起因", meaningsFr: ["Origine", "Source"], readings: ["きいん"], mnemonicFr: "L'ORIGINE du problème.", levelId: 56 },

  // Level 57 - N1 Formal/Academic vocabulary
  { word: "帰因", meaningsFr: ["Attribution"], readings: ["きいん"], mnemonicFr: "L'ATTRIBUTION de la responsabilité.", levelId: 57 },
  { word: "帰結", meaningsFr: ["Conséquence", "Conclusion"], readings: ["きけつ"], mnemonicFr: "La CONSÉQUENCE logique.", levelId: 57 },
  { word: "結末", meaningsFr: ["Dénouement", "Fin"], readings: ["けつまつ"], mnemonicFr: "Le DÉNOUEMENT de l'histoire.", levelId: 57 },
  { word: "終焉", meaningsFr: ["Fin", "Mort"], readings: ["しゅうえん"], mnemonicFr: "La FIN d'une époque.", levelId: 57 },
  { word: "終局", meaningsFr: ["Fin", "Conclusion"], readings: ["しゅうきょく"], mnemonicFr: "La CONCLUSION finale.", levelId: 57 },
  { word: "収束", meaningsFr: ["Convergence", "Fin"], readings: ["しゅうそく"], mnemonicFr: "La CONVERGENCE vers la solution.", levelId: 57 },
  { word: "終息", meaningsFr: ["Fin", "Cessation"], readings: ["しゅうそく"], mnemonicFr: "La CESSATION des hostilités.", levelId: 57 },
  { word: "消滅", meaningsFr: ["Disparition"], readings: ["しょうめつ"], mnemonicFr: "La DISPARITION complète.", levelId: 57 },
  { word: "滅亡", meaningsFr: ["Destruction", "Ruine"], readings: ["めつぼう"], mnemonicFr: "La DESTRUCTION de l'empire.", levelId: 57 },
  { word: "壊滅", meaningsFr: ["Anéantissement"], readings: ["かいめつ"], mnemonicFr: "L'ANÉANTISSEMENT total.", levelId: 57 },
  { word: "崩壊", meaningsFr: ["Effondrement"], readings: ["ほうかい"], mnemonicFr: "L'EFFONDREMENT du système.", levelId: 57 },
  { word: "瓦解", meaningsFr: ["Désintégration"], readings: ["がかい"], mnemonicFr: "La DÉSINTÉGRATION du groupe.", levelId: 57 },
  { word: "分裂", meaningsFr: ["Scission", "Division"], readings: ["ぶんれつ"], mnemonicFr: "La SCISSION du parti.", levelId: 57 },
  { word: "離散", meaningsFr: ["Dispersion"], readings: ["りさん"], mnemonicFr: "La DISPERSION de la famille.", levelId: 57 },
  { word: "散逸", meaningsFr: ["Dispersion", "Perte"], readings: ["さんいつ"], mnemonicFr: "La PERTE des documents.", levelId: 57 },
  { word: "逸失", meaningsFr: ["Perte"], readings: ["いっしつ"], mnemonicFr: "La PERTE de revenus.", levelId: 57 },
  { word: "喪失", meaningsFr: ["Perte"], readings: ["そうしつ"], mnemonicFr: "La PERTE de mémoire.", levelId: 57 },
  { word: "欠落", meaningsFr: ["Manque", "Lacune"], readings: ["けつらく"], mnemonicFr: "Une LACUNE importante.", levelId: 57 },
  { word: "欠如", meaningsFr: ["Manque", "Absence"], readings: ["けつじょ"], mnemonicFr: "L'ABSENCE de preuves.", levelId: 57 },
  { word: "不在", meaningsFr: ["Absence"], readings: ["ふざい"], mnemonicFr: "L'ABSENCE prolongée.", levelId: 57 },
  { word: "空白", meaningsFr: ["Vide", "Blanc"], readings: ["くうはく"], mnemonicFr: "Un VIDE à combler.", levelId: 57 },
  { word: "空虚", meaningsFr: ["Vacuité", "Vide"], readings: ["くうきょ"], mnemonicFr: "Le VIDE existentiel.", levelId: 57 },
  { word: "虚無", meaningsFr: ["Néant", "Nihilisme"], readings: ["きょむ"], mnemonicFr: "Le NÉANT philosophique.", levelId: 57 },
  { word: "無", meaningsFr: ["Néant", "Rien"], readings: ["む"], mnemonicFr: "Le RIEN absolu.", levelId: 57 },
  { word: "有無", meaningsFr: ["Existence ou non"], readings: ["うむ"], mnemonicFr: "L'EXISTENCE OU NON de preuves.", levelId: 57 },
  { word: "実存", meaningsFr: ["Existence"], readings: ["じつぞん"], mnemonicFr: "L'EXISTENCE humaine.", levelId: 57 },
  { word: "存在", meaningsFr: ["Existence", "Être"], readings: ["そんざい"], mnemonicFr: "L'EXISTENCE de Dieu.", levelId: 57 },
  { word: "存亡", meaningsFr: ["Survie ou mort"], readings: ["そんぼう"], mnemonicFr: "La SURVIE OU MORT de l'entreprise.", levelId: 57 },
  { word: "生存", meaningsFr: ["Survie"], readings: ["せいぞん"], mnemonicFr: "La SURVIE en milieu hostile.", levelId: 57 },
  { word: "生死", meaningsFr: ["Vie et mort"], readings: ["せいし"], mnemonicFr: "Une question de VIE ET MORT.", levelId: 57 },
  { word: "死活", meaningsFr: ["Vie ou mort"], readings: ["しかつ"], mnemonicFr: "Une question de VIE OU MORT.", levelId: 57 },
  { word: "生殺", meaningsFr: ["Vie et mort"], readings: ["せいさつ"], mnemonicFr: "Le pouvoir de VIE ET MORT.", levelId: 57 },
  { word: "存続", meaningsFr: ["Continuité", "Survie"], readings: ["そんぞく"], mnemonicFr: "La CONTINUITÉ de l'espèce.", levelId: 57 },
  { word: "永続", meaningsFr: ["Perpétuité"], readings: ["えいぞく"], mnemonicFr: "La PERPÉTUITÉ de la mémoire.", levelId: 57 },
  { word: "持続", meaningsFr: ["Durabilité", "Continuité"], readings: ["じぞく"], mnemonicFr: "La DURABILITÉ du développement.", levelId: 57 },
  { word: "連続", meaningsFr: ["Continuité", "Suite"], readings: ["れんぞく"], mnemonicFr: "La CONTINUITÉ des événements.", levelId: 57 },
  { word: "継続", meaningsFr: ["Continuation"], readings: ["けいぞく"], mnemonicFr: "La CONTINUATION du projet.", levelId: 57 },
  { word: "恒常", meaningsFr: ["Constance", "Permanence"], readings: ["こうじょう"], mnemonicFr: "La PERMANENCE des lois.", levelId: 57 },
  { word: "恒久", meaningsFr: ["Permanent", "Durable"], readings: ["こうきゅう"], mnemonicFr: "Une paix PERMANENTE.", levelId: 57 },
  { word: "永遠", meaningsFr: ["Éternité"], readings: ["えいえん"], mnemonicFr: "L'ÉTERNITÉ promise.", levelId: 57 },

  // Level 58 - N1 Philosophical/Abstract vocabulary
  { word: "不変", meaningsFr: ["Immuable", "Constant"], readings: ["ふへん"], mnemonicFr: "Une vérité IMMUABLE.", levelId: 58 },
  { word: "不朽", meaningsFr: ["Impérissable"], readings: ["ふきゅう"], mnemonicFr: "Une œuvre IMPÉRISSABLE.", levelId: 58 },
  { word: "不滅", meaningsFr: ["Immortel", "Éternel"], readings: ["ふめつ"], mnemonicFr: "Un amour IMMORTEL.", levelId: 58 },
  { word: "不死", meaningsFr: ["Immortalité"], readings: ["ふし"], mnemonicFr: "L'IMMORTALITÉ recherchée.", levelId: 58 },
  { word: "不老", meaningsFr: ["Jeunesse éternelle"], readings: ["ふろう"], mnemonicFr: "La JEUNESSE ÉTERNELLE.", levelId: 58 },
  { word: "不屈", meaningsFr: ["Indomptable"], readings: ["ふくつ"], mnemonicFr: "Un esprit INDOMPTABLE.", levelId: 58 },
  { word: "不撓", meaningsFr: ["Inflexible"], readings: ["ふとう"], mnemonicFr: "Une volonté INFLEXIBLE.", levelId: 58 },
  { word: "不動", meaningsFr: ["Immobile", "Ferme"], readings: ["ふどう"], mnemonicFr: "Une position FERME.", levelId: 58 },
  { word: "堅固", meaningsFr: ["Solide", "Ferme"], readings: ["けんご"], mnemonicFr: "Une forteresse SOLIDE.", levelId: 58 },
  { word: "堅牢", meaningsFr: ["Robuste", "Solide"], readings: ["けんろう"], mnemonicFr: "Une construction ROBUSTE.", levelId: 58 },
  { word: "強固", meaningsFr: ["Fort", "Solide"], readings: ["きょうこ"], mnemonicFr: "Une alliance FORTE.", levelId: 58 },
  { word: "強靭", meaningsFr: ["Résistant", "Tenace"], readings: ["きょうじん"], mnemonicFr: "Une volonté RÉSISTANTE.", levelId: 58 },
  { word: "頑強", meaningsFr: ["Tenace", "Obstiné"], readings: ["がんきょう"], mnemonicFr: "Une résistance TENACE.", levelId: 58 },
  { word: "頑固", meaningsFr: ["Têtu", "Obstiné"], readings: ["がんこ"], mnemonicFr: "Un caractère TÊTU.", levelId: 58 },
  { word: "強情", meaningsFr: ["Entêté"], readings: ["ごうじょう"], mnemonicFr: "Un enfant ENTÊTÉ.", levelId: 58 },
  { word: "意固地", meaningsFr: ["Obstiné", "Buté"], readings: ["いこじ"], mnemonicFr: "Une attitude BUTÉE.", levelId: 58 },
  { word: "固執", meaningsFr: ["Obstination"], readings: ["こしつ"], mnemonicFr: "L'OBSTINATION à vouloir.", levelId: 58 },
  { word: "執着", meaningsFr: ["Attachement"], readings: ["しゅうちゃく"], mnemonicFr: "L'ATTACHEMENT au passé.", levelId: 58 },
  { word: "執念", meaningsFr: ["Persévérance", "Obsession"], readings: ["しゅうねん"], mnemonicFr: "La PERSÉVÉRANCE acharnée.", levelId: 58 },
  { word: "妄執", meaningsFr: ["Obsession aveugle"], readings: ["もうしゅう"], mnemonicFr: "Une OBSESSION AVEUGLE.", levelId: 58 },
  { word: "妄想", meaningsFr: ["Illusion", "Délire"], readings: ["もうそう"], mnemonicFr: "Des ILLUSIONS dangereuses.", levelId: 58 },
  { word: "幻想", meaningsFr: ["Fantasme", "Illusion"], readings: ["げんそう"], mnemonicFr: "Un FANTASME irréalisable.", levelId: 58 },
  { word: "錯覚", meaningsFr: ["Illusion", "Méprise"], readings: ["さっかく"], mnemonicFr: "Une ILLUSION optique.", levelId: 58 },
  { word: "錯誤", meaningsFr: ["Erreur", "Méprise"], readings: ["さくご"], mnemonicFr: "Une ERREUR de jugement.", levelId: 58 },
  { word: "誤解", meaningsFr: ["Malentendu"], readings: ["ごかい"], mnemonicFr: "Un MALENTENDU fâcheux.", levelId: 58 },
  { word: "誤認", meaningsFr: ["Identification erronée"], readings: ["ごにん"], mnemonicFr: "Une IDENTIFICATION ERRONÉE.", levelId: 58 },
  { word: "誤算", meaningsFr: ["Erreur de calcul"], readings: ["ごさん"], mnemonicFr: "Une ERREUR DE CALCUL.", levelId: 58 },
  { word: "失策", meaningsFr: ["Erreur", "Gaffe"], readings: ["しっさく"], mnemonicFr: "Une GAFFE diplomatique.", levelId: 58 },
  { word: "失態", meaningsFr: ["Gaffe", "Bévue"], readings: ["しったい"], mnemonicFr: "Une BÉVUE embarrassante.", levelId: 58 },
  { word: "醜態", meaningsFr: ["Comportement honteux"], readings: ["しゅうたい"], mnemonicFr: "Un COMPORTEMENT HONTEUX.", levelId: 58 },
  { word: "醜聞", meaningsFr: ["Scandale"], readings: ["しゅうぶん"], mnemonicFr: "Un SCANDALE politique.", levelId: 58 },
  { word: "不祥事", meaningsFr: ["Incident fâcheux"], readings: ["ふしょうじ"], mnemonicFr: "Un INCIDENT FÂCHEUX.", levelId: 58 },
  { word: "不始末", meaningsFr: ["Négligence", "Faute"], readings: ["ふしまつ"], mnemonicFr: "Une NÉGLIGENCE grave.", levelId: 58 },
  { word: "不手際", meaningsFr: ["Maladresse", "Erreur"], readings: ["ふてぎわ"], mnemonicFr: "Une MALADRESSE regrettable.", levelId: 58 },
  { word: "手落ち", meaningsFr: ["Négligence", "Oubli"], readings: ["ておち"], mnemonicFr: "Un OUBLI fâcheux.", levelId: 58 },
  { word: "見落とし", meaningsFr: ["Omission"], readings: ["みおとし"], mnemonicFr: "Une OMISSION importante.", levelId: 58 },
  { word: "見過ごし", meaningsFr: ["Négligence"], readings: ["みすごし"], mnemonicFr: "Une NÉGLIGENCE coupable.", levelId: 58 },
  { word: "看過", meaningsFr: ["Tolérance", "Fermer les yeux"], readings: ["かんか"], mnemonicFr: "FERMER LES YEUX sur l'erreur.", levelId: 58 },
  { word: "黙認", meaningsFr: ["Tolérance tacite"], readings: ["もくにん"], mnemonicFr: "Une TOLÉRANCE TACITE.", levelId: 58 },
  { word: "黙殺", meaningsFr: ["Ignorer délibérément"], readings: ["もくさつ"], mnemonicFr: "IGNORER DÉLIBÉRÉMENT.", levelId: 58 },

  // Level 59 - N1 Elevated/Formal vocabulary
  { word: "黙秘", meaningsFr: ["Silence", "Mutisme"], readings: ["もくひ"], mnemonicFr: "Garder le SILENCE.", levelId: 59 },
  { word: "沈黙", meaningsFr: ["Silence"], readings: ["ちんもく"], mnemonicFr: "Le SILENCE pesant.", levelId: 59 },
  { word: "寡黙", meaningsFr: ["Taciturne"], readings: ["かもく"], mnemonicFr: "Un homme TACITURNE.", levelId: 59 },
  { word: "無口", meaningsFr: ["Silencieux", "Peu bavard"], readings: ["むくち"], mnemonicFr: "Un enfant PEU BAVARD.", levelId: 59 },
  { word: "口下手", meaningsFr: ["Mauvais orateur"], readings: ["くちべた"], mnemonicFr: "Un MAUVAIS ORATEUR.", levelId: 59 },
  { word: "雄弁", meaningsFr: ["Éloquence"], readings: ["ゆうべん"], mnemonicFr: "L'ÉLOQUENCE du leader.", levelId: 59 },
  { word: "能弁", meaningsFr: ["Éloquent"], readings: ["のうべん"], mnemonicFr: "Un orateur ÉLOQUENT.", levelId: 59 },
  { word: "詭弁", meaningsFr: ["Sophisme"], readings: ["きべん"], mnemonicFr: "Un SOPHISME trompeur.", levelId: 59 },
  { word: "弁舌", meaningsFr: ["Éloquence"], readings: ["べんぜつ"], mnemonicFr: "Une ÉLOQUENCE remarquable.", levelId: 59 },
  { word: "弁論", meaningsFr: ["Plaidoyer", "Discours"], readings: ["べんろん"], mnemonicFr: "Un DISCOURS passionné.", levelId: 59 },
  { word: "論議", meaningsFr: ["Débat", "Discussion"], readings: ["ろんぎ"], mnemonicFr: "Un DÉBAT animé.", levelId: 59 },
  { word: "論争", meaningsFr: ["Controverse"], readings: ["ろんそう"], mnemonicFr: "Une CONTROVERSE publique.", levelId: 59 },
  { word: "口論", meaningsFr: ["Dispute verbale"], readings: ["こうろん"], mnemonicFr: "Une DISPUTE VERBALE.", levelId: 59 },
  { word: "論駁", meaningsFr: ["Réfutation"], readings: ["ろんばく"], mnemonicFr: "Une RÉFUTATION solide.", levelId: 59 },
  { word: "反駁", meaningsFr: ["Réfutation", "Objection"], readings: ["はんばく"], mnemonicFr: "Une OBJECTION fondée.", levelId: 59 },
  { word: "抗弁", meaningsFr: ["Protestation"], readings: ["こうべん"], mnemonicFr: "Une PROTESTATION véhémente.", levelId: 59 },
  { word: "弁明", meaningsFr: ["Justification"], readings: ["べんめい"], mnemonicFr: "Une JUSTIFICATION nécessaire.", levelId: 59 },
  { word: "弁解", meaningsFr: ["Excuse", "Justification"], readings: ["べんかい"], mnemonicFr: "Une EXCUSE maladroite.", levelId: 59 },
  { word: "釈明", meaningsFr: ["Explication"], readings: ["しゃくめい"], mnemonicFr: "Une EXPLICATION officielle.", levelId: 59 },
  { word: "申し開き", meaningsFr: ["Justification"], readings: ["もうしひらき"], mnemonicFr: "Une JUSTIFICATION difficile.", levelId: 59 },
  { word: "言い訳", meaningsFr: ["Excuse"], readings: ["いいわけ"], mnemonicFr: "Une EXCUSE facile.", levelId: 59 },
  { word: "言い逃れ", meaningsFr: ["Échappatoire"], readings: ["いいのがれ"], mnemonicFr: "Une ÉCHAPPATOIRE commode.", levelId: 59 },
  { word: "逃げ口上", meaningsFr: ["Prétexte"], readings: ["にげこうじょう"], mnemonicFr: "Un PRÉTEXTE fallacieux.", levelId: 59 },
  { word: "口実", meaningsFr: ["Prétexte"], readings: ["こうじつ"], mnemonicFr: "Un PRÉTEXTE pour agir.", levelId: 59 },
  { word: "名目", meaningsFr: ["Prétexte", "Nom"], readings: ["めいもく"], mnemonicFr: "Sous le NOM de.", levelId: 59 },
  { word: "建前", meaningsFr: ["Apparence", "Façade"], readings: ["たてまえ"], mnemonicFr: "La FAÇADE officielle.", levelId: 59 },
  { word: "本音", meaningsFr: ["Vraie intention"], readings: ["ほんね"], mnemonicFr: "Les VRAIES INTENTIONS.", levelId: 59 },
  { word: "真意", meaningsFr: ["Vraie intention"], readings: ["しんい"], mnemonicFr: "La VRAIE INTENTION cachée.", levelId: 59 },
  { word: "意中", meaningsFr: ["Dans l'esprit", "Intentions"], readings: ["いちゅう"], mnemonicFr: "Dans son ESPRIT.", levelId: 59 },
  { word: "胸中", meaningsFr: ["Dans le cœur"], readings: ["きょうちゅう"], mnemonicFr: "Dans son CŒUR.", levelId: 59 },
  { word: "心中", meaningsFr: ["Dans le cœur", "Suicide"], readings: ["しんちゅう"], mnemonicFr: "Dans son CŒUR profond.", levelId: 59 },
  { word: "腹中", meaningsFr: ["Dans l'esprit"], readings: ["ふくちゅう"], mnemonicFr: "Dans son ESPRIT secret.", levelId: 59 },
  { word: "胸算用", meaningsFr: ["Calcul mental"], readings: ["むなざんよう"], mnemonicFr: "Un CALCUL MENTAL.", levelId: 59 },
  { word: "目論見", meaningsFr: ["Plan", "Projet"], readings: ["もくろみ"], mnemonicFr: "Un PLAN secret.", levelId: 59 },
  { word: "企み", meaningsFr: ["Complot", "Machination"], readings: ["たくらみ"], mnemonicFr: "Un COMPLOT dangereux.", levelId: 59 },
  { word: "陰謀", meaningsFr: ["Conspiration"], readings: ["いんぼう"], mnemonicFr: "Une CONSPIRATION politique.", levelId: 59 },
  { word: "謀略", meaningsFr: ["Stratagème"], readings: ["ぼうりゃく"], mnemonicFr: "Un STRATAGÈME militaire.", levelId: 59 },
  { word: "策略", meaningsFr: ["Tactique", "Ruse"], readings: ["さくりゃく"], mnemonicFr: "Une TACTIQUE habile.", levelId: 59 },
  { word: "権謀術数", meaningsFr: ["Machinations politiques"], readings: ["けんぼうじゅっすう"], mnemonicFr: "Les MACHINATIONS POLITIQUES.", levelId: 59 },
  { word: "駆け引き", meaningsFr: ["Négociation", "Manœuvre"], readings: ["かけひき"], mnemonicFr: "Une NÉGOCIATION serrée.", levelId: 59 },

  // Level 60 - N1 Master level vocabulary
  { word: "腹芸", meaningsFr: ["Art de la dissimulation"], readings: ["はらげい"], mnemonicFr: "L'ART DE LA DISSIMULATION.", levelId: 60 },
  { word: "芝居", meaningsFr: ["Comédie", "Théâtre"], readings: ["しばい"], mnemonicFr: "Une COMÉDIE jouée.", levelId: 60 },
  { word: "茶番", meaningsFr: ["Farce", "Mascarade"], readings: ["ちゃばん"], mnemonicFr: "Une FARCE ridicule.", levelId: 60 },
  { word: "猿芝居", meaningsFr: ["Mauvaise comédie"], readings: ["さるしばい"], mnemonicFr: "Une MAUVAISE COMÉDIE.", levelId: 60 },
  { word: "八百長", meaningsFr: ["Match truqué"], readings: ["やおちょう"], mnemonicFr: "Un MATCH TRUQUÉ.", levelId: 60 },
  { word: "出来レース", meaningsFr: ["Résultat prévu d'avance"], readings: ["できレース"], mnemonicFr: "Un RÉSULTAT PRÉVU D'AVANCE.", levelId: 60 },
  { word: "裏取引", meaningsFr: ["Transaction secrète"], readings: ["うらとりひき"], mnemonicFr: "Une TRANSACTION SECRÈTE.", levelId: 60 },
  { word: "裏工作", meaningsFr: ["Manœuvre secrète"], readings: ["うらこうさく"], mnemonicFr: "Une MANŒUVRE SECRÈTE.", levelId: 60 },
  { word: "根回し", meaningsFr: ["Préparation en coulisse"], readings: ["ねまわし"], mnemonicFr: "Une PRÉPARATION EN COULISSE.", levelId: 60 },
  { word: "手回し", meaningsFr: ["Préparatifs"], readings: ["てまわし"], mnemonicFr: "Les PRÉPARATIFS nécessaires.", levelId: 60 },
  { word: "段取り", meaningsFr: ["Organisation", "Étapes"], readings: ["だんどり"], mnemonicFr: "L'ORGANISATION des étapes.", levelId: 60 },
  { word: "手順", meaningsFr: ["Procédure"], readings: ["てじゅん"], mnemonicFr: "La PROCÉDURE à suivre.", levelId: 60 },
  { word: "手続き", meaningsFr: ["Formalités"], readings: ["てつづき"], mnemonicFr: "Les FORMALITÉS administratives.", levelId: 60 },
  { word: "手配", meaningsFr: ["Arrangements"], readings: ["てはい"], mnemonicFr: "Les ARRANGEMENTS nécessaires.", levelId: 60 },
  { word: "采配", meaningsFr: ["Direction"], readings: ["さいはい"], mnemonicFr: "La DIRECTION des opérations.", levelId: 60 },
  { word: "差配", meaningsFr: ["Administration"], readings: ["さはい"], mnemonicFr: "L'ADMINISTRATION du domaine.", levelId: 60 },
  { word: "配慮", meaningsFr: ["Considération"], readings: ["はいりょ"], mnemonicFr: "La CONSIDÉRATION pour autrui.", levelId: 60 },
  { word: "思慮", meaningsFr: ["Réflexion", "Prudence"], readings: ["しりょ"], mnemonicFr: "La RÉFLEXION avant l'action.", levelId: 60 },
  { word: "熟慮", meaningsFr: ["Mûre réflexion"], readings: ["じゅくりょ"], mnemonicFr: "Une MÛRE RÉFLEXION.", levelId: 60 },
  { word: "深慮", meaningsFr: ["Réflexion profonde"], readings: ["しんりょ"], mnemonicFr: "Une RÉFLEXION PROFONDE.", levelId: 60 },
  { word: "遠慮", meaningsFr: ["Retenue", "Réserve"], readings: ["えんりょ"], mnemonicFr: "La RÉSERVE polie.", levelId: 60 },
  { word: "憂慮", meaningsFr: ["Inquiétude", "Souci"], readings: ["ゆうりょ"], mnemonicFr: "L'INQUIÉTUDE face à l'avenir.", levelId: 60 },
  { word: "苦慮", meaningsFr: ["Préoccupation"], readings: ["くりょ"], mnemonicFr: "La PRÉOCCUPATION constante.", levelId: 60 },
  { word: "考慮", meaningsFr: ["Considération"], readings: ["こうりょ"], mnemonicFr: "Prendre en CONSIDÉRATION.", levelId: 60 },
  { word: "顧慮", meaningsFr: ["Égard"], readings: ["こりょ"], mnemonicFr: "Avoir des ÉGARDS.", levelId: 60 },
  { word: "一顧", meaningsFr: ["Un regard"], readings: ["いっこ"], mnemonicFr: "UN REGARD attentif.", levelId: 60 },
  { word: "回顧", meaningsFr: ["Rétrospective"], readings: ["かいこ"], mnemonicFr: "Une RÉTROSPECTIVE historique.", levelId: 60 },
  { word: "顧問", meaningsFr: ["Conseiller"], readings: ["こもん"], mnemonicFr: "Un CONSEILLER expérimenté.", levelId: 60 },
  { word: "諮問", meaningsFr: ["Consultation"], readings: ["しもん"], mnemonicFr: "Une CONSULTATION officielle.", levelId: 60 },
  { word: "諮詢", meaningsFr: ["Demande de conseil"], readings: ["しじゅん"], mnemonicFr: "Une DEMANDE DE CONSEIL.", levelId: 60 },
  { word: "詮議", meaningsFr: ["Enquête", "Examen"], readings: ["せんぎ"], mnemonicFr: "Une ENQUÊTE approfondie.", levelId: 60 },
  { word: "吟味", meaningsFr: ["Examen minutieux"], readings: ["ぎんみ"], mnemonicFr: "Un EXAMEN MINUTIEUX.", levelId: 60 },
  { word: "精査", meaningsFr: ["Examen approfondi"], readings: ["せいさ"], mnemonicFr: "Un EXAMEN APPROFONDI.", levelId: 60 },
  { word: "検分", meaningsFr: ["Inspection"], readings: ["けんぶん"], mnemonicFr: "Une INSPECTION sur place.", levelId: 60 },
  { word: "視察", meaningsFr: ["Inspection officielle"], readings: ["しさつ"], mnemonicFr: "Une INSPECTION OFFICIELLE.", levelId: 60 },
  { word: "査察", meaningsFr: ["Inspection", "Audit"], readings: ["ささつ"], mnemonicFr: "Une INSPECTION rigoureuse.", levelId: 60 },
  { word: "巡視", meaningsFr: ["Tournée d'inspection"], readings: ["じゅんし"], mnemonicFr: "Une TOURNÉE D'INSPECTION.", levelId: 60 },
  { word: "巡回", meaningsFr: ["Ronde", "Tournée"], readings: ["じゅんかい"], mnemonicFr: "Une RONDE de surveillance.", levelId: 60 },
  { word: "巡礼", meaningsFr: ["Pèlerinage"], readings: ["じゅんれい"], mnemonicFr: "Un PÈLERINAGE sacré.", levelId: 60 },
  { word: "参詣", meaningsFr: ["Visite au temple"], readings: ["さんけい"], mnemonicFr: "Une VISITE AU TEMPLE.", levelId: 60 },
];

async function main() {
  console.log("Seeding vocabulary supplement for levels 56-60...");

  for (const vocab of vocabularyData) {
    await prisma.vocabulary.upsert({
      where: {
        word_levelId: {
          word: vocab.word,
          levelId: vocab.levelId,
        },
      },
      update: {
        meaningsFr: vocab.meaningsFr,
        readings: vocab.readings,
        mnemonicFr: vocab.mnemonicFr,
      },
      create: vocab,
    });
  }

  console.log(`Seeded ${vocabularyData.length} vocabulary words for levels 56-60.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
