import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Vocabulary supplement for levels 21-25
// Adding ~50 words per level to reach target of ~80-100 per level

const vocabularyData = [
  // Level 21 - JLPT N3 vocabulary (intermediate)
  { word: "相談", meaningsFr: ["Consultation", "Discussion"], readings: ["そうだん"], mnemonicFr: "Pour une CONSULTATION, on discute ensemble.", levelId: 21 },
  { word: "経験", meaningsFr: ["Expérience"], readings: ["けいけん"], mnemonicFr: "L'EXPÉRIENCE s'acquiert avec le temps.", levelId: 21 },
  { word: "準備", meaningsFr: ["Préparation"], readings: ["じゅんび"], mnemonicFr: "La PRÉPARATION est la clé du succès.", levelId: 21 },
  { word: "関係", meaningsFr: ["Relation", "Rapport"], readings: ["かんけい"], mnemonicFr: "La RELATION entre les choses.", levelId: 21 },
  { word: "説明", meaningsFr: ["Explication"], readings: ["せつめい"], mnemonicFr: "Une EXPLICATION claire est nécessaire.", levelId: 21 },
  { word: "成功", meaningsFr: ["Succès", "Réussite"], readings: ["せいこう"], mnemonicFr: "Le SUCCÈS vient après l'effort.", levelId: 21 },
  { word: "失敗", meaningsFr: ["Échec"], readings: ["しっぱい"], mnemonicFr: "L'ÉCHEC est un tremplin vers le succès.", levelId: 21 },
  { word: "変化", meaningsFr: ["Changement", "Transformation"], readings: ["へんか"], mnemonicFr: "Le CHANGEMENT est constant.", levelId: 21 },
  { word: "影響", meaningsFr: ["Influence", "Effet"], readings: ["えいきょう"], mnemonicFr: "L'INFLUENCE peut être positive ou négative.", levelId: 21 },
  { word: "状況", meaningsFr: ["Situation", "Circonstances"], readings: ["じょうきょう"], mnemonicFr: "La SITUATION actuelle est complexe.", levelId: 21 },
  { word: "目標", meaningsFr: ["Objectif", "But"], readings: ["もくひょう"], mnemonicFr: "Un OBJECTIF clair guide nos actions.", levelId: 21 },
  { word: "努力", meaningsFr: ["Effort"], readings: ["どりょく"], mnemonicFr: "L'EFFORT constant mène au succès.", levelId: 21 },
  { word: "結局", meaningsFr: ["Finalement", "En fin de compte"], readings: ["けっきょく"], mnemonicFr: "FINALEMENT, tout s'est bien passé.", levelId: 21 },
  { word: "最近", meaningsFr: ["Récemment", "Ces derniers temps"], readings: ["さいきん"], mnemonicFr: "RÉCEMMENT, j'ai beaucoup étudié.", levelId: 21 },
  { word: "将来", meaningsFr: ["Avenir", "Futur"], readings: ["しょうらい"], mnemonicFr: "L'AVENIR nous réserve des surprises.", levelId: 21 },
  { word: "以前", meaningsFr: ["Avant", "Auparavant"], readings: ["いぜん"], mnemonicFr: "AVANT, les choses étaient différentes.", levelId: 21 },
  { word: "以後", meaningsFr: ["Après", "Désormais"], readings: ["いご"], mnemonicFr: "DÉSORMAIS, je ferai attention.", levelId: 21 },
  { word: "現在", meaningsFr: ["Actuellement", "Présent"], readings: ["げんざい"], mnemonicFr: "ACTUELLEMENT, je suis occupé.", levelId: 21 },
  { word: "反対", meaningsFr: ["Opposition", "Contraire"], readings: ["はんたい"], mnemonicFr: "Je suis OPPOSÉ à cette idée.", levelId: 21 },
  { word: "賛成", meaningsFr: ["Accord", "Approbation"], readings: ["さんせい"], mnemonicFr: "Je suis d'ACCORD avec toi.", levelId: 21 },
  { word: "意見", meaningsFr: ["Opinion", "Avis"], readings: ["いけん"], mnemonicFr: "Chacun a son OPINION.", levelId: 21 },
  { word: "提案", meaningsFr: ["Proposition", "Suggestion"], readings: ["ていあん"], mnemonicFr: "Une PROPOSITION intéressante.", levelId: 21 },
  { word: "決定", meaningsFr: ["Décision"], readings: ["けってい"], mnemonicFr: "La DÉCISION finale a été prise.", levelId: 21 },
  { word: "確認", meaningsFr: ["Confirmation", "Vérification"], readings: ["かくにん"], mnemonicFr: "Une CONFIRMATION est nécessaire.", levelId: 21 },
  { word: "連絡", meaningsFr: ["Contact", "Communication"], readings: ["れんらく"], mnemonicFr: "Reste en CONTACT avec moi.", levelId: 21 },
  { word: "紹介", meaningsFr: ["Présentation", "Introduction"], readings: ["しょうかい"], mnemonicFr: "Laisse-moi faire les PRÉSENTATIONS.", levelId: 21 },
  { word: "参加", meaningsFr: ["Participation"], readings: ["さんか"], mnemonicFr: "La PARTICIPATION est obligatoire.", levelId: 21 },
  { word: "出席", meaningsFr: ["Présence", "Assistance"], readings: ["しゅっせき"], mnemonicFr: "Ta PRÉSENCE est requise.", levelId: 21 },
  { word: "欠席", meaningsFr: ["Absence"], readings: ["けっせき"], mnemonicFr: "Son ABSENCE a été remarquée.", levelId: 21 },
  { word: "遅刻", meaningsFr: ["Retard"], readings: ["ちこく"], mnemonicFr: "Le RETARD n'est pas accepté.", levelId: 21 },
  { word: "予約", meaningsFr: ["Réservation"], readings: ["よやく"], mnemonicFr: "J'ai fait une RÉSERVATION.", levelId: 21 },
  { word: "申込", meaningsFr: ["Inscription", "Candidature"], readings: ["もうしこみ"], mnemonicFr: "L'INSCRIPTION est ouverte.", levelId: 21 },
  { word: "締切", meaningsFr: ["Date limite", "Échéance"], readings: ["しめきり"], mnemonicFr: "La DATE LIMITE approche.", levelId: 21 },
  { word: "延期", meaningsFr: ["Report", "Ajournement"], readings: ["えんき"], mnemonicFr: "Le REPORT a été annoncé.", levelId: 21 },
  { word: "中止", meaningsFr: ["Annulation", "Arrêt"], readings: ["ちゅうし"], mnemonicFr: "L'ANNULATION était inévitable.", levelId: 21 },
  { word: "再開", meaningsFr: ["Reprise", "Réouverture"], readings: ["さいかい"], mnemonicFr: "La REPRISE des activités.", levelId: 21 },
  { word: "終了", meaningsFr: ["Fin", "Achèvement"], readings: ["しゅうりょう"], mnemonicFr: "La FIN du programme.", levelId: 21 },
  { word: "開始", meaningsFr: ["Début", "Commencement"], readings: ["かいし"], mnemonicFr: "Le DÉBUT des opérations.", levelId: 21 },
  { word: "継続", meaningsFr: ["Continuation", "Poursuite"], readings: ["けいぞく"], mnemonicFr: "La CONTINUATION du projet.", levelId: 21 },
  { word: "中断", meaningsFr: ["Interruption"], readings: ["ちゅうだん"], mnemonicFr: "Une INTERRUPTION temporaire.", levelId: 21 },
  { word: "完成", meaningsFr: ["Achèvement", "Accomplissement"], readings: ["かんせい"], mnemonicFr: "L'ACHÈVEMENT du travail.", levelId: 21 },
  { word: "進行", meaningsFr: ["Progression", "Déroulement"], readings: ["しんこう"], mnemonicFr: "La PROGRESSION est bonne.", levelId: 21 },
  { word: "発展", meaningsFr: ["Développement", "Expansion"], readings: ["はってん"], mnemonicFr: "Le DÉVELOPPEMENT économique.", levelId: 21 },
  { word: "成長", meaningsFr: ["Croissance", "Développement"], readings: ["せいちょう"], mnemonicFr: "La CROISSANCE personnelle.", levelId: 21 },
  { word: "改善", meaningsFr: ["Amélioration"], readings: ["かいぜん"], mnemonicFr: "L'AMÉLIORATION continue.", levelId: 21 },
  { word: "解決", meaningsFr: ["Résolution", "Solution"], readings: ["かいけつ"], mnemonicFr: "La RÉSOLUTION du problème.", levelId: 21 },
  { word: "問題点", meaningsFr: ["Point problématique"], readings: ["もんだいてん"], mnemonicFr: "Le POINT PROBLÉMATIQUE a été identifié.", levelId: 21 },
  { word: "原因", meaningsFr: ["Cause", "Raison"], readings: ["げんいん"], mnemonicFr: "La CAUSE de l'accident.", levelId: 21 },
  { word: "結果", meaningsFr: ["Résultat", "Conséquence"], readings: ["けっか"], mnemonicFr: "Le RÉSULTAT est positif.", levelId: 21 },
  { word: "対策", meaningsFr: ["Mesure", "Contre-mesure"], readings: ["たいさく"], mnemonicFr: "Les MESURES nécessaires.", levelId: 21 },

  // Level 22 - JLPT N3 vocabulary (intermediate)
  { word: "教育", meaningsFr: ["Éducation", "Enseignement"], readings: ["きょういく"], mnemonicFr: "L'ÉDUCATION est fondamentale.", levelId: 22 },
  { word: "学習", meaningsFr: ["Apprentissage", "Étude"], readings: ["がくしゅう"], mnemonicFr: "L'APPRENTISSAGE est continu.", levelId: 22 },
  { word: "研究", meaningsFr: ["Recherche", "Étude"], readings: ["けんきゅう"], mnemonicFr: "La RECHERCHE scientifique.", levelId: 22 },
  { word: "調査", meaningsFr: ["Enquête", "Investigation"], readings: ["ちょうさ"], mnemonicFr: "Une ENQUÊTE approfondie.", levelId: 22 },
  { word: "分析", meaningsFr: ["Analyse"], readings: ["ぶんせき"], mnemonicFr: "L'ANALYSE des données.", levelId: 22 },
  { word: "比較", meaningsFr: ["Comparaison"], readings: ["ひかく"], mnemonicFr: "Une COMPARAISON utile.", levelId: 22 },
  { word: "検討", meaningsFr: ["Examen", "Considération"], readings: ["けんとう"], mnemonicFr: "L'EXAMEN de la question.", levelId: 22 },
  { word: "判断", meaningsFr: ["Jugement", "Décision"], readings: ["はんだん"], mnemonicFr: "Un bon JUGEMENT est essentiel.", levelId: 22 },
  { word: "評価", meaningsFr: ["Évaluation", "Appréciation"], readings: ["ひょうか"], mnemonicFr: "L'ÉVALUATION des résultats.", levelId: 22 },
  { word: "批判", meaningsFr: ["Critique"], readings: ["ひはん"], mnemonicFr: "La CRITIQUE constructive.", levelId: 22 },
  { word: "支持", meaningsFr: ["Soutien", "Appui"], readings: ["しじ"], mnemonicFr: "Le SOUTIEN de mes amis.", levelId: 22 },
  { word: "協力", meaningsFr: ["Coopération", "Collaboration"], readings: ["きょうりょく"], mnemonicFr: "La COOPÉRATION est nécessaire.", levelId: 22 },
  { word: "競争", meaningsFr: ["Concurrence", "Compétition"], readings: ["きょうそう"], mnemonicFr: "La CONCURRENCE est forte.", levelId: 22 },
  { word: "交流", meaningsFr: ["Échange", "Interaction"], readings: ["こうりゅう"], mnemonicFr: "L'ÉCHANGE culturel.", levelId: 22 },
  { word: "交渉", meaningsFr: ["Négociation"], readings: ["こうしょう"], mnemonicFr: "La NÉGOCIATION continue.", levelId: 22 },
  { word: "契約", meaningsFr: ["Contrat"], readings: ["けいやく"], mnemonicFr: "Signer un CONTRAT.", levelId: 22 },
  { word: "約束", meaningsFr: ["Promesse", "Rendez-vous"], readings: ["やくそく"], mnemonicFr: "Une PROMESSE à tenir.", levelId: 22 },
  { word: "責任", meaningsFr: ["Responsabilité"], readings: ["せきにん"], mnemonicFr: "La RESPONSABILITÉ est importante.", levelId: 22 },
  { word: "義務", meaningsFr: ["Obligation", "Devoir"], readings: ["ぎむ"], mnemonicFr: "C'est une OBLIGATION.", levelId: 22 },
  { word: "権利", meaningsFr: ["Droit", "Privilège"], readings: ["けんり"], mnemonicFr: "Nos DROITS fondamentaux.", levelId: 22 },
  { word: "自由", meaningsFr: ["Liberté"], readings: ["じゆう"], mnemonicFr: "La LIBERTÉ d'expression.", levelId: 22 },
  { word: "平等", meaningsFr: ["Égalité"], readings: ["びょうどう"], mnemonicFr: "L'ÉGALITÉ pour tous.", levelId: 22 },
  { word: "公平", meaningsFr: ["Équité", "Impartialité"], readings: ["こうへい"], mnemonicFr: "Un traitement ÉQUITABLE.", levelId: 22 },
  { word: "正義", meaningsFr: ["Justice"], readings: ["せいぎ"], mnemonicFr: "La JUSTICE triomphe.", levelId: 22 },
  { word: "道徳", meaningsFr: ["Morale", "Éthique"], readings: ["どうとく"], mnemonicFr: "Les valeurs MORALES.", levelId: 22 },
  { word: "常識", meaningsFr: ["Bon sens", "Sens commun"], readings: ["じょうしき"], mnemonicFr: "Le BON SENS dicte.", levelId: 22 },
  { word: "知識", meaningsFr: ["Connaissance", "Savoir"], readings: ["ちしき"], mnemonicFr: "La CONNAISSANCE s'acquiert.", levelId: 22 },
  { word: "技術", meaningsFr: ["Technique", "Technologie"], readings: ["ぎじゅつ"], mnemonicFr: "La TECHNIQUE s'améliore.", levelId: 22 },
  { word: "能力", meaningsFr: ["Capacité", "Compétence"], readings: ["のうりょく"], mnemonicFr: "La CAPACITÉ d'adaptation.", levelId: 22 },
  { word: "才能", meaningsFr: ["Talent", "Don"], readings: ["さいのう"], mnemonicFr: "Un grand TALENT.", levelId: 22 },
  { word: "実力", meaningsFr: ["Compétence réelle", "Force"], readings: ["じつりょく"], mnemonicFr: "Montrer sa vraie COMPÉTENCE.", levelId: 22 },
  { word: "資格", meaningsFr: ["Qualification", "Certificat"], readings: ["しかく"], mnemonicFr: "Obtenir une QUALIFICATION.", levelId: 22 },
  { word: "免許", meaningsFr: ["Permis", "Licence"], readings: ["めんきょ"], mnemonicFr: "Avoir son PERMIS.", levelId: 22 },
  { word: "証明", meaningsFr: ["Preuve", "Certification"], readings: ["しょうめい"], mnemonicFr: "La PREUVE est là.", levelId: 22 },
  { word: "証拠", meaningsFr: ["Preuve", "Évidence"], readings: ["しょうこ"], mnemonicFr: "Une PREUVE solide.", levelId: 22 },
  { word: "事実", meaningsFr: ["Fait", "Réalité"], readings: ["じじつ"], mnemonicFr: "C'est un FAIT.", levelId: 22 },
  { word: "真実", meaningsFr: ["Vérité"], readings: ["しんじつ"], mnemonicFr: "La VÉRITÉ doit être dite.", levelId: 22 },
  { word: "現実", meaningsFr: ["Réalité"], readings: ["げんじつ"], mnemonicFr: "La RÉALITÉ est dure.", levelId: 22 },
  { word: "理想", meaningsFr: ["Idéal"], readings: ["りそう"], mnemonicFr: "L'IDÉAL à atteindre.", levelId: 22 },
  { word: "夢想", meaningsFr: ["Rêverie", "Fantasme"], readings: ["むそう"], mnemonicFr: "Une RÊVERIE agréable.", levelId: 22 },
  { word: "想像", meaningsFr: ["Imagination"], readings: ["そうぞう"], mnemonicFr: "L'IMAGINATION sans limites.", levelId: 22 },
  { word: "創造", meaningsFr: ["Création"], readings: ["そうぞう"], mnemonicFr: "La CRÉATION artistique.", levelId: 22 },
  { word: "発明", meaningsFr: ["Invention"], readings: ["はつめい"], mnemonicFr: "Une grande INVENTION.", levelId: 22 },
  { word: "発見", meaningsFr: ["Découverte"], readings: ["はっけん"], mnemonicFr: "Une DÉCOUVERTE importante.", levelId: 22 },
  { word: "表現", meaningsFr: ["Expression"], readings: ["ひょうげん"], mnemonicFr: "L'EXPRESSION créative.", levelId: 22 },
  { word: "描写", meaningsFr: ["Description", "Dépiction"], readings: ["びょうしゃ"], mnemonicFr: "Une DESCRIPTION détaillée.", levelId: 22 },
  { word: "印象", meaningsFr: ["Impression"], readings: ["いんしょう"], mnemonicFr: "Une bonne IMPRESSION.", levelId: 22 },
  { word: "感想", meaningsFr: ["Impression", "Réflexion"], readings: ["かんそう"], mnemonicFr: "Mes IMPRESSIONS personnelles.", levelId: 22 },
  { word: "感情", meaningsFr: ["Émotion", "Sentiment"], readings: ["かんじょう"], mnemonicFr: "Les ÉMOTIONS humaines.", levelId: 22 },
  { word: "感動", meaningsFr: ["Émotion", "Être touché"], readings: ["かんどう"], mnemonicFr: "J'ai été profondément TOUCHÉ.", levelId: 22 },

  // Level 23 - JLPT N3 vocabulary (intermediate)
  { word: "健康", meaningsFr: ["Santé"], readings: ["けんこう"], mnemonicFr: "La SANTÉ est précieuse.", levelId: 23 },
  { word: "病気", meaningsFr: ["Maladie"], readings: ["びょうき"], mnemonicFr: "Tomber MALADE.", levelId: 23 },
  { word: "症状", meaningsFr: ["Symptôme"], readings: ["しょうじょう"], mnemonicFr: "Les SYMPTÔMES sont apparus.", levelId: 23 },
  { word: "治療", meaningsFr: ["Traitement", "Thérapie"], readings: ["ちりょう"], mnemonicFr: "Le TRAITEMENT médical.", levelId: 23 },
  { word: "手術", meaningsFr: ["Opération chirurgicale"], readings: ["しゅじゅつ"], mnemonicFr: "Une OPÉRATION réussie.", levelId: 23 },
  { word: "診察", meaningsFr: ["Consultation médicale"], readings: ["しんさつ"], mnemonicFr: "Une CONSULTATION chez le médecin.", levelId: 23 },
  { word: "検査", meaningsFr: ["Examen médical", "Test"], readings: ["けんさ"], mnemonicFr: "Un EXAMEN médical.", levelId: 23 },
  { word: "予防", meaningsFr: ["Prévention"], readings: ["よぼう"], mnemonicFr: "La PRÉVENTION est importante.", levelId: 23 },
  { word: "回復", meaningsFr: ["Rétablissement", "Récupération"], readings: ["かいふく"], mnemonicFr: "Un RÉTABLISSEMENT rapide.", levelId: 23 },
  { word: "安静", meaningsFr: ["Repos complet"], readings: ["あんせい"], mnemonicFr: "Garder le REPOS complet.", levelId: 23 },
  { word: "運動", meaningsFr: ["Exercice", "Sport"], readings: ["うんどう"], mnemonicFr: "Faire de l'EXERCICE.", levelId: 23 },
  { word: "体力", meaningsFr: ["Force physique", "Endurance"], readings: ["たいりょく"], mnemonicFr: "La FORCE PHYSIQUE s'entretient.", levelId: 23 },
  { word: "疲労", meaningsFr: ["Fatigue", "Épuisement"], readings: ["ひろう"], mnemonicFr: "La FATIGUE s'accumule.", levelId: 23 },
  { word: "休養", meaningsFr: ["Repos", "Récupération"], readings: ["きゅうよう"], mnemonicFr: "Prendre du REPOS.", levelId: 23 },
  { word: "睡眠", meaningsFr: ["Sommeil"], readings: ["すいみん"], mnemonicFr: "Un bon SOMMEIL est essentiel.", levelId: 23 },
  { word: "食事", meaningsFr: ["Repas"], readings: ["しょくじ"], mnemonicFr: "Prendre son REPAS.", levelId: 23 },
  { word: "栄養", meaningsFr: ["Nutrition"], readings: ["えいよう"], mnemonicFr: "Une bonne NUTRITION.", levelId: 23 },
  { word: "消化", meaningsFr: ["Digestion"], readings: ["しょうか"], mnemonicFr: "La DIGESTION prend du temps.", levelId: 23 },
  { word: "呼吸", meaningsFr: ["Respiration"], readings: ["こきゅう"], mnemonicFr: "La RESPIRATION profonde.", levelId: 23 },
  { word: "血圧", meaningsFr: ["Tension artérielle"], readings: ["けつあつ"], mnemonicFr: "Mesurer la TENSION ARTÉRIELLE.", levelId: 23 },
  { word: "体温", meaningsFr: ["Température corporelle"], readings: ["たいおん"], mnemonicFr: "La TEMPÉRATURE CORPORELLE.", levelId: 23 },
  { word: "脈拍", meaningsFr: ["Pouls"], readings: ["みゃくはく"], mnemonicFr: "Prendre le POULS.", levelId: 23 },
  { word: "精神", meaningsFr: ["Esprit", "Mental"], readings: ["せいしん"], mnemonicFr: "La santé MENTALE.", levelId: 23 },
  { word: "心理", meaningsFr: ["Psychologie", "Mental"], readings: ["しんり"], mnemonicFr: "La PSYCHOLOGIE humaine.", levelId: 23 },
  { word: "意識", meaningsFr: ["Conscience", "Conscience"], readings: ["いしき"], mnemonicFr: "Perdre CONSCIENCE.", levelId: 23 },
  { word: "記憶", meaningsFr: ["Mémoire", "Souvenir"], readings: ["きおく"], mnemonicFr: "La MÉMOIRE est fragile.", levelId: 23 },
  { word: "思考", meaningsFr: ["Pensée", "Réflexion"], readings: ["しこう"], mnemonicFr: "La PENSÉE logique.", levelId: 23 },
  { word: "認識", meaningsFr: ["Reconnaissance", "Perception"], readings: ["にんしき"], mnemonicFr: "La RECONNAISSANCE du problème.", levelId: 23 },
  { word: "理解", meaningsFr: ["Compréhension"], readings: ["りかい"], mnemonicFr: "La COMPRÉHENSION mutuelle.", levelId: 23 },
  { word: "納得", meaningsFr: ["Conviction", "Compréhension"], readings: ["なっとく"], mnemonicFr: "Être CONVAINCU.", levelId: 23 },
  { word: "同意", meaningsFr: ["Accord", "Consentement"], readings: ["どうい"], mnemonicFr: "Donner son ACCORD.", levelId: 23 },
  { word: "許可", meaningsFr: ["Permission", "Autorisation"], readings: ["きょか"], mnemonicFr: "Obtenir la PERMISSION.", levelId: 23 },
  { word: "禁止", meaningsFr: ["Interdiction"], readings: ["きんし"], mnemonicFr: "C'est INTERDIT.", levelId: 23 },
  { word: "制限", meaningsFr: ["Restriction", "Limite"], readings: ["せいげん"], mnemonicFr: "Sans RESTRICTION.", levelId: 23 },
  { word: "規則", meaningsFr: ["Règle", "Règlement"], readings: ["きそく"], mnemonicFr: "Respecter les RÈGLES.", levelId: 23 },
  { word: "法律", meaningsFr: ["Loi"], readings: ["ほうりつ"], mnemonicFr: "La LOI est la loi.", levelId: 23 },
  { word: "条件", meaningsFr: ["Condition"], readings: ["じょうけん"], mnemonicFr: "Sous certaines CONDITIONS.", levelId: 23 },
  { word: "基準", meaningsFr: ["Norme", "Standard"], readings: ["きじゅん"], mnemonicFr: "Les NORMES de qualité.", levelId: 23 },
  { word: "目的", meaningsFr: ["Objectif", "But"], readings: ["もくてき"], mnemonicFr: "L'OBJECTIF principal.", levelId: 23 },
  { word: "手段", meaningsFr: ["Moyen", "Méthode"], readings: ["しゅだん"], mnemonicFr: "Les MOYENS disponibles.", levelId: 23 },
  { word: "方法", meaningsFr: ["Méthode", "Façon"], readings: ["ほうほう"], mnemonicFr: "Une bonne MÉTHODE.", levelId: 23 },
  { word: "手順", meaningsFr: ["Procédure", "Étapes"], readings: ["てじゅん"], mnemonicFr: "Suivre la PROCÉDURE.", levelId: 23 },
  { word: "過程", meaningsFr: ["Processus", "Cours"], readings: ["かてい"], mnemonicFr: "Le PROCESSUS de fabrication.", levelId: 23 },
  { word: "段階", meaningsFr: ["Étape", "Phase"], readings: ["だんかい"], mnemonicFr: "À cette ÉTAPE.", levelId: 23 },
  { word: "程度", meaningsFr: ["Degré", "Niveau"], readings: ["ていど"], mnemonicFr: "À un certain DEGRÉ.", levelId: 23 },
  { word: "割合", meaningsFr: ["Proportion", "Taux"], readings: ["わりあい"], mnemonicFr: "La PROPORTION est bonne.", levelId: 23 },
  { word: "比率", meaningsFr: ["Ratio", "Proportion"], readings: ["ひりつ"], mnemonicFr: "Le RATIO correct.", levelId: 23 },
  { word: "平均", meaningsFr: ["Moyenne"], readings: ["へいきん"], mnemonicFr: "La MOYENNE des scores.", levelId: 23 },
  { word: "合計", meaningsFr: ["Total"], readings: ["ごうけい"], mnemonicFr: "Le TOTAL est élevé.", levelId: 23 },
  { word: "統計", meaningsFr: ["Statistique"], readings: ["とうけい"], mnemonicFr: "Les STATISTIQUES montrent.", levelId: 23 },

  // Level 24 - JLPT N3 vocabulary (intermediate)
  { word: "自然", meaningsFr: ["Nature"], readings: ["しぜん"], mnemonicFr: "La NATURE est belle.", levelId: 24 },
  { word: "環境", meaningsFr: ["Environnement"], readings: ["かんきょう"], mnemonicFr: "Protéger l'ENVIRONNEMENT.", levelId: 24 },
  { word: "気候", meaningsFr: ["Climat"], readings: ["きこう"], mnemonicFr: "Le CLIMAT change.", levelId: 24 },
  { word: "天候", meaningsFr: ["Temps (météo)"], readings: ["てんこう"], mnemonicFr: "Le TEMPS est incertain.", levelId: 24 },
  { word: "温度", meaningsFr: ["Température"], readings: ["おんど"], mnemonicFr: "La TEMPÉRATURE monte.", levelId: 24 },
  { word: "湿度", meaningsFr: ["Humidité"], readings: ["しつど"], mnemonicFr: "L'HUMIDITÉ est élevée.", levelId: 24 },
  { word: "気圧", meaningsFr: ["Pression atmosphérique"], readings: ["きあつ"], mnemonicFr: "La PRESSION ATMOSPHÉRIQUE.", levelId: 24 },
  { word: "風速", meaningsFr: ["Vitesse du vent"], readings: ["ふうそく"], mnemonicFr: "La VITESSE DU VENT.", levelId: 24 },
  { word: "降水", meaningsFr: ["Précipitations"], readings: ["こうすい"], mnemonicFr: "Les PRÉCIPITATIONS attendues.", levelId: 24 },
  { word: "積雪", meaningsFr: ["Accumulation de neige"], readings: ["せきせつ"], mnemonicFr: "L'ACCUMULATION DE NEIGE.", levelId: 24 },
  { word: "地震", meaningsFr: ["Tremblement de terre"], readings: ["じしん"], mnemonicFr: "Un TREMBLEMENT DE TERRE.", levelId: 24 },
  { word: "津波", meaningsFr: ["Tsunami"], readings: ["つなみ"], mnemonicFr: "Un TSUNAMI dévastateur.", levelId: 24 },
  { word: "台風", meaningsFr: ["Typhon"], readings: ["たいふう"], mnemonicFr: "Un TYPHON approche.", levelId: 24 },
  { word: "洪水", meaningsFr: ["Inondation"], readings: ["こうずい"], mnemonicFr: "Une INONDATION grave.", levelId: 24 },
  { word: "災害", meaningsFr: ["Catastrophe", "Désastre"], readings: ["さいがい"], mnemonicFr: "Une CATASTROPHE naturelle.", levelId: 24 },
  { word: "被害", meaningsFr: ["Dommage", "Dégât"], readings: ["ひがい"], mnemonicFr: "Les DOMMAGES sont importants.", levelId: 24 },
  { word: "避難", meaningsFr: ["Évacuation", "Refuge"], readings: ["ひなん"], mnemonicFr: "L'ÉVACUATION d'urgence.", levelId: 24 },
  { word: "救助", meaningsFr: ["Sauvetage", "Secours"], readings: ["きゅうじょ"], mnemonicFr: "Le SAUVETAGE des victimes.", levelId: 24 },
  { word: "復旧", meaningsFr: ["Restauration", "Rétablissement"], readings: ["ふっきゅう"], mnemonicFr: "La RESTAURATION des services.", levelId: 24 },
  { word: "復興", meaningsFr: ["Reconstruction", "Renaissance"], readings: ["ふっこう"], mnemonicFr: "La RECONSTRUCTION de la ville.", levelId: 24 },
  { word: "生態", meaningsFr: ["Écologie", "Écosystème"], readings: ["せいたい"], mnemonicFr: "L'ÉCOSYSTÈME fragile.", levelId: 24 },
  { word: "生物", meaningsFr: ["Être vivant", "Organisme"], readings: ["せいぶつ"], mnemonicFr: "Les ÊTRES VIVANTS.", levelId: 24 },
  { word: "動植物", meaningsFr: ["Faune et flore"], readings: ["どうしょくぶつ"], mnemonicFr: "La FAUNE ET FLORE.", levelId: 24 },
  { word: "野生", meaningsFr: ["Sauvage"], readings: ["やせい"], mnemonicFr: "Les animaux SAUVAGES.", levelId: 24 },
  { word: "絶滅", meaningsFr: ["Extinction"], readings: ["ぜつめつ"], mnemonicFr: "L'EXTINCTION des espèces.", levelId: 24 },
  { word: "保護", meaningsFr: ["Protection"], readings: ["ほご"], mnemonicFr: "La PROTECTION de la nature.", levelId: 24 },
  { word: "汚染", meaningsFr: ["Pollution", "Contamination"], readings: ["おせん"], mnemonicFr: "La POLLUTION de l'air.", levelId: 24 },
  { word: "排出", meaningsFr: ["Émission", "Rejet"], readings: ["はいしゅつ"], mnemonicFr: "L'ÉMISSION de gaz.", levelId: 24 },
  { word: "廃棄", meaningsFr: ["Élimination", "Mise au rebut"], readings: ["はいき"], mnemonicFr: "L'ÉLIMINATION des déchets.", levelId: 24 },
  { word: "再利用", meaningsFr: ["Réutilisation"], readings: ["さいりよう"], mnemonicFr: "La RÉUTILISATION des matériaux.", levelId: 24 },
  { word: "資源", meaningsFr: ["Ressource"], readings: ["しげん"], mnemonicFr: "Les RESSOURCES naturelles.", levelId: 24 },
  { word: "原料", meaningsFr: ["Matière première"], readings: ["げんりょう"], mnemonicFr: "La MATIÈRE PREMIÈRE.", levelId: 24 },
  { word: "材料", meaningsFr: ["Matériau", "Ingrédient"], readings: ["ざいりょう"], mnemonicFr: "Les MATÉRIAUX de construction.", levelId: 24 },
  { word: "製品", meaningsFr: ["Produit manufacturé"], readings: ["せいひん"], mnemonicFr: "Un PRODUIT de qualité.", levelId: 24 },
  { word: "生産", meaningsFr: ["Production"], readings: ["せいさん"], mnemonicFr: "La PRODUCTION industrielle.", levelId: 24 },
  { word: "製造", meaningsFr: ["Fabrication"], readings: ["せいぞう"], mnemonicFr: "La FABRICATION en usine.", levelId: 24 },
  { word: "加工", meaningsFr: ["Transformation", "Traitement"], readings: ["かこう"], mnemonicFr: "La TRANSFORMATION des aliments.", levelId: 24 },
  { word: "組立", meaningsFr: ["Assemblage"], readings: ["くみたて"], mnemonicFr: "L'ASSEMBLAGE des pièces.", levelId: 24 },
  { word: "検品", meaningsFr: ["Contrôle qualité"], readings: ["けんぴん"], mnemonicFr: "Le CONTRÔLE QUALITÉ.", levelId: 24 },
  { word: "出荷", meaningsFr: ["Expédition"], readings: ["しゅっか"], mnemonicFr: "L'EXPÉDITION des marchandises.", levelId: 24 },
  { word: "輸出", meaningsFr: ["Exportation"], readings: ["ゆしゅつ"], mnemonicFr: "L'EXPORTATION vers l'étranger.", levelId: 24 },
  { word: "輸入", meaningsFr: ["Importation"], readings: ["ゆにゅう"], mnemonicFr: "L'IMPORTATION de produits.", levelId: 24 },
  { word: "流通", meaningsFr: ["Distribution", "Circulation"], readings: ["りゅうつう"], mnemonicFr: "La DISTRIBUTION des biens.", levelId: 24 },
  { word: "販売", meaningsFr: ["Vente"], readings: ["はんばい"], mnemonicFr: "La VENTE en magasin.", levelId: 24 },
  { word: "購入", meaningsFr: ["Achat"], readings: ["こうにゅう"], mnemonicFr: "L'ACHAT d'un produit.", levelId: 24 },
  { word: "消費", meaningsFr: ["Consommation"], readings: ["しょうひ"], mnemonicFr: "La CONSOMMATION d'énergie.", levelId: 24 },
  { word: "需要", meaningsFr: ["Demande"], readings: ["じゅよう"], mnemonicFr: "La DEMANDE augmente.", levelId: 24 },
  { word: "供給", meaningsFr: ["Offre", "Approvisionnement"], readings: ["きょうきゅう"], mnemonicFr: "L'OFFRE et la demande.", levelId: 24 },
  { word: "在庫", meaningsFr: ["Stock"], readings: ["ざいこ"], mnemonicFr: "Le STOCK disponible.", levelId: 24 },
  { word: "不足", meaningsFr: ["Pénurie", "Manque"], readings: ["ふそく"], mnemonicFr: "Une PÉNURIE d'eau.", levelId: 24 },

  // Level 25 - JLPT N3 vocabulary (intermediate)
  { word: "社会", meaningsFr: ["Société"], readings: ["しゃかい"], mnemonicFr: "La SOCIÉTÉ moderne.", levelId: 25 },
  { word: "政治", meaningsFr: ["Politique"], readings: ["せいじ"], mnemonicFr: "La POLITIQUE nationale.", levelId: 25 },
  { word: "経済", meaningsFr: ["Économie"], readings: ["けいざい"], mnemonicFr: "L'ÉCONOMIE mondiale.", levelId: 25 },
  { word: "産業", meaningsFr: ["Industrie"], readings: ["さんぎょう"], mnemonicFr: "L'INDUSTRIE automobile.", levelId: 25 },
  { word: "農業", meaningsFr: ["Agriculture"], readings: ["のうぎょう"], mnemonicFr: "L'AGRICULTURE biologique.", levelId: 25 },
  { word: "漁業", meaningsFr: ["Pêche (industrie)"], readings: ["ぎょぎょう"], mnemonicFr: "L'industrie de la PÊCHE.", levelId: 25 },
  { word: "林業", meaningsFr: ["Sylviculture"], readings: ["りんぎょう"], mnemonicFr: "La SYLVICULTURE durable.", levelId: 25 },
  { word: "商業", meaningsFr: ["Commerce"], readings: ["しょうぎょう"], mnemonicFr: "Le COMMERCE international.", levelId: 25 },
  { word: "金融", meaningsFr: ["Finance"], readings: ["きんゆう"], mnemonicFr: "Le secteur de la FINANCE.", levelId: 25 },
  { word: "投資", meaningsFr: ["Investissement"], readings: ["とうし"], mnemonicFr: "Un INVESTISSEMENT rentable.", levelId: 25 },
  { word: "株式", meaningsFr: ["Action (bourse)"], readings: ["かぶしき"], mnemonicFr: "Les ACTIONS en bourse.", levelId: 25 },
  { word: "為替", meaningsFr: ["Change (devise)"], readings: ["かわせ"], mnemonicFr: "Le taux de CHANGE.", levelId: 25 },
  { word: "景気", meaningsFr: ["Conjoncture économique"], readings: ["けいき"], mnemonicFr: "La CONJONCTURE est bonne.", levelId: 25 },
  { word: "不況", meaningsFr: ["Récession", "Dépression"], readings: ["ふきょう"], mnemonicFr: "Une RÉCESSION économique.", levelId: 25 },
  { word: "成長率", meaningsFr: ["Taux de croissance"], readings: ["せいちょうりつ"], mnemonicFr: "Le TAUX DE CROISSANCE.", levelId: 25 },
  { word: "物価", meaningsFr: ["Prix (niveau général)"], readings: ["ぶっか"], mnemonicFr: "Le niveau des PRIX.", levelId: 25 },
  { word: "税金", meaningsFr: ["Impôt", "Taxe"], readings: ["ぜいきん"], mnemonicFr: "Payer ses IMPÔTS.", levelId: 25 },
  { word: "予算", meaningsFr: ["Budget"], readings: ["よさん"], mnemonicFr: "Le BUDGET annuel.", levelId: 25 },
  { word: "収入", meaningsFr: ["Revenu", "Recette"], readings: ["しゅうにゅう"], mnemonicFr: "Les REVENUS mensuels.", levelId: 25 },
  { word: "支出", meaningsFr: ["Dépense"], readings: ["ししゅつ"], mnemonicFr: "Les DÉPENSES du ménage.", levelId: 25 },
  { word: "利益", meaningsFr: ["Profit", "Bénéfice"], readings: ["りえき"], mnemonicFr: "Les BÉNÉFICES de l'entreprise.", levelId: 25 },
  { word: "損失", meaningsFr: ["Perte"], readings: ["そんしつ"], mnemonicFr: "Une PERTE financière.", levelId: 25 },
  { word: "債務", meaningsFr: ["Dette"], readings: ["さいむ"], mnemonicFr: "Rembourser sa DETTE.", levelId: 25 },
  { word: "融資", meaningsFr: ["Financement", "Prêt"], readings: ["ゆうし"], mnemonicFr: "Obtenir un FINANCEMENT.", levelId: 25 },
  { word: "保険", meaningsFr: ["Assurance"], readings: ["ほけん"], mnemonicFr: "L'ASSURANCE maladie.", levelId: 25 },
  { word: "年金", meaningsFr: ["Pension", "Retraite"], readings: ["ねんきん"], mnemonicFr: "La PENSION de retraite.", levelId: 25 },
  { word: "福祉", meaningsFr: ["Protection sociale"], readings: ["ふくし"], mnemonicFr: "La PROTECTION SOCIALE.", levelId: 25 },
  { word: "介護", meaningsFr: ["Soins infirmiers", "Aide"], readings: ["かいご"], mnemonicFr: "Les SOINS aux personnes âgées.", levelId: 25 },
  { word: "医療", meaningsFr: ["Soins médicaux"], readings: ["いりょう"], mnemonicFr: "Les SOINS MÉDICAUX.", levelId: 25 },
  { word: "行政", meaningsFr: ["Administration"], readings: ["ぎょうせい"], mnemonicFr: "L'ADMINISTRATION publique.", levelId: 25 },
  { word: "立法", meaningsFr: ["Législation"], readings: ["りっぽう"], mnemonicFr: "Le pouvoir LÉGISLATIF.", levelId: 25 },
  { word: "司法", meaningsFr: ["Justice (système)"], readings: ["しほう"], mnemonicFr: "Le système JUDICIAIRE.", levelId: 25 },
  { word: "選挙", meaningsFr: ["Élection"], readings: ["せんきょ"], mnemonicFr: "Les ÉLECTIONS approchent.", levelId: 25 },
  { word: "投票", meaningsFr: ["Vote"], readings: ["とうひょう"], mnemonicFr: "Aller VOTER.", levelId: 25 },
  { word: "議会", meaningsFr: ["Parlement", "Assemblée"], readings: ["ぎかい"], mnemonicFr: "Le PARLEMENT vote.", levelId: 25 },
  { word: "政党", meaningsFr: ["Parti politique"], readings: ["せいとう"], mnemonicFr: "Un PARTI POLITIQUE.", levelId: 25 },
  { word: "野党", meaningsFr: ["Opposition"], readings: ["やとう"], mnemonicFr: "Le parti d'OPPOSITION.", levelId: 25 },
  { word: "与党", meaningsFr: ["Parti au pouvoir"], readings: ["よとう"], mnemonicFr: "Le PARTI AU POUVOIR.", levelId: 25 },
  { word: "内閣", meaningsFr: ["Cabinet (gouvernement)"], readings: ["ないかく"], mnemonicFr: "Le CABINET ministériel.", levelId: 25 },
  { word: "大臣", meaningsFr: ["Ministre"], readings: ["だいじん"], mnemonicFr: "Un MINISTRE du gouvernement.", levelId: 25 },
  { word: "官僚", meaningsFr: ["Bureaucrate", "Fonctionnaire"], readings: ["かんりょう"], mnemonicFr: "Les BUREAUCRATES.", levelId: 25 },
  { word: "公務員", meaningsFr: ["Fonctionnaire"], readings: ["こうむいん"], mnemonicFr: "Un FONCTIONNAIRE.", levelId: 25 },
  { word: "市民", meaningsFr: ["Citoyen"], readings: ["しみん"], mnemonicFr: "Les CITOYENS de la ville.", levelId: 25 },
  { word: "国民", meaningsFr: ["Peuple", "Nation"], readings: ["こくみん"], mnemonicFr: "Le PEUPLE japonais.", levelId: 25 },
  { word: "住民", meaningsFr: ["Résident", "Habitant"], readings: ["じゅうみん"], mnemonicFr: "Les RÉSIDENTS du quartier.", levelId: 25 },
  { word: "移民", meaningsFr: ["Immigrant"], readings: ["いみん"], mnemonicFr: "Les IMMIGRANTS.", levelId: 25 },
  { word: "難民", meaningsFr: ["Réfugié"], readings: ["なんみん"], mnemonicFr: "Les RÉFUGIÉS de guerre.", levelId: 25 },
  { word: "外交", meaningsFr: ["Diplomatie"], readings: ["がいこう"], mnemonicFr: "La DIPLOMATIE internationale.", levelId: 25 },
  { word: "条約", meaningsFr: ["Traité"], readings: ["じょうやく"], mnemonicFr: "Signer un TRAITÉ.", levelId: 25 },
  { word: "協定", meaningsFr: ["Accord", "Convention"], readings: ["きょうてい"], mnemonicFr: "Un ACCORD commercial.", levelId: 25 },
];

async function main() {
  console.log("Seeding vocabulary supplement for levels 21-25...");

  for (const vocab of vocabularyData) {
    await prisma.vocabulary.upsert({
      where: {
        word_levelId: {
          word: vocab.word,
          levelId: vocab.levelId,
        },
      },
      update: {
        meaningsFr: vocab.meaningsFr,
        readings: vocab.readings,
        mnemonicFr: vocab.mnemonicFr,
      },
      create: vocab,
    });
  }

  console.log(`Seeded ${vocabularyData.length} vocabulary words for levels 21-25.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
