import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Final kanji batch 7 - Target: exceed 2000 kanji total
// Focusing on remaining commonly used kanji not yet included

const kanjiData = [
  // More verbs and actions
  {
    character: "縛",
    meaningsFr: ["attacher", "lier"],
    readingsOn: ["バク"],
    readingsKun: ["しば.る"],
    meaningMnemonicFr: "Le fil 糸 qui fait un serment 博 forme un lien qui ATTACHE fermement.",
    readingMnemonicFr: "BAKu - Le son d'une corde qu'on serre fermement.",
    levelId: 52,
  },
  {
    character: "朽",
    meaningsFr: ["pourrir", "décomposer"],
    readingsOn: ["キュウ"],
    readingsKun: ["く.ちる"],
    meaningMnemonicFr: "L'arbre 木 devient vieux et POURRIT naturellement.",
    readingMnemonicFr: "KYŪ - Le bois qui se décompose fait ce son.",
    levelId: 48,
  },
  {
    character: "殴",
    meaningsFr: ["frapper", "battre"],
    readingsOn: ["オウ"],
    readingsKun: ["なぐ.る"],
    meaningMnemonicFr: "La main 殳 qui frappe en faisant une marque 欧 représente FRAPPER.",
    readingMnemonicFr: "Ō - Le cri quand on se fait frapper.",
    levelId: 47,
  },
  {
    character: "蹴",
    meaningsFr: ["donner un coup de pied"],
    readingsOn: ["シュウ"],
    readingsKun: ["け.る"],
    meaningMnemonicFr: "Le pied 足 qui fait une action de la soie 蹴 donne un COUP DE PIED.",
    readingMnemonicFr: "SHŪ - Le son du coup de pied dans l'air.",
    levelId: 53,
  },
  {
    character: "掴",
    meaningsFr: ["saisir", "attraper"],
    readingsOn: ["カク"],
    readingsKun: ["つか.む"],
    meaningMnemonicFr: "La main 扌 qui prend un pays 国 symbolise SAISIR fermement.",
    readingMnemonicFr: "KAKU - Saisir quelque chose avec force.",
    levelId: 49,
  },
  {
    character: "撫",
    meaningsFr: ["caresser", "apaiser"],
    readingsOn: ["ブ"],
    readingsKun: ["な.でる"],
    meaningMnemonicFr: "La main 扌 sans 無 brusquerie CARESSE doucement.",
    readingMnemonicFr: "BU - Un geste doux et apaisant.",
    levelId: 50,
  },
  {
    character: "撃",
    meaningsFr: ["frapper", "attaquer"],
    readingsOn: ["ゲキ"],
    readingsKun: ["う.つ"],
    meaningMnemonicFr: "La main 手 qui frappe un véhicule 車 représente une ATTAQUE.",
    readingMnemonicFr: "GEKI - Le son d'un impact violent.",
    levelId: 44,
  },
  {
    character: "擦",
    meaningsFr: ["frotter", "gratter"],
    readingsOn: ["サツ"],
    readingsKun: ["す.る", "こす.る"],
    meaningMnemonicFr: "La main 扌 qui inspecte 察 en FROTTANT la surface.",
    readingMnemonicFr: "SATSU - Le son du frottement.",
    levelId: 51,
  },
  {
    character: "捻",
    meaningsFr: ["tordre", "tourner"],
    readingsOn: ["ネン"],
    readingsKun: ["ねじ.る", "ひね.る"],
    meaningMnemonicFr: "La main 扌 qui fait des pensées 念 en TORDANT.",
    readingMnemonicFr: "NEN - Le mouvement de torsion qui demande réflexion.",
    levelId: 52,
  },
  {
    character: "揉",
    meaningsFr: ["masser", "pétrir"],
    readingsOn: ["ジュウ"],
    readingsKun: ["も.む"],
    meaningMnemonicFr: "La main 扌 douce 柔 qui MASSE les muscles.",
    readingMnemonicFr: "JŪ - Le pétrissage doux et répétitif.",
    levelId: 53,
  },
  // Nature and environment
  {
    character: "渓",
    meaningsFr: ["ravin", "vallée"],
    readingsOn: ["ケイ"],
    readingsKun: ["たに"],
    meaningMnemonicFr: "L'eau 氵 qui coule dans le poulet 鶏 forme un RAVIN.",
    readingMnemonicFr: "KEI - La vallée où l'eau s'écoule.",
    levelId: 46,
  },
  {
    character: "峡",
    meaningsFr: ["gorge", "détroit"],
    readingsOn: ["キョウ"],
    readingsKun: [],
    meaningMnemonicFr: "La montagne 山 étroite 狭 forme une GORGE.",
    readingMnemonicFr: "KYŌ - Le passage étroit entre les montagnes.",
    levelId: 47,
  },
  {
    character: "崖",
    meaningsFr: ["falaise", "précipice"],
    readingsOn: ["ガイ"],
    readingsKun: ["がけ"],
    meaningMnemonicFr: "La montagne 山 avec un bord 厓 forme une FALAISE.",
    readingMnemonicFr: "GAI - Le danger du précipice.",
    levelId: 48,
  },
  {
    character: "洞",
    meaningsFr: ["caverne", "grotte"],
    readingsOn: ["ドウ"],
    readingsKun: ["ほら"],
    meaningMnemonicFr: "L'eau 氵 dans le même 同 endroit creuse une CAVERNE.",
    readingMnemonicFr: "DŌ - L'écho dans la grotte.",
    levelId: 45,
  },
  {
    character: "渦",
    meaningsFr: ["tourbillon", "vortex"],
    readingsOn: ["カ"],
    readingsKun: ["うず"],
    meaningMnemonicFr: "L'eau 氵 qui tourne dans un pot 渦 forme un TOURBILLON.",
    readingMnemonicFr: "KA - Le mouvement circulaire de l'eau.",
    levelId: 50,
  },
  {
    character: "潮",
    meaningsFr: ["marée", "courant"],
    readingsOn: ["チョウ"],
    readingsKun: ["しお"],
    meaningMnemonicFr: "L'eau 氵 du matin 朝 apporte la MARÉE.",
    readingMnemonicFr: "CHŌ - La marée du matin.",
    levelId: 43,
  },
  {
    character: "霧",
    meaningsFr: ["brouillard", "brume"],
    readingsOn: ["ム"],
    readingsKun: ["きり"],
    meaningMnemonicFr: "La pluie 雨 qui crée le vide 務 forme le BROUILLARD.",
    readingMnemonicFr: "MU - Le voile mystérieux du brouillard.",
    levelId: 47,
  },
  {
    character: "霜",
    meaningsFr: ["givre", "gelée blanche"],
    readingsOn: ["ソウ"],
    readingsKun: ["しも"],
    meaningMnemonicFr: "La pluie 雨 qui devient mutuelle 相 forme le GIVRE.",
    readingMnemonicFr: "SŌ - Le froid qui cristallise.",
    levelId: 48,
  },
  {
    character: "雫",
    meaningsFr: ["goutte"],
    readingsOn: [],
    readingsKun: ["しずく"],
    meaningMnemonicFr: "La pluie 雨 qui descend 下 forme une GOUTTE.",
    readingMnemonicFr: "Shizuku - La goutte qui tombe doucement.",
    levelId: 51,
  },
  {
    character: "露",
    meaningsFr: ["rosée", "exposer"],
    readingsOn: ["ロ", "ロウ"],
    readingsKun: ["つゆ"],
    meaningMnemonicFr: "La pluie 雨 sur le chemin 路 forme la ROSÉE.",
    readingMnemonicFr: "RO - La rosée du matin sur le chemin.",
    levelId: 44,
  },
  // Animals and creatures
  {
    character: "鯨",
    meaningsFr: ["baleine"],
    readingsOn: ["ゲイ"],
    readingsKun: ["くじら"],
    meaningMnemonicFr: "Le poisson 魚 de la capitale 京 est la grande BALEINE.",
    readingMnemonicFr: "GEI - Le chant majestueux de la baleine.",
    levelId: 49,
  },
  {
    character: "鯛",
    meaningsFr: ["daurade"],
    readingsOn: ["タイ"],
    readingsKun: ["たい"],
    meaningMnemonicFr: "Le poisson 魚 célébré 周 est la DAURADE.",
    readingMnemonicFr: "TAI - Le poisson des grandes occasions.",
    levelId: 50,
  },
  {
    character: "鮫",
    meaningsFr: ["requin"],
    readingsOn: ["コウ"],
    readingsKun: ["さめ"],
    meaningMnemonicFr: "Le poisson 魚 qui croise 交 est le REQUIN.",
    readingMnemonicFr: "KŌ - Le prédateur des mers.",
    levelId: 51,
  },
  {
    character: "鰐",
    meaningsFr: ["crocodile", "alligator"],
    readingsOn: ["ガク"],
    readingsKun: ["わに"],
    meaningMnemonicFr: "Le poisson 魚 qui mord 咢 est le CROCODILE.",
    readingMnemonicFr: "GAKU - Les mâchoires puissantes.",
    levelId: 54,
  },
  {
    character: "蛇",
    meaningsFr: ["serpent"],
    readingsOn: ["ジャ", "ダ"],
    readingsKun: ["へび"],
    meaningMnemonicFr: "L'insecte 虫 qui rampe dans la maison 它 est le SERPENT.",
    readingMnemonicFr: "JA - Le sifflement du serpent.",
    levelId: 42,
  },
  {
    character: "蝶",
    meaningsFr: ["papillon"],
    readingsOn: ["チョウ"],
    readingsKun: [],
    meaningMnemonicFr: "L'insecte 虫 qui vole en feuille 葉 est le PAPILLON.",
    readingMnemonicFr: "CHŌ - Le vol gracieux du papillon.",
    levelId: 46,
  },
  {
    character: "蟻",
    meaningsFr: ["fourmi"],
    readingsOn: ["ギ"],
    readingsKun: ["あり"],
    meaningMnemonicFr: "L'insecte 虫 avec justice 義 est la FOURMI travailleuse.",
    readingMnemonicFr: "GI - La fourmi qui suit les règles.",
    levelId: 52,
  },
  {
    character: "蜂",
    meaningsFr: ["abeille", "guêpe"],
    readingsOn: ["ホウ"],
    readingsKun: ["はち"],
    meaningMnemonicFr: "L'insecte 虫 abondant 夆 est l'ABEILLE.",
    readingMnemonicFr: "HŌ - Le bourdonnement de l'abeille.",
    levelId: 49,
  },
  {
    character: "蜘",
    meaningsFr: ["araignée"],
    readingsOn: ["チ"],
    readingsKun: [],
    meaningMnemonicFr: "L'insecte 虫 qui connaît 知 son territoire tisse sa toile - l'ARAIGNÉE.",
    readingMnemonicFr: "CHI - L'araignée intelligente.",
    levelId: 55,
  },
  {
    character: "蛛",
    meaningsFr: ["araignée"],
    readingsOn: ["シュ", "チュ"],
    readingsKun: [],
    meaningMnemonicFr: "L'insecte 虫 au centre 朱 de sa toile est l'ARAIGNÉE.",
    readingMnemonicFr: "SHU - L'araignée au centre de tout.",
    levelId: 55,
  },
  // Body parts and medical
  {
    character: "瞳",
    meaningsFr: ["pupille", "prunelle"],
    readingsOn: ["ドウ"],
    readingsKun: ["ひとみ"],
    meaningMnemonicFr: "L'œil 目 de l'enfant 童 brille - la PUPILLE.",
    readingMnemonicFr: "DŌ - Les yeux innocents de l'enfant.",
    levelId: 47,
  },
  {
    character: "瞼",
    meaningsFr: ["paupière"],
    readingsOn: ["ケン"],
    readingsKun: ["まぶた"],
    meaningMnemonicFr: "L'œil 目 avec un volet 僉 a une PAUPIÈRE.",
    readingMnemonicFr: "KEN - La paupière qui protège.",
    levelId: 54,
  },
  {
    character: "眉",
    meaningsFr: ["sourcil"],
    readingsOn: ["ビ", "ミ"],
    readingsKun: ["まゆ"],
    meaningMnemonicFr: "Au-dessus de l'œil 目 se trouve le SOURCIL.",
    readingMnemonicFr: "BI - L'arc du sourcil.",
    levelId: 45,
  },
  {
    character: "頬",
    meaningsFr: ["joue"],
    readingsOn: ["キョウ"],
    readingsKun: ["ほお", "ほほ"],
    meaningMnemonicFr: "La tête 頁 avec deux éléments 夾 montre les JOUES.",
    readingMnemonicFr: "KYŌ - Les joues rouges.",
    levelId: 50,
  },
  {
    character: "顎",
    meaningsFr: ["mâchoire", "menton"],
    readingsOn: ["ガク"],
    readingsKun: ["あご"],
    meaningMnemonicFr: "La tête 頁 qui mâche 咢 a une MÂCHOIRE.",
    readingMnemonicFr: "GAKU - La force de la mâchoire.",
    levelId: 51,
  },
  {
    character: "唇",
    meaningsFr: ["lèvre"],
    readingsOn: ["シン"],
    readingsKun: ["くちびる"],
    meaningMnemonicFr: "La bouche 口 qui parle tôt 辰 a des LÈVRES.",
    readingMnemonicFr: "SHIN - Les lèvres qui parlent.",
    levelId: 46,
  },
  {
    character: "踵",
    meaningsFr: ["talon"],
    readingsOn: ["ショウ"],
    readingsKun: ["かかと"],
    meaningMnemonicFr: "Le pied 足 qui se répète 重 marche sur le TALON.",
    readingMnemonicFr: "SHŌ - Le talon qui porte le poids.",
    levelId: 56,
  },
  {
    character: "踝",
    meaningsFr: ["cheville"],
    readingsOn: ["カ"],
    readingsKun: ["くるぶし"],
    meaningMnemonicFr: "Le pied 足 avec un fruit 果 a une CHEVILLE.",
    readingMnemonicFr: "KA - L'articulation de la cheville.",
    levelId: 57,
  },
  {
    character: "膝",
    meaningsFr: ["genou"],
    readingsOn: ["シツ"],
    readingsKun: ["ひざ"],
    meaningMnemonicFr: "La chair 月 qui plie comme une flèche 漆 est le GENOU.",
    readingMnemonicFr: "SHITSU - Le genou qui fléchit.",
    levelId: 48,
  },
  {
    character: "肘",
    meaningsFr: ["coude"],
    readingsOn: ["チュウ"],
    readingsKun: ["ひじ"],
    meaningMnemonicFr: "La chair 月 avec un pouce 寸 forme le COUDE.",
    readingMnemonicFr: "CHŪ - L'articulation du coude.",
    levelId: 49,
  },
  // Food and cooking
  {
    character: "餅",
    meaningsFr: ["gâteau de riz", "mochi"],
    readingsOn: ["ヘイ", "ベイ"],
    readingsKun: ["もち"],
    meaningMnemonicFr: "La nourriture 食 pour une combinaison 并 est le MOCHI.",
    readingMnemonicFr: "HEI - Le mochi des fêtes.",
    levelId: 50,
  },
  {
    character: "餌",
    meaningsFr: ["appât", "nourriture"],
    readingsOn: ["ジ"],
    readingsKun: ["え", "えさ"],
    meaningMnemonicFr: "La nourriture 食 pour mon moi 耳 est l'APPÂT.",
    readingMnemonicFr: "JI - L'appât qui attire.",
    levelId: 51,
  },
  {
    character: "飴",
    meaningsFr: ["bonbon", "caramel"],
    readingsOn: ["イ"],
    readingsKun: ["あめ"],
    meaningMnemonicFr: "La nourriture 食 de la plateforme 台 est le BONBON.",
    readingMnemonicFr: "I - La douceur du caramel.",
    levelId: 52,
  },
  {
    character: "醤",
    meaningsFr: ["sauce soja"],
    readingsOn: ["ショウ"],
    readingsKun: ["ひしお"],
    meaningMnemonicFr: "L'alcool 酉 avec un général 将 fait la SAUCE SOJA.",
    readingMnemonicFr: "SHŌ - L'assaisonnement japonais.",
    levelId: 53,
  },
  {
    character: "醸",
    meaningsFr: ["brasser", "fermenter"],
    readingsOn: ["ジョウ"],
    readingsKun: ["かも.す"],
    meaningMnemonicFr: "L'alcool 酉 qui cède 襄 devient BRASSÉ.",
    readingMnemonicFr: "JŌ - La fermentation lente.",
    levelId: 54,
  },
  {
    character: "麺",
    meaningsFr: ["nouilles"],
    readingsOn: ["メン"],
    readingsKun: [],
    meaningMnemonicFr: "Le blé 麦 en face 面 devient NOUILLES.",
    readingMnemonicFr: "MEN - Le plat de ramen.",
    levelId: 47,
  },
  {
    character: "粥",
    meaningsFr: ["bouillie de riz", "congee"],
    readingsOn: ["シュク"],
    readingsKun: ["かゆ"],
    meaningMnemonicFr: "Le riz 米 bouilli avec de l'eau 弓弓 fait la BOUILLIE.",
    readingMnemonicFr: "SHUKU - Le petit-déjeuner chaud.",
    levelId: 55,
  },
  {
    character: "酢",
    meaningsFr: ["vinaigre"],
    readingsOn: ["サク"],
    readingsKun: ["す"],
    meaningMnemonicFr: "L'alcool 酉 qui fait 乍 devient VINAIGRE.",
    readingMnemonicFr: "SAKU - L'acidité du vinaigre.",
    levelId: 48,
  },
  // Emotions and states
  {
    character: "惨",
    meaningsFr: ["misérable", "cruel"],
    readingsOn: ["サン", "ザン"],
    readingsKun: ["みじ.め"],
    meaningMnemonicFr: "Le cœur 忄 qui participe 参 à la souffrance est MISÉRABLE.",
    readingMnemonicFr: "SAN - La tristesse profonde.",
    levelId: 44,
  },
  {
    character: "憂",
    meaningsFr: ["tristesse", "mélancolie"],
    readingsOn: ["ユウ"],
    readingsKun: ["うれ.える", "う.い"],
    meaningMnemonicFr: "Le cœur 心 qui porte un poids forme la TRISTESSE.",
    readingMnemonicFr: "YŪ - La mélancolie profonde.",
    levelId: 47,
  },
  {
    character: "慌",
    meaningsFr: ["panique", "affolement"],
    readingsOn: ["コウ"],
    readingsKun: ["あわ.てる", "あわ.ただしい"],
    meaningMnemonicFr: "Le cœur 忄 dans le désert 荒 est en PANIQUE.",
    readingMnemonicFr: "KŌ - L'affolement soudain.",
    levelId: 46,
  },
  {
    character: "惜",
    meaningsFr: ["regretter", "avoir pitié"],
    readingsOn: ["セキ"],
    readingsKun: ["お.しい", "お.しむ"],
    meaningMnemonicFr: "Le cœur 忄 qui tient au passé 昔 REGRETTE.",
    readingMnemonicFr: "SEKI - Le regret du passé.",
    levelId: 45,
  },
  {
    character: "悔",
    meaningsFr: ["regret", "repentir"],
    readingsOn: ["カイ"],
    readingsKun: ["く.いる", "くや.む"],
    meaningMnemonicFr: "Le cœur 忄 qui a chaque 毎 erreur a des REGRETS.",
    readingMnemonicFr: "KAI - Le repentir sincère.",
    levelId: 44,
  },
  {
    character: "悟",
    meaningsFr: ["réaliser", "comprendre"],
    readingsOn: ["ゴ"],
    readingsKun: ["さと.る"],
    meaningMnemonicFr: "Le cœur 忄 qui m'appartient 吾 RÉALISE la vérité.",
    readingMnemonicFr: "GO - L'éveil spirituel.",
    levelId: 43,
  },
  {
    character: "憎",
    meaningsFr: ["haïr", "détester"],
    readingsOn: ["ゾウ"],
    readingsKun: ["にく.む", "にく.い"],
    meaningMnemonicFr: "Le cœur 忄 qui augmente 曾 négativement HAÏNE.",
    readingMnemonicFr: "ZŌ - La haine qui grandit.",
    levelId: 45,
  },
  {
    character: "懐",
    meaningsFr: ["nostalgie", "poche"],
    readingsOn: ["カイ"],
    readingsKun: ["ふところ", "なつ.かしい"],
    meaningMnemonicFr: "Le cœur 忄 qui revient 懷 garde la NOSTALGIE.",
    readingMnemonicFr: "KAI - La nostalgie du passé.",
    levelId: 48,
  },
  {
    character: "憤",
    meaningsFr: ["indignation", "colère"],
    readingsOn: ["フン"],
    readingsKun: ["いきどお.る"],
    meaningMnemonicFr: "Le cœur 忄 qui brûle 賁 d'INDIGNATION.",
    readingMnemonicFr: "FUN - La colère justifiée.",
    levelId: 49,
  },
  {
    character: "慈",
    meaningsFr: ["miséricorde", "compassion"],
    readingsOn: ["ジ"],
    readingsKun: ["いつく.しむ"],
    meaningMnemonicFr: "Le cœur 心 qui nourrit 兹 avec COMPASSION.",
    readingMnemonicFr: "JI - La bienveillance maternelle.",
    levelId: 46,
  },
  // Society and institutions
  {
    character: "獄",
    meaningsFr: ["prison"],
    readingsOn: ["ゴク"],
    readingsKun: [],
    meaningMnemonicFr: "Les chiens 犭 gardent le parleur 獄 en PRISON.",
    readingMnemonicFr: "GOKU - L'enfer de la prison.",
    levelId: 47,
  },
  {
    character: "刑",
    meaningsFr: ["punition", "peine"],
    readingsOn: ["ケイ"],
    readingsKun: [],
    meaningMnemonicFr: "Le couteau 刂 pour l'ouverture 开 est la PUNITION.",
    readingMnemonicFr: "KEI - La peine de justice.",
    levelId: 42,
  },
  {
    character: "罰",
    meaningsFr: ["punition", "sanction"],
    readingsOn: ["バツ", "バチ"],
    readingsKun: [],
    meaningMnemonicFr: "Le filet 罒 avec des paroles 詈 et le couteau 刂 inflige une PUNITION.",
    readingMnemonicFr: "BATSU - La sanction sévère.",
    levelId: 45,
  },
  {
    character: "賄",
    meaningsFr: ["pot-de-vin", "corruption"],
    readingsOn: ["ワイ"],
    readingsKun: ["まかな.う"],
    meaningMnemonicFr: "La richesse 貝 qui a 有 un prix caché est un POT-DE-VIN.",
    readingMnemonicFr: "WAI - La corruption financière.",
    levelId: 50,
  },
  {
    character: "賊",
    meaningsFr: ["voleur", "rebelle"],
    readingsOn: ["ゾク"],
    readingsKun: [],
    meaningMnemonicFr: "La richesse 貝 attaquée par une arme 戈 par le VOLEUR.",
    readingMnemonicFr: "ZOKU - Le rebelle dangereux.",
    levelId: 46,
  },
  {
    character: "賠",
    meaningsFr: ["dédommager", "compenser"],
    readingsOn: ["バイ"],
    readingsKun: [],
    meaningMnemonicFr: "La richesse 貝 qui accompagne 咅 est une COMPENSATION.",
    readingMnemonicFr: "BAI - Le dédommagement financier.",
    levelId: 48,
  },
  {
    character: "賜",
    meaningsFr: ["accorder", "octroyer"],
    readingsOn: ["シ"],
    readingsKun: ["たまわ.る"],
    meaningMnemonicFr: "La richesse 貝 qui change 易 de main est ACCORDÉE.",
    readingMnemonicFr: "SHI - Le don du supérieur.",
    levelId: 49,
  },
  {
    character: "賢",
    meaningsFr: ["sage", "intelligent"],
    readingsOn: ["ケン"],
    readingsKun: ["かしこ.い"],
    meaningMnemonicFr: "L'œil 臣 qui voit la richesse 貝 avec sagesse est SAGE.",
    readingMnemonicFr: "KEN - La sagesse du maître.",
    levelId: 43,
  },
  // Nature elements
  {
    character: "滝",
    meaningsFr: ["cascade", "chute d'eau"],
    readingsOn: ["ロウ"],
    readingsKun: ["たき"],
    meaningMnemonicFr: "L'eau 氵 qui tombe comme un dragon 竜 forme une CASCADE.",
    readingMnemonicFr: "RŌ - Le rugissement de la cascade.",
    levelId: 44,
  },
  {
    character: "泉",
    meaningsFr: ["source", "fontaine"],
    readingsOn: ["セン"],
    readingsKun: ["いずみ"],
    meaningMnemonicFr: "L'eau 水 blanche 白 qui jaillit est une SOURCE.",
    readingMnemonicFr: "SEN - L'eau pure de la source.",
    levelId: 35,
  },
  {
    character: "沼",
    meaningsFr: ["marais", "étang"],
    readingsOn: ["ショウ"],
    readingsKun: ["ぬま"],
    meaningMnemonicFr: "L'eau 氵 qui appelle 召 les moustiques est un MARAIS.",
    readingMnemonicFr: "SHŌ - Les eaux stagnantes du marais.",
    levelId: 43,
  },
  {
    character: "溝",
    meaningsFr: ["fossé", "rigole"],
    readingsOn: ["コウ"],
    readingsKun: ["みぞ"],
    meaningMnemonicFr: "L'eau 氵 qui construit 構 un chemin est un FOSSÉ.",
    readingMnemonicFr: "KŌ - Le canal creusé.",
    levelId: 46,
  },
  {
    character: "堤",
    meaningsFr: ["digue", "remblai"],
    readingsOn: ["テイ"],
    readingsKun: ["つつみ"],
    meaningMnemonicFr: "La terre 土 qui est 是 une barrière forme une DIGUE.",
    readingMnemonicFr: "TEI - La digue qui protège.",
    levelId: 47,
  },
  {
    character: "塚",
    meaningsFr: ["tumulus", "tertre"],
    readingsOn: ["チョウ"],
    readingsKun: ["つか"],
    meaningMnemonicFr: "La terre 土 avec un cochon 豕 enterré forme un TUMULUS.",
    readingMnemonicFr: "CHŌ - Le monticule funéraire.",
    levelId: 50,
  },
  // Plants and trees
  {
    character: "柳",
    meaningsFr: ["saule"],
    readingsOn: ["リュウ"],
    readingsKun: ["やなぎ"],
    meaningMnemonicFr: "L'arbre 木 qui coule 卯 est le SAULE pleureur.",
    readingMnemonicFr: "RYŪ - Le saule qui danse au vent.",
    levelId: 42,
  },
  {
    character: "杉",
    meaningsFr: ["cèdre japonais"],
    readingsOn: ["サン"],
    readingsKun: ["すぎ"],
    meaningMnemonicFr: "L'arbre 木 avec trois branches 彡 est le CÈDRE.",
    readingMnemonicFr: "SAN - Le cèdre majestueux.",
    levelId: 41,
  },
  {
    character: "桐",
    meaningsFr: ["paulownia"],
    readingsOn: ["トウ", "ドウ"],
    readingsKun: ["きり"],
    meaningMnemonicFr: "L'arbre 木 pareil 同 au ciel est le PAULOWNIA.",
    readingMnemonicFr: "TŌ - L'arbre noble du Japon.",
    levelId: 45,
  },
  {
    character: "椿",
    meaningsFr: ["camélia"],
    readingsOn: ["チン"],
    readingsKun: ["つばき"],
    meaningMnemonicFr: "L'arbre 木 du printemps 春 est le CAMÉLIA.",
    readingMnemonicFr: "CHIN - La fleur d'hiver.",
    levelId: 48,
  },
  {
    character: "楓",
    meaningsFr: ["érable"],
    readingsOn: ["フウ"],
    readingsKun: ["かえで"],
    meaningMnemonicFr: "L'arbre 木 au vent 風 est l'ÉRABLE.",
    readingMnemonicFr: "FŪ - L'érable aux feuilles rouges.",
    levelId: 46,
  },
  {
    character: "榎",
    meaningsFr: ["micocoulier"],
    readingsOn: [],
    readingsKun: ["えのき"],
    meaningMnemonicFr: "L'arbre 木 du couple 夏 est le MICOCOULIER.",
    readingMnemonicFr: "Enoki - L'arbre de l'été.",
    levelId: 55,
  },
  // Abstract concepts
  {
    character: "遂",
    meaningsFr: ["accomplir", "finalement"],
    readingsOn: ["スイ"],
    readingsKun: ["と.げる"],
    meaningMnemonicFr: "Marcher 辶 pour poursuivre 㒸 jusqu'à ACCOMPLIR.",
    readingMnemonicFr: "SUI - L'accomplissement final.",
    levelId: 47,
  },
  {
    character: "遮",
    meaningsFr: ["bloquer", "intercepter"],
    readingsOn: ["シャ"],
    readingsKun: ["さえぎ.る"],
    meaningMnemonicFr: "Marcher 辶 avec une barrière 庶 pour BLOQUER.",
    readingMnemonicFr: "SHA - L'interception du chemin.",
    levelId: 48,
  },
  {
    character: "遡",
    meaningsFr: ["remonter le courant"],
    readingsOn: ["ソ"],
    readingsKun: ["さかのぼ.る"],
    meaningMnemonicFr: "Marcher 辶 contre le flux 朔 pour REMONTER.",
    readingMnemonicFr: "SO - Remonter le temps.",
    levelId: 51,
  },
  {
    character: "遜",
    meaningsFr: ["modestie", "humilité"],
    readingsOn: ["ソン"],
    readingsKun: [],
    meaningMnemonicFr: "Marcher 辶 avec le petit-fils 孫 montre la MODESTIE.",
    readingMnemonicFr: "SON - L'humilité face aux anciens.",
    levelId: 50,
  },
  {
    character: "遵",
    meaningsFr: ["obéir", "suivre"],
    readingsOn: ["ジュン"],
    readingsKun: [],
    meaningMnemonicFr: "Marcher 辶 en respectant 尊 les règles pour OBÉIR.",
    readingMnemonicFr: "JUN - Le respect des règles.",
    levelId: 49,
  },
  // More unique kanji
  {
    character: "嘲",
    meaningsFr: ["ridiculiser", "moquer"],
    readingsOn: ["チョウ"],
    readingsKun: ["あざけ.る"],
    meaningMnemonicFr: "La bouche 口 du matin 朝 qui se MOQUE.",
    readingMnemonicFr: "CHŌ - Le rire moqueur.",
    levelId: 51,
  },
  {
    character: "嘆",
    meaningsFr: ["soupirer", "déplorer"],
    readingsOn: ["タン"],
    readingsKun: ["なげ.く"],
    meaningMnemonicFr: "La bouche 口 avec un grand soupir 𦰩 pour DÉPLORER.",
    readingMnemonicFr: "TAN - Le soupir de regret.",
    levelId: 46,
  },
  {
    character: "喚",
    meaningsFr: ["appeler", "crier"],
    readingsOn: ["カン"],
    readingsKun: ["わめ.く"],
    meaningMnemonicFr: "La bouche 口 qui échange 奐 des APPELS.",
    readingMnemonicFr: "KAN - Le cri d'appel.",
    levelId: 47,
  },
  {
    character: "唾",
    meaningsFr: ["salive", "cracher"],
    readingsOn: ["ダ"],
    readingsKun: ["つば", "つばき"],
    meaningMnemonicFr: "La bouche 口 qui tombe 垂 crache sa SALIVE.",
    readingMnemonicFr: "DA - La salive qui tombe.",
    levelId: 52,
  },
  {
    character: "呆",
    meaningsFr: ["stupéfait", "abasourdi"],
    readingsOn: ["ホウ", "ボウ"],
    readingsKun: ["あき.れる", "ほう.ける"],
    meaningMnemonicFr: "La bouche 口 de l'arbre 木 reste STUPÉFAITE.",
    readingMnemonicFr: "HŌ - La stupéfaction muette.",
    levelId: 44,
  },
  {
    character: "咳",
    meaningsFr: ["toux", "tousser"],
    readingsOn: ["ガイ"],
    readingsKun: ["せき", "せ.く"],
    meaningMnemonicFr: "La bouche 口 avec un bébé 亥 qui TOUSSE.",
    readingMnemonicFr: "GAI - La toux sèche.",
    levelId: 48,
  },
  {
    character: "喉",
    meaningsFr: ["gorge"],
    readingsOn: ["コウ"],
    readingsKun: ["のど"],
    meaningMnemonicFr: "La bouche 口 du seigneur 侯 a une GORGE.",
    readingMnemonicFr: "KŌ - La gorge qui chante.",
    levelId: 47,
  },
  {
    character: "嗅",
    meaningsFr: ["sentir", "flairer"],
    readingsOn: ["キュウ"],
    readingsKun: ["か.ぐ"],
    meaningMnemonicFr: "La bouche 口 qui sent 臭 FLAIRE les odeurs.",
    readingMnemonicFr: "KYŪ - Le flair du nez.",
    levelId: 50,
  },
  // Tools and objects
  {
    character: "鍵",
    meaningsFr: ["clé"],
    readingsOn: ["ケン"],
    readingsKun: ["かぎ"],
    meaningMnemonicFr: "Le métal 金 pour construire 建 une CLÉ.",
    readingMnemonicFr: "KEN - La clé qui ouvre.",
    levelId: 45,
  },
  {
    character: "錠",
    meaningsFr: ["serrure", "verrou"],
    readingsOn: ["ジョウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le métal 金 fixé 定 est une SERRURE.",
    readingMnemonicFr: "JŌ - Le verrou de sécurité.",
    levelId: 46,
  },
  {
    character: "鋸",
    meaningsFr: ["scie"],
    readingsOn: ["キョ"],
    readingsKun: ["のこぎり"],
    meaningMnemonicFr: "Le métal 金 qui s'assoit 居 et coupe est une SCIE.",
    readingMnemonicFr: "KYO - Le bruit de la scie.",
    levelId: 52,
  },
  {
    character: "釘",
    meaningsFr: ["clou"],
    readingsOn: ["テイ"],
    readingsKun: ["くぎ"],
    meaningMnemonicFr: "Le métal 金 en forme de T 丁 est un CLOU.",
    readingMnemonicFr: "TEI - Le clou qu'on enfonce.",
    levelId: 47,
  },
  {
    character: "釜",
    meaningsFr: ["chaudron", "marmite"],
    readingsOn: ["フ"],
    readingsKun: ["かま"],
    meaningMnemonicFr: "Le métal 金 de père 父 est un CHAUDRON.",
    readingMnemonicFr: "FU - Le chaudron qui bout.",
    levelId: 49,
  },
  {
    character: "斧",
    meaningsFr: ["hache"],
    readingsOn: ["フ"],
    readingsKun: ["おの"],
    meaningMnemonicFr: "Le père 父 avec une arme 斤 a une HACHE.",
    readingMnemonicFr: "FU - La hache du bûcheron.",
    levelId: 48,
  },
  {
    character: "鉢",
    meaningsFr: ["bol", "pot"],
    readingsOn: ["ハチ", "ハツ"],
    readingsKun: [],
    meaningMnemonicFr: "Le métal 金 pour l'origine 本 est un BOL.",
    readingMnemonicFr: "HACHI - Le bol du moine.",
    levelId: 46,
  },
  {
    character: "桶",
    meaningsFr: ["seau", "baquet"],
    readingsOn: ["トウ"],
    readingsKun: ["おけ"],
    meaningMnemonicFr: "Le bois 木 qui contient 甬 est un SEAU.",
    readingMnemonicFr: "TŌ - Le seau en bois.",
    levelId: 50,
  },
  // More verbs
  {
    character: "刈",
    meaningsFr: ["faucher", "couper"],
    readingsOn: ["ガイ"],
    readingsKun: ["か.る"],
    meaningMnemonicFr: "Le couteau 刂 qui fait 乂 FAUCHE l'herbe.",
    readingMnemonicFr: "GAI - La faux qui coupe.",
    levelId: 43,
  },
  {
    character: "剃",
    meaningsFr: ["raser"],
    readingsOn: ["テイ"],
    readingsKun: ["そ.る"],
    meaningMnemonicFr: "Le couteau 刂 du frère 弟 RASE la barbe.",
    readingMnemonicFr: "TEI - Le rasoir du barbier.",
    levelId: 49,
  },
  {
    character: "剥",
    meaningsFr: ["peler", "écorcer"],
    readingsOn: ["ハク"],
    readingsKun: ["む.く", "は.ぐ"],
    meaningMnemonicFr: "Le couteau 刂 qui enregistre 録 PÈLE la peau.",
    readingMnemonicFr: "HAKU - Peler le fruit.",
    levelId: 50,
  },
  {
    character: "剣",
    meaningsFr: ["épée", "sabre"],
    readingsOn: ["ケン"],
    readingsKun: ["つるぎ"],
    meaningMnemonicFr: "Le couteau 刂 avec une combinaison 僉 est une ÉPÉE.",
    readingMnemonicFr: "KEN - L'épée du samouraï.",
    levelId: 41,
  },
  {
    character: "砕",
    meaningsFr: ["écraser", "briser"],
    readingsOn: ["サイ"],
    readingsKun: ["くだ.く", "くだ.ける"],
    meaningMnemonicFr: "La pierre 石 qui devient neuf 卒 se BRISE.",
    readingMnemonicFr: "SAI - Le fracas de la pierre.",
    levelId: 44,
  },
  {
    character: "磨",
    meaningsFr: ["polir", "frotter"],
    readingsOn: ["マ"],
    readingsKun: ["みが.く"],
    meaningMnemonicFr: "Le chanvre 麻 sur la pierre 石 POLIT la surface.",
    readingMnemonicFr: "MA - Le polissage minutieux.",
    levelId: 45,
  },
  // Buildings and places
  {
    character: "塀",
    meaningsFr: ["mur", "clôture"],
    readingsOn: ["ヘイ"],
    readingsKun: [],
    meaningMnemonicFr: "La terre 土 en parallèle 并 forme un MUR.",
    readingMnemonicFr: "HEI - Le mur de séparation.",
    levelId: 48,
  },
  {
    character: "垣",
    meaningsFr: ["clôture", "haie"],
    readingsOn: ["エン"],
    readingsKun: ["かき"],
    meaningMnemonicFr: "La terre 土 continue 亘 forme une CLÔTURE.",
    readingMnemonicFr: "EN - La haie du jardin.",
    levelId: 47,
  },
  {
    character: "堀",
    meaningsFr: ["fossé", "canal"],
    readingsOn: ["クツ"],
    readingsKun: ["ほり"],
    meaningMnemonicFr: "La terre 土 creusée 屈 forme un FOSSÉ.",
    readingMnemonicFr: "KUTSU - Le fossé défensif.",
    levelId: 49,
  },
  {
    character: "塔",
    meaningsFr: ["tour", "pagode"],
    readingsOn: ["トウ"],
    readingsKun: [],
    meaningMnemonicFr: "La terre 土 qui rassemble 荅 forme une TOUR.",
    readingMnemonicFr: "TŌ - La tour qui s'élève.",
    levelId: 44,
  },
  {
    character: "墳",
    meaningsFr: ["tombe", "tumulus"],
    readingsOn: ["フン"],
    readingsKun: [],
    meaningMnemonicFr: "La terre 土 qui brûle 賁 d'énergie est une TOMBE.",
    readingMnemonicFr: "FUN - Le tumulus ancien.",
    levelId: 50,
  },
  // Final unique kanji to reach target
  {
    character: "痒",
    meaningsFr: ["démangeaison"],
    readingsOn: ["ヨウ"],
    readingsKun: ["かゆ.い"],
    meaningMnemonicFr: "La maladie 疒 du mouton 羊 cause une DÉMANGEAISON.",
    readingMnemonicFr: "YŌ - L'envie de se gratter.",
    levelId: 51,
  },
  {
    character: "痺",
    meaningsFr: ["engourdissement"],
    readingsOn: ["ヒ"],
    readingsKun: ["しび.れる"],
    meaningMnemonicFr: "La maladie 疒 qui compare 卑 les sensations cause l'ENGOURDISSEMENT.",
    readingMnemonicFr: "HI - Les fourmis dans les membres.",
    levelId: 52,
  },
  {
    character: "痩",
    meaningsFr: ["maigrir", "mince"],
    readingsOn: ["ソウ"],
    readingsKun: ["や.せる"],
    meaningMnemonicFr: "La maladie 疒 qui sèche 叟 fait MAIGRIR.",
    readingMnemonicFr: "SŌ - La perte de poids.",
    levelId: 50,
  },
  {
    character: "疲",
    meaningsFr: ["fatigué", "épuisé"],
    readingsOn: ["ヒ"],
    readingsKun: ["つか.れる"],
    meaningMnemonicFr: "La maladie 疒 de la peau 皮 rend FATIGUÉ.",
    readingMnemonicFr: "HI - L'épuisement total.",
    levelId: 42,
  },
  {
    character: "疎",
    meaningsFr: ["négligé", "distant"],
    readingsOn: ["ソ"],
    readingsKun: ["うと.い", "まば.ら"],
    meaningMnemonicFr: "La maladie 疒 qui rend la bouche 疋 束 DISTANTE.",
    readingMnemonicFr: "SO - La relation négligée.",
    levelId: 47,
  },
  {
    character: "癒",
    meaningsFr: ["guérir", "soigner"],
    readingsOn: ["ユ"],
    readingsKun: ["い.える", "いや.す"],
    meaningMnemonicFr: "La maladie 疒 avec un cœur 愈 qui GUÉRIT.",
    readingMnemonicFr: "YU - La guérison lente.",
    levelId: 48,
  },
  {
    character: "癖",
    meaningsFr: ["habitude", "manie"],
    readingsOn: ["ヘキ"],
    readingsKun: ["くせ"],
    meaningMnemonicFr: "La maladie 疒 du roi 辟 est une mauvaise HABITUDE.",
    readingMnemonicFr: "HEKI - La manie difficile à changer.",
    levelId: 49,
  },
  {
    character: "窮",
    meaningsFr: ["détresse", "extrémité"],
    readingsOn: ["キュウ"],
    readingsKun: ["きわ.める"],
    meaningMnemonicFr: "La grotte 穴 du corps 身 et de l'arc 弓 est en DÉTRESSE.",
    readingMnemonicFr: "KYŪ - L'impasse totale.",
    levelId: 48,
  },
  {
    character: "窃",
    meaningsFr: ["voler", "dérober"],
    readingsOn: ["セツ"],
    readingsKun: ["ぬす.む"],
    meaningMnemonicFr: "La grotte 穴 où l'on coupe 切 pour VOLER.",
    readingMnemonicFr: "SETSU - Le vol discret.",
    levelId: 49,
  },
  {
    character: "窟",
    meaningsFr: ["caverne", "tanière"],
    readingsOn: ["クツ"],
    readingsKun: [],
    meaningMnemonicFr: "La grotte 穴 creusée 屈 est une CAVERNE.",
    readingMnemonicFr: "KUTSU - La tanière profonde.",
    levelId: 50,
  },
  {
    character: "窯",
    meaningsFr: ["four", "fourneau"],
    readingsOn: ["ヨウ"],
    readingsKun: ["かま"],
    meaningMnemonicFr: "La grotte 穴 avec le mouton 羊 et le feu 灬 est un FOUR.",
    readingMnemonicFr: "YŌ - Le four du potier.",
    levelId: 51,
  },
  {
    character: "穂",
    meaningsFr: ["épi", "pointe"],
    readingsOn: ["スイ"],
    readingsKun: ["ほ"],
    meaningMnemonicFr: "Le grain 禾 qui favorise 恵 forme un ÉPI.",
    readingMnemonicFr: "SUI - L'épi de blé.",
    levelId: 46,
  },
  {
    character: "稲",
    meaningsFr: ["riz", "plant de riz"],
    readingsOn: ["トウ"],
    readingsKun: ["いね"],
    meaningMnemonicFr: "Le grain 禾 qui reste 旧 est le PLANT DE RIZ.",
    readingMnemonicFr: "TŌ - Le riz japonais.",
    levelId: 44,
  },
  {
    character: "穀",
    meaningsFr: ["céréale"],
    readingsOn: ["コク"],
    readingsKun: [],
    meaningMnemonicFr: "Le grain 禾 battu 殳 avec une coquille 士冖 est une CÉRÉALE.",
    readingMnemonicFr: "KOKU - Les céréales de base.",
    levelId: 47,
  },
  {
    character: "租",
    meaningsFr: ["taxe", "impôt"],
    readingsOn: ["ソ"],
    readingsKun: [],
    meaningMnemonicFr: "Le grain 禾 avec l'ancêtre 且 paie la TAXE.",
    readingMnemonicFr: "SO - L'impôt sur les récoltes.",
    levelId: 48,
  },
  {
    character: "稼",
    meaningsFr: ["gagner sa vie", "cultiver"],
    readingsOn: ["カ"],
    readingsKun: ["かせ.ぐ"],
    meaningMnemonicFr: "Le grain 禾 de la maison 家 permet de GAGNER SA VIE.",
    readingMnemonicFr: "KA - Le travail qui nourrit.",
    levelId: 45,
  },
  {
    character: "稽",
    meaningsFr: ["examiner", "comparer"],
    readingsOn: ["ケイ"],
    readingsKun: [],
    meaningMnemonicFr: "Le grain 禾 examiné par le frère 旨 est COMPARÉ.",
    readingMnemonicFr: "KEI - L'examen minutieux.",
    levelId: 50,
  },
];

async function main() {
  console.log("Seeding final kanji batch 7 to exceed 2000...");

  for (const kanji of kanjiData) {
    await prisma.kanji.upsert({
      where: { character: kanji.character },
      update: {
        meaningsFr: kanji.meaningsFr,
        readingsOn: kanji.readingsOn,
        readingsKun: kanji.readingsKun,
        meaningMnemonicFr: kanji.meaningMnemonicFr,
        readingMnemonicFr: kanji.readingMnemonicFr,
        levelId: kanji.levelId,
      },
      create: kanji,
    });
  }

  console.log(`Seeded ${kanjiData.length} kanji.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
