import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Vocabulary supplement for levels 41-45
// Adding ~50 words per level to reach target of ~80-100 per level

const vocabularyData = [
  // Level 41 - JLPT N2/N1 vocabulary (advanced)
  { word: "哲学", meaningsFr: ["Philosophie"], readings: ["てつがく"], mnemonicFr: "La PHILOSOPHIE occidentale.", levelId: 41 },
  { word: "思想", meaningsFr: ["Pensée", "Idéologie"], readings: ["しそう"], mnemonicFr: "La PENSÉE philosophique.", levelId: 41 },
  { word: "概念", meaningsFr: ["Concept", "Notion"], readings: ["がいねん"], mnemonicFr: "Un CONCEPT abstrait.", levelId: 41 },
  { word: "論理", meaningsFr: ["Logique"], readings: ["ろんり"], mnemonicFr: "La LOGIQUE formelle.", levelId: 41 },
  { word: "推論", meaningsFr: ["Raisonnement", "Déduction"], readings: ["すいろん"], mnemonicFr: "Le RAISONNEMENT logique.", levelId: 41 },
  { word: "帰納", meaningsFr: ["Induction"], readings: ["きのう"], mnemonicFr: "L'INDUCTION scientifique.", levelId: 41 },
  { word: "演繹", meaningsFr: ["Déduction"], readings: ["えんえき"], mnemonicFr: "La DÉDUCTION logique.", levelId: 41 },
  { word: "矛盾", meaningsFr: ["Contradiction"], readings: ["むじゅん"], mnemonicFr: "Une CONTRADICTION évidente.", levelId: 41 },
  { word: "対比", meaningsFr: ["Contraste"], readings: ["たいひ"], mnemonicFr: "Un CONTRASTE marqué.", levelId: 41 },
  { word: "類似", meaningsFr: ["Similarité"], readings: ["るいじ"], mnemonicFr: "Une SIMILARITÉ frappante.", levelId: 41 },
  { word: "相違", meaningsFr: ["Différence"], readings: ["そうい"], mnemonicFr: "Une DIFFÉRENCE notable.", levelId: 41 },
  { word: "同一", meaningsFr: ["Identique"], readings: ["どういつ"], mnemonicFr: "Deux choses IDENTIQUES.", levelId: 41 },
  { word: "別個", meaningsFr: ["Distinct", "Séparé"], readings: ["べっこ"], mnemonicFr: "Deux éléments DISTINCTS.", levelId: 41 },
  { word: "独自", meaningsFr: ["Original", "Propre"], readings: ["どくじ"], mnemonicFr: "Un style ORIGINAL.", levelId: 41 },
  { word: "固有", meaningsFr: ["Propre à", "Inhérent"], readings: ["こゆう"], mnemonicFr: "Une caractéristique PROPRE.", levelId: 41 },
  { word: "普遍", meaningsFr: ["Universel"], readings: ["ふへん"], mnemonicFr: "Une vérité UNIVERSELLE.", levelId: 41 },
  { word: "絶対", meaningsFr: ["Absolu"], readings: ["ぜったい"], mnemonicFr: "Une valeur ABSOLUE.", levelId: 41 },
  { word: "相対", meaningsFr: ["Relatif"], readings: ["そうたい"], mnemonicFr: "Une notion RELATIVE.", levelId: 41 },
  { word: "主観", meaningsFr: ["Subjectif"], readings: ["しゅかん"], mnemonicFr: "Un point de vue SUBJECTIF.", levelId: 41 },
  { word: "客観", meaningsFr: ["Objectif"], readings: ["きゃっかん"], mnemonicFr: "Une analyse OBJECTIVE.", levelId: 41 },
  { word: "本質", meaningsFr: ["Essence"], readings: ["ほんしつ"], mnemonicFr: "L'ESSENCE du problème.", levelId: 41 },
  { word: "現象", meaningsFr: ["Phénomène"], readings: ["げんしょう"], mnemonicFr: "Un PHÉNOMÈNE naturel.", levelId: 41 },
  { word: "実体", meaningsFr: ["Substance", "Entité"], readings: ["じったい"], mnemonicFr: "La SUBSTANCE réelle.", levelId: 41 },
  { word: "形態", meaningsFr: ["Forme", "Configuration"], readings: ["けいたい"], mnemonicFr: "La FORME du concept.", levelId: 41 },
  { word: "形式", meaningsFr: ["Format", "Formalité"], readings: ["けいしき"], mnemonicFr: "Le FORMAT standard.", levelId: 41 },
  { word: "内容", meaningsFr: ["Contenu"], readings: ["ないよう"], mnemonicFr: "Le CONTENU du livre.", levelId: 41 },
  { word: "物質", meaningsFr: ["Matière", "Substance"], readings: ["ぶっしつ"], mnemonicFr: "La MATIÈRE physique.", levelId: 41 },
  { word: "精神", meaningsFr: ["Esprit"], readings: ["せいしん"], mnemonicFr: "L'ESPRIT et le corps.", levelId: 41 },
  { word: "意志", meaningsFr: ["Volonté"], readings: ["いし"], mnemonicFr: "La VOLONTÉ de réussir.", levelId: 41 },
  { word: "意図", meaningsFr: ["Intention"], readings: ["いと"], mnemonicFr: "L'INTENTION cachée.", levelId: 41 },
  { word: "動機", meaningsFr: ["Motif", "Motivation"], readings: ["どうき"], mnemonicFr: "Le MOTIF du crime.", levelId: 41 },
  { word: "欲望", meaningsFr: ["Désir"], readings: ["よくぼう"], mnemonicFr: "Le DÉSIR profond.", levelId: 41 },
  { word: "衝動", meaningsFr: ["Impulsion"], readings: ["しょうどう"], mnemonicFr: "Une IMPULSION soudaine.", levelId: 41 },
  { word: "本能", meaningsFr: ["Instinct"], readings: ["ほんのう"], mnemonicFr: "L'INSTINCT de survie.", levelId: 41 },
  { word: "感覚", meaningsFr: ["Sensation", "Sens"], readings: ["かんかく"], mnemonicFr: "La SENSATION de froid.", levelId: 41 },
  { word: "知覚", meaningsFr: ["Perception"], readings: ["ちかく"], mnemonicFr: "La PERCEPTION sensorielle.", levelId: 41 },
  { word: "直感", meaningsFr: ["Intuition"], readings: ["ちょっかん"], mnemonicFr: "L'INTUITION féminine.", levelId: 41 },
  { word: "洞察", meaningsFr: ["Perspicacité"], readings: ["どうさつ"], mnemonicFr: "Une grande PERSPICACITÉ.", levelId: 41 },
  { word: "見識", meaningsFr: ["Discernement"], readings: ["けんしき"], mnemonicFr: "Un grand DISCERNEMENT.", levelId: 41 },
  { word: "判断力", meaningsFr: ["Jugement"], readings: ["はんだんりょく"], mnemonicFr: "Un bon JUGEMENT.", levelId: 41 },
  { word: "想像力", meaningsFr: ["Imagination"], readings: ["そうぞうりょく"], mnemonicFr: "Une grande IMAGINATION.", levelId: 41 },
  { word: "創造力", meaningsFr: ["Créativité"], readings: ["そうぞうりょく"], mnemonicFr: "La CRÉATIVITÉ artistique.", levelId: 41 },
  { word: "思考力", meaningsFr: ["Capacité de réflexion"], readings: ["しこうりょく"], mnemonicFr: "La CAPACITÉ DE RÉFLEXION.", levelId: 41 },
  { word: "集中力", meaningsFr: ["Concentration"], readings: ["しゅうちゅうりょく"], mnemonicFr: "Une grande CONCENTRATION.", levelId: 41 },
  { word: "忍耐力", meaningsFr: ["Patience"], readings: ["にんたいりょく"], mnemonicFr: "Avoir de la PATIENCE.", levelId: 41 },
  { word: "持久力", meaningsFr: ["Endurance"], readings: ["じきゅうりょく"], mnemonicFr: "L'ENDURANCE physique.", levelId: 41 },
  { word: "体力", meaningsFr: ["Force physique"], readings: ["たいりょく"], mnemonicFr: "La FORCE PHYSIQUE.", levelId: 41 },
  { word: "精力", meaningsFr: ["Énergie", "Vitalité"], readings: ["せいりょく"], mnemonicFr: "Plein d'ÉNERGIE.", levelId: 41 },
  { word: "気力", meaningsFr: ["Volonté", "Énergie mentale"], readings: ["きりょく"], mnemonicFr: "La VOLONTÉ de continuer.", levelId: 41 },
  { word: "活力", meaningsFr: ["Vitalité"], readings: ["かつりょく"], mnemonicFr: "Plein de VITALITÉ.", levelId: 41 },

  // Level 42 - JLPT N2/N1 vocabulary (advanced)
  { word: "歴史", meaningsFr: ["Histoire"], readings: ["れきし"], mnemonicFr: "L'HISTOIRE du Japon.", levelId: 42 },
  { word: "時代", meaningsFr: ["Époque", "Ère"], readings: ["じだい"], mnemonicFr: "Une ÉPOQUE révolue.", levelId: 42 },
  { word: "世紀", meaningsFr: ["Siècle"], readings: ["せいき"], mnemonicFr: "Le 21e SIÈCLE.", levelId: 42 },
  { word: "年代", meaningsFr: ["Décennie", "Époque"], readings: ["ねんだい"], mnemonicFr: "Les années 90.", levelId: 42 },
  { word: "起源", meaningsFr: ["Origine"], readings: ["きげん"], mnemonicFr: "L'ORIGINE de l'humanité.", levelId: 42 },
  { word: "発祥", meaningsFr: ["Berceau", "Origine"], readings: ["はっしょう"], mnemonicFr: "Le BERCEAU de la civilisation.", levelId: 42 },
  { word: "文明", meaningsFr: ["Civilisation"], readings: ["ぶんめい"], mnemonicFr: "La CIVILISATION ancienne.", levelId: 42 },
  { word: "王朝", meaningsFr: ["Dynastie"], readings: ["おうちょう"], mnemonicFr: "Une grande DYNASTIE.", levelId: 42 },
  { word: "帝国", meaningsFr: ["Empire"], readings: ["ていこく"], mnemonicFr: "L'EMPIRE romain.", levelId: 42 },
  { word: "領土", meaningsFr: ["Territoire"], readings: ["りょうど"], mnemonicFr: "Le TERRITOIRE national.", levelId: 42 },
  { word: "支配", meaningsFr: ["Domination", "Contrôle"], readings: ["しはい"], mnemonicFr: "La DOMINATION étrangère.", levelId: 42 },
  { word: "征服", meaningsFr: ["Conquête"], readings: ["せいふく"], mnemonicFr: "La CONQUÊTE du monde.", levelId: 42 },
  { word: "侵略", meaningsFr: ["Invasion"], readings: ["しんりゃく"], mnemonicFr: "Une INVASION militaire.", levelId: 42 },
  { word: "植民地", meaningsFr: ["Colonie"], readings: ["しょくみんち"], mnemonicFr: "Une ancienne COLONIE.", levelId: 42 },
  { word: "独立", meaningsFr: ["Indépendance"], readings: ["どくりつ"], mnemonicFr: "L'INDÉPENDANCE nationale.", levelId: 42 },
  { word: "革命", meaningsFr: ["Révolution"], readings: ["かくめい"], mnemonicFr: "La RÉVOLUTION française.", levelId: 42 },
  { word: "改革", meaningsFr: ["Réforme"], readings: ["かいかく"], mnemonicFr: "Une RÉFORME importante.", levelId: 42 },
  { word: "維新", meaningsFr: ["Restauration"], readings: ["いしん"], mnemonicFr: "La RESTAURATION Meiji.", levelId: 42 },
  { word: "近代化", meaningsFr: ["Modernisation"], readings: ["きんだいか"], mnemonicFr: "La MODERNISATION du pays.", levelId: 42 },
  { word: "工業化", meaningsFr: ["Industrialisation"], readings: ["こうぎょうか"], mnemonicFr: "L'INDUSTRIALISATION rapide.", levelId: 42 },
  { word: "都市化", meaningsFr: ["Urbanisation"], readings: ["としか"], mnemonicFr: "L'URBANISATION croissante.", levelId: 42 },
  { word: "国際化", meaningsFr: ["Internationalisation"], readings: ["こくさいか"], mnemonicFr: "L'INTERNATIONALISATION des échanges.", levelId: 42 },
  { word: "民主化", meaningsFr: ["Démocratisation"], readings: ["みんしゅか"], mnemonicFr: "La DÉMOCRATISATION du pays.", levelId: 42 },
  { word: "自由化", meaningsFr: ["Libéralisation"], readings: ["じゆうか"], mnemonicFr: "La LIBÉRALISATION du marché.", levelId: 42 },
  { word: "合理化", meaningsFr: ["Rationalisation"], readings: ["ごうりか"], mnemonicFr: "La RATIONALISATION des coûts.", levelId: 42 },
  { word: "効率化", meaningsFr: ["Optimisation"], readings: ["こうりつか"], mnemonicFr: "L'OPTIMISATION des processus.", levelId: 42 },
  { word: "活性化", meaningsFr: ["Revitalisation"], readings: ["かっせいか"], mnemonicFr: "La REVITALISATION de l'économie.", levelId: 42 },
  { word: "多様化", meaningsFr: ["Diversification"], readings: ["たようか"], mnemonicFr: "La DIVERSIFICATION des activités.", levelId: 42 },
  { word: "高齢化", meaningsFr: ["Vieillissement"], readings: ["こうれいか"], mnemonicFr: "Le VIEILLISSEMENT de la population.", levelId: 42 },
  { word: "少子化", meaningsFr: ["Baisse de la natalité"], readings: ["しょうしか"], mnemonicFr: "La BAISSE DE LA NATALITÉ.", levelId: 42 },
  { word: "過疎化", meaningsFr: ["Dépeuplement"], readings: ["かそか"], mnemonicFr: "Le DÉPEUPLEMENT rural.", levelId: 42 },
  { word: "過密", meaningsFr: ["Surpeuplement"], readings: ["かみつ"], mnemonicFr: "Le SURPEUPLEMENT urbain.", levelId: 42 },
  { word: "格差", meaningsFr: ["Écart", "Disparité"], readings: ["かくさ"], mnemonicFr: "L'ÉCART de revenus.", levelId: 42 },
  { word: "貧困", meaningsFr: ["Pauvreté"], readings: ["ひんこん"], mnemonicFr: "La PAUVRETÉ mondiale.", levelId: 42 },
  { word: "飢餓", meaningsFr: ["Famine"], readings: ["きが"], mnemonicFr: "La FAMINE en Afrique.", levelId: 42 },
  { word: "失業", meaningsFr: ["Chômage"], readings: ["しつぎょう"], mnemonicFr: "Le CHÔMAGE augmente.", levelId: 42 },
  { word: "雇用", meaningsFr: ["Emploi"], readings: ["こよう"], mnemonicFr: "L'EMPLOI stable.", levelId: 42 },
  { word: "労働", meaningsFr: ["Travail"], readings: ["ろうどう"], mnemonicFr: "Le TRAVAIL manuel.", levelId: 42 },
  { word: "賃金", meaningsFr: ["Salaire"], readings: ["ちんぎん"], mnemonicFr: "Le SALAIRE minimum.", levelId: 42 },
  { word: "報酬", meaningsFr: ["Rémunération"], readings: ["ほうしゅう"], mnemonicFr: "La RÉMUNÉRATION adéquate.", levelId: 42 },
  { word: "福利厚生", meaningsFr: ["Avantages sociaux"], readings: ["ふくりこうせい"], mnemonicFr: "Les AVANTAGES SOCIAUX.", levelId: 42 },
  { word: "社会保障", meaningsFr: ["Sécurité sociale"], readings: ["しゃかいほしょう"], mnemonicFr: "La SÉCURITÉ SOCIALE.", levelId: 42 },
  { word: "生活保護", meaningsFr: ["Aide sociale"], readings: ["せいかつほご"], mnemonicFr: "L'AIDE SOCIALE.", levelId: 42 },
  { word: "年金制度", meaningsFr: ["Système de retraite"], readings: ["ねんきんせいど"], mnemonicFr: "Le SYSTÈME DE RETRAITE.", levelId: 42 },
  { word: "医療保険", meaningsFr: ["Assurance maladie"], readings: ["いりょうほけん"], mnemonicFr: "L'ASSURANCE MALADIE.", levelId: 42 },
  { word: "介護保険", meaningsFr: ["Assurance dépendance"], readings: ["かいごほけん"], mnemonicFr: "L'ASSURANCE DÉPENDANCE.", levelId: 42 },
  { word: "失業保険", meaningsFr: ["Assurance chômage"], readings: ["しつぎょうほけん"], mnemonicFr: "L'ASSURANCE CHÔMAGE.", levelId: 42 },
  { word: "労災保険", meaningsFr: ["Assurance accident du travail"], readings: ["ろうさいほけん"], mnemonicFr: "L'ASSURANCE ACCIDENT DU TRAVAIL.", levelId: 42 },
  { word: "確定申告", meaningsFr: ["Déclaration d'impôts"], readings: ["かくていしんこく"], mnemonicFr: "La DÉCLARATION D'IMPÔTS.", levelId: 42 },
  { word: "源泉徴収", meaningsFr: ["Retenue à la source"], readings: ["げんせんちょうしゅう"], mnemonicFr: "La RETENUE À LA SOURCE.", levelId: 42 },

  // Level 43 - JLPT N2/N1 vocabulary (advanced)
  { word: "学問", meaningsFr: ["Science", "Savoir"], readings: ["がくもん"], mnemonicFr: "Le SAVOIR académique.", levelId: 43 },
  { word: "科学", meaningsFr: ["Science"], readings: ["かがく"], mnemonicFr: "La SCIENCE moderne.", levelId: 43 },
  { word: "物理", meaningsFr: ["Physique"], readings: ["ぶつり"], mnemonicFr: "La PHYSIQUE quantique.", levelId: 43 },
  { word: "化学", meaningsFr: ["Chimie"], readings: ["かがく"], mnemonicFr: "La CHIMIE organique.", levelId: 43 },
  { word: "生物", meaningsFr: ["Biologie"], readings: ["せいぶつ"], mnemonicFr: "La BIOLOGIE moléculaire.", levelId: 43 },
  { word: "地学", meaningsFr: ["Géologie"], readings: ["ちがく"], mnemonicFr: "La GÉOLOGIE terrestre.", levelId: 43 },
  { word: "天文", meaningsFr: ["Astronomie"], readings: ["てんもん"], mnemonicFr: "L'ASTRONOMIE ancienne.", levelId: 43 },
  { word: "数学", meaningsFr: ["Mathématiques"], readings: ["すうがく"], mnemonicFr: "Les MATHÉMATIQUES pures.", levelId: 43 },
  { word: "統計学", meaningsFr: ["Statistiques"], readings: ["とうけいがく"], mnemonicFr: "Les STATISTIQUES appliquées.", levelId: 43 },
  { word: "経済学", meaningsFr: ["Économie"], readings: ["けいざいがく"], mnemonicFr: "L'ÉCONOMIE politique.", levelId: 43 },
  { word: "社会学", meaningsFr: ["Sociologie"], readings: ["しゃかいがく"], mnemonicFr: "La SOCIOLOGIE moderne.", levelId: 43 },
  { word: "心理学", meaningsFr: ["Psychologie"], readings: ["しんりがく"], mnemonicFr: "La PSYCHOLOGIE cognitive.", levelId: 43 },
  { word: "言語学", meaningsFr: ["Linguistique"], readings: ["げんごがく"], mnemonicFr: "La LINGUISTIQUE générale.", levelId: 43 },
  { word: "人類学", meaningsFr: ["Anthropologie"], readings: ["じんるいがく"], mnemonicFr: "L'ANTHROPOLOGIE culturelle.", levelId: 43 },
  { word: "考古学", meaningsFr: ["Archéologie"], readings: ["こうこがく"], mnemonicFr: "L'ARCHÉOLOGIE ancienne.", levelId: 43 },
  { word: "民俗学", meaningsFr: ["Folklore"], readings: ["みんぞくがく"], mnemonicFr: "Le FOLKLORE japonais.", levelId: 43 },
  { word: "倫理学", meaningsFr: ["Éthique"], readings: ["りんりがく"], mnemonicFr: "L'ÉTHIQUE appliquée.", levelId: 43 },
  { word: "美学", meaningsFr: ["Esthétique"], readings: ["びがく"], mnemonicFr: "L'ESTHÉTIQUE moderne.", levelId: 43 },
  { word: "宗教学", meaningsFr: ["Sciences religieuses"], readings: ["しゅうきょうがく"], mnemonicFr: "Les SCIENCES RELIGIEUSES.", levelId: 43 },
  { word: "法学", meaningsFr: ["Droit"], readings: ["ほうがく"], mnemonicFr: "Le DROIT constitutionnel.", levelId: 43 },
  { word: "政治学", meaningsFr: ["Science politique"], readings: ["せいじがく"], mnemonicFr: "La SCIENCE POLITIQUE.", levelId: 43 },
  { word: "国際関係", meaningsFr: ["Relations internationales"], readings: ["こくさいかんけい"], mnemonicFr: "Les RELATIONS INTERNATIONALES.", levelId: 43 },
  { word: "外交政策", meaningsFr: ["Politique étrangère"], readings: ["がいこうせいさく"], mnemonicFr: "La POLITIQUE ÉTRANGÈRE.", levelId: 43 },
  { word: "安全保障", meaningsFr: ["Sécurité nationale"], readings: ["あんぜんほしょう"], mnemonicFr: "La SÉCURITÉ NATIONALE.", levelId: 43 },
  { word: "軍事", meaningsFr: ["Militaire"], readings: ["ぐんじ"], mnemonicFr: "Le secteur MILITAIRE.", levelId: 43 },
  { word: "防衛", meaningsFr: ["Défense"], readings: ["ぼうえい"], mnemonicFr: "La DÉFENSE nationale.", levelId: 43 },
  { word: "戦争", meaningsFr: ["Guerre"], readings: ["せんそう"], mnemonicFr: "La GUERRE mondiale.", levelId: 43 },
  { word: "平和", meaningsFr: ["Paix"], readings: ["へいわ"], mnemonicFr: "La PAIX mondiale.", levelId: 43 },
  { word: "紛争", meaningsFr: ["Conflit"], readings: ["ふんそう"], mnemonicFr: "Un CONFLIT régional.", levelId: 43 },
  { word: "停戦", meaningsFr: ["Cessez-le-feu"], readings: ["ていせん"], mnemonicFr: "Un CESSEZ-LE-FEU.", levelId: 43 },
  { word: "休戦", meaningsFr: ["Armistice"], readings: ["きゅうせん"], mnemonicFr: "Un ARMISTICE temporaire.", levelId: 43 },
  { word: "講和", meaningsFr: ["Traité de paix"], readings: ["こうわ"], mnemonicFr: "Un TRAITÉ DE PAIX.", levelId: 43 },
  { word: "同盟", meaningsFr: ["Alliance"], readings: ["どうめい"], mnemonicFr: "Une ALLIANCE militaire.", levelId: 43 },
  { word: "連合", meaningsFr: ["Coalition"], readings: ["れんごう"], mnemonicFr: "Une COALITION internationale.", levelId: 43 },
  { word: "国連", meaningsFr: ["ONU"], readings: ["こくれん"], mnemonicFr: "L'ONU intervient.", levelId: 43 },
  { word: "首脳会談", meaningsFr: ["Sommet"], readings: ["しゅのうかいだん"], mnemonicFr: "Un SOMMET diplomatique.", levelId: 43 },
  { word: "国際会議", meaningsFr: ["Conférence internationale"], readings: ["こくさいかいぎ"], mnemonicFr: "Une CONFÉRENCE INTERNATIONALE.", levelId: 43 },
  { word: "多国間", meaningsFr: ["Multilatéral"], readings: ["たこくかん"], mnemonicFr: "Un accord MULTILATÉRAL.", levelId: 43 },
  { word: "二国間", meaningsFr: ["Bilatéral"], readings: ["にこくかん"], mnemonicFr: "Un accord BILATÉRAL.", levelId: 43 },
  { word: "貿易協定", meaningsFr: ["Accord commercial"], readings: ["ぼうえききょうてい"], mnemonicFr: "Un ACCORD COMMERCIAL.", levelId: 43 },
  { word: "自由貿易", meaningsFr: ["Libre-échange"], readings: ["じゆうぼうえき"], mnemonicFr: "Le LIBRE-ÉCHANGE.", levelId: 43 },
  { word: "保護貿易", meaningsFr: ["Protectionnisme"], readings: ["ほごぼうえき"], mnemonicFr: "Le PROTECTIONNISME économique.", levelId: 43 },
  { word: "関税", meaningsFr: ["Tarif douanier"], readings: ["かんぜい"], mnemonicFr: "Les TARIFS DOUANIERS.", levelId: 43 },
  { word: "輸出入", meaningsFr: ["Import-export"], readings: ["ゆしゅつにゅう"], mnemonicFr: "L'IMPORT-EXPORT.", levelId: 43 },
  { word: "貿易収支", meaningsFr: ["Balance commerciale"], readings: ["ぼうえきしゅうし"], mnemonicFr: "La BALANCE COMMERCIALE.", levelId: 43 },
  { word: "経常収支", meaningsFr: ["Balance courante"], readings: ["けいじょうしゅうし"], mnemonicFr: "La BALANCE COURANTE.", levelId: 43 },
  { word: "為替相場", meaningsFr: ["Taux de change"], readings: ["かわせそうば"], mnemonicFr: "Le TAUX DE CHANGE.", levelId: 43 },
  { word: "円高", meaningsFr: ["Hausse du yen"], readings: ["えんだか"], mnemonicFr: "La HAUSSE DU YEN.", levelId: 43 },
  { word: "円安", meaningsFr: ["Baisse du yen"], readings: ["えんやす"], mnemonicFr: "La BAISSE DU YEN.", levelId: 43 },
  { word: "金利", meaningsFr: ["Taux d'intérêt"], readings: ["きんり"], mnemonicFr: "Le TAUX D'INTÉRÊT.", levelId: 43 },

  // Level 44 - JLPT N1 vocabulary (advanced)
  { word: "医学", meaningsFr: ["Médecine"], readings: ["いがく"], mnemonicFr: "La MÉDECINE moderne.", levelId: 44 },
  { word: "外科", meaningsFr: ["Chirurgie"], readings: ["げか"], mnemonicFr: "La CHIRURGIE cardiaque.", levelId: 44 },
  { word: "内科", meaningsFr: ["Médecine interne"], readings: ["ないか"], mnemonicFr: "La MÉDECINE INTERNE.", levelId: 44 },
  { word: "小児科", meaningsFr: ["Pédiatrie"], readings: ["しょうにか"], mnemonicFr: "La PÉDIATRIE.", levelId: 44 },
  { word: "産婦人科", meaningsFr: ["Gynécologie-obstétrique"], readings: ["さんふじんか"], mnemonicFr: "La GYNÉCOLOGIE.", levelId: 44 },
  { word: "精神科", meaningsFr: ["Psychiatrie"], readings: ["せいしんか"], mnemonicFr: "La PSYCHIATRIE.", levelId: 44 },
  { word: "眼科", meaningsFr: ["Ophtalmologie"], readings: ["がんか"], mnemonicFr: "L'OPHTALMOLOGIE.", levelId: 44 },
  { word: "耳鼻科", meaningsFr: ["ORL"], readings: ["じびか"], mnemonicFr: "L'ORL.", levelId: 44 },
  { word: "皮膚科", meaningsFr: ["Dermatologie"], readings: ["ひふか"], mnemonicFr: "La DERMATOLOGIE.", levelId: 44 },
  { word: "歯科", meaningsFr: ["Dentisterie"], readings: ["しか"], mnemonicFr: "La DENTISTERIE.", levelId: 44 },
  { word: "整形外科", meaningsFr: ["Orthopédie"], readings: ["せいけいげか"], mnemonicFr: "L'ORTHOPÉDIE.", levelId: 44 },
  { word: "放射線科", meaningsFr: ["Radiologie"], readings: ["ほうしゃせんか"], mnemonicFr: "La RADIOLOGIE.", levelId: 44 },
  { word: "麻酔科", meaningsFr: ["Anesthésiologie"], readings: ["ますいか"], mnemonicFr: "L'ANESTHÉSIOLOGIE.", levelId: 44 },
  { word: "救急医療", meaningsFr: ["Médecine d'urgence"], readings: ["きゅうきゅういりょう"], mnemonicFr: "La MÉDECINE D'URGENCE.", levelId: 44 },
  { word: "集中治療", meaningsFr: ["Soins intensifs"], readings: ["しゅうちゅうちりょう"], mnemonicFr: "Les SOINS INTENSIFS.", levelId: 44 },
  { word: "薬学", meaningsFr: ["Pharmacie"], readings: ["やくがく"], mnemonicFr: "La PHARMACIE.", levelId: 44 },
  { word: "処方", meaningsFr: ["Prescription"], readings: ["しょほう"], mnemonicFr: "Une PRESCRIPTION médicale.", levelId: 44 },
  { word: "投薬", meaningsFr: ["Administration de médicaments"], readings: ["とうやく"], mnemonicFr: "L'ADMINISTRATION DE MÉDICAMENTS.", levelId: 44 },
  { word: "副作用", meaningsFr: ["Effet secondaire"], readings: ["ふくさよう"], mnemonicFr: "Un EFFET SECONDAIRE.", levelId: 44 },
  { word: "禁忌", meaningsFr: ["Contre-indication"], readings: ["きんき"], mnemonicFr: "Une CONTRE-INDICATION.", levelId: 44 },
  { word: "臨床", meaningsFr: ["Clinique"], readings: ["りんしょう"], mnemonicFr: "La recherche CLINIQUE.", levelId: 44 },
  { word: "診断", meaningsFr: ["Diagnostic"], readings: ["しんだん"], mnemonicFr: "Le DIAGNOSTIC médical.", levelId: 44 },
  { word: "予後", meaningsFr: ["Pronostic"], readings: ["よご"], mnemonicFr: "Le PRONOSTIC est bon.", levelId: 44 },
  { word: "合併症", meaningsFr: ["Complication"], readings: ["がっぺいしょう"], mnemonicFr: "Une COMPLICATION grave.", levelId: 44 },
  { word: "後遺症", meaningsFr: ["Séquelle"], readings: ["こういしょう"], mnemonicFr: "Des SÉQUELLES durables.", levelId: 44 },
  { word: "慢性", meaningsFr: ["Chronique"], readings: ["まんせい"], mnemonicFr: "Une maladie CHRONIQUE.", levelId: 44 },
  { word: "急性", meaningsFr: ["Aigu"], readings: ["きゅうせい"], mnemonicFr: "Une douleur AIGUË.", levelId: 44 },
  { word: "良性", meaningsFr: ["Bénin"], readings: ["りょうせい"], mnemonicFr: "Une tumeur BÉNIGNE.", levelId: 44 },
  { word: "悪性", meaningsFr: ["Malin"], readings: ["あくせい"], mnemonicFr: "Une tumeur MALIGNE.", levelId: 44 },
  { word: "伝染", meaningsFr: ["Contagion"], readings: ["でんせん"], mnemonicFr: "La CONTAGION du virus.", levelId: 44 },
  { word: "感染", meaningsFr: ["Infection"], readings: ["かんせん"], mnemonicFr: "Une INFECTION bactérienne.", levelId: 44 },
  { word: "発症", meaningsFr: ["Apparition (maladie)"], readings: ["はっしょう"], mnemonicFr: "L'APPARITION des symptômes.", levelId: 44 },
  { word: "発病", meaningsFr: ["Développement (maladie)"], readings: ["はつびょう"], mnemonicFr: "Le DÉVELOPPEMENT de la maladie.", levelId: 44 },
  { word: "再発", meaningsFr: ["Récidive"], readings: ["さいはつ"], mnemonicFr: "Une RÉCIDIVE du cancer.", levelId: 44 },
  { word: "完治", meaningsFr: ["Guérison complète"], readings: ["かんち"], mnemonicFr: "La GUÉRISON COMPLÈTE.", levelId: 44 },
  { word: "寛解", meaningsFr: ["Rémission"], readings: ["かんかい"], mnemonicFr: "En RÉMISSION.", levelId: 44 },
  { word: "緩和", meaningsFr: ["Soulagement"], readings: ["かんわ"], mnemonicFr: "Le SOULAGEMENT de la douleur.", levelId: 44 },
  { word: "延命", meaningsFr: ["Prolongation de la vie"], readings: ["えんめい"], mnemonicFr: "La PROLONGATION DE LA VIE.", levelId: 44 },
  { word: "終末期", meaningsFr: ["Phase terminale"], readings: ["しゅうまつき"], mnemonicFr: "La PHASE TERMINALE.", levelId: 44 },
  { word: "尊厳死", meaningsFr: ["Mort digne"], readings: ["そんげんし"], mnemonicFr: "La MORT DIGNE.", levelId: 44 },
  { word: "安楽死", meaningsFr: ["Euthanasie"], readings: ["あんらくし"], mnemonicFr: "L'EUTHANASIE.", levelId: 44 },
  { word: "臓器移植", meaningsFr: ["Transplantation d'organes"], readings: ["ぞうきいしょく"], mnemonicFr: "La TRANSPLANTATION D'ORGANES.", levelId: 44 },
  { word: "人工臓器", meaningsFr: ["Organe artificiel"], readings: ["じんこうぞうき"], mnemonicFr: "Un ORGANE ARTIFICIEL.", levelId: 44 },
  { word: "再生医療", meaningsFr: ["Médecine régénérative"], readings: ["さいせいいりょう"], mnemonicFr: "La MÉDECINE RÉGÉNÉRATIVE.", levelId: 44 },
  { word: "遺伝子治療", meaningsFr: ["Thérapie génique"], readings: ["いでんしちりょう"], mnemonicFr: "La THÉRAPIE GÉNIQUE.", levelId: 44 },
  { word: "免疫療法", meaningsFr: ["Immunothérapie"], readings: ["めんえきりょうほう"], mnemonicFr: "L'IMMUNOTHÉRAPIE.", levelId: 44 },
  { word: "化学療法", meaningsFr: ["Chimiothérapie"], readings: ["かがくりょうほう"], mnemonicFr: "La CHIMIOTHÉRAPIE.", levelId: 44 },
  { word: "放射線療法", meaningsFr: ["Radiothérapie"], readings: ["ほうしゃせんりょうほう"], mnemonicFr: "La RADIOTHÉRAPIE.", levelId: 44 },
  { word: "理学療法", meaningsFr: ["Kinésithérapie"], readings: ["りがくりょうほう"], mnemonicFr: "La KINÉSITHÉRAPIE.", levelId: 44 },
  { word: "作業療法", meaningsFr: ["Ergothérapie"], readings: ["さぎょうりょうほう"], mnemonicFr: "L'ERGOTHÉRAPIE.", levelId: 44 },

  // Level 45 - JLPT N1 vocabulary (advanced)
  { word: "工学", meaningsFr: ["Ingénierie"], readings: ["こうがく"], mnemonicFr: "L'INGÉNIERIE mécanique.", levelId: 45 },
  { word: "機械工学", meaningsFr: ["Génie mécanique"], readings: ["きかいこうがく"], mnemonicFr: "Le GÉNIE MÉCANIQUE.", levelId: 45 },
  { word: "電気工学", meaningsFr: ["Génie électrique"], readings: ["でんきこうがく"], mnemonicFr: "Le GÉNIE ÉLECTRIQUE.", levelId: 45 },
  { word: "電子工学", meaningsFr: ["Électronique"], readings: ["でんしこうがく"], mnemonicFr: "L'ÉLECTRONIQUE.", levelId: 45 },
  { word: "情報工学", meaningsFr: ["Informatique"], readings: ["じょうほうこうがく"], mnemonicFr: "L'INFORMATIQUE.", levelId: 45 },
  { word: "土木工学", meaningsFr: ["Génie civil"], readings: ["どぼくこうがく"], mnemonicFr: "Le GÉNIE CIVIL.", levelId: 45 },
  { word: "建築工学", meaningsFr: ["Génie architectural"], readings: ["けんちくこうがく"], mnemonicFr: "Le GÉNIE ARCHITECTURAL.", levelId: 45 },
  { word: "化学工学", meaningsFr: ["Génie chimique"], readings: ["かがくこうがく"], mnemonicFr: "Le GÉNIE CHIMIQUE.", levelId: 45 },
  { word: "生命工学", meaningsFr: ["Biotechnologie"], readings: ["せいめいこうがく"], mnemonicFr: "La BIOTECHNOLOGIE.", levelId: 45 },
  { word: "環境工学", meaningsFr: ["Génie environnemental"], readings: ["かんきょうこうがく"], mnemonicFr: "Le GÉNIE ENVIRONNEMENTAL.", levelId: 45 },
  { word: "航空工学", meaningsFr: ["Aéronautique"], readings: ["こうくうこうがく"], mnemonicFr: "L'AÉRONAUTIQUE.", levelId: 45 },
  { word: "宇宙工学", meaningsFr: ["Astronautique"], readings: ["うちゅうこうがく"], mnemonicFr: "L'ASTRONAUTIQUE.", levelId: 45 },
  { word: "原子力工学", meaningsFr: ["Génie nucléaire"], readings: ["げんしりょくこうがく"], mnemonicFr: "Le GÉNIE NUCLÉAIRE.", levelId: 45 },
  { word: "材料工学", meaningsFr: ["Science des matériaux"], readings: ["ざいりょうこうがく"], mnemonicFr: "La SCIENCE DES MATÉRIAUX.", levelId: 45 },
  { word: "ナノテクノロジー", meaningsFr: ["Nanotechnologie"], readings: ["ナノテクノロジー"], mnemonicFr: "La NANOTECHNOLOGIE.", levelId: 45 },
  { word: "人工知能", meaningsFr: ["Intelligence artificielle"], readings: ["じんこうちのう"], mnemonicFr: "L'INTELLIGENCE ARTIFICIELLE.", levelId: 45 },
  { word: "機械学習", meaningsFr: ["Apprentissage automatique"], readings: ["きかいがくしゅう"], mnemonicFr: "L'APPRENTISSAGE AUTOMATIQUE.", levelId: 45 },
  { word: "深層学習", meaningsFr: ["Apprentissage profond"], readings: ["しんそうがくしゅう"], mnemonicFr: "L'APPRENTISSAGE PROFOND.", levelId: 45 },
  { word: "自動運転", meaningsFr: ["Conduite autonome"], readings: ["じどううんてん"], mnemonicFr: "La CONDUITE AUTONOME.", levelId: 45 },
  { word: "ロボット工学", meaningsFr: ["Robotique"], readings: ["ロボットこうがく"], mnemonicFr: "La ROBOTIQUE.", levelId: 45 },
  { word: "仮想現実", meaningsFr: ["Réalité virtuelle"], readings: ["かそうげんじつ"], mnemonicFr: "La RÉALITÉ VIRTUELLE.", levelId: 45 },
  { word: "拡張現実", meaningsFr: ["Réalité augmentée"], readings: ["かくちょうげんじつ"], mnemonicFr: "La RÉALITÉ AUGMENTÉE.", levelId: 45 },
  { word: "量子コンピュータ", meaningsFr: ["Ordinateur quantique"], readings: ["りょうしコンピュータ"], mnemonicFr: "L'ORDINATEUR QUANTIQUE.", levelId: 45 },
  { word: "ブロックチェーン", meaningsFr: ["Blockchain"], readings: ["ブロックチェーン"], mnemonicFr: "La BLOCKCHAIN.", levelId: 45 },
  { word: "暗号通貨", meaningsFr: ["Cryptomonnaie"], readings: ["あんごうつうか"], mnemonicFr: "La CRYPTOMONNAIE.", levelId: 45 },
  { word: "サイバーセキュリティ", meaningsFr: ["Cybersécurité"], readings: ["サイバーセキュリティ"], mnemonicFr: "La CYBERSÉCURITÉ.", levelId: 45 },
  { word: "データ解析", meaningsFr: ["Analyse de données"], readings: ["データかいせき"], mnemonicFr: "L'ANALYSE DE DONNÉES.", levelId: 45 },
  { word: "ビッグデータ", meaningsFr: ["Big data"], readings: ["ビッグデータ"], mnemonicFr: "Le BIG DATA.", levelId: 45 },
  { word: "クラウド", meaningsFr: ["Cloud"], readings: ["クラウド"], mnemonicFr: "Le CLOUD computing.", levelId: 45 },
  { word: "ネットワーク", meaningsFr: ["Réseau"], readings: ["ネットワーク"], mnemonicFr: "Le RÉSEAU informatique.", levelId: 45 },
  { word: "通信網", meaningsFr: ["Réseau de communication"], readings: ["つうしんもう"], mnemonicFr: "Le RÉSEAU DE COMMUNICATION.", levelId: 45 },
  { word: "衛星通信", meaningsFr: ["Communication par satellite"], readings: ["えいせいつうしん"], mnemonicFr: "La COMMUNICATION PAR SATELLITE.", levelId: 45 },
  { word: "光ファイバー", meaningsFr: ["Fibre optique"], readings: ["ひかりファイバー"], mnemonicFr: "La FIBRE OPTIQUE.", levelId: 45 },
  { word: "無線通信", meaningsFr: ["Communication sans fil"], readings: ["むせんつうしん"], mnemonicFr: "La COMMUNICATION SANS FIL.", levelId: 45 },
  { word: "携帯電話", meaningsFr: ["Téléphone portable"], readings: ["けいたいでんわ"], mnemonicFr: "Le TÉLÉPHONE PORTABLE.", levelId: 45 },
  { word: "スマートフォン", meaningsFr: ["Smartphone"], readings: ["スマートフォン"], mnemonicFr: "Le SMARTPHONE.", levelId: 45 },
  { word: "タブレット", meaningsFr: ["Tablette"], readings: ["タブレット"], mnemonicFr: "La TABLETTE.", levelId: 45 },
  { word: "ウェアラブル", meaningsFr: ["Wearable"], readings: ["ウェアラブル"], mnemonicFr: "Le WEARABLE.", levelId: 45 },
  { word: "モノのインターネット", meaningsFr: ["Internet des objets"], readings: ["モノのインターネット"], mnemonicFr: "L'INTERNET DES OBJETS.", levelId: 45 },
  { word: "スマートホーム", meaningsFr: ["Maison connectée"], readings: ["スマートホーム"], mnemonicFr: "La MAISON CONNECTÉE.", levelId: 45 },
  { word: "再生可能エネルギー", meaningsFr: ["Énergie renouvelable"], readings: ["さいせいかのうエネルギー"], mnemonicFr: "L'ÉNERGIE RENOUVELABLE.", levelId: 45 },
  { word: "太陽光発電", meaningsFr: ["Énergie solaire"], readings: ["たいようこうはつでん"], mnemonicFr: "L'ÉNERGIE SOLAIRE.", levelId: 45 },
  { word: "風力発電", meaningsFr: ["Énergie éolienne"], readings: ["ふうりょくはつでん"], mnemonicFr: "L'ÉNERGIE ÉOLIENNE.", levelId: 45 },
  { word: "水力発電", meaningsFr: ["Énergie hydraulique"], readings: ["すいりょくはつでん"], mnemonicFr: "L'ÉNERGIE HYDRAULIQUE.", levelId: 45 },
  { word: "地熱発電", meaningsFr: ["Énergie géothermique"], readings: ["ちねつはつでん"], mnemonicFr: "L'ÉNERGIE GÉOTHERMIQUE.", levelId: 45 },
  { word: "原子力発電", meaningsFr: ["Énergie nucléaire"], readings: ["げんしりょくはつでん"], mnemonicFr: "L'ÉNERGIE NUCLÉAIRE.", levelId: 45 },
  { word: "火力発電", meaningsFr: ["Centrale thermique"], readings: ["かりょくはつでん"], mnemonicFr: "La CENTRALE THERMIQUE.", levelId: 45 },
  { word: "電力網", meaningsFr: ["Réseau électrique"], readings: ["でんりょくもう"], mnemonicFr: "Le RÉSEAU ÉLECTRIQUE.", levelId: 45 },
  { word: "送電", meaningsFr: ["Transmission électrique"], readings: ["そうでん"], mnemonicFr: "La TRANSMISSION ÉLECTRIQUE.", levelId: 45 },
  { word: "蓄電", meaningsFr: ["Stockage d'énergie"], readings: ["ちくでん"], mnemonicFr: "Le STOCKAGE D'ÉNERGIE.", levelId: 45 },
];

async function main() {
  console.log("Seeding vocabulary supplement for levels 41-45...");

  for (const vocab of vocabularyData) {
    await prisma.vocabulary.upsert({
      where: {
        word_levelId: {
          word: vocab.word,
          levelId: vocab.levelId,
        },
      },
      update: {
        meaningsFr: vocab.meaningsFr,
        readings: vocab.readings,
        mnemonicFr: vocab.mnemonicFr,
      },
      create: vocab,
    });
  }

  console.log(`Seeded ${vocabularyData.length} vocabulary words for levels 41-45.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
