import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Vocabulary supplement for levels 26-30
// Adding ~50 words per level to reach target of ~80-100 per level

const vocabularyData = [
  // Level 26 - JLPT N3/N2 vocabulary (upper intermediate)
  { word: "文化", meaningsFr: ["Culture"], readings: ["ぶんか"], mnemonicFr: "La CULTURE japonaise.", levelId: 26 },
  { word: "伝統", meaningsFr: ["Tradition"], readings: ["でんとう"], mnemonicFr: "Les TRADITIONS anciennes.", levelId: 26 },
  { word: "習慣", meaningsFr: ["Habitude", "Coutume"], readings: ["しゅうかん"], mnemonicFr: "Les HABITUDES quotidiennes.", levelId: 26 },
  { word: "風習", meaningsFr: ["Coutume", "Usage"], readings: ["ふうしゅう"], mnemonicFr: "Les COUTUMES locales.", levelId: 26 },
  { word: "儀式", meaningsFr: ["Cérémonie", "Rituel"], readings: ["ぎしき"], mnemonicFr: "Une CÉRÉMONIE traditionnelle.", levelId: 26 },
  { word: "祭り", meaningsFr: ["Festival", "Fête"], readings: ["まつり"], mnemonicFr: "Un grand FESTIVAL.", levelId: 26 },
  { word: "宗教", meaningsFr: ["Religion"], readings: ["しゅうきょう"], mnemonicFr: "La RELIGION au Japon.", levelId: 26 },
  { word: "信仰", meaningsFr: ["Foi", "Croyance"], readings: ["しんこう"], mnemonicFr: "La FOI profonde.", levelId: 26 },
  { word: "神話", meaningsFr: ["Mythologie", "Mythe"], readings: ["しんわ"], mnemonicFr: "Les MYTHES japonais.", levelId: 26 },
  { word: "伝説", meaningsFr: ["Légende"], readings: ["でんせつ"], mnemonicFr: "Une LÉGENDE ancienne.", levelId: 26 },
  { word: "民話", meaningsFr: ["Conte populaire"], readings: ["みんわ"], mnemonicFr: "Un CONTE POPULAIRE.", levelId: 26 },
  { word: "芸術", meaningsFr: ["Art"], readings: ["げいじゅつ"], mnemonicFr: "L'ART contemporain.", levelId: 26 },
  { word: "美術", meaningsFr: ["Beaux-arts"], readings: ["びじゅつ"], mnemonicFr: "Les BEAUX-ARTS.", levelId: 26 },
  { word: "絵画", meaningsFr: ["Peinture"], readings: ["かいが"], mnemonicFr: "Une PEINTURE célèbre.", levelId: 26 },
  { word: "彫刻", meaningsFr: ["Sculpture"], readings: ["ちょうこく"], mnemonicFr: "Une belle SCULPTURE.", levelId: 26 },
  { word: "陶芸", meaningsFr: ["Poterie", "Céramique"], readings: ["とうげい"], mnemonicFr: "L'art de la POTERIE.", levelId: 26 },
  { word: "建築", meaningsFr: ["Architecture"], readings: ["けんちく"], mnemonicFr: "L'ARCHITECTURE moderne.", levelId: 26 },
  { word: "文学", meaningsFr: ["Littérature"], readings: ["ぶんがく"], mnemonicFr: "La LITTÉRATURE japonaise.", levelId: 26 },
  { word: "詩歌", meaningsFr: ["Poésie"], readings: ["しいか"], mnemonicFr: "La POÉSIE lyrique.", levelId: 26 },
  { word: "小説", meaningsFr: ["Roman"], readings: ["しょうせつ"], mnemonicFr: "Écrire un ROMAN.", levelId: 26 },
  { word: "随筆", meaningsFr: ["Essai"], readings: ["ずいひつ"], mnemonicFr: "Un ESSAI littéraire.", levelId: 26 },
  { word: "演劇", meaningsFr: ["Théâtre"], readings: ["えんげき"], mnemonicFr: "Le THÉÂTRE classique.", levelId: 26 },
  { word: "音楽", meaningsFr: ["Musique"], readings: ["おんがく"], mnemonicFr: "La MUSIQUE apaise.", levelId: 26 },
  { word: "舞踊", meaningsFr: ["Danse"], readings: ["ぶよう"], mnemonicFr: "La DANSE traditionnelle.", levelId: 26 },
  { word: "映画", meaningsFr: ["Film", "Cinéma"], readings: ["えいが"], mnemonicFr: "Un bon FILM.", levelId: 26 },
  { word: "娯楽", meaningsFr: ["Divertissement", "Loisir"], readings: ["ごらく"], mnemonicFr: "Le DIVERTISSEMENT populaire.", levelId: 26 },
  { word: "趣味", meaningsFr: ["Hobby", "Goût"], readings: ["しゅみ"], mnemonicFr: "Mes HOBBIES préférés.", levelId: 26 },
  { word: "余暇", meaningsFr: ["Temps libre", "Loisir"], readings: ["よか"], mnemonicFr: "Le TEMPS LIBRE.", levelId: 26 },
  { word: "旅行", meaningsFr: ["Voyage"], readings: ["りょこう"], mnemonicFr: "Un VOYAGE inoubliable.", levelId: 26 },
  { word: "観光", meaningsFr: ["Tourisme"], readings: ["かんこう"], mnemonicFr: "Le TOURISME au Japon.", levelId: 26 },
  { word: "名所", meaningsFr: ["Site célèbre"], readings: ["めいしょ"], mnemonicFr: "Un SITE CÉLÈBRE.", levelId: 26 },
  { word: "遺跡", meaningsFr: ["Ruines", "Vestiges"], readings: ["いせき"], mnemonicFr: "Des RUINES anciennes.", levelId: 26 },
  { word: "世界遺産", meaningsFr: ["Patrimoine mondial"], readings: ["せかいいさん"], mnemonicFr: "Le PATRIMOINE MONDIAL.", levelId: 26 },
  { word: "国宝", meaningsFr: ["Trésor national"], readings: ["こくほう"], mnemonicFr: "Un TRÉSOR NATIONAL.", levelId: 26 },
  { word: "記念", meaningsFr: ["Commémoration", "Souvenir"], readings: ["きねん"], mnemonicFr: "En COMMÉMORATION de.", levelId: 26 },
  { word: "展示", meaningsFr: ["Exposition"], readings: ["てんじ"], mnemonicFr: "Une EXPOSITION d'art.", levelId: 26 },
  { word: "収集", meaningsFr: ["Collection"], readings: ["しゅうしゅう"], mnemonicFr: "Une COLLECTION de timbres.", levelId: 26 },
  { word: "鑑賞", meaningsFr: ["Appréciation"], readings: ["かんしょう"], mnemonicFr: "L'APPRÉCIATION de l'art.", levelId: 26 },
  { word: "批評", meaningsFr: ["Critique"], readings: ["ひひょう"], mnemonicFr: "Une CRITIQUE positive.", levelId: 26 },
  { word: "評論", meaningsFr: ["Critique", "Commentaire"], readings: ["ひょうろん"], mnemonicFr: "Un COMMENTAIRE détaillé.", levelId: 26 },
  { word: "解釈", meaningsFr: ["Interprétation"], readings: ["かいしゃく"], mnemonicFr: "Une INTERPRÉTATION différente.", levelId: 26 },
  { word: "翻訳", meaningsFr: ["Traduction"], readings: ["ほんやく"], mnemonicFr: "Une TRADUCTION fidèle.", levelId: 26 },
  { word: "通訳", meaningsFr: ["Interprétation orale"], readings: ["つうやく"], mnemonicFr: "L'INTERPRÈTE traduit.", levelId: 26 },
  { word: "出版", meaningsFr: ["Publication", "Édition"], readings: ["しゅっぱん"], mnemonicFr: "La PUBLICATION du livre.", levelId: 26 },
  { word: "発行", meaningsFr: ["Émission", "Publication"], readings: ["はっこう"], mnemonicFr: "L'ÉMISSION d'un journal.", levelId: 26 },
  { word: "編集", meaningsFr: ["Édition", "Rédaction"], readings: ["へんしゅう"], mnemonicFr: "L'ÉDITION du magazine.", levelId: 26 },
  { word: "報道", meaningsFr: ["Presse", "Information"], readings: ["ほうどう"], mnemonicFr: "La PRESSE couvre l'événement.", levelId: 26 },
  { word: "放送", meaningsFr: ["Diffusion", "Émission"], readings: ["ほうそう"], mnemonicFr: "La DIFFUSION en direct.", levelId: 26 },
  { word: "広告", meaningsFr: ["Publicité"], readings: ["こうこく"], mnemonicFr: "Une PUBLICITÉ efficace.", levelId: 26 },
  { word: "宣伝", meaningsFr: ["Promotion", "Propagande"], readings: ["せんでん"], mnemonicFr: "La PROMOTION du produit.", levelId: 26 },

  // Level 27 - JLPT N3/N2 vocabulary (upper intermediate)
  { word: "通信", meaningsFr: ["Communication", "Télécommunication"], readings: ["つうしん"], mnemonicFr: "Les TÉLÉCOMMUNICATIONS.", levelId: 27 },
  { word: "情報", meaningsFr: ["Information"], readings: ["じょうほう"], mnemonicFr: "L'INFORMATION circule.", levelId: 27 },
  { word: "知識", meaningsFr: ["Connaissance"], readings: ["ちしき"], mnemonicFr: "La CONNAISSANCE s'acquiert.", levelId: 27 },
  { word: "データ", meaningsFr: ["Données"], readings: ["データ"], mnemonicFr: "Analyser les DONNÉES.", levelId: 27 },
  { word: "記録", meaningsFr: ["Enregistrement", "Record"], readings: ["きろく"], mnemonicFr: "Un ENREGISTREMENT important.", levelId: 27 },
  { word: "文書", meaningsFr: ["Document"], readings: ["ぶんしょ"], mnemonicFr: "Un DOCUMENT officiel.", levelId: 27 },
  { word: "書類", meaningsFr: ["Documents", "Papiers"], readings: ["しょるい"], mnemonicFr: "Les DOCUMENTS nécessaires.", levelId: 27 },
  { word: "報告", meaningsFr: ["Rapport", "Compte-rendu"], readings: ["ほうこく"], mnemonicFr: "Un RAPPORT détaillé.", levelId: 27 },
  { word: "発表", meaningsFr: ["Annonce", "Présentation"], readings: ["はっぴょう"], mnemonicFr: "L'ANNONCE officielle.", levelId: 27 },
  { word: "論文", meaningsFr: ["Thèse", "Article"], readings: ["ろんぶん"], mnemonicFr: "Une THÈSE de doctorat.", levelId: 27 },
  { word: "資料", meaningsFr: ["Documents", "Matériaux"], readings: ["しりょう"], mnemonicFr: "Les DOCUMENTS de référence.", levelId: 27 },
  { word: "参考", meaningsFr: ["Référence"], readings: ["さんこう"], mnemonicFr: "Pour RÉFÉRENCE.", levelId: 27 },
  { word: "引用", meaningsFr: ["Citation"], readings: ["いんよう"], mnemonicFr: "Une CITATION célèbre.", levelId: 27 },
  { word: "出典", meaningsFr: ["Source", "Référence"], readings: ["しゅってん"], mnemonicFr: "La SOURCE de l'information.", levelId: 27 },
  { word: "概要", meaningsFr: ["Résumé", "Aperçu"], readings: ["がいよう"], mnemonicFr: "Un RÉSUMÉ clair.", levelId: 27 },
  { word: "要点", meaningsFr: ["Point essentiel"], readings: ["ようてん"], mnemonicFr: "Le POINT ESSENTIEL.", levelId: 27 },
  { word: "詳細", meaningsFr: ["Détails"], readings: ["しょうさい"], mnemonicFr: "Les DÉTAILS importants.", levelId: 27 },
  { word: "具体", meaningsFr: ["Concret"], readings: ["ぐたい"], mnemonicFr: "Un exemple CONCRET.", levelId: 27 },
  { word: "抽象", meaningsFr: ["Abstrait"], readings: ["ちゅうしょう"], mnemonicFr: "Un concept ABSTRAIT.", levelId: 27 },
  { word: "理論", meaningsFr: ["Théorie"], readings: ["りろん"], mnemonicFr: "Une THÉORIE scientifique.", levelId: 27 },
  { word: "仮説", meaningsFr: ["Hypothèse"], readings: ["かせつ"], mnemonicFr: "Une HYPOTHÈSE intéressante.", levelId: 27 },
  { word: "実験", meaningsFr: ["Expérience"], readings: ["じっけん"], mnemonicFr: "Une EXPÉRIENCE en laboratoire.", levelId: 27 },
  { word: "観察", meaningsFr: ["Observation"], readings: ["かんさつ"], mnemonicFr: "L'OBSERVATION attentive.", levelId: 27 },
  { word: "測定", meaningsFr: ["Mesure"], readings: ["そくてい"], mnemonicFr: "La MESURE précise.", levelId: 27 },
  { word: "計算", meaningsFr: ["Calcul"], readings: ["けいさん"], mnemonicFr: "Un CALCUL complexe.", levelId: 27 },
  { word: "数値", meaningsFr: ["Valeur numérique"], readings: ["すうち"], mnemonicFr: "La VALEUR NUMÉRIQUE.", levelId: 27 },
  { word: "公式", meaningsFr: ["Formule"], readings: ["こうしき"], mnemonicFr: "Une FORMULE mathématique.", levelId: 27 },
  { word: "定理", meaningsFr: ["Théorème"], readings: ["ていり"], mnemonicFr: "Un THÉORÈME prouvé.", levelId: 27 },
  { word: "法則", meaningsFr: ["Loi (scientifique)"], readings: ["ほうそく"], mnemonicFr: "Une LOI de la physique.", levelId: 27 },
  { word: "原理", meaningsFr: ["Principe"], readings: ["げんり"], mnemonicFr: "Le PRINCIPE de base.", levelId: 27 },
  { word: "構造", meaningsFr: ["Structure"], readings: ["こうぞう"], mnemonicFr: "La STRUCTURE du bâtiment.", levelId: 27 },
  { word: "機能", meaningsFr: ["Fonction"], readings: ["きのう"], mnemonicFr: "La FONCTION principale.", levelId: 27 },
  { word: "特徴", meaningsFr: ["Caractéristique"], readings: ["とくちょう"], mnemonicFr: "Une CARACTÉRISTIQUE unique.", levelId: 27 },
  { word: "性質", meaningsFr: ["Nature", "Propriété"], readings: ["せいしつ"], mnemonicFr: "La NATURE du matériau.", levelId: 27 },
  { word: "特性", meaningsFr: ["Propriété", "Attribut"], readings: ["とくせい"], mnemonicFr: "Les PROPRIÉTÉS spéciales.", levelId: 27 },
  { word: "要素", meaningsFr: ["Élément", "Facteur"], readings: ["ようそ"], mnemonicFr: "Un ÉLÉMENT important.", levelId: 27 },
  { word: "成分", meaningsFr: ["Composant", "Ingrédient"], readings: ["せいぶん"], mnemonicFr: "Les COMPOSANTS du produit.", levelId: 27 },
  { word: "組成", meaningsFr: ["Composition"], readings: ["そせい"], mnemonicFr: "La COMPOSITION chimique.", levelId: 27 },
  { word: "分類", meaningsFr: ["Classification"], readings: ["ぶんるい"], mnemonicFr: "La CLASSIFICATION des espèces.", levelId: 27 },
  { word: "種類", meaningsFr: ["Type", "Sorte"], readings: ["しゅるい"], mnemonicFr: "Plusieurs TYPES différents.", levelId: 27 },
  { word: "区分", meaningsFr: ["Division", "Catégorie"], readings: ["くぶん"], mnemonicFr: "La DIVISION en catégories.", levelId: 27 },
  { word: "範囲", meaningsFr: ["Portée", "Étendue"], readings: ["はんい"], mnemonicFr: "La PORTÉE de l'étude.", levelId: 27 },
  { word: "領域", meaningsFr: ["Domaine", "Territoire"], readings: ["りょういき"], mnemonicFr: "Le DOMAINE de recherche.", levelId: 27 },
  { word: "分野", meaningsFr: ["Domaine", "Champ"], readings: ["ぶんや"], mnemonicFr: "Un DOMAINE d'expertise.", levelId: 27 },
  { word: "専門", meaningsFr: ["Spécialité"], readings: ["せんもん"], mnemonicFr: "Ma SPÉCIALITÉ.", levelId: 27 },
  { word: "基礎", meaningsFr: ["Base", "Fondement"], readings: ["きそ"], mnemonicFr: "Les BASES solides.", levelId: 27 },
  { word: "応用", meaningsFr: ["Application"], readings: ["おうよう"], mnemonicFr: "L'APPLICATION pratique.", levelId: 27 },
  { word: "実用", meaningsFr: ["Pratique", "Utilitaire"], readings: ["じつよう"], mnemonicFr: "Un usage PRATIQUE.", levelId: 27 },
  { word: "効率", meaningsFr: ["Efficacité"], readings: ["こうりつ"], mnemonicFr: "L'EFFICACITÉ maximale.", levelId: 27 },
  { word: "精度", meaningsFr: ["Précision"], readings: ["せいど"], mnemonicFr: "Une grande PRÉCISION.", levelId: 27 },

  // Level 28 - JLPT N2 vocabulary (upper intermediate)
  { word: "交通", meaningsFr: ["Transport", "Circulation"], readings: ["こうつう"], mnemonicFr: "Le TRANSPORT en commun.", levelId: 28 },
  { word: "運輸", meaningsFr: ["Transport", "Fret"], readings: ["うんゆ"], mnemonicFr: "Le TRANSPORT de marchandises.", levelId: 28 },
  { word: "鉄道", meaningsFr: ["Chemin de fer"], readings: ["てつどう"], mnemonicFr: "Le CHEMIN DE FER.", levelId: 28 },
  { word: "航空", meaningsFr: ["Aviation"], readings: ["こうくう"], mnemonicFr: "L'AVIATION civile.", levelId: 28 },
  { word: "海運", meaningsFr: ["Transport maritime"], readings: ["かいうん"], mnemonicFr: "Le TRANSPORT MARITIME.", levelId: 28 },
  { word: "物流", meaningsFr: ["Logistique"], readings: ["ぶつりゅう"], mnemonicFr: "La LOGISTIQUE moderne.", levelId: 28 },
  { word: "配送", meaningsFr: ["Livraison"], readings: ["はいそう"], mnemonicFr: "La LIVRAISON à domicile.", levelId: 28 },
  { word: "輸送", meaningsFr: ["Transport"], readings: ["ゆそう"], mnemonicFr: "Le TRANSPORT des biens.", levelId: 28 },
  { word: "通勤", meaningsFr: ["Trajet domicile-travail"], readings: ["つうきん"], mnemonicFr: "Le TRAJET quotidien.", levelId: 28 },
  { word: "通学", meaningsFr: ["Trajet domicile-école"], readings: ["つうがく"], mnemonicFr: "Le TRAJET vers l'école.", levelId: 28 },
  { word: "往復", meaningsFr: ["Aller-retour"], readings: ["おうふく"], mnemonicFr: "Un billet ALLER-RETOUR.", levelId: 28 },
  { word: "片道", meaningsFr: ["Aller simple"], readings: ["かたみち"], mnemonicFr: "Un billet ALLER SIMPLE.", levelId: 28 },
  { word: "乗車", meaningsFr: ["Embarquement"], readings: ["じょうしゃ"], mnemonicFr: "L'EMBARQUEMENT dans le train.", levelId: 28 },
  { word: "下車", meaningsFr: ["Descente (véhicule)"], readings: ["げしゃ"], mnemonicFr: "La DESCENTE du bus.", levelId: 28 },
  { word: "乗換", meaningsFr: ["Correspondance"], readings: ["のりかえ"], mnemonicFr: "La CORRESPONDANCE au métro.", levelId: 28 },
  { word: "運賃", meaningsFr: ["Tarif de transport"], readings: ["うんちん"], mnemonicFr: "Le TARIF du transport.", levelId: 28 },
  { word: "料金", meaningsFr: ["Frais", "Tarif"], readings: ["りょうきん"], mnemonicFr: "Les FRAIS de service.", levelId: 28 },
  { word: "手数料", meaningsFr: ["Commission", "Frais"], readings: ["てすうりょう"], mnemonicFr: "La COMMISSION bancaire.", levelId: 28 },
  { word: "割引", meaningsFr: ["Réduction"], readings: ["わりびき"], mnemonicFr: "Une RÉDUCTION de prix.", levelId: 28 },
  { word: "免税", meaningsFr: ["Détaxe"], readings: ["めんぜい"], mnemonicFr: "Achat DÉTAXÉ.", levelId: 28 },
  { word: "両替", meaningsFr: ["Change (monnaie)"], readings: ["りょうがえ"], mnemonicFr: "Le CHANGE de devises.", levelId: 28 },
  { word: "送金", meaningsFr: ["Virement"], readings: ["そうきん"], mnemonicFr: "Un VIREMENT bancaire.", levelId: 28 },
  { word: "振込", meaningsFr: ["Virement bancaire"], readings: ["ふりこみ"], mnemonicFr: "Faire un VIREMENT.", levelId: 28 },
  { word: "引出", meaningsFr: ["Retrait"], readings: ["ひきだし"], mnemonicFr: "Un RETRAIT d'argent.", levelId: 28 },
  { word: "預金", meaningsFr: ["Dépôt bancaire"], readings: ["よきん"], mnemonicFr: "Un DÉPÔT sur le compte.", levelId: 28 },
  { word: "貯金", meaningsFr: ["Épargne"], readings: ["ちょきん"], mnemonicFr: "Mon ÉPARGNE augmente.", levelId: 28 },
  { word: "残高", meaningsFr: ["Solde (compte)"], readings: ["ざんだか"], mnemonicFr: "Le SOLDE du compte.", levelId: 28 },
  { word: "口座", meaningsFr: ["Compte bancaire"], readings: ["こうざ"], mnemonicFr: "Ouvrir un COMPTE.", levelId: 28 },
  { word: "現金", meaningsFr: ["Espèces", "Liquide"], readings: ["げんきん"], mnemonicFr: "Payer en ESPÈCES.", levelId: 28 },
  { word: "小銭", meaningsFr: ["Monnaie", "Pièces"], readings: ["こぜに"], mnemonicFr: "Avoir de la MONNAIE.", levelId: 28 },
  { word: "硬貨", meaningsFr: ["Pièce de monnaie"], readings: ["こうか"], mnemonicFr: "Une PIÈCE de monnaie.", levelId: 28 },
  { word: "紙幣", meaningsFr: ["Billet de banque"], readings: ["しへい"], mnemonicFr: "Un BILLET de banque.", levelId: 28 },
  { word: "収支", meaningsFr: ["Recettes et dépenses"], readings: ["しゅうし"], mnemonicFr: "Le bilan des RECETTES ET DÉPENSES.", levelId: 28 },
  { word: "決算", meaningsFr: ["Bilan comptable"], readings: ["けっさん"], mnemonicFr: "Le BILAN annuel.", levelId: 28 },
  { word: "会計", meaningsFr: ["Comptabilité"], readings: ["かいけい"], mnemonicFr: "La COMPTABILITÉ de l'entreprise.", levelId: 28 },
  { word: "経理", meaningsFr: ["Comptabilité", "Finance"], readings: ["けいり"], mnemonicFr: "Le service COMPTABLE.", levelId: 28 },
  { word: "監査", meaningsFr: ["Audit"], readings: ["かんさ"], mnemonicFr: "Un AUDIT financier.", levelId: 28 },
  { word: "管理", meaningsFr: ["Gestion", "Administration"], readings: ["かんり"], mnemonicFr: "La GESTION des ressources.", levelId: 28 },
  { word: "運営", meaningsFr: ["Exploitation", "Gestion"], readings: ["うんえい"], mnemonicFr: "L'EXPLOITATION du site.", levelId: 28 },
  { word: "経営", meaningsFr: ["Direction", "Gestion"], readings: ["けいえい"], mnemonicFr: "La DIRECTION de l'entreprise.", levelId: 28 },
  { word: "事業", meaningsFr: ["Entreprise", "Activité"], readings: ["じぎょう"], mnemonicFr: "Une ENTREPRISE prospère.", levelId: 28 },
  { word: "業務", meaningsFr: ["Activités", "Tâches"], readings: ["ぎょうむ"], mnemonicFr: "Les ACTIVITÉS quotidiennes.", levelId: 28 },
  { word: "職務", meaningsFr: ["Fonction", "Rôle"], readings: ["しょくむ"], mnemonicFr: "Mes FONCTIONS au travail.", levelId: 28 },
  { word: "任務", meaningsFr: ["Mission", "Devoir"], readings: ["にんむ"], mnemonicFr: "Une MISSION importante.", levelId: 28 },
  { word: "役割", meaningsFr: ["Rôle"], readings: ["やくわり"], mnemonicFr: "Mon RÔLE dans l'équipe.", levelId: 28 },
  { word: "担当", meaningsFr: ["Charge", "Responsabilité"], readings: ["たんとう"], mnemonicFr: "Être en CHARGE de.", levelId: 28 },
  { word: "配属", meaningsFr: ["Affectation"], readings: ["はいぞく"], mnemonicFr: "L'AFFECTATION à un poste.", levelId: 28 },
  { word: "異動", meaningsFr: ["Mutation", "Transfert"], readings: ["いどう"], mnemonicFr: "Une MUTATION professionnelle.", levelId: 28 },
  { word: "昇進", meaningsFr: ["Promotion"], readings: ["しょうしん"], mnemonicFr: "Obtenir une PROMOTION.", levelId: 28 },
  { word: "退職", meaningsFr: ["Démission", "Retraite"], readings: ["たいしょく"], mnemonicFr: "La DÉMISSION ou la retraite.", levelId: 28 },

  // Level 29 - JLPT N2 vocabulary (upper intermediate)
  { word: "人事", meaningsFr: ["Ressources humaines"], readings: ["じんじ"], mnemonicFr: "Le département des RESSOURCES HUMAINES.", levelId: 29 },
  { word: "採用", meaningsFr: ["Recrutement", "Embauche"], readings: ["さいよう"], mnemonicFr: "Le RECRUTEMENT de personnel.", levelId: 29 },
  { word: "面接", meaningsFr: ["Entretien"], readings: ["めんせつ"], mnemonicFr: "Un ENTRETIEN d'embauche.", levelId: 29 },
  { word: "履歴", meaningsFr: ["Historique", "CV"], readings: ["りれき"], mnemonicFr: "Mon HISTORIQUE professionnel.", levelId: 29 },
  { word: "経歴", meaningsFr: ["Parcours", "Carrière"], readings: ["けいれき"], mnemonicFr: "Mon PARCOURS professionnel.", levelId: 29 },
  { word: "資質", meaningsFr: ["Qualité", "Aptitude"], readings: ["ししつ"], mnemonicFr: "Les QUALITÉS requises.", levelId: 29 },
  { word: "適性", meaningsFr: ["Aptitude"], readings: ["てきせい"], mnemonicFr: "L'APTITUDE au poste.", levelId: 29 },
  { word: "研修", meaningsFr: ["Formation"], readings: ["けんしゅう"], mnemonicFr: "Une FORMATION professionnelle.", levelId: 29 },
  { word: "指導", meaningsFr: ["Guidance", "Direction"], readings: ["しどう"], mnemonicFr: "La GUIDANCE du professeur.", levelId: 29 },
  { word: "教訓", meaningsFr: ["Leçon", "Enseignement"], readings: ["きょうくん"], mnemonicFr: "Une LEÇON de vie.", levelId: 29 },
  { word: "助言", meaningsFr: ["Conseil"], readings: ["じょげん"], mnemonicFr: "Un bon CONSEIL.", levelId: 29 },
  { word: "忠告", meaningsFr: ["Avertissement", "Conseil"], readings: ["ちゅうこく"], mnemonicFr: "Un AVERTISSEMENT sincère.", levelId: 29 },
  { word: "注意", meaningsFr: ["Attention", "Avertissement"], readings: ["ちゅうい"], mnemonicFr: "Faire ATTENTION.", levelId: 29 },
  { word: "警告", meaningsFr: ["Avertissement"], readings: ["けいこく"], mnemonicFr: "Un AVERTISSEMENT sérieux.", levelId: 29 },
  { word: "勧告", meaningsFr: ["Recommandation"], readings: ["かんこく"], mnemonicFr: "Une RECOMMANDATION officielle.", levelId: 29 },
  { word: "命令", meaningsFr: ["Ordre", "Commandement"], readings: ["めいれい"], mnemonicFr: "Un ORDRE direct.", levelId: 29 },
  { word: "指示", meaningsFr: ["Instruction"], readings: ["しじ"], mnemonicFr: "Suivre les INSTRUCTIONS.", levelId: 29 },
  { word: "要請", meaningsFr: ["Demande", "Requête"], readings: ["ようせい"], mnemonicFr: "Une DEMANDE officielle.", levelId: 29 },
  { word: "依頼", meaningsFr: ["Demande", "Requête"], readings: ["いらい"], mnemonicFr: "Une REQUÊTE polie.", levelId: 29 },
  { word: "申請", meaningsFr: ["Demande (administrative)"], readings: ["しんせい"], mnemonicFr: "Une DEMANDE administrative.", levelId: 29 },
  { word: "届出", meaningsFr: ["Déclaration", "Notification"], readings: ["とどけで"], mnemonicFr: "Une DÉCLARATION officielle.", levelId: 29 },
  { word: "認可", meaningsFr: ["Autorisation"], readings: ["にんか"], mnemonicFr: "Obtenir l'AUTORISATION.", levelId: 29 },
  { word: "承認", meaningsFr: ["Approbation"], readings: ["しょうにん"], mnemonicFr: "L'APPROBATION du projet.", levelId: 29 },
  { word: "却下", meaningsFr: ["Rejet"], readings: ["きゃっか"], mnemonicFr: "Le REJET de la demande.", levelId: 29 },
  { word: "取消", meaningsFr: ["Annulation"], readings: ["とりけし"], mnemonicFr: "L'ANNULATION de la commande.", levelId: 29 },
  { word: "撤回", meaningsFr: ["Retrait"], readings: ["てっかい"], mnemonicFr: "Le RETRAIT de la proposition.", levelId: 29 },
  { word: "廃止", meaningsFr: ["Abolition"], readings: ["はいし"], mnemonicFr: "L'ABOLITION de la loi.", levelId: 29 },
  { word: "改正", meaningsFr: ["Révision", "Amendement"], readings: ["かいせい"], mnemonicFr: "La RÉVISION de la loi.", levelId: 29 },
  { word: "施行", meaningsFr: ["Mise en application"], readings: ["しこう"], mnemonicFr: "La MISE EN APPLICATION.", levelId: 29 },
  { word: "適用", meaningsFr: ["Application"], readings: ["てきよう"], mnemonicFr: "L'APPLICATION de la règle.", levelId: 29 },
  { word: "違反", meaningsFr: ["Violation", "Infraction"], readings: ["いはん"], mnemonicFr: "Une VIOLATION du règlement.", levelId: 29 },
  { word: "遵守", meaningsFr: ["Respect", "Observation"], readings: ["じゅんしゅ"], mnemonicFr: "Le RESPECT des règles.", levelId: 29 },
  { word: "服従", meaningsFr: ["Obéissance", "Soumission"], readings: ["ふくじゅう"], mnemonicFr: "L'OBÉISSANCE aux ordres.", levelId: 29 },
  { word: "抵抗", meaningsFr: ["Résistance"], readings: ["ていこう"], mnemonicFr: "La RÉSISTANCE face à.", levelId: 29 },
  { word: "反発", meaningsFr: ["Réaction", "Opposition"], readings: ["はんぱつ"], mnemonicFr: "Une RÉACTION négative.", levelId: 29 },
  { word: "対立", meaningsFr: ["Opposition", "Conflit"], readings: ["たいりつ"], mnemonicFr: "Un CONFLIT d'intérêts.", levelId: 29 },
  { word: "紛争", meaningsFr: ["Conflit", "Dispute"], readings: ["ふんそう"], mnemonicFr: "Un CONFLIT international.", levelId: 29 },
  { word: "和解", meaningsFr: ["Réconciliation"], readings: ["わかい"], mnemonicFr: "La RÉCONCILIATION est possible.", levelId: 29 },
  { word: "妥協", meaningsFr: ["Compromis"], readings: ["だきょう"], mnemonicFr: "Trouver un COMPROMIS.", levelId: 29 },
  { word: "譲歩", meaningsFr: ["Concession"], readings: ["じょうほ"], mnemonicFr: "Faire des CONCESSIONS.", levelId: 29 },
  { word: "合意", meaningsFr: ["Accord mutuel"], readings: ["ごうい"], mnemonicFr: "Parvenir à un ACCORD.", levelId: 29 },
  { word: "調停", meaningsFr: ["Médiation"], readings: ["ちょうてい"], mnemonicFr: "La MÉDIATION du conflit.", levelId: 29 },
  { word: "仲裁", meaningsFr: ["Arbitrage"], readings: ["ちゅうさい"], mnemonicFr: "L'ARBITRAGE du différend.", levelId: 29 },
  { word: "裁判", meaningsFr: ["Procès", "Tribunal"], readings: ["さいばん"], mnemonicFr: "Un PROCÈS équitable.", levelId: 29 },
  { word: "訴訟", meaningsFr: ["Procès", "Litige"], readings: ["そしょう"], mnemonicFr: "Intenter un PROCÈS.", levelId: 29 },
  { word: "起訴", meaningsFr: ["Poursuite judiciaire"], readings: ["きそ"], mnemonicFr: "La POURSUITE en justice.", levelId: 29 },
  { word: "判決", meaningsFr: ["Verdict", "Jugement"], readings: ["はんけつ"], mnemonicFr: "Le VERDICT du tribunal.", levelId: 29 },
  { word: "有罪", meaningsFr: ["Coupable"], readings: ["ゆうざい"], mnemonicFr: "Déclaré COUPABLE.", levelId: 29 },
  { word: "無罪", meaningsFr: ["Innocent"], readings: ["むざい"], mnemonicFr: "Déclaré INNOCENT.", levelId: 29 },
  { word: "刑罰", meaningsFr: ["Peine", "Châtiment"], readings: ["けいばつ"], mnemonicFr: "Une PEINE sévère.", levelId: 29 },

  // Level 30 - JLPT N2 vocabulary (upper intermediate)
  { word: "安全", meaningsFr: ["Sécurité"], readings: ["あんぜん"], mnemonicFr: "La SÉCURITÉ avant tout.", levelId: 30 },
  { word: "危険", meaningsFr: ["Danger"], readings: ["きけん"], mnemonicFr: "Un DANGER potentiel.", levelId: 30 },
  { word: "事故", meaningsFr: ["Accident"], readings: ["じこ"], mnemonicFr: "Un ACCIDENT de la route.", levelId: 30 },
  { word: "犯罪", meaningsFr: ["Crime"], readings: ["はんざい"], mnemonicFr: "Un CRIME grave.", levelId: 30 },
  { word: "暴力", meaningsFr: ["Violence"], readings: ["ぼうりょく"], mnemonicFr: "La VIOLENCE est inacceptable.", levelId: 30 },
  { word: "窃盗", meaningsFr: ["Vol"], readings: ["せっとう"], mnemonicFr: "Un VOL à l'étalage.", levelId: 30 },
  { word: "詐欺", meaningsFr: ["Fraude", "Escroquerie"], readings: ["さぎ"], mnemonicFr: "Une ESCROQUERIE financière.", levelId: 30 },
  { word: "脅迫", meaningsFr: ["Menace", "Chantage"], readings: ["きょうはく"], mnemonicFr: "Une MENACE sérieuse.", levelId: 30 },
  { word: "被疑者", meaningsFr: ["Suspect"], readings: ["ひぎしゃ"], mnemonicFr: "Le SUSPECT principal.", levelId: 30 },
  { word: "逮捕", meaningsFr: ["Arrestation"], readings: ["たいほ"], mnemonicFr: "L'ARRESTATION du criminel.", levelId: 30 },
  { word: "捜査", meaningsFr: ["Enquête", "Investigation"], readings: ["そうさ"], mnemonicFr: "L'ENQUÊTE policière.", levelId: 30 },
  { word: "証言", meaningsFr: ["Témoignage"], readings: ["しょうげん"], mnemonicFr: "Un TÉMOIGNAGE crucial.", levelId: 30 },
  { word: "証人", meaningsFr: ["Témoin"], readings: ["しょうにん"], mnemonicFr: "Un TÉMOIN oculaire.", levelId: 30 },
  { word: "弁護", meaningsFr: ["Défense (juridique)"], readings: ["べんご"], mnemonicFr: "La DÉFENSE de l'accusé.", levelId: 30 },
  { word: "弁護士", meaningsFr: ["Avocat"], readings: ["べんごし"], mnemonicFr: "Consulter un AVOCAT.", levelId: 30 },
  { word: "検察", meaningsFr: ["Ministère public"], readings: ["けんさつ"], mnemonicFr: "Le MINISTÈRE PUBLIC.", levelId: 30 },
  { word: "警察", meaningsFr: ["Police"], readings: ["けいさつ"], mnemonicFr: "Appeler la POLICE.", levelId: 30 },
  { word: "消防", meaningsFr: ["Pompiers"], readings: ["しょうぼう"], mnemonicFr: "Les POMPIERS arrivent.", levelId: 30 },
  { word: "救急", meaningsFr: ["Urgences"], readings: ["きゅうきゅう"], mnemonicFr: "Les URGENCES médicales.", levelId: 30 },
  { word: "防災", meaningsFr: ["Prévention des catastrophes"], readings: ["ぼうさい"], mnemonicFr: "La PRÉVENTION DES CATASTROPHES.", levelId: 30 },
  { word: "防犯", meaningsFr: ["Prévention du crime"], readings: ["ぼうはん"], mnemonicFr: "La PRÉVENTION DU CRIME.", levelId: 30 },
  { word: "警備", meaningsFr: ["Sécurité", "Garde"], readings: ["けいび"], mnemonicFr: "La SÉCURITÉ du bâtiment.", levelId: 30 },
  { word: "監視", meaningsFr: ["Surveillance"], readings: ["かんし"], mnemonicFr: "Sous SURVEILLANCE constante.", levelId: 30 },
  { word: "保安", meaningsFr: ["Sécurité"], readings: ["ほあん"], mnemonicFr: "Le personnel de SÉCURITÉ.", levelId: 30 },
  { word: "治安", meaningsFr: ["Ordre public"], readings: ["ちあん"], mnemonicFr: "L'ORDRE PUBLIC maintenu.", levelId: 30 },
  { word: "秩序", meaningsFr: ["Ordre", "Discipline"], readings: ["ちつじょ"], mnemonicFr: "L'ORDRE social.", levelId: 30 },
  { word: "規律", meaningsFr: ["Discipline"], readings: ["きりつ"], mnemonicFr: "La DISCIPLINE stricte.", levelId: 30 },
  { word: "風紀", meaningsFr: ["Morale publique"], readings: ["ふうき"], mnemonicFr: "La MORALE PUBLIQUE.", levelId: 30 },
  { word: "倫理", meaningsFr: ["Éthique"], readings: ["りんり"], mnemonicFr: "L'ÉTHIQUE professionnelle.", levelId: 30 },
  { word: "道義", meaningsFr: ["Moralité"], readings: ["どうぎ"], mnemonicFr: "La MORALITÉ dans les affaires.", levelId: 30 },
  { word: "人権", meaningsFr: ["Droits de l'homme"], readings: ["じんけん"], mnemonicFr: "Les DROITS DE L'HOMME.", levelId: 30 },
  { word: "市民権", meaningsFr: ["Citoyenneté"], readings: ["しみんけん"], mnemonicFr: "Obtenir la CITOYENNETÉ.", levelId: 30 },
  { word: "参政権", meaningsFr: ["Droit de vote"], readings: ["さんせいけん"], mnemonicFr: "Le DROIT DE VOTE.", levelId: 30 },
  { word: "基本権", meaningsFr: ["Droits fondamentaux"], readings: ["きほんけん"], mnemonicFr: "Les DROITS FONDAMENTAUX.", levelId: 30 },
  { word: "自然権", meaningsFr: ["Droits naturels"], readings: ["しぜんけん"], mnemonicFr: "Les DROITS NATURELS.", levelId: 30 },
  { word: "財産権", meaningsFr: ["Droit de propriété"], readings: ["ざいさんけん"], mnemonicFr: "Le DROIT DE PROPRIÉTÉ.", levelId: 30 },
  { word: "所有権", meaningsFr: ["Propriété"], readings: ["しょゆうけん"], mnemonicFr: "Le droit de PROPRIÉTÉ.", levelId: 30 },
  { word: "著作権", meaningsFr: ["Droit d'auteur"], readings: ["ちょさくけん"], mnemonicFr: "Le DROIT D'AUTEUR.", levelId: 30 },
  { word: "特許", meaningsFr: ["Brevet"], readings: ["とっきょ"], mnemonicFr: "Déposer un BREVET.", levelId: 30 },
  { word: "商標", meaningsFr: ["Marque déposée"], readings: ["しょうひょう"], mnemonicFr: "Une MARQUE DÉPOSÉE.", levelId: 30 },
  { word: "登録", meaningsFr: ["Enregistrement"], readings: ["とうろく"], mnemonicFr: "L'ENREGISTREMENT officiel.", levelId: 30 },
  { word: "認証", meaningsFr: ["Certification"], readings: ["にんしょう"], mnemonicFr: "La CERTIFICATION du produit.", levelId: 30 },
  { word: "検証", meaningsFr: ["Vérification"], readings: ["けんしょう"], mnemonicFr: "La VÉRIFICATION des faits.", levelId: 30 },
  { word: "確証", meaningsFr: ["Confirmation"], readings: ["かくしょう"], mnemonicFr: "La CONFIRMATION définitive.", levelId: 30 },
  { word: "立証", meaningsFr: ["Preuve"], readings: ["りっしょう"], mnemonicFr: "Apporter la PREUVE.", levelId: 30 },
  { word: "論証", meaningsFr: ["Démonstration"], readings: ["ろんしょう"], mnemonicFr: "La DÉMONSTRATION logique.", levelId: 30 },
  { word: "実証", meaningsFr: ["Démonstration pratique"], readings: ["じっしょう"], mnemonicFr: "La DÉMONSTRATION PRATIQUE.", levelId: 30 },
  { word: "反証", meaningsFr: ["Réfutation"], readings: ["はんしょう"], mnemonicFr: "Une RÉFUTATION solide.", levelId: 30 },
  { word: "傍証", meaningsFr: ["Preuve indirecte"], readings: ["ぼうしょう"], mnemonicFr: "Une PREUVE INDIRECTE.", levelId: 30 },
  { word: "状況証拠", meaningsFr: ["Preuve circonstancielle"], readings: ["じょうきょうしょうこ"], mnemonicFr: "Une PREUVE CIRCONSTANCIELLE.", levelId: 30 },
];

async function main() {
  console.log("Seeding vocabulary supplement for levels 26-30...");

  for (const vocab of vocabularyData) {
    await prisma.vocabulary.upsert({
      where: {
        word_levelId: {
          word: vocab.word,
          levelId: vocab.levelId,
        },
      },
      update: {
        meaningsFr: vocab.meaningsFr,
        readings: vocab.readings,
        mnemonicFr: vocab.mnemonicFr,
      },
      create: vocab,
    });
  }

  console.log(`Seeded ${vocabularyData.length} vocabulary words for levels 26-30.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
