import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Vocabulary supplement for levels 46-50
// Adding ~50 words per level to reach target of ~80-100 per level

const vocabularyData = [
  // Level 46 - JLPT N1 vocabulary (advanced)
  { word: "農学", meaningsFr: ["Agronomie"], readings: ["のうがく"], mnemonicFr: "L'AGRONOMIE moderne.", levelId: 46 },
  { word: "畜産", meaningsFr: ["Élevage"], readings: ["ちくさん"], mnemonicFr: "L'ÉLEVAGE intensif.", levelId: 46 },
  { word: "酪農", meaningsFr: ["Industrie laitière"], readings: ["らくのう"], mnemonicFr: "L'INDUSTRIE LAITIÈRE.", levelId: 46 },
  { word: "養殖", meaningsFr: ["Aquaculture"], readings: ["ようしょく"], mnemonicFr: "L'AQUACULTURE.", levelId: 46 },
  { word: "有機農業", meaningsFr: ["Agriculture biologique"], readings: ["ゆうきのうぎょう"], mnemonicFr: "L'AGRICULTURE BIOLOGIQUE.", levelId: 46 },
  { word: "遺伝子組換", meaningsFr: ["OGM"], readings: ["いでんしくみかえ"], mnemonicFr: "Les OGM.", levelId: 46 },
  { word: "品種改良", meaningsFr: ["Amélioration des variétés"], readings: ["ひんしゅかいりょう"], mnemonicFr: "L'AMÉLIORATION DES VARIÉTÉS.", levelId: 46 },
  { word: "収穫", meaningsFr: ["Récolte"], readings: ["しゅうかく"], mnemonicFr: "La RÉCOLTE du riz.", levelId: 46 },
  { word: "耕作", meaningsFr: ["Culture (agricole)"], readings: ["こうさく"], mnemonicFr: "La CULTURE des terres.", levelId: 46 },
  { word: "灌漑", meaningsFr: ["Irrigation"], readings: ["かんがい"], mnemonicFr: "L'IRRIGATION des champs.", levelId: 46 },
  { word: "肥料", meaningsFr: ["Engrais"], readings: ["ひりょう"], mnemonicFr: "L'ENGRAIS naturel.", levelId: 46 },
  { word: "農薬", meaningsFr: ["Pesticide"], readings: ["のうやく"], mnemonicFr: "Les PESTICIDES.", levelId: 46 },
  { word: "除草剤", meaningsFr: ["Herbicide"], readings: ["じょそうざい"], mnemonicFr: "L'HERBICIDE.", levelId: 46 },
  { word: "殺虫剤", meaningsFr: ["Insecticide"], readings: ["さっちゅうざい"], mnemonicFr: "L'INSECTICIDE.", levelId: 46 },
  { word: "食糧", meaningsFr: ["Denrées alimentaires"], readings: ["しょくりょう"], mnemonicFr: "Les DENRÉES ALIMENTAIRES.", levelId: 46 },
  { word: "穀物", meaningsFr: ["Céréales"], readings: ["こくもつ"], mnemonicFr: "Les CÉRÉALES.", levelId: 46 },
  { word: "畑作", meaningsFr: ["Culture sèche"], readings: ["はたさく"], mnemonicFr: "La CULTURE SÈCHE.", levelId: 46 },
  { word: "稲作", meaningsFr: ["Riziculture"], readings: ["いなさく"], mnemonicFr: "La RIZICULTURE.", levelId: 46 },
  { word: "果樹園", meaningsFr: ["Verger"], readings: ["かじゅえん"], mnemonicFr: "Le VERGER.", levelId: 46 },
  { word: "温室", meaningsFr: ["Serre"], readings: ["おんしつ"], mnemonicFr: "La SERRE.", levelId: 46 },
  { word: "植物園", meaningsFr: ["Jardin botanique"], readings: ["しょくぶつえん"], mnemonicFr: "Le JARDIN BOTANIQUE.", levelId: 46 },
  { word: "動物園", meaningsFr: ["Zoo"], readings: ["どうぶつえん"], mnemonicFr: "Le ZOO.", levelId: 46 },
  { word: "水族館", meaningsFr: ["Aquarium"], readings: ["すいぞくかん"], mnemonicFr: "L'AQUARIUM.", levelId: 46 },
  { word: "博物館", meaningsFr: ["Musée"], readings: ["はくぶつかん"], mnemonicFr: "Le MUSÉE.", levelId: 46 },
  { word: "美術館", meaningsFr: ["Musée d'art"], readings: ["びじゅつかん"], mnemonicFr: "Le MUSÉE D'ART.", levelId: 46 },
  { word: "図書館", meaningsFr: ["Bibliothèque"], readings: ["としょかん"], mnemonicFr: "La BIBLIOTHÈQUE.", levelId: 46 },
  { word: "公文書館", meaningsFr: ["Archives"], readings: ["こうぶんしょかん"], mnemonicFr: "Les ARCHIVES.", levelId: 46 },
  { word: "劇場", meaningsFr: ["Théâtre"], readings: ["げきじょう"], mnemonicFr: "Le THÉÂTRE.", levelId: 46 },
  { word: "映画館", meaningsFr: ["Cinéma"], readings: ["えいがかん"], mnemonicFr: "Le CINÉMA.", levelId: 46 },
  { word: "音楽堂", meaningsFr: ["Salle de concert"], readings: ["おんがくどう"], mnemonicFr: "La SALLE DE CONCERT.", levelId: 46 },
  { word: "美術展", meaningsFr: ["Exposition d'art"], readings: ["びじゅつてん"], mnemonicFr: "L'EXPOSITION D'ART.", levelId: 46 },
  { word: "個展", meaningsFr: ["Exposition personnelle"], readings: ["こてん"], mnemonicFr: "L'EXPOSITION PERSONNELLE.", levelId: 46 },
  { word: "回顧展", meaningsFr: ["Rétrospective"], readings: ["かいこてん"], mnemonicFr: "La RÉTROSPECTIVE.", levelId: 46 },
  { word: "常設展", meaningsFr: ["Exposition permanente"], readings: ["じょうせつてん"], mnemonicFr: "L'EXPOSITION PERMANENTE.", levelId: 46 },
  { word: "特別展", meaningsFr: ["Exposition spéciale"], readings: ["とくべつてん"], mnemonicFr: "L'EXPOSITION SPÉCIALE.", levelId: 46 },
  { word: "企画展", meaningsFr: ["Exposition thématique"], readings: ["きかくてん"], mnemonicFr: "L'EXPOSITION THÉMATIQUE.", levelId: 46 },
  { word: "国宝", meaningsFr: ["Trésor national"], readings: ["こくほう"], mnemonicFr: "Le TRÉSOR NATIONAL.", levelId: 46 },
  { word: "重要文化財", meaningsFr: ["Bien culturel important"], readings: ["じゅうようぶんかざい"], mnemonicFr: "Le BIEN CULTUREL IMPORTANT.", levelId: 46 },
  { word: "無形文化財", meaningsFr: ["Patrimoine immatériel"], readings: ["むけいぶんかざい"], mnemonicFr: "Le PATRIMOINE IMMATÉRIEL.", levelId: 46 },
  { word: "人間国宝", meaningsFr: ["Trésor national vivant"], readings: ["にんげんこくほう"], mnemonicFr: "Le TRÉSOR NATIONAL VIVANT.", levelId: 46 },
  { word: "伝統芸能", meaningsFr: ["Arts traditionnels"], readings: ["でんとうげいのう"], mnemonicFr: "Les ARTS TRADITIONNELS.", levelId: 46 },
  { word: "能楽", meaningsFr: ["Théâtre nô"], readings: ["のうがく"], mnemonicFr: "Le THÉÂTRE NÔ.", levelId: 46 },
  { word: "歌舞伎", meaningsFr: ["Kabuki"], readings: ["かぶき"], mnemonicFr: "Le KABUKI.", levelId: 46 },
  { word: "文楽", meaningsFr: ["Bunraku"], readings: ["ぶんらく"], mnemonicFr: "Le BUNRAKU.", levelId: 46 },
  { word: "落語", meaningsFr: ["Rakugo"], readings: ["らくご"], mnemonicFr: "Le RAKUGO.", levelId: 46 },
  { word: "茶道", meaningsFr: ["Cérémonie du thé"], readings: ["さどう"], mnemonicFr: "La CÉRÉMONIE DU THÉ.", levelId: 46 },
  { word: "華道", meaningsFr: ["Art floral"], readings: ["かどう"], mnemonicFr: "L'ART FLORAL.", levelId: 46 },
  { word: "書道", meaningsFr: ["Calligraphie"], readings: ["しょどう"], mnemonicFr: "La CALLIGRAPHIE.", levelId: 46 },
  { word: "武道", meaningsFr: ["Arts martiaux"], readings: ["ぶどう"], mnemonicFr: "Les ARTS MARTIAUX.", levelId: 46 },
  { word: "剣道", meaningsFr: ["Kendo"], readings: ["けんどう"], mnemonicFr: "Le KENDO.", levelId: 46 },

  // Level 47 - JLPT N1 vocabulary (advanced)
  { word: "柔道", meaningsFr: ["Judo"], readings: ["じゅうどう"], mnemonicFr: "Le JUDO.", levelId: 47 },
  { word: "空手", meaningsFr: ["Karaté"], readings: ["からて"], mnemonicFr: "Le KARATÉ.", levelId: 47 },
  { word: "相撲", meaningsFr: ["Sumo"], readings: ["すもう"], mnemonicFr: "Le SUMO.", levelId: 47 },
  { word: "弓道", meaningsFr: ["Tir à l'arc"], readings: ["きゅうどう"], mnemonicFr: "Le TIR À L'ARC.", levelId: 47 },
  { word: "合気道", meaningsFr: ["Aïkido"], readings: ["あいきどう"], mnemonicFr: "L'AÏKIDO.", levelId: 47 },
  { word: "囲碁", meaningsFr: ["Go"], readings: ["いご"], mnemonicFr: "Le GO.", levelId: 47 },
  { word: "将棋", meaningsFr: ["Shogi"], readings: ["しょうぎ"], mnemonicFr: "Le SHOGI.", levelId: 47 },
  { word: "麻雀", meaningsFr: ["Mahjong"], readings: ["マージャン"], mnemonicFr: "Le MAHJONG.", levelId: 47 },
  { word: "俳句", meaningsFr: ["Haïku"], readings: ["はいく"], mnemonicFr: "Le HAÏKU.", levelId: 47 },
  { word: "短歌", meaningsFr: ["Tanka"], readings: ["たんか"], mnemonicFr: "Le TANKA.", levelId: 47 },
  { word: "和歌", meaningsFr: ["Waka"], readings: ["わか"], mnemonicFr: "Le WAKA.", levelId: 47 },
  { word: "漢詩", meaningsFr: ["Poésie chinoise"], readings: ["かんし"], mnemonicFr: "La POÉSIE CHINOISE.", levelId: 47 },
  { word: "浮世絵", meaningsFr: ["Ukiyo-e"], readings: ["うきよえ"], mnemonicFr: "L'UKIYO-E.", levelId: 47 },
  { word: "水墨画", meaningsFr: ["Peinture à l'encre"], readings: ["すいぼくが"], mnemonicFr: "La PEINTURE À L'ENCRE.", levelId: 47 },
  { word: "日本画", meaningsFr: ["Peinture japonaise"], readings: ["にほんが"], mnemonicFr: "La PEINTURE JAPONAISE.", levelId: 47 },
  { word: "洋画", meaningsFr: ["Peinture occidentale"], readings: ["ようが"], mnemonicFr: "La PEINTURE OCCIDENTALE.", levelId: 47 },
  { word: "彫塑", meaningsFr: ["Sculpture"], readings: ["ちょうそ"], mnemonicFr: "La SCULPTURE.", levelId: 47 },
  { word: "版画", meaningsFr: ["Gravure"], readings: ["はんが"], mnemonicFr: "La GRAVURE.", levelId: 47 },
  { word: "工芸", meaningsFr: ["Artisanat"], readings: ["こうげい"], mnemonicFr: "L'ARTISANAT.", levelId: 47 },
  { word: "漆器", meaningsFr: ["Laque"], readings: ["しっき"], mnemonicFr: "La LAQUE.", levelId: 47 },
  { word: "焼物", meaningsFr: ["Céramique"], readings: ["やきもの"], mnemonicFr: "La CÉRAMIQUE.", levelId: 47 },
  { word: "染織", meaningsFr: ["Teinture et tissage"], readings: ["せんしょく"], mnemonicFr: "La TEINTURE ET LE TISSAGE.", levelId: 47 },
  { word: "和服", meaningsFr: ["Vêtement japonais"], readings: ["わふく"], mnemonicFr: "Le VÊTEMENT JAPONAIS.", levelId: 47 },
  { word: "着物", meaningsFr: ["Kimono"], readings: ["きもの"], mnemonicFr: "Le KIMONO.", levelId: 47 },
  { word: "浴衣", meaningsFr: ["Yukata"], readings: ["ゆかた"], mnemonicFr: "Le YUKATA.", levelId: 47 },
  { word: "帯", meaningsFr: ["Ceinture de kimono"], readings: ["おび"], mnemonicFr: "La CEINTURE DE KIMONO.", levelId: 47 },
  { word: "下駄", meaningsFr: ["Geta"], readings: ["げた"], mnemonicFr: "Les GETA.", levelId: 47 },
  { word: "草履", meaningsFr: ["Zori"], readings: ["ぞうり"], mnemonicFr: "Les ZORI.", levelId: 47 },
  { word: "和食", meaningsFr: ["Cuisine japonaise"], readings: ["わしょく"], mnemonicFr: "La CUISINE JAPONAISE.", levelId: 47 },
  { word: "懐石", meaningsFr: ["Kaiseki"], readings: ["かいせき"], mnemonicFr: "Le KAISEKI.", levelId: 47 },
  { word: "精進料理", meaningsFr: ["Cuisine végétarienne bouddhiste"], readings: ["しょうじんりょうり"], mnemonicFr: "La CUISINE VÉGÉTARIENNE BOUDDHISTE.", levelId: 47 },
  { word: "郷土料理", meaningsFr: ["Cuisine régionale"], readings: ["きょうどりょうり"], mnemonicFr: "La CUISINE RÉGIONALE.", levelId: 47 },
  { word: "家庭料理", meaningsFr: ["Cuisine maison"], readings: ["かていりょうり"], mnemonicFr: "La CUISINE MAISON.", levelId: 47 },
  { word: "味噌汁", meaningsFr: ["Soupe miso"], readings: ["みそしる"], mnemonicFr: "La SOUPE MISO.", levelId: 47 },
  { word: "漬物", meaningsFr: ["Légumes marinés"], readings: ["つけもの"], mnemonicFr: "Les LÉGUMES MARINÉS.", levelId: 47 },
  { word: "刺身", meaningsFr: ["Sashimi"], readings: ["さしみ"], mnemonicFr: "Le SASHIMI.", levelId: 47 },
  { word: "寿司", meaningsFr: ["Sushi"], readings: ["すし"], mnemonicFr: "Le SUSHI.", levelId: 47 },
  { word: "天ぷら", meaningsFr: ["Tempura"], readings: ["てんぷら"], mnemonicFr: "Le TEMPURA.", levelId: 47 },
  { word: "焼鳥", meaningsFr: ["Yakitori"], readings: ["やきとり"], mnemonicFr: "Le YAKITORI.", levelId: 47 },
  { word: "鍋物", meaningsFr: ["Plat mijoté"], readings: ["なべもの"], mnemonicFr: "Le PLAT MIJOTÉ.", levelId: 47 },
  { word: "丼物", meaningsFr: ["Bol de riz garni"], readings: ["どんぶりもの"], mnemonicFr: "Le BOL DE RIZ GARNI.", levelId: 47 },
  { word: "麺類", meaningsFr: ["Nouilles"], readings: ["めんるい"], mnemonicFr: "Les NOUILLES.", levelId: 47 },
  { word: "蕎麦", meaningsFr: ["Soba"], readings: ["そば"], mnemonicFr: "Les SOBA.", levelId: 47 },
  { word: "饂飩", meaningsFr: ["Udon"], readings: ["うどん"], mnemonicFr: "Les UDON.", levelId: 47 },
  { word: "拉麺", meaningsFr: ["Ramen"], readings: ["ラーメン"], mnemonicFr: "Les RAMEN.", levelId: 47 },
  { word: "和菓子", meaningsFr: ["Pâtisserie japonaise"], readings: ["わがし"], mnemonicFr: "La PÂTISSERIE JAPONAISE.", levelId: 47 },
  { word: "洋菓子", meaningsFr: ["Pâtisserie occidentale"], readings: ["ようがし"], mnemonicFr: "La PÂTISSERIE OCCIDENTALE.", levelId: 47 },
  { word: "日本酒", meaningsFr: ["Saké"], readings: ["にほんしゅ"], mnemonicFr: "Le SAKÉ.", levelId: 47 },
  { word: "焼酎", meaningsFr: ["Shochu"], readings: ["しょうちゅう"], mnemonicFr: "Le SHOCHU.", levelId: 47 },
  { word: "梅酒", meaningsFr: ["Umeshu"], readings: ["うめしゅ"], mnemonicFr: "L'UMESHU.", levelId: 47 },

  // Level 48 - JLPT N1 vocabulary (advanced)
  { word: "神道", meaningsFr: ["Shintoïsme"], readings: ["しんとう"], mnemonicFr: "Le SHINTOÏSME.", levelId: 48 },
  { word: "仏教", meaningsFr: ["Bouddhisme"], readings: ["ぶっきょう"], mnemonicFr: "Le BOUDDHISME.", levelId: 48 },
  { word: "禅", meaningsFr: ["Zen"], readings: ["ぜん"], mnemonicFr: "Le ZEN.", levelId: 48 },
  { word: "儒教", meaningsFr: ["Confucianisme"], readings: ["じゅきょう"], mnemonicFr: "Le CONFUCIANISME.", levelId: 48 },
  { word: "道教", meaningsFr: ["Taoïsme"], readings: ["どうきょう"], mnemonicFr: "Le TAOÏSME.", levelId: 48 },
  { word: "神社", meaningsFr: ["Sanctuaire shinto"], readings: ["じんじゃ"], mnemonicFr: "Le SANCTUAIRE SHINTO.", levelId: 48 },
  { word: "寺院", meaningsFr: ["Temple bouddhiste"], readings: ["じいん"], mnemonicFr: "Le TEMPLE BOUDDHISTE.", levelId: 48 },
  { word: "参拝", meaningsFr: ["Visite de prière"], readings: ["さんぱい"], mnemonicFr: "La VISITE DE PRIÈRE.", levelId: 48 },
  { word: "御参り", meaningsFr: ["Prière au temple"], readings: ["おまいり"], mnemonicFr: "La PRIÈRE AU TEMPLE.", levelId: 48 },
  { word: "お守り", meaningsFr: ["Amulette"], readings: ["おまもり"], mnemonicFr: "L'AMULETTE.", levelId: 48 },
  { word: "御札", meaningsFr: ["Talisman"], readings: ["おふだ"], mnemonicFr: "Le TALISMAN.", levelId: 48 },
  { word: "御神籤", meaningsFr: ["Oracle"], readings: ["おみくじ"], mnemonicFr: "L'ORACLE.", levelId: 48 },
  { word: "絵馬", meaningsFr: ["Tablette votive"], readings: ["えま"], mnemonicFr: "La TABLETTE VOTIVE.", levelId: 48 },
  { word: "鳥居", meaningsFr: ["Torii"], readings: ["とりい"], mnemonicFr: "Le TORII.", levelId: 48 },
  { word: "狛犬", meaningsFr: ["Lion gardien"], readings: ["こまいぬ"], mnemonicFr: "Le LION GARDIEN.", levelId: 48 },
  { word: "仏像", meaningsFr: ["Statue de Bouddha"], readings: ["ぶつぞう"], mnemonicFr: "La STATUE DE BOUDDHA.", levelId: 48 },
  { word: "地蔵", meaningsFr: ["Jizo"], readings: ["じぞう"], mnemonicFr: "Le JIZO.", levelId: 48 },
  { word: "御盆", meaningsFr: ["Obon"], readings: ["おぼん"], mnemonicFr: "L'OBON.", levelId: 48 },
  { word: "正月", meaningsFr: ["Nouvel An"], readings: ["しょうがつ"], mnemonicFr: "Le NOUVEL AN.", levelId: 48 },
  { word: "節分", meaningsFr: ["Setsubun"], readings: ["せつぶん"], mnemonicFr: "Le SETSUBUN.", levelId: 48 },
  { word: "雛祭り", meaningsFr: ["Fête des poupées"], readings: ["ひなまつり"], mnemonicFr: "La FÊTE DES POUPÉES.", levelId: 48 },
  { word: "端午の節句", meaningsFr: ["Fête des garçons"], readings: ["たんごのせっく"], mnemonicFr: "La FÊTE DES GARÇONS.", levelId: 48 },
  { word: "七夕", meaningsFr: ["Tanabata"], readings: ["たなばた"], mnemonicFr: "Le TANABATA.", levelId: 48 },
  { word: "七五三", meaningsFr: ["Shichi-go-san"], readings: ["しちごさん"], mnemonicFr: "Le SHICHI-GO-SAN.", levelId: 48 },
  { word: "成人式", meaningsFr: ["Cérémonie de majorité"], readings: ["せいじんしき"], mnemonicFr: "La CÉRÉMONIE DE MAJORITÉ.", levelId: 48 },
  { word: "結婚式", meaningsFr: ["Cérémonie de mariage"], readings: ["けっこんしき"], mnemonicFr: "La CÉRÉMONIE DE MARIAGE.", levelId: 48 },
  { word: "葬式", meaningsFr: ["Funérailles"], readings: ["そうしき"], mnemonicFr: "Les FUNÉRAILLES.", levelId: 48 },
  { word: "法事", meaningsFr: ["Service commémoratif"], readings: ["ほうじ"], mnemonicFr: "Le SERVICE COMMÉMORATIF.", levelId: 48 },
  { word: "墓参り", meaningsFr: ["Visite de tombe"], readings: ["はかまいり"], mnemonicFr: "La VISITE DE TOMBE.", levelId: 48 },
  { word: "供養", meaningsFr: ["Offrande aux morts"], readings: ["くよう"], mnemonicFr: "L'OFFRANDE AUX MORTS.", levelId: 48 },
  { word: "祈祷", meaningsFr: ["Prière", "Invocation"], readings: ["きとう"], mnemonicFr: "La PRIÈRE.", levelId: 48 },
  { word: "祝詞", meaningsFr: ["Prière shinto"], readings: ["のりと"], mnemonicFr: "La PRIÈRE SHINTO.", levelId: 48 },
  { word: "読経", meaningsFr: ["Lecture de sutra"], readings: ["どっきょう"], mnemonicFr: "La LECTURE DE SUTRA.", levelId: 48 },
  { word: "座禅", meaningsFr: ["Méditation zen"], readings: ["ざぜん"], mnemonicFr: "La MÉDITATION ZEN.", levelId: 48 },
  { word: "瞑想", meaningsFr: ["Méditation"], readings: ["めいそう"], mnemonicFr: "La MÉDITATION.", levelId: 48 },
  { word: "修行", meaningsFr: ["Pratique ascétique"], readings: ["しゅぎょう"], mnemonicFr: "La PRATIQUE ASCÉTIQUE.", levelId: 48 },
  { word: "悟り", meaningsFr: ["Éveil", "Illumination"], readings: ["さとり"], mnemonicFr: "L'ÉVEIL spirituel.", levelId: 48 },
  { word: "輪廻", meaningsFr: ["Réincarnation"], readings: ["りんね"], mnemonicFr: "La RÉINCARNATION.", levelId: 48 },
  { word: "因果", meaningsFr: ["Karma"], readings: ["いんが"], mnemonicFr: "Le KARMA.", levelId: 48 },
  { word: "極楽", meaningsFr: ["Paradis bouddhiste"], readings: ["ごくらく"], mnemonicFr: "Le PARADIS BOUDDHISTE.", levelId: 48 },
  { word: "地獄", meaningsFr: ["Enfer"], readings: ["じごく"], mnemonicFr: "L'ENFER.", levelId: 48 },
  { word: "菩薩", meaningsFr: ["Bodhisattva"], readings: ["ぼさつ"], mnemonicFr: "Le BODHISATTVA.", levelId: 48 },
  { word: "如来", meaningsFr: ["Bouddha"], readings: ["にょらい"], mnemonicFr: "Le BOUDDHA.", levelId: 48 },
  { word: "観音", meaningsFr: ["Kannon"], readings: ["かんのん"], mnemonicFr: "KANNON.", levelId: 48 },
  { word: "阿弥陀", meaningsFr: ["Amida"], readings: ["あみだ"], mnemonicFr: "AMIDA.", levelId: 48 },
  { word: "不動明王", meaningsFr: ["Fudo Myoo"], readings: ["ふどうみょうおう"], mnemonicFr: "FUDO MYOO.", levelId: 48 },
  { word: "天照大神", meaningsFr: ["Amaterasu"], readings: ["あまてらすおおみかみ"], mnemonicFr: "AMATERASU.", levelId: 48 },
  { word: "八百万の神", meaningsFr: ["Les huit millions de dieux"], readings: ["やおよろずのかみ"], mnemonicFr: "Les HUIT MILLIONS DE DIEUX.", levelId: 48 },
  { word: "氏神", meaningsFr: ["Divinité tutélaire"], readings: ["うじがみ"], mnemonicFr: "La DIVINITÉ TUTÉLAIRE.", levelId: 48 },
  { word: "祖霊", meaningsFr: ["Esprit des ancêtres"], readings: ["それい"], mnemonicFr: "L'ESPRIT DES ANCÊTRES.", levelId: 48 },

  // Level 49 - JLPT N1 vocabulary (advanced)
  { word: "国語", meaningsFr: ["Langue nationale"], readings: ["こくご"], mnemonicFr: "La LANGUE NATIONALE.", levelId: 49 },
  { word: "日本語", meaningsFr: ["Japonais"], readings: ["にほんご"], mnemonicFr: "Le JAPONAIS.", levelId: 49 },
  { word: "標準語", meaningsFr: ["Langue standard"], readings: ["ひょうじゅんご"], mnemonicFr: "La LANGUE STANDARD.", levelId: 49 },
  { word: "方言", meaningsFr: ["Dialecte"], readings: ["ほうげん"], mnemonicFr: "Le DIALECTE.", levelId: 49 },
  { word: "敬語", meaningsFr: ["Langage honorifique"], readings: ["けいご"], mnemonicFr: "Le LANGAGE HONORIFIQUE.", levelId: 49 },
  { word: "丁寧語", meaningsFr: ["Langage poli"], readings: ["ていねいご"], mnemonicFr: "Le LANGAGE POLI.", levelId: 49 },
  { word: "尊敬語", meaningsFr: ["Langage de respect"], readings: ["そんけいご"], mnemonicFr: "Le LANGAGE DE RESPECT.", levelId: 49 },
  { word: "謙譲語", meaningsFr: ["Langage humble"], readings: ["けんじょうご"], mnemonicFr: "Le LANGAGE HUMBLE.", levelId: 49 },
  { word: "口語", meaningsFr: ["Langue parlée"], readings: ["こうご"], mnemonicFr: "La LANGUE PARLÉE.", levelId: 49 },
  { word: "文語", meaningsFr: ["Langue écrite"], readings: ["ぶんご"], mnemonicFr: "La LANGUE ÉCRITE.", levelId: 49 },
  { word: "古語", meaningsFr: ["Langue ancienne"], readings: ["こご"], mnemonicFr: "La LANGUE ANCIENNE.", levelId: 49 },
  { word: "外来語", meaningsFr: ["Mot d'emprunt"], readings: ["がいらいご"], mnemonicFr: "Le MOT D'EMPRUNT.", levelId: 49 },
  { word: "和語", meaningsFr: ["Mot japonais natif"], readings: ["わご"], mnemonicFr: "Le MOT JAPONAIS NATIF.", levelId: 49 },
  { word: "漢語", meaningsFr: ["Mot sino-japonais"], readings: ["かんご"], mnemonicFr: "Le MOT SINO-JAPONAIS.", levelId: 49 },
  { word: "熟語", meaningsFr: ["Mot composé"], readings: ["じゅくご"], mnemonicFr: "Le MOT COMPOSÉ.", levelId: 49 },
  { word: "慣用句", meaningsFr: ["Expression idiomatique"], readings: ["かんようく"], mnemonicFr: "L'EXPRESSION IDIOMATIQUE.", levelId: 49 },
  { word: "諺", meaningsFr: ["Proverbe"], readings: ["ことわざ"], mnemonicFr: "Le PROVERBE.", levelId: 49 },
  { word: "四字熟語", meaningsFr: ["Expression de quatre caractères"], readings: ["よじじゅくご"], mnemonicFr: "L'EXPRESSION DE QUATRE CARACTÈRES.", levelId: 49 },
  { word: "語源", meaningsFr: ["Étymologie"], readings: ["ごげん"], mnemonicFr: "L'ÉTYMOLOGIE.", levelId: 49 },
  { word: "語彙", meaningsFr: ["Vocabulaire"], readings: ["ごい"], mnemonicFr: "Le VOCABULAIRE.", levelId: 49 },
  { word: "文法", meaningsFr: ["Grammaire"], readings: ["ぶんぽう"], mnemonicFr: "La GRAMMAIRE.", levelId: 49 },
  { word: "構文", meaningsFr: ["Syntaxe"], readings: ["こうぶん"], mnemonicFr: "La SYNTAXE.", levelId: 49 },
  { word: "品詞", meaningsFr: ["Partie du discours"], readings: ["ひんし"], mnemonicFr: "La PARTIE DU DISCOURS.", levelId: 49 },
  { word: "名詞", meaningsFr: ["Nom"], readings: ["めいし"], mnemonicFr: "Le NOM.", levelId: 49 },
  { word: "動詞", meaningsFr: ["Verbe"], readings: ["どうし"], mnemonicFr: "Le VERBE.", levelId: 49 },
  { word: "形容詞", meaningsFr: ["Adjectif"], readings: ["けいようし"], mnemonicFr: "L'ADJECTIF.", levelId: 49 },
  { word: "副詞", meaningsFr: ["Adverbe"], readings: ["ふくし"], mnemonicFr: "L'ADVERBE.", levelId: 49 },
  { word: "助詞", meaningsFr: ["Particule"], readings: ["じょし"], mnemonicFr: "La PARTICULE.", levelId: 49 },
  { word: "助動詞", meaningsFr: ["Verbe auxiliaire"], readings: ["じょどうし"], mnemonicFr: "Le VERBE AUXILIAIRE.", levelId: 49 },
  { word: "接続詞", meaningsFr: ["Conjonction"], readings: ["せつぞくし"], mnemonicFr: "La CONJONCTION.", levelId: 49 },
  { word: "感動詞", meaningsFr: ["Interjection"], readings: ["かんどうし"], mnemonicFr: "L'INTERJECTION.", levelId: 49 },
  { word: "代名詞", meaningsFr: ["Pronom"], readings: ["だいめいし"], mnemonicFr: "Le PRONOM.", levelId: 49 },
  { word: "連体詞", meaningsFr: ["Déterminant"], readings: ["れんたいし"], mnemonicFr: "Le DÉTERMINANT.", levelId: 49 },
  { word: "活用", meaningsFr: ["Conjugaison"], readings: ["かつよう"], mnemonicFr: "La CONJUGAISON.", levelId: 49 },
  { word: "時制", meaningsFr: ["Temps (grammatical)"], readings: ["じせい"], mnemonicFr: "Le TEMPS grammatical.", levelId: 49 },
  { word: "態", meaningsFr: ["Voix (grammaticale)"], readings: ["たい"], mnemonicFr: "La VOIX grammaticale.", levelId: 49 },
  { word: "受身", meaningsFr: ["Passif"], readings: ["うけみ"], mnemonicFr: "Le PASSIF.", levelId: 49 },
  { word: "使役", meaningsFr: ["Causatif"], readings: ["しえき"], mnemonicFr: "Le CAUSATIF.", levelId: 49 },
  { word: "可能", meaningsFr: ["Potentiel"], readings: ["かのう"], mnemonicFr: "Le POTENTIEL.", levelId: 49 },
  { word: "意志", meaningsFr: ["Volitionnel"], readings: ["いし"], mnemonicFr: "Le VOLITIONNEL.", levelId: 49 },
  { word: "推量", meaningsFr: ["Conjectural"], readings: ["すいりょう"], mnemonicFr: "Le CONJECTURAL.", levelId: 49 },
  { word: "命令", meaningsFr: ["Impératif"], readings: ["めいれい"], mnemonicFr: "L'IMPÉRATIF.", levelId: 49 },
  { word: "仮定", meaningsFr: ["Conditionnel"], readings: ["かてい"], mnemonicFr: "Le CONDITIONNEL.", levelId: 49 },
  { word: "否定", meaningsFr: ["Négatif"], readings: ["ひてい"], mnemonicFr: "Le NÉGATIF.", levelId: 49 },
  { word: "肯定", meaningsFr: ["Affirmatif"], readings: ["こうてい"], mnemonicFr: "L'AFFIRMATIF.", levelId: 49 },
  { word: "疑問", meaningsFr: ["Interrogatif"], readings: ["ぎもん"], mnemonicFr: "L'INTERROGATIF.", levelId: 49 },
  { word: "感嘆", meaningsFr: ["Exclamatif"], readings: ["かんたん"], mnemonicFr: "L'EXCLAMATIF.", levelId: 49 },
  { word: "音韻", meaningsFr: ["Phonologie"], readings: ["おんいん"], mnemonicFr: "La PHONOLOGIE.", levelId: 49 },
  { word: "発音", meaningsFr: ["Prononciation"], readings: ["はつおん"], mnemonicFr: "La PRONONCIATION.", levelId: 49 },
  { word: "音節", meaningsFr: ["Syllabe"], readings: ["おんせつ"], mnemonicFr: "La SYLLABE.", levelId: 49 },

  // Level 50 - JLPT N1 vocabulary (advanced)
  { word: "拍", meaningsFr: ["Mora"], readings: ["はく"], mnemonicFr: "La MORA.", levelId: 50 },
  { word: "母音", meaningsFr: ["Voyelle"], readings: ["ぼいん"], mnemonicFr: "La VOYELLE.", levelId: 50 },
  { word: "子音", meaningsFr: ["Consonne"], readings: ["しいん"], mnemonicFr: "La CONSONNE.", levelId: 50 },
  { word: "清音", meaningsFr: ["Son non voisé"], readings: ["せいおん"], mnemonicFr: "Le SON NON VOISÉ.", levelId: 50 },
  { word: "濁音", meaningsFr: ["Son voisé"], readings: ["だくおん"], mnemonicFr: "Le SON VOISÉ.", levelId: 50 },
  { word: "半濁音", meaningsFr: ["Son semi-voisé"], readings: ["はんだくおん"], mnemonicFr: "Le SON SEMI-VOISÉ.", levelId: 50 },
  { word: "促音", meaningsFr: ["Consonne géminée"], readings: ["そくおん"], mnemonicFr: "La CONSONNE GÉMINÉE.", levelId: 50 },
  { word: "撥音", meaningsFr: ["Son nasal"], readings: ["はつおん"], mnemonicFr: "Le SON NASAL.", levelId: 50 },
  { word: "長音", meaningsFr: ["Voyelle longue"], readings: ["ちょうおん"], mnemonicFr: "La VOYELLE LONGUE.", levelId: 50 },
  { word: "拗音", meaningsFr: ["Son palatalisé"], readings: ["ようおん"], mnemonicFr: "Le SON PALATALISÉ.", levelId: 50 },
  { word: "平仮名", meaningsFr: ["Hiragana"], readings: ["ひらがな"], mnemonicFr: "Le HIRAGANA.", levelId: 50 },
  { word: "片仮名", meaningsFr: ["Katakana"], readings: ["かたかな"], mnemonicFr: "Le KATAKANA.", levelId: 50 },
  { word: "漢字", meaningsFr: ["Kanji"], readings: ["かんじ"], mnemonicFr: "Le KANJI.", levelId: 50 },
  { word: "常用漢字", meaningsFr: ["Kanji courant"], readings: ["じょうようかんじ"], mnemonicFr: "Le KANJI COURANT.", levelId: 50 },
  { word: "人名用漢字", meaningsFr: ["Kanji pour noms propres"], readings: ["じんめいようかんじ"], mnemonicFr: "Le KANJI POUR NOMS PROPRES.", levelId: 50 },
  { word: "音読み", meaningsFr: ["Lecture on'yomi"], readings: ["おんよみ"], mnemonicFr: "La LECTURE ON'YOMI.", levelId: 50 },
  { word: "訓読み", meaningsFr: ["Lecture kun'yomi"], readings: ["くんよみ"], mnemonicFr: "La LECTURE KUN'YOMI.", levelId: 50 },
  { word: "部首", meaningsFr: ["Radical"], readings: ["ぶしゅ"], mnemonicFr: "Le RADICAL.", levelId: 50 },
  { word: "画数", meaningsFr: ["Nombre de traits"], readings: ["かくすう"], mnemonicFr: "Le NOMBRE DE TRAITS.", levelId: 50 },
  { word: "筆順", meaningsFr: ["Ordre des traits"], readings: ["ひつじゅん"], mnemonicFr: "L'ORDRE DES TRAITS.", levelId: 50 },
  { word: "書体", meaningsFr: ["Style d'écriture"], readings: ["しょたい"], mnemonicFr: "Le STYLE D'ÉCRITURE.", levelId: 50 },
  { word: "楷書", meaningsFr: ["Écriture régulière"], readings: ["かいしょ"], mnemonicFr: "L'ÉCRITURE RÉGULIÈRE.", levelId: 50 },
  { word: "行書", meaningsFr: ["Écriture semi-cursive"], readings: ["ぎょうしょ"], mnemonicFr: "L'ÉCRITURE SEMI-CURSIVE.", levelId: 50 },
  { word: "草書", meaningsFr: ["Écriture cursive"], readings: ["そうしょ"], mnemonicFr: "L'ÉCRITURE CURSIVE.", levelId: 50 },
  { word: "篆書", meaningsFr: ["Écriture sigillaire"], readings: ["てんしょ"], mnemonicFr: "L'ÉCRITURE SIGILLAIRE.", levelId: 50 },
  { word: "隷書", meaningsFr: ["Écriture des scribes"], readings: ["れいしょ"], mnemonicFr: "L'ÉCRITURE DES SCRIBES.", levelId: 50 },
  { word: "縦書き", meaningsFr: ["Écriture verticale"], readings: ["たてがき"], mnemonicFr: "L'ÉCRITURE VERTICALE.", levelId: 50 },
  { word: "横書き", meaningsFr: ["Écriture horizontale"], readings: ["よこがき"], mnemonicFr: "L'ÉCRITURE HORIZONTALE.", levelId: 50 },
  { word: "句読点", meaningsFr: ["Ponctuation"], readings: ["くとうてん"], mnemonicFr: "La PONCTUATION.", levelId: 50 },
  { word: "原稿", meaningsFr: ["Manuscrit"], readings: ["げんこう"], mnemonicFr: "Le MANUSCRIT.", levelId: 50 },
  { word: "草稿", meaningsFr: ["Brouillon"], readings: ["そうこう"], mnemonicFr: "Le BROUILLON.", levelId: 50 },
  { word: "校正", meaningsFr: ["Correction"], readings: ["こうせい"], mnemonicFr: "La CORRECTION.", levelId: 50 },
  { word: "推敲", meaningsFr: ["Peaufinage"], readings: ["すいこう"], mnemonicFr: "Le PEAUFINAGE.", levelId: 50 },
  { word: "添削", meaningsFr: ["Correction et révision"], readings: ["てんさく"], mnemonicFr: "La CORRECTION ET RÉVISION.", levelId: 50 },
  { word: "要約", meaningsFr: ["Résumé"], readings: ["ようやく"], mnemonicFr: "Le RÉSUMÉ.", levelId: 50 },
  { word: "抜粋", meaningsFr: ["Extrait"], readings: ["ばっすい"], mnemonicFr: "L'EXTRAIT.", levelId: 50 },
  { word: "注釈", meaningsFr: ["Annotation"], readings: ["ちゅうしゃく"], mnemonicFr: "L'ANNOTATION.", levelId: 50 },
  { word: "脚注", meaningsFr: ["Note de bas de page"], readings: ["きゃくちゅう"], mnemonicFr: "La NOTE DE BAS DE PAGE.", levelId: 50 },
  { word: "索引", meaningsFr: ["Index"], readings: ["さくいん"], mnemonicFr: "L'INDEX.", levelId: 50 },
  { word: "目次", meaningsFr: ["Table des matières"], readings: ["もくじ"], mnemonicFr: "La TABLE DES MATIÈRES.", levelId: 50 },
  { word: "序文", meaningsFr: ["Préface"], readings: ["じょぶん"], mnemonicFr: "La PRÉFACE.", levelId: 50 },
  { word: "跋文", meaningsFr: ["Postface"], readings: ["ばつぶん"], mnemonicFr: "La POSTFACE.", levelId: 50 },
  { word: "奥付", meaningsFr: ["Colophon"], readings: ["おくづけ"], mnemonicFr: "Le COLOPHON.", levelId: 50 },
  { word: "装丁", meaningsFr: ["Reliure"], readings: ["そうてい"], mnemonicFr: "La RELIURE.", levelId: 50 },
  { word: "製本", meaningsFr: ["Façonnage"], readings: ["せいほん"], mnemonicFr: "Le FAÇONNAGE.", levelId: 50 },
  { word: "活字", meaningsFr: ["Caractère d'imprimerie"], readings: ["かつじ"], mnemonicFr: "Le CARACTÈRE D'IMPRIMERIE.", levelId: 50 },
  { word: "植字", meaningsFr: ["Composition typographique"], readings: ["しょくじ"], mnemonicFr: "La COMPOSITION TYPOGRAPHIQUE.", levelId: 50 },
  { word: "誤植", meaningsFr: ["Coquille"], readings: ["ごしょく"], mnemonicFr: "La COQUILLE.", levelId: 50 },
  { word: "正誤表", meaningsFr: ["Errata"], readings: ["せいごひょう"], mnemonicFr: "L'ERRATA.", levelId: 50 },
  { word: "改訂版", meaningsFr: ["Édition révisée"], readings: ["かいていばん"], mnemonicFr: "L'ÉDITION RÉVISÉE.", levelId: 50 },
];

async function main() {
  console.log("Seeding vocabulary supplement for levels 46-50...");

  for (const vocab of vocabularyData) {
    await prisma.vocabulary.upsert({
      where: {
        word_levelId: {
          word: vocab.word,
          levelId: vocab.levelId,
        },
      },
      update: {
        meaningsFr: vocab.meaningsFr,
        readings: vocab.readings,
        mnemonicFr: vocab.mnemonicFr,
      },
      create: vocab,
    });
  }

  console.log(`Seeded ${vocabularyData.length} vocabulary words for levels 46-50.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
