import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Final kanji batch 8 - Target: exceed 2000 kanji total
// Need ~115 more unique kanji

const kanjiData = [
  // More common verbs
  {
    character: "拭",
    meaningsFr: ["essuyer", "nettoyer"],
    readingsOn: ["ショク", "シキ"],
    readingsKun: ["ぬぐ.う", "ふ.く"],
    meaningMnemonicFr: "La main 扌 avec une cérémonie 式 ESSUIE proprement.",
    readingMnemonicFr: "SHOKU - Le geste d'essuyer.",
    levelId: 49,
  },
  {
    character: "拳",
    meaningsFr: ["poing"],
    readingsOn: ["ケン", "ゲン"],
    readingsKun: ["こぶし"],
    meaningMnemonicFr: "La main 手 jointe 巻 forme un POING.",
    readingMnemonicFr: "KEN - Le poing fermé.",
    levelId: 47,
  },
  {
    character: "拷",
    meaningsFr: ["torturer"],
    readingsOn: ["ゴウ"],
    readingsKun: [],
    meaningMnemonicFr: "La main 扌 qui teste 考 les limites TORTURE.",
    readingMnemonicFr: "GŌ - La torture cruelle.",
    levelId: 53,
  },
  {
    character: "括",
    meaningsFr: ["attacher", "regrouper"],
    readingsOn: ["カツ"],
    readingsKun: ["くく.る"],
    meaningMnemonicFr: "La main 扌 avec la langue 舌 REGROUPE les idées.",
    readingMnemonicFr: "KATSU - Regrouper ensemble.",
    levelId: 46,
  },
  {
    character: "拐",
    meaningsFr: ["kidnapper", "enlever"],
    readingsOn: ["カイ"],
    readingsKun: [],
    meaningMnemonicFr: "La main 扌 qui contourne 刀口 ENLÈVE quelqu'un.",
    readingMnemonicFr: "KAI - L'enlèvement criminel.",
    levelId: 52,
  },
  {
    character: "抄",
    meaningsFr: ["copier", "extraire"],
    readingsOn: ["ショウ"],
    readingsKun: [],
    meaningMnemonicFr: "La main 扌 qui prend peu 少 COPIE l'essentiel.",
    readingMnemonicFr: "SHŌ - Copier les extraits.",
    levelId: 48,
  },
  {
    character: "抉",
    meaningsFr: ["creuser", "extraire"],
    readingsOn: ["ケツ"],
    readingsKun: ["えぐ.る"],
    meaningMnemonicFr: "La main 扌 qui décide 決 CREUSE profondément.",
    readingMnemonicFr: "KETSU - Creuser avec force.",
    levelId: 54,
  },
  {
    character: "披",
    meaningsFr: ["ouvrir", "dévoiler"],
    readingsOn: ["ヒ"],
    readingsKun: [],
    meaningMnemonicFr: "La main 扌 avec la peau 皮 DÉVOILE le secret.",
    readingMnemonicFr: "HI - Dévoiler au grand jour.",
    levelId: 47,
  },
  {
    character: "抹",
    meaningsFr: ["effacer", "frotter"],
    readingsOn: ["マツ"],
    readingsKun: [],
    meaningMnemonicFr: "La main 扌 à la fin 末 EFFACE tout.",
    readingMnemonicFr: "MATSU - Effacer les traces.",
    levelId: 48,
  },
  {
    character: "拘",
    meaningsFr: ["retenir", "arrêter"],
    readingsOn: ["コウ"],
    readingsKun: ["かか.わる"],
    meaningMnemonicFr: "La main 扌 avec une phrase 句 RETIENT l'attention.",
    readingMnemonicFr: "KŌ - Retenir quelqu'un.",
    levelId: 47,
  },
  // Nature and weather
  {
    character: "靄",
    meaningsFr: ["brume", "brouillard"],
    readingsOn: ["アイ"],
    readingsKun: ["もや"],
    meaningMnemonicFr: "La pluie 雨 qui apaise 靉 crée la BRUME.",
    readingMnemonicFr: "AI - La brume légère.",
    levelId: 58,
  },
  {
    character: "虹",
    meaningsFr: ["arc-en-ciel"],
    readingsOn: ["コウ"],
    readingsKun: ["にじ"],
    meaningMnemonicFr: "L'insecte 虫 qui travaille 工 dans le ciel fait l'ARC-EN-CIEL.",
    readingMnemonicFr: "KŌ - L'arc coloré après la pluie.",
    levelId: 41,
  },
  {
    character: "雷",
    meaningsFr: ["tonnerre", "foudre"],
    readingsOn: ["ライ"],
    readingsKun: ["かみなり"],
    meaningMnemonicFr: "La pluie 雨 dans le champ 田 apporte le TONNERRE.",
    readingMnemonicFr: "RAI - Le grondement du tonnerre.",
    levelId: 40,
  },
  {
    character: "嵐",
    meaningsFr: ["tempête", "orage"],
    readingsOn: ["ラン"],
    readingsKun: ["あらし"],
    meaningMnemonicFr: "La montagne 山 avec le vent 風 crée la TEMPÊTE.",
    readingMnemonicFr: "RAN - La tempête de montagne.",
    levelId: 45,
  },
  {
    character: "曇",
    meaningsFr: ["nuageux", "couvert"],
    readingsOn: ["ドン"],
    readingsKun: ["くも.る"],
    meaningMnemonicFr: "Le soleil 日 avec des nuages 雲 rend le ciel NUAGEUX.",
    readingMnemonicFr: "DON - Le temps couvert.",
    levelId: 43,
  },
  // Colors and materials
  {
    character: "紺",
    meaningsFr: ["bleu marine", "indigo"],
    readingsOn: ["コン"],
    readingsKun: [],
    meaningMnemonicFr: "Le fil 糸 très 甘 foncé est BLEU MARINE.",
    readingMnemonicFr: "KON - Le bleu profond.",
    levelId: 46,
  },
  {
    character: "紫",
    meaningsFr: ["violet", "pourpre"],
    readingsOn: ["シ"],
    readingsKun: ["むらさき"],
    meaningMnemonicFr: "Le fil 糸 de cette 此 couleur est VIOLET.",
    readingMnemonicFr: "SHI - La couleur royale.",
    levelId: 44,
  },
  {
    character: "朱",
    meaningsFr: ["vermillon", "rouge"],
    readingsOn: ["シュ"],
    readingsKun: ["あけ"],
    meaningMnemonicFr: "L'arbre 木 avec une marque est VERMILLON.",
    readingMnemonicFr: "SHU - Le rouge des temples.",
    levelId: 43,
  },
  {
    character: "褐",
    meaningsFr: ["brun", "marron"],
    readingsOn: ["カツ"],
    readingsKun: [],
    meaningMnemonicFr: "Le vêtement 衤 qui fait 曷 cette couleur est BRUN.",
    readingMnemonicFr: "KATSU - La couleur terre.",
    levelId: 50,
  },
  {
    character: "灰",
    meaningsFr: ["cendre", "gris"],
    readingsOn: ["カイ"],
    readingsKun: ["はい"],
    meaningMnemonicFr: "Le feu 火 de la falaise 厂 laisse des CENDRES.",
    readingMnemonicFr: "KAI - La cendre grise.",
    levelId: 38,
  },
  // Animals
  {
    character: "鶴",
    meaningsFr: ["grue"],
    readingsOn: ["カク"],
    readingsKun: ["つる"],
    meaningMnemonicFr: "L'oiseau 鳥 qui appelle 隺 est la GRUE.",
    readingMnemonicFr: "KAKU - L'oiseau de longévité.",
    levelId: 48,
  },
  {
    character: "鷹",
    meaningsFr: ["faucon", "épervier"],
    readingsOn: ["ヨウ", "オウ"],
    readingsKun: ["たか"],
    meaningMnemonicFr: "L'oiseau 鳥 qui attaque 廣 est le FAUCON.",
    readingMnemonicFr: "YŌ - Le faucon chasseur.",
    levelId: 52,
  },
  {
    character: "鳩",
    meaningsFr: ["pigeon", "colombe"],
    readingsOn: ["キュウ"],
    readingsKun: ["はと"],
    meaningMnemonicFr: "L'oiseau 鳥 qui rassemble 九 est le PIGEON.",
    readingMnemonicFr: "KYŪ - La colombe de paix.",
    levelId: 49,
  },
  {
    character: "鴨",
    meaningsFr: ["canard"],
    readingsOn: ["オウ"],
    readingsKun: ["かも"],
    meaningMnemonicFr: "L'oiseau 鳥 avec un chapeau 甲 est le CANARD.",
    readingMnemonicFr: "Ō - Le canard qui nage.",
    levelId: 50,
  },
  {
    character: "鬼",
    meaningsFr: ["démon", "ogre"],
    readingsOn: ["キ"],
    readingsKun: ["おに"],
    meaningMnemonicFr: "La créature avec des cornes est un DÉMON.",
    readingMnemonicFr: "KI - Le démon japonais.",
    levelId: 41,
  },
  {
    character: "亀",
    meaningsFr: ["tortue"],
    readingsOn: ["キ"],
    readingsKun: ["かめ"],
    meaningMnemonicFr: "La créature avec sa carapace est la TORTUE.",
    readingMnemonicFr: "KI - La tortue sage.",
    levelId: 46,
  },
  // Abstract concepts
  {
    character: "虚",
    meaningsFr: ["vide", "faux"],
    readingsOn: ["キョ", "コ"],
    readingsKun: ["むな.しい"],
    meaningMnemonicFr: "Le tigre 虍 avec la colline 丘 montre le VIDE.",
    readingMnemonicFr: "KYO - Le vide intérieur.",
    levelId: 46,
  },
  {
    character: "虜",
    meaningsFr: ["captif", "prisonnier"],
    readingsOn: ["リョ", "ロ"],
    readingsKun: ["とりこ"],
    meaningMnemonicFr: "Le tigre 虍 qui force 男 crée un CAPTIF.",
    readingMnemonicFr: "RYO - Le prisonnier de guerre.",
    levelId: 49,
  },
  {
    character: "慮",
    meaningsFr: ["réflexion", "prudence"],
    readingsOn: ["リョ"],
    readingsKun: ["おもんぱか.る"],
    meaningMnemonicFr: "Le tigre 虍 pense 思 avec PRUDENCE.",
    readingMnemonicFr: "RYO - La réflexion profonde.",
    levelId: 47,
  },
  {
    character: "虞",
    meaningsFr: ["crainte", "appréhension"],
    readingsOn: ["グ"],
    readingsKun: ["おそれ"],
    meaningMnemonicFr: "Le tigre 虍 qui prédit 呉 cause la CRAINTE.",
    readingMnemonicFr: "GU - L'appréhension du danger.",
    levelId: 52,
  },
  // Society
  {
    character: "詐",
    meaningsFr: ["fraude", "tromperie"],
    readingsOn: ["サ"],
    readingsKun: ["いつわ.る"],
    meaningMnemonicFr: "Les paroles 言 qui font 乍 des mensonges sont une FRAUDE.",
    readingMnemonicFr: "SA - La tromperie calculée.",
    levelId: 48,
  },
  {
    character: "詔",
    meaningsFr: ["édit impérial", "décret"],
    readingsOn: ["ショウ"],
    readingsKun: ["みことのり"],
    meaningMnemonicFr: "Les paroles 言 qui appellent 召 sont un ÉDIT.",
    readingMnemonicFr: "SHŌ - Le décret de l'empereur.",
    levelId: 51,
  },
  {
    character: "詣",
    meaningsFr: ["visite d'un temple"],
    readingsOn: ["ケイ"],
    readingsKun: ["もう.でる"],
    meaningMnemonicFr: "Les paroles 言 qui vont 旨 au temple forment la VISITE.",
    readingMnemonicFr: "KEI - Le pèlerinage sacré.",
    levelId: 50,
  },
  {
    character: "誇",
    meaningsFr: ["fierté", "vanter"],
    readingsOn: ["コ"],
    readingsKun: ["ほこ.る"],
    meaningMnemonicFr: "Les paroles 言 qui exagèrent 夸 montrent la FIERTÉ.",
    readingMnemonicFr: "KO - La fierté excessive.",
    levelId: 45,
  },
  {
    character: "諭",
    meaningsFr: ["conseiller", "admonester"],
    readingsOn: ["ユ"],
    readingsKun: ["さと.す"],
    meaningMnemonicFr: "Les paroles 言 qui transportent 兪 CONSEILLENT.",
    readingMnemonicFr: "YU - Le conseil sage.",
    levelId: 49,
  },
  {
    character: "諮",
    meaningsFr: ["consulter", "demander conseil"],
    readingsOn: ["シ"],
    readingsKun: ["はか.る"],
    meaningMnemonicFr: "Les paroles 言 qui cherchent 咨 CONSULTENT.",
    readingMnemonicFr: "SHI - La consultation officielle.",
    levelId: 50,
  },
  {
    character: "謀",
    meaningsFr: ["complot", "stratégie"],
    readingsOn: ["ボウ", "ム"],
    readingsKun: ["はか.る"],
    meaningMnemonicFr: "Les paroles 言 de quelqu'un 某 forment un COMPLOT.",
    readingMnemonicFr: "BŌ - La stratégie secrète.",
    levelId: 47,
  },
  {
    character: "謎",
    meaningsFr: ["énigme", "mystère"],
    readingsOn: ["メイ"],
    readingsKun: ["なぞ"],
    meaningMnemonicFr: "Les paroles 言 qui égarent 迷 sont une ÉNIGME.",
    readingMnemonicFr: "MEI - Le mystère à résoudre.",
    levelId: 46,
  },
  {
    character: "謝",
    meaningsFr: ["remercier", "s'excuser"],
    readingsOn: ["シャ"],
    readingsKun: ["あやま.る"],
    meaningMnemonicFr: "Les paroles 言 qui tirent 射 l'arc REMERCIENT.",
    readingMnemonicFr: "SHA - Les excuses sincères.",
    levelId: 42,
  },
  // Buildings
  {
    character: "廊",
    meaningsFr: ["couloir", "corridor"],
    readingsOn: ["ロウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le bâtiment 广 avec l'homme 郎 a un COULOIR.",
    readingMnemonicFr: "RŌ - Le long corridor.",
    levelId: 47,
  },
  {
    character: "廟",
    meaningsFr: ["temple", "mausolée"],
    readingsOn: ["ビョウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le bâtiment 广 du matin 朝 est un TEMPLE.",
    readingMnemonicFr: "BYŌ - Le mausolée sacré.",
    levelId: 53,
  },
  {
    character: "庵",
    meaningsFr: ["ermitage", "hutte"],
    readingsOn: ["アン"],
    readingsKun: ["いおり"],
    meaningMnemonicFr: "Le bâtiment 广 calme 奄 est un ERMITAGE.",
    readingMnemonicFr: "AN - La hutte du moine.",
    levelId: 51,
  },
  {
    character: "庇",
    meaningsFr: ["protéger", "auvent"],
    readingsOn: ["ヒ"],
    readingsKun: ["ひさし", "かば.う"],
    meaningMnemonicFr: "Le bâtiment 广 qui compare 比 forme un AUVENT.",
    readingMnemonicFr: "HI - L'auvent protecteur.",
    levelId: 50,
  },
  {
    character: "庸",
    meaningsFr: ["ordinaire", "médiocre"],
    readingsOn: ["ヨウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le bâtiment 广 avec usage 用 est ORDINAIRE.",
    readingMnemonicFr: "YŌ - Le commun et l'ordinaire.",
    levelId: 48,
  },
  // More unique kanji - body related
  {
    character: "尻",
    meaningsFr: ["fesses", "derrière"],
    readingsOn: ["コウ"],
    readingsKun: ["しり"],
    meaningMnemonicFr: "Le corps 尸 avec neuf 九 parties a des FESSES.",
    readingMnemonicFr: "KŌ - L'arrière du corps.",
    levelId: 44,
  },
  {
    character: "尿",
    meaningsFr: ["urine"],
    readingsOn: ["ニョウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le corps 尸 avec l'eau 水 produit l'URINE.",
    readingMnemonicFr: "NYŌ - Le liquide corporel.",
    levelId: 45,
  },
  {
    character: "屍",
    meaningsFr: ["cadavre", "corps"],
    readingsOn: ["シ"],
    readingsKun: ["しかばね"],
    meaningMnemonicFr: "Le corps 尸 qui meurt 死 devient CADAVRE.",
    readingMnemonicFr: "SHI - Le corps sans vie.",
    levelId: 52,
  },
  // Time and periods
  {
    character: "暁",
    meaningsFr: ["aube", "aurore"],
    readingsOn: ["ギョウ"],
    readingsKun: ["あかつき"],
    meaningMnemonicFr: "Le soleil 日 qui réveille 尭 l'AUBE.",
    readingMnemonicFr: "GYŌ - Le lever du jour.",
    levelId: 47,
  },
  {
    character: "昏",
    meaningsFr: ["crépuscule", "sombre"],
    readingsOn: ["コン"],
    readingsKun: ["くら.い"],
    meaningMnemonicFr: "Le soleil 日 qui épouse 氏 le soir est le CRÉPUSCULE.",
    readingMnemonicFr: "KON - L'heure sombre.",
    levelId: 51,
  },
  {
    character: "晦",
    meaningsFr: ["obscur", "dernier jour du mois"],
    readingsOn: ["カイ"],
    readingsKun: ["つごもり", "くら.い"],
    meaningMnemonicFr: "Le soleil 日 qui regrette 毎 est OBSCUR.",
    readingMnemonicFr: "KAI - La nuit sans lune.",
    levelId: 54,
  },
  {
    character: "旦",
    meaningsFr: ["aube", "matin"],
    readingsOn: ["タン", "ダン"],
    readingsKun: [],
    meaningMnemonicFr: "Le soleil 日 sur la ligne 一 de l'horizon est l'AUBE.",
    readingMnemonicFr: "TAN - Le premier jour.",
    levelId: 43,
  },
  {
    character: "昼",
    meaningsFr: ["midi", "journée"],
    readingsOn: ["チュウ"],
    readingsKun: ["ひる"],
    meaningMnemonicFr: "Le soleil 日 qui mesure 尺 le temps marque MIDI.",
    readingMnemonicFr: "CHŪ - Le milieu du jour.",
    levelId: 35,
  },
  // Food and drink
  {
    character: "酎",
    meaningsFr: ["saké", "alcool"],
    readingsOn: ["チュウ"],
    readingsKun: [],
    meaningMnemonicFr: "L'alcool 酉 de la terre 寸 est le SAKÉ.",
    readingMnemonicFr: "CHŪ - Le saké japonais.",
    levelId: 48,
  },
  {
    character: "酪",
    meaningsFr: ["produits laitiers"],
    readingsOn: ["ラク"],
    readingsKun: [],
    meaningMnemonicFr: "L'alcool 酉 de chaque 各 fermentation fait les PRODUITS LAITIERS.",
    readingMnemonicFr: "RAKU - Le lait fermenté.",
    levelId: 49,
  },
  {
    character: "酬",
    meaningsFr: ["récompense", "rétribution"],
    readingsOn: ["シュウ"],
    readingsKun: ["むく.いる"],
    meaningMnemonicFr: "L'alcool 酉 qu'on verse 州 est une RÉCOMPENSE.",
    readingMnemonicFr: "SHŪ - La rétribution méritée.",
    levelId: 47,
  },
  {
    character: "酵",
    meaningsFr: ["fermentation", "levure"],
    readingsOn: ["コウ"],
    readingsKun: [],
    meaningMnemonicFr: "L'alcool 酉 avec la piété filiale 孝 FERMENTE.",
    readingMnemonicFr: "KŌ - Le processus de fermentation.",
    levelId: 48,
  },
  // More verbs
  {
    character: "据",
    meaningsFr: ["installer", "placer"],
    readingsOn: ["キョ"],
    readingsKun: ["す.える"],
    meaningMnemonicFr: "La main 扌 qui s'assoit 居 INSTALLE.",
    readingMnemonicFr: "KYO - Placer fermement.",
    levelId: 46,
  },
  {
    character: "捗",
    meaningsFr: ["progresser", "avancer"],
    readingsOn: ["チョク", "ホ"],
    readingsKun: ["はかど.る"],
    meaningMnemonicFr: "La main 扌 qui marche 歩 PROGRESSE.",
    readingMnemonicFr: "CHOKU - L'avancement du travail.",
    levelId: 51,
  },
  {
    character: "捜",
    meaningsFr: ["chercher", "fouiller"],
    readingsOn: ["ソウ"],
    readingsKun: ["さが.す"],
    meaningMnemonicFr: "La main 扌 qui retire 叟 CHERCHE partout.",
    readingMnemonicFr: "SŌ - La recherche intense.",
    levelId: 44,
  },
  {
    character: "挫",
    meaningsFr: ["frustrer", "échouer"],
    readingsOn: ["ザ"],
    readingsKun: ["くじ.く"],
    meaningMnemonicFr: "La main 扌 qui s'assoit 坐 est FRUSTRÉE.",
    readingMnemonicFr: "ZA - L'échec douloureux.",
    levelId: 48,
  },
  {
    character: "振",
    meaningsFr: ["agiter", "secouer"],
    readingsOn: ["シン"],
    readingsKun: ["ふ.る", "ふ.るう"],
    meaningMnemonicFr: "La main 扌 qui se lève 辰 AGITE.",
    readingMnemonicFr: "SHIN - Le mouvement de secousse.",
    levelId: 40,
  },
  {
    character: "捧",
    meaningsFr: ["offrir", "présenter"],
    readingsOn: ["ホウ"],
    readingsKun: ["ささ.げる"],
    meaningMnemonicFr: "La main 扌 qui réunit 奉 OFFRE avec respect.",
    readingMnemonicFr: "HŌ - L'offrande respectueuse.",
    levelId: 49,
  },
  {
    character: "描",
    meaningsFr: ["dessiner", "décrire"],
    readingsOn: ["ビョウ"],
    readingsKun: ["えが.く", "か.く"],
    meaningMnemonicFr: "La main 扌 qui attrape 苗 DESSINE.",
    readingMnemonicFr: "BYŌ - Dessiner une image.",
    levelId: 43,
  },
  // Emotions
  {
    character: "怠",
    meaningsFr: ["paresse", "négliger"],
    readingsOn: ["タイ"],
    readingsKun: ["おこた.る", "なま.ける"],
    meaningMnemonicFr: "Le cœur 心 de la plateforme 台 est PARESSEUX.",
    readingMnemonicFr: "TAI - La négligence coupable.",
    levelId: 44,
  },
  {
    character: "怪",
    meaningsFr: ["étrange", "mystérieux"],
    readingsOn: ["カイ", "ケ"],
    readingsKun: ["あや.しい"],
    meaningMnemonicFr: "Le cœur 忄 de la terre 圣 est ÉTRANGE.",
    readingMnemonicFr: "KAI - Le mystère inquiétant.",
    levelId: 42,
  },
  {
    character: "恨",
    meaningsFr: ["rancune", "ressentiment"],
    readingsOn: ["コン"],
    readingsKun: ["うら.む"],
    meaningMnemonicFr: "Le cœur 忄 qui s'oppose 艮 garde de la RANCUNE.",
    readingMnemonicFr: "KON - Le ressentiment persistant.",
    levelId: 45,
  },
  {
    character: "恭",
    meaningsFr: ["respect", "révérence"],
    readingsOn: ["キョウ"],
    readingsKun: ["うやうや.しい"],
    meaningMnemonicFr: "Le cœur 心 avec 共 le communautaire montre le RESPECT.",
    readingMnemonicFr: "KYŌ - La révérence sincère.",
    levelId: 47,
  },
  {
    character: "悦",
    meaningsFr: ["joie", "plaisir"],
    readingsOn: ["エツ"],
    readingsKun: ["よろこ.ぶ"],
    meaningMnemonicFr: "Le cœur 忄 qui parle 兌 exprime la JOIE.",
    readingMnemonicFr: "ETSU - Le plaisir profond.",
    levelId: 46,
  },
  {
    character: "悼",
    meaningsFr: ["pleurer", "se lamenter"],
    readingsOn: ["トウ"],
    readingsKun: ["いた.む"],
    meaningMnemonicFr: "Le cœur 忄 qui s'élève 卓 PLEURE les morts.",
    readingMnemonicFr: "TŌ - Le deuil sincère.",
    levelId: 48,
  },
  // Tools and objects
  {
    character: "杖",
    meaningsFr: ["canne", "bâton"],
    readingsOn: ["ジョウ"],
    readingsKun: ["つえ"],
    meaningMnemonicFr: "L'arbre 木 pour le grand 丈 est une CANNE.",
    readingMnemonicFr: "JŌ - La canne de marche.",
    levelId: 45,
  },
  {
    character: "槍",
    meaningsFr: ["lance", "javelot"],
    readingsOn: ["ソウ"],
    readingsKun: ["やり"],
    meaningMnemonicFr: "L'arbre 木 qui stocke 倉 est une LANCE.",
    readingMnemonicFr: "SŌ - La lance du guerrier.",
    levelId: 49,
  },
  {
    character: "槌",
    meaningsFr: ["marteau", "maillet"],
    readingsOn: ["ツイ"],
    readingsKun: ["つち"],
    meaningMnemonicFr: "L'arbre 木 qui suit 追 la forme est un MARTEAU.",
    readingMnemonicFr: "TSUI - Le marteau en bois.",
    levelId: 50,
  },
  {
    character: "枕",
    meaningsFr: ["oreiller"],
    readingsOn: ["チン"],
    readingsKun: ["まくら"],
    meaningMnemonicFr: "L'arbre 木 pour se coucher 冘 est un OREILLER.",
    readingMnemonicFr: "CHIN - L'oreiller pour dormir.",
    levelId: 47,
  },
  {
    character: "棺",
    meaningsFr: ["cercueil"],
    readingsOn: ["カン"],
    readingsKun: [],
    meaningMnemonicFr: "L'arbre 木 officiel 官 est un CERCUEIL.",
    readingMnemonicFr: "KAN - Le cercueil en bois.",
    levelId: 49,
  },
  {
    character: "椅",
    meaningsFr: ["chaise"],
    readingsOn: ["イ"],
    readingsKun: [],
    meaningMnemonicFr: "L'arbre 木 étrange 奇 forme une CHAISE.",
    readingMnemonicFr: "I - La chaise en bois.",
    levelId: 45,
  },
  // Nature
  {
    character: "芽",
    meaningsFr: ["bourgeon", "germe"],
    readingsOn: ["ガ"],
    readingsKun: ["め"],
    meaningMnemonicFr: "L'herbe 艹 qui montre ses dents 牙 est un BOURGEON.",
    readingMnemonicFr: "GA - Le germe qui pousse.",
    levelId: 41,
  },
  {
    character: "茎",
    meaningsFr: ["tige"],
    readingsOn: ["ケイ"],
    readingsKun: ["くき"],
    meaningMnemonicFr: "L'herbe 艹 qui passe 経 forme une TIGE.",
    readingMnemonicFr: "KEI - La tige de la plante.",
    levelId: 46,
  },
  {
    character: "茂",
    meaningsFr: ["luxuriant", "touffu"],
    readingsOn: ["モ"],
    readingsKun: ["しげ.る"],
    meaningMnemonicFr: "L'herbe 艹 qui mûrit 戊 est LUXURIANTE.",
    readingMnemonicFr: "MO - La végétation dense.",
    levelId: 45,
  },
  {
    character: "荘",
    meaningsFr: ["villa", "majestueux"],
    readingsOn: ["ソウ"],
    readingsKun: [],
    meaningMnemonicFr: "L'herbe 艹 près du lit 壮 forme une VILLA.",
    readingMnemonicFr: "SŌ - La résidence majestueuse.",
    levelId: 47,
  },
  {
    character: "菌",
    meaningsFr: ["bactérie", "champignon"],
    readingsOn: ["キン"],
    readingsKun: [],
    meaningMnemonicFr: "L'herbe 艹 avec un enfant 囷 est une BACTÉRIE.",
    readingMnemonicFr: "KIN - Les micro-organismes.",
    levelId: 44,
  },
  {
    character: "菊",
    meaningsFr: ["chrysanthème"],
    readingsOn: ["キク"],
    readingsKun: [],
    meaningMnemonicFr: "L'herbe 艹 du riz 米 dans les mains 勹 est le CHRYSANTHÈME.",
    readingMnemonicFr: "KIKU - La fleur impériale.",
    levelId: 46,
  },
  {
    character: "蓄",
    meaningsFr: ["accumuler", "stocker"],
    readingsOn: ["チク"],
    readingsKun: ["たくわ.える"],
    meaningMnemonicFr: "L'herbe 艹 avec la vache 畜 ACCUMULE.",
    readingMnemonicFr: "CHIKU - L'accumulation des réserves.",
    levelId: 47,
  },
  // Actions and states
  {
    character: "墜",
    meaningsFr: ["tomber", "s'écraser"],
    readingsOn: ["ツイ"],
    readingsKun: ["お.ちる"],
    meaningMnemonicFr: "La terre 土 qui se remplit 隊 TOMBE.",
    readingMnemonicFr: "TSUI - La chute brutale.",
    levelId: 48,
  },
  {
    character: "堕",
    meaningsFr: ["tomber", "déchoir"],
    readingsOn: ["ダ"],
    readingsKun: ["お.ちる"],
    meaningMnemonicFr: "La terre 土 avec la gauche 左 DÉCHOIT.",
    readingMnemonicFr: "DA - La déchéance morale.",
    levelId: 49,
  },
  {
    character: "奔",
    meaningsFr: ["courir", "fuir"],
    readingsOn: ["ホン"],
    readingsKun: ["はし.る"],
    meaningMnemonicFr: "Le grand 大 qui dérive 卉 COURT.",
    readingMnemonicFr: "HON - La course effrénée.",
    levelId: 48,
  },
  {
    character: "奪",
    meaningsFr: ["voler", "ravir"],
    readingsOn: ["ダツ"],
    readingsKun: ["うば.う"],
    meaningMnemonicFr: "Le grand 大 oiseau 隹 avec des mains 寸 VOLE.",
    readingMnemonicFr: "DATSU - L'action de ravir.",
    levelId: 46,
  },
  {
    character: "奮",
    meaningsFr: ["s'efforcer", "stimuler"],
    readingsOn: ["フン"],
    readingsKun: ["ふる.う"],
    meaningMnemonicFr: "Le grand 大 oiseau 隹 dans le champ 田 S'EFFORCE.",
    readingMnemonicFr: "FUN - L'effort intense.",
    levelId: 45,
  },
  // Final unique kanji
  {
    character: "乏",
    meaningsFr: ["manque", "pénurie"],
    readingsOn: ["ボウ"],
    readingsKun: ["とぼ.しい"],
    meaningMnemonicFr: "Le signe qui penche vers le bas indique le MANQUE.",
    readingMnemonicFr: "BŌ - La pénurie ressentie.",
    levelId: 43,
  },
  {
    character: "傲",
    meaningsFr: ["arrogant", "orgueilleux"],
    readingsOn: ["ゴウ"],
    readingsKun: ["おご.る"],
    meaningMnemonicFr: "La personne 亻 qui joue 敖 est ARROGANTE.",
    readingMnemonicFr: "GŌ - L'arrogance excessive.",
    levelId: 50,
  },
  {
    character: "僅",
    meaningsFr: ["seulement", "à peine"],
    readingsOn: ["キン"],
    readingsKun: ["わず.か"],
    meaningMnemonicFr: "La personne 亻 avec peu 堇 n'a que SEULEMENT.",
    readingMnemonicFr: "KIN - La quantité minime.",
    levelId: 48,
  },
  {
    character: "僻",
    meaningsFr: ["éloigné", "isolé"],
    readingsOn: ["ヘキ"],
    readingsKun: ["ひが.む"],
    meaningMnemonicFr: "La personne 亻 du roi 辟 vit ISOLÉE.",
    readingMnemonicFr: "HEKI - L'endroit reculé.",
    levelId: 51,
  },
  {
    character: "儀",
    meaningsFr: ["cérémonie", "rituel"],
    readingsOn: ["ギ"],
    readingsKun: [],
    meaningMnemonicFr: "La personne 亻 avec justice 義 suit la CÉRÉMONIE.",
    readingMnemonicFr: "GI - Le rituel solennel.",
    levelId: 44,
  },
  {
    character: "償",
    meaningsFr: ["compenser", "rembourser"],
    readingsOn: ["ショウ"],
    readingsKun: ["つぐな.う"],
    meaningMnemonicFr: "La personne 亻 qui récompense 賞 COMPENSE.",
    readingMnemonicFr: "SHŌ - Le remboursement dû.",
    levelId: 46,
  },
  {
    character: "凝",
    meaningsFr: ["figer", "concentrer"],
    readingsOn: ["ギョウ"],
    readingsKun: ["こ.る", "こ.らす"],
    meaningMnemonicFr: "La glace 冫 qui doute 疑 SE FIGE.",
    readingMnemonicFr: "GYŌ - La concentration intense.",
    levelId: 47,
  },
  {
    character: "刹",
    meaningsFr: ["instant", "temple"],
    readingsOn: ["サツ", "セツ"],
    readingsKun: [],
    meaningMnemonicFr: "Le couteau 刂 qui coupe l'arbre 朮 représente l'INSTANT.",
    readingMnemonicFr: "SATSU - L'instant fugace.",
    levelId: 52,
  },
  {
    character: "勘",
    meaningsFr: ["intuition", "pressentiment"],
    readingsOn: ["カン"],
    readingsKun: [],
    meaningMnemonicFr: "La force 力 avec le vide 甚 donne l'INTUITION.",
    readingMnemonicFr: "KAN - Le sixième sens.",
    levelId: 45,
  },
  {
    character: "勲",
    meaningsFr: ["mérite", "exploit"],
    readingsOn: ["クン"],
    readingsKun: ["いさお"],
    meaningMnemonicFr: "La force 力 qui brûle 熏 obtient le MÉRITE.",
    readingMnemonicFr: "KUN - L'exploit reconnu.",
    levelId: 48,
  },
  {
    character: "匠",
    meaningsFr: ["artisan", "maître"],
    readingsOn: ["ショウ"],
    readingsKun: ["たくみ"],
    meaningMnemonicFr: "La boîte 匚 avec la hache 斤 représente l'ARTISAN.",
    readingMnemonicFr: "SHŌ - Le maître artisan.",
    levelId: 44,
  },
  {
    character: "匿",
    meaningsFr: ["cacher", "dissimuler"],
    readingsOn: ["トク"],
    readingsKun: ["かくま.う"],
    meaningMnemonicFr: "La boîte 匚 avec le jeune 若 SE CACHE.",
    readingMnemonicFr: "TOKU - La dissimulation.",
    levelId: 49,
  },
  {
    character: "卑",
    meaningsFr: ["humble", "bas"],
    readingsOn: ["ヒ"],
    readingsKun: ["いや.しい"],
    meaningMnemonicFr: "Le signe en bas avec le champ 田 est HUMBLE.",
    readingMnemonicFr: "HI - La position basse.",
    levelId: 45,
  },
  {
    character: "卓",
    meaningsFr: ["table", "éminent"],
    readingsOn: ["タク"],
    readingsKun: [],
    meaningMnemonicFr: "Le signe en haut avec tôt 早 est ÉMINENT comme une TABLE.",
    readingMnemonicFr: "TAKU - L'excellence remarquable.",
    levelId: 44,
  },
  {
    character: "厄",
    meaningsFr: ["malheur", "calamité"],
    readingsOn: ["ヤク"],
    readingsKun: [],
    meaningMnemonicFr: "La falaise 厂 qui piège 卩 apporte le MALHEUR.",
    readingMnemonicFr: "YAKU - La malchance persistante.",
    levelId: 46,
  },
  {
    character: "双",
    meaningsFr: ["paire", "double"],
    readingsOn: ["ソウ"],
    readingsKun: ["ふた", "ならぶ"],
    meaningMnemonicFr: "Deux mains 又 forment une PAIRE.",
    readingMnemonicFr: "SŌ - Le double identique.",
    levelId: 38,
  },
  {
    character: "叔",
    meaningsFr: ["oncle", "plus jeune"],
    readingsOn: ["シュク"],
    readingsKun: [],
    meaningMnemonicFr: "Le petit 小 qui prend 又 des haricots 尗 est l'ONCLE.",
    readingMnemonicFr: "SHUKU - L'oncle plus jeune.",
    levelId: 47,
  },
  {
    character: "叙",
    meaningsFr: ["raconter", "narrer"],
    readingsOn: ["ジョ"],
    readingsKun: ["つい.でる"],
    meaningMnemonicFr: "Le reste 余 avec la main 又 RACONTE.",
    readingMnemonicFr: "JO - La narration des faits.",
    levelId: 48,
  },
  {
    character: "吟",
    meaningsFr: ["réciter", "chanter"],
    readingsOn: ["ギン"],
    readingsKun: [],
    meaningMnemonicFr: "La bouche 口 qui est maintenant 今 RÉCITE.",
    readingMnemonicFr: "GIN - La récitation poétique.",
    levelId: 46,
  },
  {
    character: "呈",
    meaningsFr: ["présenter", "offrir"],
    readingsOn: ["テイ"],
    readingsKun: [],
    meaningMnemonicFr: "La bouche 口 qui offre un roi 王 PRÉSENTE.",
    readingMnemonicFr: "TEI - L'offrande formelle.",
    levelId: 47,
  },
  {
    character: "呪",
    meaningsFr: ["malédiction", "sort"],
    readingsOn: ["ジュ"],
    readingsKun: ["のろ.う"],
    meaningMnemonicFr: "La bouche 口 du frère 兄 jette une MALÉDICTION.",
    readingMnemonicFr: "JU - Le sort maléfique.",
    levelId: 48,
  },
];

async function main() {
  console.log("Seeding final kanji batch 8 to exceed 2000...");

  for (const kanji of kanjiData) {
    await prisma.kanji.upsert({
      where: { character: kanji.character },
      update: {
        meaningsFr: kanji.meaningsFr,
        readingsOn: kanji.readingsOn,
        readingsKun: kanji.readingsKun,
        meaningMnemonicFr: kanji.meaningMnemonicFr,
        readingMnemonicFr: kanji.readingMnemonicFr,
        levelId: kanji.levelId,
      },
      create: kanji,
    });
  }

  console.log(`Seeded ${kanjiData.length} kanji.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
