import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ABSOLUTE FINAL batch - targeting 40 unique kanji to exceed 2000

const kanjiData = [
  {
    character: "護",
    meaningsFr: ["protéger", "défendre"],
    readingsOn: ["ゴ"],
    readingsKun: ["まも.る"],
    meaningMnemonicFr: "Les paroles 言 avec l'oiseau 蒦 PROTÈGENT.",
    readingMnemonicFr: "GO - La protection assurée.",
    levelId: 45,
  },
  {
    character: "豊",
    meaningsFr: ["abondant", "riche"],
    readingsOn: ["ホウ"],
    readingsKun: ["ゆた.か"],
    meaningMnemonicFr: "Le tambour 豆 avec les grains 丰 est ABONDANT.",
    readingMnemonicFr: "HŌ - L'abondance naturelle.",
    levelId: 44,
  },
  {
    character: "貢",
    meaningsFr: ["tribut", "contribuer"],
    readingsOn: ["コウ", "ク"],
    readingsKun: ["みつ.ぐ"],
    meaningMnemonicFr: "Le travail 工 avec la richesse 貝 est un TRIBUT.",
    readingMnemonicFr: "KŌ - La contribution versée.",
    levelId: 46,
  },
  {
    character: "貞",
    meaningsFr: ["chasteté", "fidélité"],
    readingsOn: ["テイ"],
    readingsKun: [],
    meaningMnemonicFr: "La divination 卜 avec la richesse 貝 montre la CHASTETÉ.",
    readingMnemonicFr: "TEI - La fidélité absolue.",
    levelId: 48,
  },
  {
    character: "貧",
    meaningsFr: ["pauvre", "indigent"],
    readingsOn: ["ヒン", "ビン"],
    readingsKun: ["まず.しい"],
    meaningMnemonicFr: "La division 分 de la richesse 貝 rend PAUVRE.",
    readingMnemonicFr: "HIN - La pauvreté subie.",
    levelId: 43,
  },
  {
    character: "貨",
    meaningsFr: ["marchandise", "monnaie"],
    readingsOn: ["カ"],
    readingsKun: [],
    meaningMnemonicFr: "Le changement 化 de la richesse 貝 forme la MARCHANDISE.",
    readingMnemonicFr: "KA - La monnaie d'échange.",
    levelId: 44,
  },
  {
    character: "販",
    meaningsFr: ["vendre", "commerce"],
    readingsOn: ["ハン"],
    readingsKun: [],
    meaningMnemonicFr: "La richesse 貝 avec la contre-attaque 反 sert à VENDRE.",
    readingMnemonicFr: "HAN - La vente commerciale.",
    levelId: 45,
  },
  {
    character: "貯",
    meaningsFr: ["épargner", "économiser"],
    readingsOn: ["チョ"],
    readingsKun: ["た.める"],
    meaningMnemonicFr: "La richesse 貝 qui reste 宁 ÉPARGNE.",
    readingMnemonicFr: "CHO - L'épargne accumulée.",
    levelId: 44,
  },
  {
    character: "貸",
    meaningsFr: ["prêter", "louer"],
    readingsOn: ["タイ"],
    readingsKun: ["か.す"],
    meaningMnemonicFr: "La richesse 貝 qui remplace 代 sert à PRÊTER.",
    readingMnemonicFr: "TAI - Le prêt accordé.",
    levelId: 43,
  },
  {
    character: "費",
    meaningsFr: ["dépense", "frais"],
    readingsOn: ["ヒ"],
    readingsKun: ["つい.やす"],
    meaningMnemonicFr: "L'opposition 弗 avec la richesse 貝 forme la DÉPENSE.",
    readingMnemonicFr: "HI - Les frais engagés.",
    levelId: 42,
  },
  {
    character: "資",
    meaningsFr: ["ressource", "capital"],
    readingsOn: ["シ"],
    readingsKun: [],
    meaningMnemonicFr: "La prochaine 次 richesse 貝 est une RESSOURCE.",
    readingMnemonicFr: "SHI - Le capital investi.",
    levelId: 43,
  },
  {
    character: "賀",
    meaningsFr: ["félicitations"],
    readingsOn: ["ガ"],
    readingsKun: [],
    meaningMnemonicFr: "L'addition 加 de la richesse 貝 mérite FÉLICITATIONS.",
    readingMnemonicFr: "GA - Les félicitations offertes.",
    levelId: 45,
  },
  {
    character: "賃",
    meaningsFr: ["loyer", "salaire"],
    readingsOn: ["チン"],
    readingsKun: [],
    meaningMnemonicFr: "La responsabilité 任 de la richesse 貝 est le LOYER.",
    readingMnemonicFr: "CHIN - Le salaire versé.",
    levelId: 44,
  },
  {
    character: "賛",
    meaningsFr: ["approuver", "louer"],
    readingsOn: ["サン"],
    readingsKun: [],
    meaningMnemonicFr: "Les deux 夫 avec la richesse 貝 APPROUVENT.",
    readingMnemonicFr: "SAN - L'approbation donnée.",
    levelId: 45,
  },
  {
    character: "購",
    meaningsFr: ["acheter"],
    readingsOn: ["コウ"],
    readingsKun: [],
    meaningMnemonicFr: "La structure 冓 avec la richesse 貝 sert à ACHETER.",
    readingMnemonicFr: "KŌ - L'achat effectué.",
    levelId: 46,
  },
  {
    character: "贈",
    meaningsFr: ["offrir", "cadeau"],
    readingsOn: ["ゾウ", "ソウ"],
    readingsKun: ["おく.る"],
    meaningMnemonicFr: "L'augmentation 曾 de richesse 貝 sert à OFFRIR.",
    readingMnemonicFr: "ZŌ - Le cadeau offert.",
    levelId: 47,
  },
  {
    character: "越",
    meaningsFr: ["dépasser", "traverser"],
    readingsOn: ["エツ"],
    readingsKun: ["こ.える", "こ.す"],
    meaningMnemonicFr: "Marcher 走 pour dépasser 戉 TRAVERSE.",
    readingMnemonicFr: "ETSU - Le dépassement réussi.",
    levelId: 44,
  },
  {
    character: "趣",
    meaningsFr: ["goût", "intérêt"],
    readingsOn: ["シュ"],
    readingsKun: ["おもむき"],
    meaningMnemonicFr: "Marcher 走 vers le plaisir 取 montre le GOÛT.",
    readingMnemonicFr: "SHU - L'intérêt personnel.",
    levelId: 46,
  },
  {
    character: "距",
    meaningsFr: ["distance"],
    readingsOn: ["キョ"],
    readingsKun: [],
    meaningMnemonicFr: "Le pied 足 avec le grand 巨 mesure la DISTANCE.",
    readingMnemonicFr: "KYO - La distance mesurée.",
    levelId: 45,
  },
  {
    character: "跡",
    meaningsFr: ["trace", "vestige"],
    readingsOn: ["セキ"],
    readingsKun: ["あと"],
    meaningMnemonicFr: "Le pied 足 avec le passé 亦 laisse une TRACE.",
    readingMnemonicFr: "SEKI - La trace laissée.",
    levelId: 44,
  },
  {
    character: "践",
    meaningsFr: ["pratiquer", "marcher"],
    readingsOn: ["セン"],
    readingsKun: ["ふ.む"],
    meaningMnemonicFr: "Le pied 足 avec les deux 戔 PRATIQUE.",
    readingMnemonicFr: "SEN - La pratique active.",
    levelId: 48,
  },
  {
    character: "踏",
    meaningsFr: ["marcher sur", "piétiner"],
    readingsOn: ["トウ"],
    readingsKun: ["ふ.む"],
    meaningMnemonicFr: "Le pied 足 avec l'eau 沓 PIÉTINE.",
    readingMnemonicFr: "TŌ - Le pas qui foule.",
    levelId: 45,
  },
  {
    character: "踊",
    meaningsFr: ["danser"],
    readingsOn: ["ヨウ"],
    readingsKun: ["おど.る"],
    meaningMnemonicFr: "Le pied 足 qui utilise 甬 DANSE.",
    readingMnemonicFr: "YŌ - La danse joyeuse.",
    levelId: 46,
  },
  {
    character: "躍",
    meaningsFr: ["sauter", "bondir"],
    readingsOn: ["ヤク"],
    readingsKun: ["おど.る"],
    meaningMnemonicFr: "Le pied 足 avec le saut 翟 BONDIT.",
    readingMnemonicFr: "YAKU - Le bond énergique.",
    levelId: 47,
  },
  {
    character: "輝",
    meaningsFr: ["briller", "éclat"],
    readingsOn: ["キ"],
    readingsKun: ["かがや.く"],
    meaningMnemonicFr: "La lumière 光 avec le véhicule 軍 BRILLE.",
    readingMnemonicFr: "KI - L'éclat brillant.",
    levelId: 45,
  },
  {
    character: "輩",
    meaningsFr: ["collègue", "génération"],
    readingsOn: ["ハイ"],
    readingsKun: ["やから"],
    meaningMnemonicFr: "Ce qui n'est pas 非 un véhicule 車 est un COLLÈGUE.",
    readingMnemonicFr: "HAI - Les collègues proches.",
    levelId: 47,
  },
  {
    character: "輪",
    meaningsFr: ["roue", "cercle"],
    readingsOn: ["リン"],
    readingsKun: ["わ"],
    meaningMnemonicFr: "Le véhicule 車 avec l'ordre 侖 forme une ROUE.",
    readingMnemonicFr: "RIN - La roue qui tourne.",
    levelId: 44,
  },
  {
    character: "輸",
    meaningsFr: ["transporter", "exporter"],
    readingsOn: ["ユ", "シュ"],
    readingsKun: [],
    meaningMnemonicFr: "Le véhicule 車 avec le mois 俞 TRANSPORTE.",
    readingMnemonicFr: "YU - Le transport effectué.",
    levelId: 45,
  },
  {
    character: "轄",
    meaningsFr: ["juridiction", "contrôle"],
    readingsOn: ["カツ"],
    readingsKun: [],
    meaningMnemonicFr: "Le véhicule 車 avec la langue 害 a la JURIDICTION.",
    readingMnemonicFr: "KATSU - Le contrôle exercé.",
    levelId: 49,
  },
  {
    character: "辛",
    meaningsFr: ["épicé", "pénible"],
    readingsOn: ["シン"],
    readingsKun: ["から.い", "つら.い"],
    meaningMnemonicFr: "Le signe qui pique est ÉPICÉ.",
    readingMnemonicFr: "SHIN - Le piquant douloureux.",
    levelId: 43,
  },
  {
    character: "辰",
    meaningsFr: ["dragon", "matin"],
    readingsOn: ["シン"],
    readingsKun: ["たつ"],
    meaningMnemonicFr: "Le signe du zodiaque est le DRAGON.",
    readingMnemonicFr: "SHIN - Le dragon du matin.",
    levelId: 48,
  },
  {
    character: "辱",
    meaningsFr: ["honte", "humilier"],
    readingsOn: ["ジョク"],
    readingsKun: ["はずかし.める"],
    meaningMnemonicFr: "Le dragon 辰 qui domine avec le pouce 寸 HUMILIE.",
    readingMnemonicFr: "JOKU - L'humiliation subie.",
    levelId: 49,
  },
  {
    character: "込",
    meaningsFr: ["entrer", "inclure"],
    readingsOn: [],
    readingsKun: ["こ.む", "こ.める"],
    meaningMnemonicFr: "Marcher 辶 vers l'intérieur 入 ENTRE.",
    readingMnemonicFr: "Komu - L'entrée incluse.",
    levelId: 38,
  },
  {
    character: "迅",
    meaningsFr: ["rapide", "prompt"],
    readingsOn: ["ジン"],
    readingsKun: [],
    meaningMnemonicFr: "Marcher 辶 avec le nid 卂 est RAPIDE.",
    readingMnemonicFr: "JIN - La rapidité prompte.",
    levelId: 47,
  },
  {
    character: "迎",
    meaningsFr: ["accueillir", "aller chercher"],
    readingsOn: ["ゲイ"],
    readingsKun: ["むか.える"],
    meaningMnemonicFr: "Marcher 辶 vers le haut 卬 ACCUEILLE.",
    readingMnemonicFr: "GEI - L'accueil chaleureux.",
    levelId: 43,
  },
  {
    character: "逆",
    meaningsFr: ["inverse", "opposé"],
    readingsOn: ["ギャク"],
    readingsKun: ["さか", "さか.らう"],
    meaningMnemonicFr: "Marcher 辶 à rebours 屰 est INVERSE.",
    readingMnemonicFr: "GYAKU - L'opposition directe.",
    levelId: 42,
  },
  {
    character: "逃",
    meaningsFr: ["fuir", "échapper"],
    readingsOn: ["トウ"],
    readingsKun: ["に.げる", "のが.れる"],
    meaningMnemonicFr: "Marcher 辶 avec le signe 兆 pour FUIR.",
    readingMnemonicFr: "TŌ - La fuite précipitée.",
    levelId: 42,
  },
  {
    character: "透",
    meaningsFr: ["transparent", "traverser"],
    readingsOn: ["トウ"],
    readingsKun: ["す.く", "す.かす"],
    meaningMnemonicFr: "Marcher 辶 avec le cache 秀 est TRANSPARENT.",
    readingMnemonicFr: "TŌ - La transparence parfaite.",
    levelId: 46,
  },
  {
    character: "逐",
    meaningsFr: ["poursuivre", "chasser"],
    readingsOn: ["チク"],
    readingsKun: [],
    meaningMnemonicFr: "Marcher 辶 avec le cochon 豕 POURSUIT.",
    readingMnemonicFr: "CHIKU - La poursuite acharnée.",
    levelId: 48,
  },
  {
    character: "途",
    meaningsFr: ["route", "chemin"],
    readingsOn: ["ト"],
    readingsKun: ["みち"],
    meaningMnemonicFr: "Marcher 辶 avec le reste 余 forme la ROUTE.",
    readingMnemonicFr: "TO - Le chemin parcouru.",
    levelId: 44,
  },
];

async function main() {
  console.log("Seeding ABSOLUTE FINAL kanji batch to exceed 2000...");

  for (const kanji of kanjiData) {
    await prisma.kanji.upsert({
      where: { character: kanji.character },
      update: {
        meaningsFr: kanji.meaningsFr,
        readingsOn: kanji.readingsOn,
        readingsKun: kanji.readingsKun,
        meaningMnemonicFr: kanji.meaningMnemonicFr,
        readingMnemonicFr: kanji.readingMnemonicFr,
        levelId: kanji.levelId,
      },
      create: kanji,
    });
  }

  console.log(`Seeded ${kanjiData.length} kanji.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
