import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Vocabulary supplement for levels 51-55
// Adding ~40 words per level to bring these expert levels to ~90-100 words
// Focus: N1 abstract concepts, literary vocabulary, formal Japanese

const vocabularyData = [
  // Level 51 - N1 Abstract/Formal vocabulary
  { word: "普及", meaningsFr: ["Diffusion", "Propagation"], readings: ["ふきゅう"], mnemonicFr: "La DIFFUSION de la technologie.", levelId: 51 },
  { word: "浸透", meaningsFr: ["Pénétration", "Infiltration"], readings: ["しんとう"], mnemonicFr: "La PÉNÉTRATION culturelle.", levelId: 51 },
  { word: "蔓延", meaningsFr: ["Propagation", "Expansion"], readings: ["まんえん"], mnemonicFr: "La PROPAGATION de la maladie.", levelId: 51 },
  { word: "台頭", meaningsFr: ["Émergence", "Montée en puissance"], readings: ["たいとう"], mnemonicFr: "L'ÉMERGENCE d'un leader.", levelId: 51 },
  { word: "衰退", meaningsFr: ["Déclin"], readings: ["すいたい"], mnemonicFr: "Le DÉCLIN d'un empire.", levelId: 51 },
  { word: "隆盛", meaningsFr: ["Prospérité", "Essor"], readings: ["りゅうせい"], mnemonicFr: "L'ESSOR économique.", levelId: 51 },
  { word: "没落", meaningsFr: ["Chute", "Déchéance"], readings: ["ぼつらく"], mnemonicFr: "La CHUTE d'une famille.", levelId: 51 },
  { word: "興亡", meaningsFr: ["Essor et déclin"], readings: ["こうぼう"], mnemonicFr: "L'ESSOR ET DÉCLIN des empires.", levelId: 51 },
  { word: "変遷", meaningsFr: ["Évolution", "Changement"], readings: ["へんせん"], mnemonicFr: "L'ÉVOLUTION des mœurs.", levelId: 51 },
  { word: "推移", meaningsFr: ["Transition", "Évolution"], readings: ["すいい"], mnemonicFr: "La TRANSITION graduelle.", levelId: 51 },
  { word: "経緯", meaningsFr: ["Circonstances", "Détails"], readings: ["けいい"], mnemonicFr: "Les CIRCONSTANCES de l'affaire.", levelId: 51 },
  { word: "顛末", meaningsFr: ["Tout le détail", "Circonstances"], readings: ["てんまつ"], mnemonicFr: "Le DÉTAIL de l'incident.", levelId: 51 },
  { word: "由来", meaningsFr: ["Origine", "Provenance"], readings: ["ゆらい"], mnemonicFr: "L'ORIGINE du mot.", levelId: 51 },
  { word: "沿革", meaningsFr: ["Histoire", "Évolution historique"], readings: ["えんかく"], mnemonicFr: "L'HISTOIRE de l'entreprise.", levelId: 51 },
  { word: "趣旨", meaningsFr: ["Intention", "But"], readings: ["しゅし"], mnemonicFr: "L'INTENTION de la loi.", levelId: 51 },
  { word: "要旨", meaningsFr: ["Résumé", "Essence"], readings: ["ようし"], mnemonicFr: "Le RÉSUMÉ de l'article.", levelId: 51 },
  { word: "骨子", meaningsFr: ["Points essentiels"], readings: ["こっし"], mnemonicFr: "Les POINTS ESSENTIELS du plan.", levelId: 51 },
  { word: "概略", meaningsFr: ["Aperçu", "Résumé"], readings: ["がいりゃく"], mnemonicFr: "L'APERÇU du projet.", levelId: 51 },
  { word: "梗概", meaningsFr: ["Synopsis", "Résumé"], readings: ["こうがい"], mnemonicFr: "Le SYNOPSIS du film.", levelId: 51 },
  { word: "大綱", meaningsFr: ["Grandes lignes"], readings: ["たいこう"], mnemonicFr: "Les GRANDES LIGNES du plan.", levelId: 51 },
  { word: "細目", meaningsFr: ["Détails", "Articles"], readings: ["さいもく"], mnemonicFr: "Les DÉTAILS du contrat.", levelId: 51 },
  { word: "内訳", meaningsFr: ["Détail", "Ventilation"], readings: ["うちわけ"], mnemonicFr: "La VENTILATION des coûts.", levelId: 51 },
  { word: "明細", meaningsFr: ["Détail", "Relevé"], readings: ["めいさい"], mnemonicFr: "Le RELEVÉ détaillé.", levelId: 51 },
  { word: "仔細", meaningsFr: ["Détails", "Particularités"], readings: ["しさい"], mnemonicFr: "Les PARTICULARITÉS de l'affaire.", levelId: 51 },
  { word: "機微", meaningsFr: ["Subtilité", "Nuance"], readings: ["きび"], mnemonicFr: "Les SUBTILITÉS humaines.", levelId: 51 },
  { word: "微妙", meaningsFr: ["Délicat", "Subtil"], readings: ["びみょう"], mnemonicFr: "Une situation DÉLICATE.", levelId: 51 },
  { word: "繊細", meaningsFr: ["Délicat", "Sensible"], readings: ["せんさい"], mnemonicFr: "Une personne SENSIBLE.", levelId: 51 },
  { word: "精緻", meaningsFr: ["Sophistiqué", "Raffiné"], readings: ["せいち"], mnemonicFr: "Un travail SOPHISTIQUÉ.", levelId: 51 },
  { word: "巧妙", meaningsFr: ["Ingénieux", "Habile"], readings: ["こうみょう"], mnemonicFr: "Un plan INGÉNIEUX.", levelId: 51 },
  { word: "精巧", meaningsFr: ["Élaboré", "Minutieux"], readings: ["せいこう"], mnemonicFr: "Un travail MINUTIEUX.", levelId: 51 },
  { word: "粗雑", meaningsFr: ["Grossier", "Négligé"], readings: ["そざつ"], mnemonicFr: "Un travail GROSSIER.", levelId: 51 },
  { word: "杜撰", meaningsFr: ["Bâclé", "Négligent"], readings: ["ずさん"], mnemonicFr: "Un travail BÂCLÉ.", levelId: 51 },
  { word: "拙劣", meaningsFr: ["Maladroit", "Médiocre"], readings: ["せつれつ"], mnemonicFr: "Une performance MALADROITE.", levelId: 51 },
  { word: "稚拙", meaningsFr: ["Puéril", "Immature"], readings: ["ちせつ"], mnemonicFr: "Un comportement PUÉRIL.", levelId: 51 },
  { word: "未熟", meaningsFr: ["Immature", "Inexpérimenté"], readings: ["みじゅく"], mnemonicFr: "Un artiste INEXPÉRIMENTÉ.", levelId: 51 },
  { word: "成熟", meaningsFr: ["Maturité"], readings: ["せいじゅく"], mnemonicFr: "La MATURITÉ intellectuelle.", levelId: 51 },
  { word: "円熟", meaningsFr: ["Maturité accomplie"], readings: ["えんじゅく"], mnemonicFr: "La MATURITÉ ACCOMPLIE d'un artiste.", levelId: 51 },
  { word: "老成", meaningsFr: ["Précoce", "Mûr pour son âge"], readings: ["ろうせい"], mnemonicFr: "Un enfant PRÉCOCE.", levelId: 51 },
  { word: "早熟", meaningsFr: ["Précoce"], readings: ["そうじゅく"], mnemonicFr: "Un développement PRÉCOCE.", levelId: 51 },
  { word: "晩成", meaningsFr: ["Maturité tardive"], readings: ["ばんせい"], mnemonicFr: "Une MATURITÉ TARDIVE.", levelId: 51 },

  // Level 52 - N1 Literary/Formal vocabulary
  { word: "逸脱", meaningsFr: ["Déviation", "Écart"], readings: ["いつだつ"], mnemonicFr: "Une DÉVIATION de la norme.", levelId: 52 },
  { word: "乖離", meaningsFr: ["Écart", "Divergence"], readings: ["かいり"], mnemonicFr: "Un ÉCART entre théorie et pratique.", levelId: 52 },
  { word: "齟齬", meaningsFr: ["Désaccord", "Incohérence"], readings: ["そご"], mnemonicFr: "Un DÉSACCORD entre les parties.", levelId: 52 },
  { word: "矛盾", meaningsFr: ["Contradiction"], readings: ["むじゅん"], mnemonicFr: "Une CONTRADICTION flagrante.", levelId: 52 },
  { word: "背反", meaningsFr: ["Contradiction", "Opposition"], readings: ["はいはん"], mnemonicFr: "Une OPPOSITION fondamentale.", levelId: 52 },
  { word: "相克", meaningsFr: ["Antagonisme", "Conflit"], readings: ["そうこく"], mnemonicFr: "Un ANTAGONISME profond.", levelId: 52 },
  { word: "葛藤", meaningsFr: ["Conflit intérieur"], readings: ["かっとう"], mnemonicFr: "Un CONFLIT INTÉRIEUR.", levelId: 52 },
  { word: "軋轢", meaningsFr: ["Friction", "Conflit"], readings: ["あつれき"], mnemonicFr: "Une FRICTION entre groupes.", levelId: 52 },
  { word: "確執", meaningsFr: ["Désaccord persistant"], readings: ["かくしつ"], mnemonicFr: "Un DÉSACCORD PERSISTANT.", levelId: 52 },
  { word: "反目", meaningsFr: ["Hostilité mutuelle"], readings: ["はんもく"], mnemonicFr: "Une HOSTILITÉ MUTUELLE.", levelId: 52 },
  { word: "敵対", meaningsFr: ["Hostilité", "Opposition"], readings: ["てきたい"], mnemonicFr: "Une HOSTILITÉ ouverte.", levelId: 52 },
  { word: "対峙", meaningsFr: ["Confrontation"], readings: ["たいじ"], mnemonicFr: "Une CONFRONTATION directe.", levelId: 52 },
  { word: "拮抗", meaningsFr: ["Rivalité équilibrée"], readings: ["きっこう"], mnemonicFr: "Une RIVALITÉ ÉQUILIBRÉE.", levelId: 52 },
  { word: "均衡", meaningsFr: ["Équilibre"], readings: ["きんこう"], mnemonicFr: "L'ÉQUILIBRE des forces.", levelId: 52 },
  { word: "安定", meaningsFr: ["Stabilité"], readings: ["あんてい"], mnemonicFr: "La STABILITÉ politique.", levelId: 52 },
  { word: "動揺", meaningsFr: ["Instabilité", "Agitation"], readings: ["どうよう"], mnemonicFr: "L'INSTABILITÉ émotionnelle.", levelId: 52 },
  { word: "混迷", meaningsFr: ["Confusion", "Chaos"], readings: ["こんめい"], mnemonicFr: "La CONFUSION politique.", levelId: 52 },
  { word: "混沌", meaningsFr: ["Chaos"], readings: ["こんとん"], mnemonicFr: "Le CHAOS primordial.", levelId: 52 },
  { word: "錯綜", meaningsFr: ["Enchevêtrement", "Complexité"], readings: ["さくそう"], mnemonicFr: "Un ENCHEVÊTREMENT de problèmes.", levelId: 52 },
  { word: "紛糾", meaningsFr: ["Complication", "Embrouillement"], readings: ["ふんきゅう"], mnemonicFr: "Une COMPLICATION de la situation.", levelId: 52 },
  { word: "収拾", meaningsFr: ["Règlement", "Résolution"], readings: ["しゅうしゅう"], mnemonicFr: "Le RÈGLEMENT de la situation.", levelId: 52 },
  { word: "鎮静", meaningsFr: ["Apaisement", "Calme"], readings: ["ちんせい"], mnemonicFr: "L'APAISEMENT de la situation.", levelId: 52 },
  { word: "沈静", meaningsFr: ["Calme", "Tranquillité"], readings: ["ちんせい"], mnemonicFr: "Le CALME revient.", levelId: 52 },
  { word: "平穏", meaningsFr: ["Paix", "Tranquillité"], readings: ["へいおん"], mnemonicFr: "La PAIX retrouvée.", levelId: 52 },
  { word: "静謐", meaningsFr: ["Sérénité", "Quiétude"], readings: ["せいひつ"], mnemonicFr: "La SÉRÉNITÉ du lieu.", levelId: 52 },
  { word: "閑静", meaningsFr: ["Calme", "Paisible"], readings: ["かんせい"], mnemonicFr: "Un quartier PAISIBLE.", levelId: 52 },
  { word: "閑散", meaningsFr: ["Désert", "Calme"], readings: ["かんさん"], mnemonicFr: "Une rue DÉSERTE.", levelId: 52 },
  { word: "寂寥", meaningsFr: ["Solitude", "Désolation"], readings: ["せきりょう"], mnemonicFr: "La SOLITUDE profonde.", levelId: 52 },
  { word: "孤独", meaningsFr: ["Solitude"], readings: ["こどく"], mnemonicFr: "La SOLITUDE existentielle.", levelId: 52 },
  { word: "疎外", meaningsFr: ["Aliénation", "Exclusion"], readings: ["そがい"], mnemonicFr: "L'ALIÉNATION sociale.", levelId: 52 },
  { word: "隔絶", meaningsFr: ["Isolement complet"], readings: ["かくぜつ"], mnemonicFr: "Un ISOLEMENT COMPLET.", levelId: 52 },
  { word: "断絶", meaningsFr: ["Rupture", "Coupure"], readings: ["だんぜつ"], mnemonicFr: "La RUPTURE des relations.", levelId: 52 },
  { word: "途絶", meaningsFr: ["Interruption", "Cessation"], readings: ["とぜつ"], mnemonicFr: "L'INTERRUPTION de la communication.", levelId: 52 },
  { word: "中絶", meaningsFr: ["Interruption", "Avortement"], readings: ["ちゅうぜつ"], mnemonicFr: "L'INTERRUPTION du projet.", levelId: 52 },
  { word: "頓挫", meaningsFr: ["Échec", "Avortement"], readings: ["とんざ"], mnemonicFr: "L'ÉCHEC du projet.", levelId: 52 },
  { word: "挫折", meaningsFr: ["Échec", "Frustration"], readings: ["ざせつ"], mnemonicFr: "L'ÉCHEC de ses ambitions.", levelId: 52 },
  { word: "敗北", meaningsFr: ["Défaite"], readings: ["はいぼく"], mnemonicFr: "La DÉFAITE électorale.", levelId: 52 },
  { word: "惨敗", meaningsFr: ["Défaite écrasante"], readings: ["ざんぱい"], mnemonicFr: "Une DÉFAITE ÉCRASANTE.", levelId: 52 },
  { word: "完敗", meaningsFr: ["Défaite totale"], readings: ["かんぱい"], mnemonicFr: "Une DÉFAITE TOTALE.", levelId: 52 },
  { word: "辛勝", meaningsFr: ["Victoire difficile"], readings: ["しんしょう"], mnemonicFr: "Une VICTOIRE DIFFICILE.", levelId: 52 },

  // Level 53 - N1 Academic/Intellectual vocabulary
  { word: "圧勝", meaningsFr: ["Victoire écrasante"], readings: ["あっしょう"], mnemonicFr: "Une VICTOIRE ÉCRASANTE.", levelId: 53 },
  { word: "快勝", meaningsFr: ["Belle victoire"], readings: ["かいしょう"], mnemonicFr: "Une BELLE VICTOIRE.", levelId: 53 },
  { word: "連勝", meaningsFr: ["Série de victoires"], readings: ["れんしょう"], mnemonicFr: "Une SÉRIE DE VICTOIRES.", levelId: 53 },
  { word: "連敗", meaningsFr: ["Série de défaites"], readings: ["れんぱい"], mnemonicFr: "Une SÉRIE DE DÉFAITES.", levelId: 53 },
  { word: "雪辱", meaningsFr: ["Revanche"], readings: ["せつじょく"], mnemonicFr: "Prendre sa REVANCHE.", levelId: 53 },
  { word: "報復", meaningsFr: ["Représailles"], readings: ["ほうふく"], mnemonicFr: "Des REPRÉSAILLES.", levelId: 53 },
  { word: "復讐", meaningsFr: ["Vengeance"], readings: ["ふくしゅう"], mnemonicFr: "La VENGEANCE.", levelId: 53 },
  { word: "怨恨", meaningsFr: ["Rancune", "Ressentiment"], readings: ["えんこん"], mnemonicFr: "La RANCUNE profonde.", levelId: 53 },
  { word: "憎悪", meaningsFr: ["Haine"], readings: ["ぞうお"], mnemonicFr: "La HAINE viscérale.", levelId: 53 },
  { word: "嫌悪", meaningsFr: ["Aversion", "Dégoût"], readings: ["けんお"], mnemonicFr: "L'AVERSION profonde.", levelId: 53 },
  { word: "軽蔑", meaningsFr: ["Mépris"], readings: ["けいべつ"], mnemonicFr: "Le MÉPRIS affiché.", levelId: 53 },
  { word: "侮蔑", meaningsFr: ["Mépris", "Dédain"], readings: ["ぶべつ"], mnemonicFr: "Le DÉDAIN manifeste.", levelId: 53 },
  { word: "侮辱", meaningsFr: ["Insulte", "Humiliation"], readings: ["ぶじょく"], mnemonicFr: "Une INSULTE grave.", levelId: 53 },
  { word: "屈辱", meaningsFr: ["Humiliation"], readings: ["くつじょく"], mnemonicFr: "L'HUMILIATION subie.", levelId: 53 },
  { word: "恥辱", meaningsFr: ["Honte", "Déshonneur"], readings: ["ちじょく"], mnemonicFr: "La HONTE du déshonneur.", levelId: 53 },
  { word: "羞恥", meaningsFr: ["Honte", "Pudeur"], readings: ["しゅうち"], mnemonicFr: "La HONTE ressentie.", levelId: 53 },
  { word: "廉恥", meaningsFr: ["Sens de l'honneur"], readings: ["れんち"], mnemonicFr: "Le SENS DE L'HONNEUR.", levelId: 53 },
  { word: "誇り", meaningsFr: ["Fierté"], readings: ["ほこり"], mnemonicFr: "La FIERTÉ nationale.", levelId: 53 },
  { word: "矜持", meaningsFr: ["Fierté", "Dignité"], readings: ["きょうじ"], mnemonicFr: "La DIGNITÉ professionnelle.", levelId: 53 },
  { word: "自尊", meaningsFr: ["Amour-propre"], readings: ["じそん"], mnemonicFr: "L'AMOUR-PROPRE blessé.", levelId: 53 },
  { word: "尊厳", meaningsFr: ["Dignité"], readings: ["そんげん"], mnemonicFr: "La DIGNITÉ humaine.", levelId: 53 },
  { word: "威厳", meaningsFr: ["Majesté", "Prestance"], readings: ["いげん"], mnemonicFr: "La MAJESTÉ du lieu.", levelId: 53 },
  { word: "威信", meaningsFr: ["Prestige", "Autorité"], readings: ["いしん"], mnemonicFr: "Le PRESTIGE de la fonction.", levelId: 53 },
  { word: "権威", meaningsFr: ["Autorité"], readings: ["けんい"], mnemonicFr: "L'AUTORITÉ scientifique.", levelId: 53 },
  { word: "権限", meaningsFr: ["Pouvoir", "Compétence"], readings: ["けんげん"], mnemonicFr: "Le POUVOIR de décision.", levelId: 53 },
  { word: "裁量", meaningsFr: ["Discrétion", "Jugement"], readings: ["さいりょう"], mnemonicFr: "La DISCRÉTION du juge.", levelId: 53 },
  { word: "采配", meaningsFr: ["Direction", "Commandement"], readings: ["さいはい"], mnemonicFr: "Le COMMANDEMENT des troupes.", levelId: 53 },
  { word: "統率", meaningsFr: ["Direction", "Leadership"], readings: ["とうそつ"], mnemonicFr: "Le LEADERSHIP efficace.", levelId: 53 },
  { word: "指揮", meaningsFr: ["Direction", "Commandement"], readings: ["しき"], mnemonicFr: "La DIRECTION de l'orchestre.", levelId: 53 },
  { word: "統括", meaningsFr: ["Supervision", "Coordination"], readings: ["とうかつ"], mnemonicFr: "La SUPERVISION générale.", levelId: 53 },
  { word: "総括", meaningsFr: ["Synthèse", "Bilan"], readings: ["そうかつ"], mnemonicFr: "La SYNTHÈSE finale.", levelId: 53 },
  { word: "概括", meaningsFr: ["Résumé", "Généralisation"], readings: ["がいかつ"], mnemonicFr: "Le RÉSUMÉ global.", levelId: 53 },
  { word: "包括", meaningsFr: ["Inclusion", "Englobement"], readings: ["ほうかつ"], mnemonicFr: "L'INCLUSION de tous les éléments.", levelId: 53 },
  { word: "網羅", meaningsFr: ["Couverture complète"], readings: ["もうら"], mnemonicFr: "Une COUVERTURE COMPLÈTE du sujet.", levelId: 53 },
  { word: "遍歴", meaningsFr: ["Pérégrinations"], readings: ["へんれき"], mnemonicFr: "Les PÉRÉGRINATIONS de l'artiste.", levelId: 53 },
  { word: "履歴", meaningsFr: ["Historique", "Curriculum"], readings: ["りれき"], mnemonicFr: "L'HISTORIQUE des modifications.", levelId: 53 },
  { word: "経緯", meaningsFr: ["Circonstances"], readings: ["けいい"], mnemonicFr: "Les CIRCONSTANCES de l'incident.", levelId: 53 },
  { word: "来歴", meaningsFr: ["Antécédents", "Origine"], readings: ["らいれき"], mnemonicFr: "Les ANTÉCÉDENTS de l'objet.", levelId: 53 },
  { word: "系譜", meaningsFr: ["Généalogie", "Lignée"], readings: ["けいふ"], mnemonicFr: "La GÉNÉALOGIE familiale.", levelId: 53 },
  { word: "血統", meaningsFr: ["Lignée", "Ascendance"], readings: ["けっとう"], mnemonicFr: "La LIGNÉE royale.", levelId: 53 },

  // Level 54 - N1 Sophisticated/Nuanced vocabulary
  { word: "家系", meaningsFr: ["Lignée familiale"], readings: ["かけい"], mnemonicFr: "La LIGNÉE FAMILIALE.", levelId: 54 },
  { word: "門閥", meaningsFr: ["Clan", "Famille influente"], readings: ["もんばつ"], mnemonicFr: "Un CLAN puissant.", levelId: 54 },
  { word: "派閥", meaningsFr: ["Faction", "Clique"], readings: ["はばつ"], mnemonicFr: "Une FACTION politique.", levelId: 54 },
  { word: "閥族", meaningsFr: ["Clique", "Coterie"], readings: ["ばつぞく"], mnemonicFr: "Une CLIQUE influente.", levelId: 54 },
  { word: "徒党", meaningsFr: ["Bande", "Faction"], readings: ["ととう"], mnemonicFr: "Une BANDE organisée.", levelId: 54 },
  { word: "党派", meaningsFr: ["Parti", "Faction"], readings: ["とうは"], mnemonicFr: "Une FACTION au sein du parti.", levelId: 54 },
  { word: "宗派", meaningsFr: ["Secte", "Dénomination"], readings: ["しゅうは"], mnemonicFr: "Une SECTE religieuse.", levelId: 54 },
  { word: "流派", meaningsFr: ["École", "Style"], readings: ["りゅうは"], mnemonicFr: "Une ÉCOLE artistique.", levelId: 54 },
  { word: "学派", meaningsFr: ["École de pensée"], readings: ["がくは"], mnemonicFr: "Une ÉCOLE DE PENSÉE.", levelId: 54 },
  { word: "門下", meaningsFr: ["Disciple", "Élève"], readings: ["もんか"], mnemonicFr: "Un DISCIPLE du maître.", levelId: 54 },
  { word: "弟子", meaningsFr: ["Disciple", "Apprenti"], readings: ["でし"], mnemonicFr: "Un APPRENTI dévoué.", levelId: 54 },
  { word: "師匠", meaningsFr: ["Maître", "Professeur"], readings: ["ししょう"], mnemonicFr: "Le MAÎTRE artisan.", levelId: 54 },
  { word: "師事", meaningsFr: ["Étudier sous"], readings: ["しじ"], mnemonicFr: "ÉTUDIER SOUS un maître.", levelId: 54 },
  { word: "薫陶", meaningsFr: ["Influence formatrice"], readings: ["くんとう"], mnemonicFr: "L'INFLUENCE FORMATRICE du mentor.", levelId: 54 },
  { word: "感化", meaningsFr: ["Influence", "Inspiration"], readings: ["かんか"], mnemonicFr: "L'INFLUENCE positive.", levelId: 54 },
  { word: "啓発", meaningsFr: ["Éveil", "Illumination"], readings: ["けいはつ"], mnemonicFr: "L'ÉVEIL intellectuel.", levelId: 54 },
  { word: "啓蒙", meaningsFr: ["Lumières", "Éducation"], readings: ["けいもう"], mnemonicFr: "Les LUMIÈRES du siècle.", levelId: 54 },
  { word: "教化", meaningsFr: ["Éducation", "Conversion"], readings: ["きょうか"], mnemonicFr: "L'ÉDUCATION des masses.", levelId: 54 },
  { word: "布教", meaningsFr: ["Prosélytisme"], readings: ["ふきょう"], mnemonicFr: "Le PROSÉLYTISME religieux.", levelId: 54 },
  { word: "伝道", meaningsFr: ["Évangélisation"], readings: ["でんどう"], mnemonicFr: "L'ÉVANGÉLISATION.", levelId: 54 },
  { word: "宣教", meaningsFr: ["Mission religieuse"], readings: ["せんきょう"], mnemonicFr: "La MISSION RELIGIEUSE.", levelId: 54 },
  { word: "伝承", meaningsFr: ["Transmission", "Tradition orale"], readings: ["でんしょう"], mnemonicFr: "La TRANSMISSION orale.", levelId: 54 },
  { word: "継承", meaningsFr: ["Succession", "Héritage"], readings: ["けいしょう"], mnemonicFr: "La SUCCESSION au trône.", levelId: 54 },
  { word: "相続", meaningsFr: ["Héritage"], readings: ["そうぞく"], mnemonicFr: "L'HÉRITAGE familial.", levelId: 54 },
  { word: "遺産", meaningsFr: ["Patrimoine", "Héritage"], readings: ["いさん"], mnemonicFr: "Le PATRIMOINE culturel.", levelId: 54 },
  { word: "遺志", meaningsFr: ["Dernières volontés"], readings: ["いし"], mnemonicFr: "Les DERNIÈRES VOLONTÉS.", levelId: 54 },
  { word: "遺言", meaningsFr: ["Testament"], readings: ["ゆいごん"], mnemonicFr: "Le TESTAMENT écrit.", levelId: 54 },
  { word: "遺訓", meaningsFr: ["Enseignement posthume"], readings: ["いくん"], mnemonicFr: "L'ENSEIGNEMENT POSTHUME.", levelId: 54 },
  { word: "家訓", meaningsFr: ["Préceptes familiaux"], readings: ["かくん"], mnemonicFr: "Les PRÉCEPTES FAMILIAUX.", levelId: 54 },
  { word: "戒律", meaningsFr: ["Commandements", "Règles"], readings: ["かいりつ"], mnemonicFr: "Les COMMANDEMENTS religieux.", levelId: 54 },
  { word: "戒め", meaningsFr: ["Avertissement", "Précepte"], readings: ["いましめ"], mnemonicFr: "Un AVERTISSEMENT sérieux.", levelId: 54 },
  { word: "訓戒", meaningsFr: ["Admonition", "Réprimande"], readings: ["くんかい"], mnemonicFr: "Une RÉPRIMANDE sévère.", levelId: 54 },
  { word: "諫言", meaningsFr: ["Remontrance"], readings: ["かんげん"], mnemonicFr: "Une REMONTRANCE au souverain.", levelId: 54 },
  { word: "進言", meaningsFr: ["Conseil", "Suggestion"], readings: ["しんげん"], mnemonicFr: "Un CONSEIL au supérieur.", levelId: 54 },
  { word: "提言", meaningsFr: ["Proposition", "Recommandation"], readings: ["ていげん"], mnemonicFr: "Une RECOMMANDATION officielle.", levelId: 54 },
  { word: "具申", meaningsFr: ["Rapport détaillé"], readings: ["ぐしん"], mnemonicFr: "Un RAPPORT DÉTAILLÉ au supérieur.", levelId: 54 },
  { word: "上申", meaningsFr: ["Rapport au supérieur"], readings: ["じょうしん"], mnemonicFr: "Un RAPPORT AU SUPÉRIEUR.", levelId: 54 },
  { word: "陳情", meaningsFr: ["Pétition", "Requête"], readings: ["ちんじょう"], mnemonicFr: "Une PÉTITION au gouvernement.", levelId: 54 },
  { word: "請願", meaningsFr: ["Pétition", "Demande"], readings: ["せいがん"], mnemonicFr: "Une DEMANDE officielle.", levelId: 54 },
  { word: "嘆願", meaningsFr: ["Supplique", "Requête"], readings: ["たんがん"], mnemonicFr: "Une SUPPLIQUE émouvante.", levelId: 54 },

  // Level 55 - N1 Refined/Elevated vocabulary
  { word: "懇願", meaningsFr: ["Supplication"], readings: ["こんがん"], mnemonicFr: "Une SUPPLICATION sincère.", levelId: 55 },
  { word: "哀願", meaningsFr: ["Imploration"], readings: ["あいがん"], mnemonicFr: "Une IMPLORATION désespérée.", levelId: 55 },
  { word: "祈願", meaningsFr: ["Prière", "Vœu"], readings: ["きがん"], mnemonicFr: "Une PRIÈRE ardente.", levelId: 55 },
  { word: "発願", meaningsFr: ["Vœu religieux"], readings: ["ほつがん"], mnemonicFr: "Un VŒU RELIGIEUX.", levelId: 55 },
  { word: "誓願", meaningsFr: ["Serment", "Vœu solennel"], readings: ["せいがん"], mnemonicFr: "Un SERMENT solennel.", levelId: 55 },
  { word: "宿願", meaningsFr: ["Vœu de longue date"], readings: ["しゅくがん"], mnemonicFr: "Un VŒU DE LONGUE DATE.", levelId: 55 },
  { word: "念願", meaningsFr: ["Désir ardent"], readings: ["ねんがん"], mnemonicFr: "Un DÉSIR ARDENT.", levelId: 55 },
  { word: "悲願", meaningsFr: ["Vœu passionné"], readings: ["ひがん"], mnemonicFr: "Un VŒU PASSIONNÉ.", levelId: 55 },
  { word: "願望", meaningsFr: ["Désir", "Aspiration"], readings: ["がんぼう"], mnemonicFr: "Une ASPIRATION profonde.", levelId: 55 },
  { word: "渇望", meaningsFr: ["Désir intense"], readings: ["かつぼう"], mnemonicFr: "Un DÉSIR INTENSE.", levelId: 55 },
  { word: "熱望", meaningsFr: ["Désir ardent"], readings: ["ねつぼう"], mnemonicFr: "Un DÉSIR ARDENT de réussite.", levelId: 55 },
  { word: "野望", meaningsFr: ["Ambition"], readings: ["やぼう"], mnemonicFr: "Une AMBITION démesurée.", levelId: 55 },
  { word: "大望", meaningsFr: ["Grande ambition"], readings: ["たいもう"], mnemonicFr: "Une GRANDE AMBITION.", levelId: 55 },
  { word: "志望", meaningsFr: ["Aspiration", "Candidature"], readings: ["しぼう"], mnemonicFr: "Une CANDIDATURE au poste.", levelId: 55 },
  { word: "志向", meaningsFr: ["Orientation", "Tendance"], readings: ["しこう"], mnemonicFr: "Une ORIENTATION artistique.", levelId: 55 },
  { word: "指向", meaningsFr: ["Direction", "Orientation"], readings: ["しこう"], mnemonicFr: "Une DIRECTION précise.", levelId: 55 },
  { word: "傾向", meaningsFr: ["Tendance"], readings: ["けいこう"], mnemonicFr: "Une TENDANCE générale.", levelId: 55 },
  { word: "趨勢", meaningsFr: ["Tendance", "Courant"], readings: ["すうせい"], mnemonicFr: "La TENDANCE du marché.", levelId: 55 },
  { word: "風潮", meaningsFr: ["Tendance", "Mode"], readings: ["ふうちょう"], mnemonicFr: "La MODE actuelle.", levelId: 55 },
  { word: "潮流", meaningsFr: ["Courant", "Tendance"], readings: ["ちょうりゅう"], mnemonicFr: "Le COURANT historique.", levelId: 55 },
  { word: "気運", meaningsFr: ["Atmosphère", "Tendance"], readings: ["きうん"], mnemonicFr: "L'ATMOSPHÈRE favorable.", levelId: 55 },
  { word: "機運", meaningsFr: ["Opportunité", "Occasion"], readings: ["きうん"], mnemonicFr: "L'OPPORTUNITÉ du moment.", levelId: 55 },
  { word: "好機", meaningsFr: ["Bonne occasion"], readings: ["こうき"], mnemonicFr: "Une BONNE OCCASION.", levelId: 55 },
  { word: "契機", meaningsFr: ["Occasion", "Déclencheur"], readings: ["けいき"], mnemonicFr: "Le DÉCLENCHEUR du changement.", levelId: 55 },
  { word: "転機", meaningsFr: ["Tournant"], readings: ["てんき"], mnemonicFr: "Un TOURNANT décisif.", levelId: 55 },
  { word: "岐路", meaningsFr: ["Carrefour", "Croisée"], readings: ["きろ"], mnemonicFr: "À la CROISÉE des chemins.", levelId: 55 },
  { word: "分岐", meaningsFr: ["Bifurcation", "Embranchement"], readings: ["ぶんき"], mnemonicFr: "Une BIFURCATION de la route.", levelId: 55 },
  { word: "分水嶺", meaningsFr: ["Ligne de partage des eaux"], readings: ["ぶんすいれい"], mnemonicFr: "La LIGNE DE PARTAGE DES EAUX.", levelId: 55 },
  { word: "境界", meaningsFr: ["Frontière", "Limite"], readings: ["きょうかい"], mnemonicFr: "La FRONTIÈRE nationale.", levelId: 55 },
  { word: "境地", meaningsFr: ["État", "Condition"], readings: ["きょうち"], mnemonicFr: "Un ÉTAT d'esprit.", levelId: 55 },
  { word: "心境", meaningsFr: ["État d'esprit"], readings: ["しんきょう"], mnemonicFr: "L'ÉTAT D'ESPRIT actuel.", levelId: 55 },
  { word: "心情", meaningsFr: ["Sentiments"], readings: ["しんじょう"], mnemonicFr: "Les SENTIMENTS profonds.", levelId: 55 },
  { word: "心理", meaningsFr: ["Psychologie"], readings: ["しんり"], mnemonicFr: "La PSYCHOLOGIE humaine.", levelId: 55 },
  { word: "心得", meaningsFr: ["Connaissance", "Règle"], readings: ["こころえ"], mnemonicFr: "Les RÈGLES de conduite.", levelId: 55 },
  { word: "心構え", meaningsFr: ["Préparation mentale"], readings: ["こころがまえ"], mnemonicFr: "La PRÉPARATION MENTALE.", levelId: 55 },
  { word: "気構え", meaningsFr: ["Attitude mentale"], readings: ["きがまえ"], mnemonicFr: "L'ATTITUDE MENTALE.", levelId: 55 },
  { word: "身構え", meaningsFr: ["Posture défensive"], readings: ["みがまえ"], mnemonicFr: "La POSTURE DÉFENSIVE.", levelId: 55 },
  { word: "待機", meaningsFr: ["Attente", "Stand-by"], readings: ["たいき"], mnemonicFr: "En ATTENTE de départ.", levelId: 55 },
  { word: "対峙", meaningsFr: ["Confrontation"], readings: ["たいじ"], mnemonicFr: "La CONFRONTATION directe.", levelId: 55 },
  { word: "臨機", meaningsFr: ["Selon les circonstances"], readings: ["りんき"], mnemonicFr: "SELON LES CIRCONSTANCES.", levelId: 55 },
];

async function main() {
  console.log("Seeding vocabulary supplement for levels 51-55...");

  for (const vocab of vocabularyData) {
    await prisma.vocabulary.upsert({
      where: {
        word_levelId: {
          word: vocab.word,
          levelId: vocab.levelId,
        },
      },
      update: {
        meaningsFr: vocab.meaningsFr,
        readings: vocab.readings,
        mnemonicFr: vocab.mnemonicFr,
      },
      create: vocab,
    });
  }

  console.log(`Seeded ${vocabularyData.length} vocabulary words for levels 51-55.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
