import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// VICTORY batch - the final 30 kanji to exceed 2000!

const kanjiData = [
  {
    character: "雄",
    meaningsFr: ["mâle", "héros"],
    readingsOn: ["ユウ"],
    readingsKun: ["お", "おす"],
    meaningMnemonicFr: "L'oiseau 隹 avec le bras 厷 est un MÂLE héroïque.",
    readingMnemonicFr: "YŪ - Le héros masculin.",
    levelId: 45,
  },
  {
    character: "雌",
    meaningsFr: ["femelle"],
    readingsOn: ["シ"],
    readingsKun: ["め", "めす"],
    meaningMnemonicFr: "L'oiseau 隹 avec l'arrêt 此 est une FEMELLE.",
    readingMnemonicFr: "SHI - La femelle douce.",
    levelId: 48,
  },
  {
    character: "離",
    meaningsFr: ["séparer", "quitter"],
    readingsOn: ["リ"],
    readingsKun: ["はな.れる"],
    meaningMnemonicFr: "L'oiseau 隹 avec le départ 离 SE SÉPARE.",
    readingMnemonicFr: "RI - La séparation douloureuse.",
    levelId: 46,
  },
  {
    character: "難",
    meaningsFr: ["difficile", "problème"],
    readingsOn: ["ナン"],
    readingsKun: ["かた.い", "むずか.しい"],
    meaningMnemonicFr: "L'oiseau 隹 qui brûle 𦰩 est DIFFICILE.",
    readingMnemonicFr: "NAN - La difficulté extrême.",
    levelId: 44,
  },
  {
    character: "震",
    meaningsFr: ["trembler", "séisme"],
    readingsOn: ["シン"],
    readingsKun: ["ふる.う", "ふる.える"],
    meaningMnemonicFr: "La pluie 雨 avec le dragon 辰 TREMBLE.",
    readingMnemonicFr: "SHIN - Le tremblement de terre.",
    levelId: 45,
  },
  {
    character: "霊",
    meaningsFr: ["esprit", "âme"],
    readingsOn: ["レイ", "リョウ"],
    readingsKun: ["たま"],
    meaningMnemonicFr: "La pluie 雨 avec les mains 业 forme l'ESPRIT.",
    readingMnemonicFr: "REI - L'esprit immortel.",
    levelId: 47,
  },
  {
    character: "青",
    meaningsFr: ["bleu", "vert"],
    readingsOn: ["セイ", "ショウ"],
    readingsKun: ["あお"],
    meaningMnemonicFr: "La vie 生 avec la lune 月 est BLEUE.",
    readingMnemonicFr: "SEI - Le bleu du ciel.",
    levelId: 36,
  },
  {
    character: "静",
    meaningsFr: ["calme", "silencieux"],
    readingsOn: ["セイ", "ジョウ"],
    readingsKun: ["しず.か", "しず.める"],
    meaningMnemonicFr: "Le bleu 青 avec le conflit 争 devient CALME.",
    readingMnemonicFr: "SEI - Le silence paisible.",
    levelId: 43,
  },
  {
    character: "非",
    meaningsFr: ["non", "faute"],
    readingsOn: ["ヒ"],
    readingsKun: [],
    meaningMnemonicFr: "Les deux ailes opposées signifient NON.",
    readingMnemonicFr: "HI - La négation directe.",
    levelId: 42,
  },
  {
    character: "韻",
    meaningsFr: ["rime", "charme"],
    readingsOn: ["イン"],
    readingsKun: [],
    meaningMnemonicFr: "Le son 音 avec le membre 員 forme la RIME.",
    readingMnemonicFr: "IN - La rime poétique.",
    levelId: 49,
  },
  {
    character: "響",
    meaningsFr: ["résonner", "écho"],
    readingsOn: ["キョウ"],
    readingsKun: ["ひび.く"],
    meaningMnemonicFr: "La campagne 郷 avec le son 音 RÉSONNE.",
    readingMnemonicFr: "KYŌ - L'écho qui résonne.",
    levelId: 46,
  },
  {
    character: "頂",
    meaningsFr: ["sommet", "recevoir"],
    readingsOn: ["チョウ"],
    readingsKun: ["いただ.く", "いただき"],
    meaningMnemonicFr: "Le clou 丁 sur la tête 頁 est le SOMMET.",
    readingMnemonicFr: "CHŌ - Le sommet atteint.",
    levelId: 44,
  },
  {
    character: "順",
    meaningsFr: ["ordre", "obéir"],
    readingsOn: ["ジュン"],
    readingsKun: [],
    meaningMnemonicFr: "Le fleuve 川 avec la tête 頁 suit l'ORDRE.",
    readingMnemonicFr: "JUN - L'ordre naturel.",
    levelId: 43,
  },
  {
    character: "須",
    meaningsFr: ["devoir", "barbe"],
    readingsOn: ["ス"],
    readingsKun: [],
    meaningMnemonicFr: "Les trois traits 彡 avec la tête 頁 forment la BARBE.",
    readingMnemonicFr: "SU - La nécessité absolue.",
    levelId: 49,
  },
  {
    character: "預",
    meaningsFr: ["confier", "déposer"],
    readingsOn: ["ヨ"],
    readingsKun: ["あず.ける", "あず.かる"],
    meaningMnemonicFr: "Le préalable 予 avec la tête 頁 CONFIE.",
    readingMnemonicFr: "YO - Le dépôt confié.",
    levelId: 45,
  },
  {
    character: "頑",
    meaningsFr: ["têtu", "obstiné"],
    readingsOn: ["ガン"],
    readingsKun: ["かたく.な"],
    meaningMnemonicFr: "L'origine 元 de la tête 頁 est TÊTUE.",
    readingMnemonicFr: "GAN - L'obstination tenace.",
    levelId: 47,
  },
  {
    character: "頒",
    meaningsFr: ["distribuer", "publier"],
    readingsOn: ["ハン"],
    readingsKun: [],
    meaningMnemonicFr: "La division 分 de la tête 頁 DISTRIBUE.",
    readingMnemonicFr: "HAN - La distribution officielle.",
    levelId: 50,
  },
  {
    character: "領",
    meaningsFr: ["territoire", "diriger"],
    readingsOn: ["リョウ"],
    readingsKun: [],
    meaningMnemonicFr: "L'ordre 令 de la tête 頁 gouverne le TERRITOIRE.",
    readingMnemonicFr: "RYŌ - Le territoire administré.",
    levelId: 44,
  },
  {
    character: "頻",
    meaningsFr: ["fréquent", "répété"],
    readingsOn: ["ヒン"],
    readingsKun: ["しき.りに"],
    meaningMnemonicFr: "Le pas 歩 avec la tête 頁 est FRÉQUENT.",
    readingMnemonicFr: "HIN - La fréquence élevée.",
    levelId: 47,
  },
  {
    character: "額",
    meaningsFr: ["front", "montant"],
    readingsOn: ["ガク"],
    readingsKun: ["ひたい"],
    meaningMnemonicFr: "Le client 客 avec la tête 頁 montre le FRONT.",
    readingMnemonicFr: "GAKU - Le montant inscrit.",
    levelId: 45,
  },
  {
    character: "顔",
    meaningsFr: ["visage", "face"],
    readingsOn: ["ガン"],
    readingsKun: ["かお"],
    meaningMnemonicFr: "La couleur 彦 de la tête 頁 est le VISAGE.",
    readingMnemonicFr: "GAN - Le visage expressif.",
    levelId: 40,
  },
  {
    character: "願",
    meaningsFr: ["souhait", "désir"],
    readingsOn: ["ガン"],
    readingsKun: ["ねが.う"],
    meaningMnemonicFr: "L'origine 原 de la tête 頁 forme le SOUHAIT.",
    readingMnemonicFr: "GAN - Le désir profond.",
    levelId: 43,
  },
  {
    character: "類",
    meaningsFr: ["genre", "sorte"],
    readingsOn: ["ルイ"],
    readingsKun: ["たぐ.い"],
    meaningMnemonicFr: "Le riz 米 avec le grand 大 et la tête 頁 forme un GENRE.",
    readingMnemonicFr: "RUI - La catégorie définie.",
    levelId: 44,
  },
  {
    character: "顧",
    meaningsFr: ["regarder en arrière", "client"],
    readingsOn: ["コ"],
    readingsKun: ["かえり.みる"],
    meaningMnemonicFr: "L'ancien 雇 avec la tête 頁 REGARDE EN ARRIÈRE.",
    readingMnemonicFr: "KO - Le regard rétrospectif.",
    levelId: 47,
  },
  {
    character: "風",
    meaningsFr: ["vent", "style"],
    readingsOn: ["フウ", "フ"],
    readingsKun: ["かぜ", "かざ"],
    meaningMnemonicFr: "L'insecte 虫 dans l'enclos 几 forme le VENT.",
    readingMnemonicFr: "FŪ - Le vent qui souffle.",
    levelId: 35,
  },
  {
    character: "飛",
    meaningsFr: ["voler"],
    readingsOn: ["ヒ"],
    readingsKun: ["と.ぶ"],
    meaningMnemonicFr: "Les ailes qui s'élèvent VOLENT.",
    readingMnemonicFr: "HI - Le vol dans le ciel.",
    levelId: 38,
  },
  {
    character: "養",
    meaningsFr: ["élever", "nourrir"],
    readingsOn: ["ヨウ"],
    readingsKun: ["やしな.う"],
    meaningMnemonicFr: "Le mouton 羊 avec la nourriture 食 ÉLÈVE.",
    readingMnemonicFr: "YŌ - L'éducation nourricière.",
    levelId: 44,
  },
  {
    character: "首",
    meaningsFr: ["cou", "tête"],
    readingsOn: ["シュ"],
    readingsKun: ["くび"],
    meaningMnemonicFr: "Le signe sur les cheveux 自 représente le COU.",
    readingMnemonicFr: "SHU - La tête sur le cou.",
    levelId: 37,
  },
  {
    character: "香",
    meaningsFr: ["parfum", "encens"],
    readingsOn: ["コウ", "キョウ"],
    readingsKun: ["か", "かお.り"],
    meaningMnemonicFr: "Le grain 禾 avec le jour 日 forme le PARFUM.",
    readingMnemonicFr: "KŌ - Le parfum agréable.",
    levelId: 44,
  },
  {
    character: "駆",
    meaningsFr: ["conduire", "galoper"],
    readingsOn: ["ク"],
    readingsKun: ["か.ける", "か.る"],
    meaningMnemonicFr: "Le cheval 馬 qui s'écarte 区 GALOPE.",
    readingMnemonicFr: "KU - La course rapide.",
    levelId: 46,
  },
];

async function main() {
  console.log("Seeding VICTORY kanji batch to exceed 2000...");

  for (const kanji of kanjiData) {
    await prisma.kanji.upsert({
      where: { character: kanji.character },
      update: {
        meaningsFr: kanji.meaningsFr,
        readingsOn: kanji.readingsOn,
        readingsKun: kanji.readingsKun,
        meaningMnemonicFr: kanji.meaningMnemonicFr,
        readingMnemonicFr: kanji.readingMnemonicFr,
        levelId: kanji.levelId,
      },
      create: kanji,
    });
  }

  console.log(`Seeded ${kanjiData.length} kanji.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
