import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// FINAL kanji batch 10 - THE LAST ONE to exceed 2000 kanji
// Need ~75 more unique kanji

const kanjiData = [
  {
    character: "棟",
    meaningsFr: ["poutre", "bâtiment"],
    readingsOn: ["トウ"],
    readingsKun: ["むね"],
    meaningMnemonicFr: "L'arbre 木 de l'est 東 forme une POUTRE.",
    readingMnemonicFr: "TŌ - La poutre maîtresse.",
    levelId: 46,
  },
  {
    character: "款",
    meaningsFr: ["article", "clause"],
    readingsOn: ["カン"],
    readingsKun: [],
    meaningMnemonicFr: "Les mots 士 qui manquent 欠 forment un ARTICLE.",
    readingMnemonicFr: "KAN - La clause du contrat.",
    levelId: 49,
  },
  {
    character: "殊",
    meaningsFr: ["spécial", "particulier"],
    readingsOn: ["シュ"],
    readingsKun: ["こと"],
    meaningMnemonicFr: "La mort 歹 du vermillon 朱 est SPÉCIALE.",
    readingMnemonicFr: "SHU - Le cas particulier.",
    levelId: 47,
  },
  {
    character: "殻",
    meaningsFr: ["coquille", "carapace"],
    readingsOn: ["カク"],
    readingsKun: ["から"],
    meaningMnemonicFr: "Le corps 殳 qui frappe 几 a une COQUILLE.",
    readingMnemonicFr: "KAKU - La coquille protectrice.",
    levelId: 48,
  },
  {
    character: "汁",
    meaningsFr: ["jus", "soupe"],
    readingsOn: ["ジュウ"],
    readingsKun: ["しる"],
    meaningMnemonicFr: "L'eau 氵 avec dix 十 fait du JUS.",
    readingMnemonicFr: "JŪ - Le bouillon chaud.",
    levelId: 41,
  },
  {
    character: "汗",
    meaningsFr: ["sueur", "transpiration"],
    readingsOn: ["カン"],
    readingsKun: ["あせ"],
    meaningMnemonicFr: "L'eau 氵 du ciel 干 est la SUEUR.",
    readingMnemonicFr: "KAN - La transpiration de l'effort.",
    levelId: 42,
  },
  {
    character: "沈",
    meaningsFr: ["couler", "s'enfoncer"],
    readingsOn: ["チン"],
    readingsKun: ["しず.む"],
    meaningMnemonicFr: "L'eau 氵 qui est froide 冖几 COULE.",
    readingMnemonicFr: "CHIN - L'enfoncement lent.",
    levelId: 43,
  },
  {
    character: "沖",
    meaningsFr: ["large", "haute mer"],
    readingsOn: ["チュウ"],
    readingsKun: ["おき"],
    meaningMnemonicFr: "L'eau 氵 au milieu 中 est le LARGE.",
    readingMnemonicFr: "CHŪ - La haute mer.",
    levelId: 44,
  },
  {
    character: "沢",
    meaningsFr: ["marais", "abondance"],
    readingsOn: ["タク"],
    readingsKun: ["さわ"],
    meaningMnemonicFr: "L'eau 氵 qui libère 尺 forme un MARAIS.",
    readingMnemonicFr: "TAKU - L'abondance naturelle.",
    levelId: 43,
  },
  {
    character: "沿",
    meaningsFr: ["longer", "suivre"],
    readingsOn: ["エン"],
    readingsKun: ["そ.う"],
    meaningMnemonicFr: "L'eau 氵 qui va par le bord 㕣 LONGE.",
    readingMnemonicFr: "EN - Longer le rivage.",
    levelId: 45,
  },
  {
    character: "泊",
    meaningsFr: ["séjourner", "mouiller"],
    readingsOn: ["ハク"],
    readingsKun: ["と.まる"],
    meaningMnemonicFr: "L'eau 氵 blanche 白 permet de SÉJOURNER.",
    readingMnemonicFr: "HAKU - La nuit à l'hôtel.",
    levelId: 42,
  },
  {
    character: "浄",
    meaningsFr: ["pur", "propre"],
    readingsOn: ["ジョウ"],
    readingsKun: ["きよ.い"],
    meaningMnemonicFr: "L'eau 氵 qui lutte 争 devient PURE.",
    readingMnemonicFr: "JŌ - La pureté de l'eau.",
    levelId: 44,
  },
  {
    character: "浜",
    meaningsFr: ["plage", "rivage"],
    readingsOn: ["ヒン"],
    readingsKun: ["はま"],
    meaningMnemonicFr: "L'eau 氵 du soldat 兵 forme la PLAGE.",
    readingMnemonicFr: "HIN - Le rivage sableux.",
    levelId: 45,
  },
  {
    character: "浦",
    meaningsFr: ["baie", "côte"],
    readingsOn: ["ホ"],
    readingsKun: ["うら"],
    meaningMnemonicFr: "L'eau 氵 avec le plat 甫 forme une BAIE.",
    readingMnemonicFr: "HO - La petite baie.",
    levelId: 47,
  },
  {
    character: "浸",
    meaningsFr: ["tremper", "imbiber"],
    readingsOn: ["シン"],
    readingsKun: ["ひた.す"],
    meaningMnemonicFr: "L'eau 氵 qui envahit 侵 TREMPE.",
    readingMnemonicFr: "SHIN - L'immersion totale.",
    levelId: 46,
  },
  {
    character: "涙",
    meaningsFr: ["larme"],
    readingsOn: ["ルイ"],
    readingsKun: ["なみだ"],
    meaningMnemonicFr: "L'eau 氵 avec le chien 戻 forme une LARME.",
    readingMnemonicFr: "RUI - Les larmes qui coulent.",
    levelId: 43,
  },
  {
    character: "涯",
    meaningsFr: ["limite", "horizon"],
    readingsOn: ["ガイ"],
    readingsKun: [],
    meaningMnemonicFr: "L'eau 氵 avec le bord 厓 forme la LIMITE.",
    readingMnemonicFr: "GAI - L'horizon lointain.",
    levelId: 47,
  },
  {
    character: "淡",
    meaningsFr: ["pâle", "fade"],
    readingsOn: ["タン"],
    readingsKun: ["あわ.い"],
    meaningMnemonicFr: "L'eau 氵 avec les flammes 炎 est PÂLE.",
    readingMnemonicFr: "TAN - La couleur fade.",
    levelId: 45,
  },
  {
    character: "添",
    meaningsFr: ["ajouter", "accompagner"],
    readingsOn: ["テン"],
    readingsKun: ["そ.える"],
    meaningMnemonicFr: "L'eau 氵 avec le ciel 天 et le cœur 心 AJOUTE.",
    readingMnemonicFr: "TEN - L'ajout délicat.",
    levelId: 46,
  },
  {
    character: "渋",
    meaningsFr: ["astringent", "amer"],
    readingsOn: ["ジュウ"],
    readingsKun: ["しぶ.い"],
    meaningMnemonicFr: "L'eau 氵 qui s'arrête 止 est ASTRINGENTE.",
    readingMnemonicFr: "JŪ - Le goût amer.",
    levelId: 47,
  },
  {
    character: "渉",
    meaningsFr: ["traverser", "négocier"],
    readingsOn: ["ショウ"],
    readingsKun: ["わた.る"],
    meaningMnemonicFr: "L'eau 氵 que les pas 歩 TRAVERSENT.",
    readingMnemonicFr: "SHŌ - La traversée négociée.",
    levelId: 46,
  },
  {
    character: "湾",
    meaningsFr: ["baie", "golfe"],
    readingsOn: ["ワン"],
    readingsKun: [],
    meaningMnemonicFr: "L'eau 氵 qui se courbe 弯 forme une BAIE.",
    readingMnemonicFr: "WAN - Le golfe naturel.",
    levelId: 45,
  },
  {
    character: "湿",
    meaningsFr: ["humide", "mouillé"],
    readingsOn: ["シツ"],
    readingsKun: ["しめ.る"],
    meaningMnemonicFr: "L'eau 氵 qui brille 顯 est HUMIDE.",
    readingMnemonicFr: "SHITSU - L'humidité de l'air.",
    levelId: 44,
  },
  {
    character: "溶",
    meaningsFr: ["fondre", "dissoudre"],
    readingsOn: ["ヨウ"],
    readingsKun: ["と.ける", "と.かす"],
    meaningMnemonicFr: "L'eau 氵 avec la vallée 谷 FOND.",
    readingMnemonicFr: "YŌ - La dissolution complète.",
    levelId: 45,
  },
  {
    character: "滅",
    meaningsFr: ["détruire", "éteindre"],
    readingsOn: ["メツ"],
    readingsKun: ["ほろ.びる", "ほろ.ぼす"],
    meaningMnemonicFr: "L'eau 氵 avec le feu 火 et l'arme 戈 DÉTRUIT.",
    readingMnemonicFr: "METSU - La destruction totale.",
    levelId: 46,
  },
  {
    character: "滑",
    meaningsFr: ["glisser", "lisse"],
    readingsOn: ["カツ", "コツ"],
    readingsKun: ["すべ.る", "なめ.らか"],
    meaningMnemonicFr: "L'eau 氵 de l'os 骨 GLISSE.",
    readingMnemonicFr: "KATSU - Le glissement doux.",
    levelId: 44,
  },
  {
    character: "滴",
    meaningsFr: ["goutte", "tomber"],
    readingsOn: ["テキ"],
    readingsKun: ["しずく", "したた.る"],
    meaningMnemonicFr: "L'eau 氵 de l'ennemi 啇 forme une GOUTTE.",
    readingMnemonicFr: "TEKI - La goutte qui tombe.",
    levelId: 47,
  },
  {
    character: "漂",
    meaningsFr: ["flotter", "dériver"],
    readingsOn: ["ヒョウ"],
    readingsKun: ["ただよ.う"],
    meaningMnemonicFr: "L'eau 氵 avec le signe 票 FLOTTE.",
    readingMnemonicFr: "HYŌ - La dérive sur l'eau.",
    levelId: 48,
  },
  {
    character: "漠",
    meaningsFr: ["vague", "désert"],
    readingsOn: ["バク"],
    readingsKun: [],
    meaningMnemonicFr: "L'eau 氵 du soir 莫 est VAGUE.",
    readingMnemonicFr: "BAKU - L'immensité désertique.",
    levelId: 47,
  },
  {
    character: "漫",
    meaningsFr: ["libre", "manga"],
    readingsOn: ["マン"],
    readingsKun: [],
    meaningMnemonicFr: "L'eau 氵 qui coule 曼 est LIBRE.",
    readingMnemonicFr: "MAN - La liberté créative.",
    levelId: 45,
  },
  {
    character: "潜",
    meaningsFr: ["plonger", "cacher"],
    readingsOn: ["セン"],
    readingsKun: ["ひそ.む", "もぐ.る"],
    meaningMnemonicFr: "L'eau 氵 qui remplace 替 PLONGE.",
    readingMnemonicFr: "SEN - La plongée secrète.",
    levelId: 46,
  },
  {
    character: "澄",
    meaningsFr: ["clair", "limpide"],
    readingsOn: ["チョウ"],
    readingsKun: ["す.む"],
    meaningMnemonicFr: "L'eau 氵 qui monte 登 est LIMPIDE.",
    readingMnemonicFr: "CHŌ - La clarté de l'eau.",
    levelId: 47,
  },
  {
    character: "濁",
    meaningsFr: ["trouble", "impur"],
    readingsOn: ["ダク"],
    readingsKun: ["にご.る"],
    meaningMnemonicFr: "L'eau 氵 avec l'insecte 蜀 est TROUBLE.",
    readingMnemonicFr: "DAKU - L'eau impure.",
    levelId: 48,
  },
  {
    character: "濃",
    meaningsFr: ["épais", "concentré"],
    readingsOn: ["ノウ"],
    readingsKun: ["こ.い"],
    meaningMnemonicFr: "L'eau 氵 de l'agriculture 農 est ÉPAISSE.",
    readingMnemonicFr: "NŌ - La concentration dense.",
    levelId: 46,
  },
  {
    character: "濫",
    meaningsFr: ["déborder", "excessif"],
    readingsOn: ["ラン"],
    readingsKun: ["みだ.りに"],
    meaningMnemonicFr: "L'eau 氵 qui surveille 監 DÉBORDE.",
    readingMnemonicFr: "RAN - L'excès incontrôlé.",
    levelId: 49,
  },
  {
    character: "瀬",
    meaningsFr: ["rapides", "gué"],
    readingsOn: ["ライ"],
    readingsKun: ["せ"],
    meaningMnemonicFr: "L'eau 氵 qui s'appuie 頼 forme des RAPIDES.",
    readingMnemonicFr: "RAI - Les rapides dangereux.",
    levelId: 48,
  },
  {
    character: "炊",
    meaningsFr: ["cuire", "cuisiner"],
    readingsOn: ["スイ"],
    readingsKun: ["た.く"],
    meaningMnemonicFr: "Le feu 火 qui manque 欠 pour CUIRE.",
    readingMnemonicFr: "SUI - La cuisson du riz.",
    levelId: 43,
  },
  {
    character: "炉",
    meaningsFr: ["four", "fourneau"],
    readingsOn: ["ロ"],
    readingsKun: [],
    meaningMnemonicFr: "Le feu 火 de la porte 戸 est un FOUR.",
    readingMnemonicFr: "RO - Le fourneau ardent.",
    levelId: 45,
  },
  {
    character: "焦",
    meaningsFr: ["brûler", "hâte"],
    readingsOn: ["ショウ"],
    readingsKun: ["こ.げる", "あせ.る"],
    meaningMnemonicFr: "L'oiseau 隹 sur le feu 灬 BRÛLE.",
    readingMnemonicFr: "SHŌ - La hâte qui brûle.",
    levelId: 44,
  },
  {
    character: "煙",
    meaningsFr: ["fumée"],
    readingsOn: ["エン"],
    readingsKun: ["けむり", "けむ.る"],
    meaningMnemonicFr: "Le feu 火 qui dit 西土 fait de la FUMÉE.",
    readingMnemonicFr: "EN - La fumée qui s'élève.",
    levelId: 43,
  },
  {
    character: "燃",
    meaningsFr: ["brûler", "flamber"],
    readingsOn: ["ネン"],
    readingsKun: ["も.える", "も.やす"],
    meaningMnemonicFr: "Le feu 火 naturel 然 BRÛLE.",
    readingMnemonicFr: "NEN - La combustion vive.",
    levelId: 42,
  },
  {
    character: "爆",
    meaningsFr: ["exploser"],
    readingsOn: ["バク"],
    readingsKun: [],
    meaningMnemonicFr: "Le feu 火 violent 暴 EXPLOSE.",
    readingMnemonicFr: "BAKU - L'explosion soudaine.",
    levelId: 44,
  },
  {
    character: "牲",
    meaningsFr: ["sacrifice", "victime"],
    readingsOn: ["セイ"],
    readingsKun: [],
    meaningMnemonicFr: "La vache 牛 qui naît 生 est un SACRIFICE.",
    readingMnemonicFr: "SEI - Le sacrifice rituel.",
    levelId: 46,
  },
  {
    character: "犠",
    meaningsFr: ["sacrifice", "victime"],
    readingsOn: ["ギ"],
    readingsKun: [],
    meaningMnemonicFr: "La vache 牛 avec la justice 義 est un SACRIFICE.",
    readingMnemonicFr: "GI - La victime sacrifiée.",
    levelId: 47,
  },
  {
    character: "獣",
    meaningsFr: ["bête", "animal sauvage"],
    readingsOn: ["ジュウ"],
    readingsKun: ["けもの"],
    meaningMnemonicFr: "Le chien 犬 avec la bouche 口 et les traits est une BÊTE.",
    readingMnemonicFr: "JŪ - L'animal sauvage.",
    levelId: 45,
  },
  {
    character: "獲",
    meaningsFr: ["capturer", "obtenir"],
    readingsOn: ["カク"],
    readingsKun: ["え.る"],
    meaningMnemonicFr: "Le chien 犬 qui protège 蒦 CAPTURE.",
    readingMnemonicFr: "KAKU - La capture réussie.",
    levelId: 46,
  },
  {
    character: "玄",
    meaningsFr: ["mystère", "noir"],
    readingsOn: ["ゲン"],
    readingsKun: [],
    meaningMnemonicFr: "Le toit 亠 avec les fils 幺 cache le MYSTÈRE.",
    readingMnemonicFr: "GEN - Le noir mystérieux.",
    levelId: 45,
  },
  {
    character: "珠",
    meaningsFr: ["perle"],
    readingsOn: ["シュ"],
    readingsKun: ["たま"],
    meaningMnemonicFr: "Le jade 王 vermillon 朱 est une PERLE.",
    readingMnemonicFr: "SHU - La perle précieuse.",
    levelId: 44,
  },
  {
    character: "琴",
    meaningsFr: ["koto", "cithare"],
    readingsOn: ["キン", "ゴン"],
    readingsKun: ["こと"],
    meaningMnemonicFr: "Le jade 王 qui résonne 今 est le KOTO.",
    readingMnemonicFr: "KIN - L'instrument japonais.",
    levelId: 46,
  },
  {
    character: "瓶",
    meaningsFr: ["bouteille", "vase"],
    readingsOn: ["ビン"],
    readingsKun: [],
    meaningMnemonicFr: "Le vase 瓦 avec le parallèle 并 est une BOUTEILLE.",
    readingMnemonicFr: "BIN - La bouteille en verre.",
    levelId: 47,
  },
  {
    character: "甘",
    meaningsFr: ["sucré", "doux"],
    readingsOn: ["カン"],
    readingsKun: ["あま.い"],
    meaningMnemonicFr: "Le signe qui ferme la bouche savoure le SUCRÉ.",
    readingMnemonicFr: "KAN - La douceur sucrée.",
    levelId: 41,
  },
  {
    character: "畔",
    meaningsFr: ["bord", "rive"],
    readingsOn: ["ハン"],
    readingsKun: ["あぜ"],
    meaningMnemonicFr: "Le champ 田 à moitié 半 est le BORD.",
    readingMnemonicFr: "HAN - Le bord du champ.",
    levelId: 49,
  },
  {
    character: "畝",
    meaningsFr: ["sillon", "crête"],
    readingsOn: ["ボウ"],
    readingsKun: ["うね"],
    meaningMnemonicFr: "Le champ 田 qui tourne 久 forme un SILLON.",
    readingMnemonicFr: "BŌ - Les sillons du champ.",
    levelId: 50,
  },
  {
    character: "疫",
    meaningsFr: ["épidémie", "peste"],
    readingsOn: ["エキ"],
    readingsKun: [],
    meaningMnemonicFr: "La maladie 疒 qui frappe 殳 est une ÉPIDÉMIE.",
    readingMnemonicFr: "EKI - L'épidémie dangereuse.",
    levelId: 46,
  },
  {
    character: "症",
    meaningsFr: ["symptôme", "maladie"],
    readingsOn: ["ショウ"],
    readingsKun: [],
    meaningMnemonicFr: "La maladie 疒 qui prouve 正 un SYMPTÔME.",
    readingMnemonicFr: "SHŌ - Le symptôme révélateur.",
    levelId: 44,
  },
  {
    character: "盆",
    meaningsFr: ["plateau", "bassin"],
    readingsOn: ["ボン"],
    readingsKun: [],
    meaningMnemonicFr: "La division 分 du plat 皿 est un PLATEAU.",
    readingMnemonicFr: "BON - Le plateau de service.",
    levelId: 45,
  },
  {
    character: "盗",
    meaningsFr: ["voler", "dérober"],
    readingsOn: ["トウ"],
    readingsKun: ["ぬす.む"],
    meaningMnemonicFr: "Les yeux 欠 sur le plat 皿 VOLENT.",
    readingMnemonicFr: "TŌ - Le vol discret.",
    levelId: 43,
  },
  {
    character: "盛",
    meaningsFr: ["prospère", "servir"],
    readingsOn: ["セイ", "ジョウ"],
    readingsKun: ["も.る", "さか.る"],
    meaningMnemonicFr: "Le fait 成 de remplir le plat 皿 est PROSPÈRE.",
    readingMnemonicFr: "SEI - La prospérité abondante.",
    levelId: 44,
  },
  {
    character: "盟",
    meaningsFr: ["alliance", "serment"],
    readingsOn: ["メイ"],
    readingsKun: [],
    meaningMnemonicFr: "Le clair 明 du plat 皿 scelle l'ALLIANCE.",
    readingMnemonicFr: "MEI - L'alliance jurée.",
    levelId: 46,
  },
  {
    character: "督",
    meaningsFr: ["surveiller", "diriger"],
    readingsOn: ["トク"],
    readingsKun: [],
    meaningMnemonicFr: "Le haut 叔 de l'œil 目 SURVEILLE.",
    readingMnemonicFr: "TOKU - La surveillance attentive.",
    levelId: 47,
  },
  {
    character: "睡",
    meaningsFr: ["sommeil", "dormir"],
    readingsOn: ["スイ"],
    readingsKun: [],
    meaningMnemonicFr: "L'œil 目 qui pend 垂 dort - SOMMEIL.",
    readingMnemonicFr: "SUI - Le sommeil profond.",
    levelId: 44,
  },
  {
    character: "矛",
    meaningsFr: ["lance", "contradiction"],
    readingsOn: ["ム", "ボウ"],
    readingsKun: ["ほこ"],
    meaningMnemonicFr: "L'arme pointue est une LANCE.",
    readingMnemonicFr: "MU - La lance du guerrier.",
    levelId: 46,
  },
  {
    character: "砲",
    meaningsFr: ["canon", "artillerie"],
    readingsOn: ["ホウ"],
    readingsKun: [],
    meaningMnemonicFr: "La pierre 石 qui enveloppe 包 est un CANON.",
    readingMnemonicFr: "HŌ - Le canon de guerre.",
    levelId: 45,
  },
  {
    character: "硬",
    meaningsFr: ["dur", "rigide"],
    readingsOn: ["コウ"],
    readingsKun: ["かた.い"],
    meaningMnemonicFr: "La pierre 石 qui change 更 est DURE.",
    readingMnemonicFr: "KŌ - La rigidité de la pierre.",
    levelId: 44,
  },
  {
    character: "碁",
    meaningsFr: ["go", "jeu de go"],
    readingsOn: ["ゴ"],
    readingsKun: [],
    meaningMnemonicFr: "La pierre 石 sur la base 其 sert au GO.",
    readingMnemonicFr: "GO - Le jeu de stratégie.",
    levelId: 48,
  },
  {
    character: "磁",
    meaningsFr: ["aimant", "porcelaine"],
    readingsOn: ["ジ"],
    readingsKun: [],
    meaningMnemonicFr: "La pierre 石 qui nourrit 兹 est un AIMANT.",
    readingMnemonicFr: "JI - L'aimant magnétique.",
    levelId: 45,
  },
  {
    character: "礁",
    meaningsFr: ["récif"],
    readingsOn: ["ショウ"],
    readingsKun: [],
    meaningMnemonicFr: "La pierre 石 qui brûle 焦 forme un RÉCIF.",
    readingMnemonicFr: "SHŌ - Le récif dangereux.",
    levelId: 49,
  },
  {
    character: "祥",
    meaningsFr: ["bon augure", "félicité"],
    readingsOn: ["ショウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le dieu 礻 du mouton 羊 est de BON AUGURE.",
    readingMnemonicFr: "SHŌ - La félicité divine.",
    levelId: 47,
  },
  {
    character: "禅",
    meaningsFr: ["zen", "méditation"],
    readingsOn: ["ゼン"],
    readingsKun: [],
    meaningMnemonicFr: "Le dieu 礻 avec le simple 単 est le ZEN.",
    readingMnemonicFr: "ZEN - La méditation profonde.",
    levelId: 46,
  },
  {
    character: "秀",
    meaningsFr: ["excellent", "surpasser"],
    readingsOn: ["シュウ"],
    readingsKun: ["ひい.でる"],
    meaningMnemonicFr: "Le grain 禾 qui s'élève 乃 est EXCELLENT.",
    readingMnemonicFr: "SHŪ - L'excellence reconnue.",
    levelId: 44,
  },
  {
    character: "秩",
    meaningsFr: ["ordre", "rang"],
    readingsOn: ["チツ"],
    readingsKun: [],
    meaningMnemonicFr: "Le grain 禾 qui manque 失 a besoin d'ORDRE.",
    readingMnemonicFr: "CHITSU - L'ordre établi.",
    levelId: 46,
  },
  {
    character: "称",
    meaningsFr: ["appeler", "titre"],
    readingsOn: ["ショウ"],
    readingsKun: ["たた.える"],
    meaningMnemonicFr: "Le grain 禾 qu'on appelle 尔 a un TITRE.",
    readingMnemonicFr: "SHŌ - Le titre honorifique.",
    levelId: 45,
  },
  {
    character: "稚",
    meaningsFr: ["jeune", "enfantin"],
    readingsOn: ["チ"],
    readingsKun: [],
    meaningMnemonicFr: "Le grain 禾 de l'oiseau 隹 est JEUNE.",
    readingMnemonicFr: "CHI - La jeunesse innocente.",
    levelId: 48,
  },
  {
    character: "穏",
    meaningsFr: ["calme", "paisible"],
    readingsOn: ["オン"],
    readingsKun: ["おだ.やか"],
    meaningMnemonicFr: "Le grain 禾 urgent 急 devient CALME sous le cœur 心.",
    readingMnemonicFr: "ON - La paix tranquille.",
    levelId: 47,
  },
];

async function main() {
  console.log("Seeding THE FINAL kanji batch 10 to exceed 2000...");

  for (const kanji of kanjiData) {
    await prisma.kanji.upsert({
      where: { character: kanji.character },
      update: {
        meaningsFr: kanji.meaningsFr,
        readingsOn: kanji.readingsOn,
        readingsKun: kanji.readingsKun,
        meaningMnemonicFr: kanji.meaningMnemonicFr,
        readingMnemonicFr: kanji.readingMnemonicFr,
        levelId: kanji.levelId,
      },
      create: kanji,
    });
  }

  console.log(`Seeded ${kanjiData.length} kanji.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
