import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Final kanji batch 9 - The LAST batch to exceed 2000 kanji
// Need ~80 more unique kanji

const kanjiData = [
  // Common useful kanji
  {
    character: "垂",
    meaningsFr: ["pendre", "tomber"],
    readingsOn: ["スイ"],
    readingsKun: ["た.れる", "た.らす"],
    meaningMnemonicFr: "La ligne qui descend représente quelque chose qui PEND.",
    readingMnemonicFr: "SUI - La chute verticale.",
    levelId: 43,
  },
  {
    character: "寡",
    meaningsFr: ["peu nombreux", "veuve"],
    readingsOn: ["カ"],
    readingsKun: [],
    meaningMnemonicFr: "Le toit 宀 avec peu 頁 représente le PEU NOMBREUX.",
    readingMnemonicFr: "KA - La rareté.",
    levelId: 50,
  },
  {
    character: "寧",
    meaningsFr: ["tranquille", "plutôt"],
    readingsOn: ["ネイ"],
    readingsKun: ["むし.ろ"],
    meaningMnemonicFr: "Le toit 宀 avec le cœur 心 et la table 丁 est TRANQUILLE.",
    readingMnemonicFr: "NEI - La tranquillité d'esprit.",
    levelId: 47,
  },
  {
    character: "寮",
    meaningsFr: ["dortoir", "résidence"],
    readingsOn: ["リョウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le toit 宀 pour les fonctionnaires 僚 est un DORTOIR.",
    readingMnemonicFr: "RYŌ - Le dortoir étudiant.",
    levelId: 46,
  },
  {
    character: "尉",
    meaningsFr: ["lieutenant", "réconforter"],
    readingsOn: ["イ"],
    readingsKun: [],
    meaningMnemonicFr: "Le corps 尸 avec le feu 火 et des mains 寸 est le LIEUTENANT.",
    readingMnemonicFr: "I - Le grade militaire.",
    levelId: 49,
  },
  {
    character: "尋",
    meaningsFr: ["chercher", "demander"],
    readingsOn: ["ジン"],
    readingsKun: ["たず.ねる"],
    meaningMnemonicFr: "Les mains 彐 qui travaillent 工 avec la bouche 口 et les mains 寸 CHERCHENT.",
    readingMnemonicFr: "JIN - La recherche active.",
    levelId: 45,
  },
  {
    character: "尚",
    meaningsFr: ["encore", "respecter"],
    readingsOn: ["ショウ"],
    readingsKun: ["なお"],
    meaningMnemonicFr: "Le petit 小 avec la bouche 冂口 signifie ENCORE.",
    readingMnemonicFr: "SHŌ - Le respect continu.",
    levelId: 44,
  },
  {
    character: "屈",
    meaningsFr: ["plier", "soumettre"],
    readingsOn: ["クツ"],
    readingsKun: ["かが.む"],
    meaningMnemonicFr: "Le corps 尸 qui sort 出 se PLIE.",
    readingMnemonicFr: "KUTSU - La soumission forcée.",
    levelId: 46,
  },
  {
    character: "峰",
    meaningsFr: ["pic", "sommet"],
    readingsOn: ["ホウ"],
    readingsKun: ["みね"],
    meaningMnemonicFr: "La montagne 山 qui rencontre 夆 le ciel est un PIC.",
    readingMnemonicFr: "HŌ - Le sommet de la montagne.",
    levelId: 45,
  },
  {
    character: "巡",
    meaningsFr: ["faire le tour", "patrouiller"],
    readingsOn: ["ジュン"],
    readingsKun: ["めぐ.る"],
    meaningMnemonicFr: "Marcher 辶 avec le fleuve 巛 pour FAIRE LE TOUR.",
    readingMnemonicFr: "JUN - La patrouille régulière.",
    levelId: 44,
  },
  {
    character: "帆",
    meaningsFr: ["voile"],
    readingsOn: ["ハン"],
    readingsKun: ["ほ"],
    meaningMnemonicFr: "Le tissu 巾 qui prend le vent 凡 est une VOILE.",
    readingMnemonicFr: "HAN - La voile du bateau.",
    levelId: 43,
  },
  {
    character: "帥",
    meaningsFr: ["commandant", "général"],
    readingsOn: ["スイ"],
    readingsKun: [],
    meaningMnemonicFr: "Le tissu 巾 qui coupe 帀 est le COMMANDANT.",
    readingMnemonicFr: "SUI - Le général en chef.",
    levelId: 48,
  },
  {
    character: "幅",
    meaningsFr: ["largeur", "ampleur"],
    readingsOn: ["フク"],
    readingsKun: ["はば"],
    meaningMnemonicFr: "Le tissu 巾 avec la richesse 畐 a de la LARGEUR.",
    readingMnemonicFr: "FUKU - La largeur du tissu.",
    levelId: 44,
  },
  {
    character: "幣",
    meaningsFr: ["monnaie", "offrande"],
    readingsOn: ["ヘイ"],
    readingsKun: [],
    meaningMnemonicFr: "Le tissu 巾 qui se divise 敝 est la MONNAIE.",
    readingMnemonicFr: "HEI - La monnaie d'échange.",
    levelId: 47,
  },
  {
    character: "幽",
    meaningsFr: ["sombre", "fantôme"],
    readingsOn: ["ユウ"],
    readingsKun: [],
    meaningMnemonicFr: "La montagne 山 avec les fils 幺幺 est SOMBRE.",
    readingMnemonicFr: "YŪ - L'obscurité mystérieuse.",
    levelId: 48,
  },
  {
    character: "庶",
    meaningsFr: ["commun", "peuple"],
    readingsOn: ["ショ"],
    readingsKun: [],
    meaningMnemonicFr: "Le bâtiment 广 avec le feu 灬 abrite le PEUPLE.",
    readingMnemonicFr: "SHO - Le peuple commun.",
    levelId: 49,
  },
  {
    character: "弊",
    meaningsFr: ["abus", "défaut"],
    readingsOn: ["ヘイ"],
    readingsKun: [],
    meaningMnemonicFr: "Le tissu 敝 abîmé est un ABUS.",
    readingMnemonicFr: "HEI - Le défaut du système.",
    levelId: 50,
  },
  {
    character: "弔",
    meaningsFr: ["condoléances", "deuil"],
    readingsOn: ["チョウ"],
    readingsKun: ["とむら.う"],
    meaningMnemonicFr: "L'arc 弓 qui touche le sol offre les CONDOLÉANCES.",
    readingMnemonicFr: "CHŌ - Les funérailles.",
    levelId: 46,
  },
  {
    character: "弦",
    meaningsFr: ["corde", "arc"],
    readingsOn: ["ゲン"],
    readingsKun: ["つる"],
    meaningMnemonicFr: "L'arc 弓 avec la lune 玄 a une CORDE.",
    readingMnemonicFr: "GEN - La corde de l'instrument.",
    levelId: 45,
  },
  {
    character: "彩",
    meaningsFr: ["couleur", "coloré"],
    readingsOn: ["サイ"],
    readingsKun: ["いろど.る"],
    meaningMnemonicFr: "La cueillette 采 avec les poils 彡 crée la COULEUR.",
    readingMnemonicFr: "SAI - Les couleurs vives.",
    levelId: 43,
  },
  {
    character: "彫",
    meaningsFr: ["sculpter", "graver"],
    readingsOn: ["チョウ"],
    readingsKun: ["ほ.る"],
    meaningMnemonicFr: "La semaine 周 avec les poils 彡 SCULPTE.",
    readingMnemonicFr: "CHŌ - La sculpture fine.",
    levelId: 46,
  },
  {
    character: "徐",
    meaningsFr: ["lent", "doucement"],
    readingsOn: ["ジョ"],
    readingsKun: ["おもむ.ろに"],
    meaningMnemonicFr: "Marcher 彳 avec le reste 余 va LENTEMENT.",
    readingMnemonicFr: "JO - Le mouvement lent.",
    levelId: 47,
  },
  {
    character: "徴",
    meaningsFr: ["signe", "collecter"],
    readingsOn: ["チョウ"],
    readingsKun: ["しるし"],
    meaningMnemonicFr: "Marcher 彳 avec la montagne 山 et le roi 王 pour COLLECTER un SIGNE.",
    readingMnemonicFr: "CHŌ - Le signe distinctif.",
    levelId: 45,
  },
  {
    character: "忌",
    meaningsFr: ["éviter", "tabou"],
    readingsOn: ["キ"],
    readingsKun: ["い.む"],
    meaningMnemonicFr: "Soi-même 己 avec le cœur 心 forme le TABOU.",
    readingMnemonicFr: "KI - Ce qu'il faut éviter.",
    levelId: 47,
  },
  {
    character: "怒",
    meaningsFr: ["colère", "se fâcher"],
    readingsOn: ["ド"],
    readingsKun: ["いか.る", "おこ.る"],
    meaningMnemonicFr: "L'esclave 奴 avec le cœur 心 ressent la COLÈRE.",
    readingMnemonicFr: "DO - La colère intense.",
    levelId: 42,
  },
  {
    character: "恐",
    meaningsFr: ["crainte", "peur"],
    readingsOn: ["キョウ"],
    readingsKun: ["おそ.れる", "こわ.い"],
    meaningMnemonicFr: "Le travail 工 avec le cœur 心 et les mains 凡 crée la PEUR.",
    readingMnemonicFr: "KYŌ - La crainte profonde.",
    levelId: 42,
  },
  {
    character: "恥",
    meaningsFr: ["honte"],
    readingsOn: ["チ"],
    readingsKun: ["は.じる", "はずかし.い"],
    meaningMnemonicFr: "L'oreille 耳 avec le cœur 心 ressent la HONTE.",
    readingMnemonicFr: "CHI - La honte qui rougit.",
    levelId: 43,
  },
  {
    character: "恵",
    meaningsFr: ["faveur", "bénédiction"],
    readingsOn: ["ケイ", "エ"],
    readingsKun: ["めぐ.む"],
    meaningMnemonicFr: "Le dix 十 avec le champ 田 et le cœur 心 donne la FAVEUR.",
    readingMnemonicFr: "KEI - La bénédiction reçue.",
    levelId: 44,
  },
  {
    character: "悠",
    meaningsFr: ["lointain", "éternel"],
    readingsOn: ["ユウ"],
    readingsKun: [],
    meaningMnemonicFr: "La personne 亻 avec la tête 攸 et le cœur 心 est ÉTERNELLE.",
    readingMnemonicFr: "YŪ - L'éternité paisible.",
    levelId: 48,
  },
  {
    character: "患",
    meaningsFr: ["maladie", "souffrir"],
    readingsOn: ["カン"],
    readingsKun: ["わずら.う"],
    meaningMnemonicFr: "La chaîne 串 avec le cœur 心 cause la MALADIE.",
    readingMnemonicFr: "KAN - La souffrance de la maladie.",
    levelId: 46,
  },
  {
    character: "悩",
    meaningsFr: ["souci", "problème"],
    readingsOn: ["ノウ"],
    readingsKun: ["なや.む"],
    meaningMnemonicFr: "Le cœur 忄 avec le cerveau 悩 a des SOUCIS.",
    readingMnemonicFr: "NŌ - Les problèmes qui tourmentent.",
    levelId: 44,
  },
  {
    character: "戒",
    meaningsFr: ["avertir", "commandement"],
    readingsOn: ["カイ"],
    readingsKun: ["いまし.める"],
    meaningMnemonicFr: "Les deux mains 廾 avec l'arme 戈 AVERTISSENT.",
    readingMnemonicFr: "KAI - L'avertissement sérieux.",
    levelId: 45,
  },
  {
    character: "戯",
    meaningsFr: ["jouer", "plaisanter"],
    readingsOn: ["ギ", "ゲ"],
    readingsKun: ["たわむ.れる"],
    meaningMnemonicFr: "L'arme factice 虚 avec l'arme 戈 sert à JOUER.",
    readingMnemonicFr: "GI - Le jeu amusant.",
    levelId: 48,
  },
  {
    character: "扇",
    meaningsFr: ["éventail"],
    readingsOn: ["セン"],
    readingsKun: ["おうぎ"],
    meaningMnemonicFr: "La porte 戸 avec les plumes 羽 forme un ÉVENTAIL.",
    readingMnemonicFr: "SEN - L'éventail traditionnel.",
    levelId: 46,
  },
  {
    character: "扉",
    meaningsFr: ["porte", "battant"],
    readingsOn: ["ヒ"],
    readingsKun: ["とびら"],
    meaningMnemonicFr: "La porte 戸 qui n'est pas 非 ouverte est une PORTE.",
    readingMnemonicFr: "HI - La porte qui s'ouvre.",
    levelId: 47,
  },
  {
    character: "抑",
    meaningsFr: ["réprimer", "contrôler"],
    readingsOn: ["ヨク"],
    readingsKun: ["おさ.える"],
    meaningMnemonicFr: "La main 扌 qui se courbe 卬 RÉPRIME.",
    readingMnemonicFr: "YOKU - Le contrôle des émotions.",
    levelId: 45,
  },
  {
    character: "抗",
    meaningsFr: ["résister", "s'opposer"],
    readingsOn: ["コウ"],
    readingsKun: ["あらが.う"],
    meaningMnemonicFr: "La main 扌 contre le haut 亢 RÉSISTE.",
    readingMnemonicFr: "KŌ - La résistance active.",
    levelId: 44,
  },
  {
    character: "択",
    meaningsFr: ["choisir", "sélectionner"],
    readingsOn: ["タク"],
    readingsKun: ["えら.ぶ"],
    meaningMnemonicFr: "La main 扌 qui libère 尺 CHOISIT.",
    readingMnemonicFr: "TAKU - Le choix délibéré.",
    levelId: 43,
  },
  {
    character: "拒",
    meaningsFr: ["refuser", "rejeter"],
    readingsOn: ["キョ"],
    readingsKun: ["こば.む"],
    meaningMnemonicFr: "La main 扌 qui est grande 巨 REFUSE.",
    readingMnemonicFr: "KYO - Le refus catégorique.",
    levelId: 44,
  },
  {
    character: "拠",
    meaningsFr: ["base", "s'appuyer"],
    readingsOn: ["キョ", "コ"],
    readingsKun: ["よ.る"],
    meaningMnemonicFr: "La main 扌 avec le cochon 処 forme une BASE.",
    readingMnemonicFr: "KYO - Le point d'appui.",
    levelId: 45,
  },
  {
    character: "拡",
    meaningsFr: ["étendre", "élargir"],
    readingsOn: ["カク"],
    readingsKun: ["ひろ.がる", "ひろ.げる"],
    meaningMnemonicFr: "La main 扌 avec le large 広 ÉTEND.",
    readingMnemonicFr: "KAKU - L'expansion progressive.",
    levelId: 43,
  },
  {
    character: "拝",
    meaningsFr: ["prier", "vénérer"],
    readingsOn: ["ハイ"],
    readingsKun: ["おが.む"],
    meaningMnemonicFr: "La main 扌 qui salue 手 PRIE.",
    readingMnemonicFr: "HAI - La prière respectueuse.",
    levelId: 42,
  },
  {
    character: "拾",
    meaningsFr: ["ramasser", "dix"],
    readingsOn: ["シュウ", "ジュウ"],
    readingsKun: ["ひろ.う"],
    meaningMnemonicFr: "La main 扌 qui réunit 合 RAMASSE.",
    readingMnemonicFr: "SHŪ - Ramasser par terre.",
    levelId: 41,
  },
  {
    character: "挑",
    meaningsFr: ["défier", "provoquer"],
    readingsOn: ["チョウ"],
    readingsKun: ["いど.む"],
    meaningMnemonicFr: "La main 扌 qui saute 兆 DÉFIE.",
    readingMnemonicFr: "CHŌ - Le défi lancé.",
    levelId: 45,
  },
  {
    character: "挙",
    meaningsFr: ["lever", "élever"],
    readingsOn: ["キョ"],
    readingsKun: ["あ.げる", "あ.がる"],
    meaningMnemonicFr: "Le joint 与 avec les mains 手 LÈVE.",
    readingMnemonicFr: "KYO - L'élévation de la main.",
    levelId: 43,
  },
  {
    character: "捕",
    meaningsFr: ["attraper", "capturer"],
    readingsOn: ["ホ"],
    readingsKun: ["つか.まえる", "と.らえる"],
    meaningMnemonicFr: "La main 扌 avec le plat 甫 ATTRAPE.",
    readingMnemonicFr: "HO - La capture réussie.",
    levelId: 42,
  },
  {
    character: "捨",
    meaningsFr: ["jeter", "abandonner"],
    readingsOn: ["シャ"],
    readingsKun: ["す.てる"],
    meaningMnemonicFr: "La main 扌 avec la maison 舎 JETTE.",
    readingMnemonicFr: "SHA - L'abandon définitif.",
    levelId: 43,
  },
  {
    character: "掃",
    meaningsFr: ["balayer", "nettoyer"],
    readingsOn: ["ソウ"],
    readingsKun: ["は.く"],
    meaningMnemonicFr: "La main 扌 avec le balai 帚 BALAIE.",
    readingMnemonicFr: "SŌ - Le nettoyage complet.",
    levelId: 42,
  },
  {
    character: "掌",
    meaningsFr: ["paume", "maîtriser"],
    readingsOn: ["ショウ"],
    readingsKun: ["てのひら"],
    meaningMnemonicFr: "Le haut 尚 avec la main 手 forme la PAUME.",
    readingMnemonicFr: "SHŌ - La paume de la main.",
    levelId: 46,
  },
  {
    character: "排",
    meaningsFr: ["rejeter", "exclure"],
    readingsOn: ["ハイ"],
    readingsKun: [],
    meaningMnemonicFr: "La main 扌 qui n'est pas 非 d'accord REJETTE.",
    readingMnemonicFr: "HAI - L'exclusion forcée.",
    levelId: 45,
  },
  {
    character: "掘",
    meaningsFr: ["creuser", "fouiller"],
    readingsOn: ["クツ"],
    readingsKun: ["ほ.る"],
    meaningMnemonicFr: "La main 扌 qui se plie 屈 CREUSE.",
    readingMnemonicFr: "KUTSU - Le creusement profond.",
    levelId: 44,
  },
  {
    character: "探",
    meaningsFr: ["chercher", "explorer"],
    readingsOn: ["タン"],
    readingsKun: ["さぐ.る", "さが.す"],
    meaningMnemonicFr: "La main 扌 avec la profondeur 深 EXPLORE.",
    readingMnemonicFr: "TAN - L'exploration attentive.",
    levelId: 43,
  },
  {
    character: "控",
    meaningsFr: ["retenir", "noter"],
    readingsOn: ["コウ"],
    readingsKun: ["ひか.える"],
    meaningMnemonicFr: "La main 扌 qui est vide 空 SE RETIENT.",
    readingMnemonicFr: "KŌ - La retenue prudente.",
    levelId: 45,
  },
  {
    character: "推",
    meaningsFr: ["pousser", "recommander"],
    readingsOn: ["スイ"],
    readingsKun: ["お.す"],
    meaningMnemonicFr: "La main 扌 de l'oiseau 隹 POUSSE.",
    readingMnemonicFr: "SUI - La recommandation active.",
    levelId: 43,
  },
  {
    character: "措",
    meaningsFr: ["mesure", "disposition"],
    readingsOn: ["ソ"],
    readingsKun: [],
    meaningMnemonicFr: "La main 扌 qui place 昔 prend des MESURES.",
    readingMnemonicFr: "SO - La disposition prise.",
    levelId: 46,
  },
  {
    character: "揚",
    meaningsFr: ["élever", "frire"],
    readingsOn: ["ヨウ"],
    readingsKun: ["あ.げる"],
    meaningMnemonicFr: "La main 扌 avec le soleil 昜 ÉLÈVE.",
    readingMnemonicFr: "YŌ - L'élévation joyeuse.",
    levelId: 45,
  },
  {
    character: "援",
    meaningsFr: ["aide", "assistance"],
    readingsOn: ["エン"],
    readingsKun: [],
    meaningMnemonicFr: "La main 扌 avec l'ami 爰 offre l'AIDE.",
    readingMnemonicFr: "EN - L'assistance précieuse.",
    levelId: 44,
  },
  {
    character: "損",
    meaningsFr: ["perte", "dommage"],
    readingsOn: ["ソン"],
    readingsKun: ["そこ.なう"],
    meaningMnemonicFr: "La main 扌 avec le membre 員 cause une PERTE.",
    readingMnemonicFr: "SON - Le dommage subi.",
    levelId: 43,
  },
  {
    character: "搭",
    meaningsFr: ["monter", "embarquer"],
    readingsOn: ["トウ"],
    readingsKun: [],
    meaningMnemonicFr: "La main 扌 avec la tour 荅 EMBARQUE.",
    readingMnemonicFr: "TŌ - L'embarquement à bord.",
    levelId: 47,
  },
  {
    character: "携",
    meaningsFr: ["porter", "transporter"],
    readingsOn: ["ケイ"],
    readingsKun: ["たずさ.える"],
    meaningMnemonicFr: "La main 扌 avec l'oiseau 隹 PORTE.",
    readingMnemonicFr: "KEI - Porter avec soi.",
    levelId: 46,
  },
  {
    character: "摘",
    meaningsFr: ["cueillir", "pincer"],
    readingsOn: ["テキ"],
    readingsKun: ["つ.む"],
    meaningMnemonicFr: "La main 扌 avec l'ennemi 啇 CUEILLE.",
    readingMnemonicFr: "TEKI - La cueillette délicate.",
    levelId: 47,
  },
  {
    character: "撤",
    meaningsFr: ["retirer", "enlever"],
    readingsOn: ["テツ"],
    readingsKun: [],
    meaningMnemonicFr: "La main 扌 avec le clou 徹 RETIRE.",
    readingMnemonicFr: "TETSU - Le retrait ordonné.",
    levelId: 48,
  },
  {
    character: "敏",
    meaningsFr: ["agile", "rapide"],
    readingsOn: ["ビン"],
    readingsKun: ["さとい"],
    meaningMnemonicFr: "Chaque 毎 action 攵 est AGILE.",
    readingMnemonicFr: "BIN - La rapidité d'esprit.",
    levelId: 44,
  },
  {
    character: "敢",
    meaningsFr: ["oser", "audacieux"],
    readingsOn: ["カン"],
    readingsKun: ["あ.えて"],
    meaningMnemonicFr: "Les actions 攵 douces 甘 OSENT.",
    readingMnemonicFr: "KAN - L'audace courageuse.",
    levelId: 46,
  },
  {
    character: "斉",
    meaningsFr: ["égal", "uniforme"],
    readingsOn: ["セイ"],
    readingsKun: ["ひと.しい"],
    meaningMnemonicFr: "Les lignes parallèles forment l'ÉGAL.",
    readingMnemonicFr: "SEI - L'uniformité parfaite.",
    levelId: 45,
  },
  {
    character: "斜",
    meaningsFr: ["oblique", "penché"],
    readingsOn: ["シャ"],
    readingsKun: ["なな.め"],
    meaningMnemonicFr: "La louche 斗 avec le reste 余 est OBLIQUE.",
    readingMnemonicFr: "SHA - L'angle penché.",
    levelId: 46,
  },
  {
    character: "旋",
    meaningsFr: ["tourner", "rotation"],
    readingsOn: ["セン"],
    readingsKun: [],
    meaningMnemonicFr: "Le drapeau 方 avec les pieds 疋 TOURNE.",
    readingMnemonicFr: "SEN - La rotation continue.",
    levelId: 47,
  },
  {
    character: "既",
    meaningsFr: ["déjà", "antérieur"],
    readingsOn: ["キ"],
    readingsKun: ["すで.に"],
    meaningMnemonicFr: "Manger 艮 le riz 旡 c'est DÉJÀ fait.",
    readingMnemonicFr: "KI - Ce qui est déjà accompli.",
    levelId: 45,
  },
  {
    character: "昇",
    meaningsFr: ["monter", "s'élever"],
    readingsOn: ["ショウ"],
    readingsKun: ["のぼ.る"],
    meaningMnemonicFr: "Le soleil 日 qui monte 升 S'ÉLÈVE.",
    readingMnemonicFr: "SHŌ - L'ascension du soleil.",
    levelId: 43,
  },
  {
    character: "昭",
    meaningsFr: ["clair", "lumineux"],
    readingsOn: ["ショウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le soleil 日 qui appelle 召 est LUMINEUX.",
    readingMnemonicFr: "SHŌ - La clarté lumineuse.",
    levelId: 44,
  },
  {
    character: "晶",
    meaningsFr: ["cristal", "clair"],
    readingsOn: ["ショウ"],
    readingsKun: [],
    meaningMnemonicFr: "Trois soleils 日 forment un CRISTAL.",
    readingMnemonicFr: "SHŌ - Le cristal brillant.",
    levelId: 45,
  },
  {
    character: "暇",
    meaningsFr: ["temps libre", "loisir"],
    readingsOn: ["カ"],
    readingsKun: ["ひま"],
    meaningMnemonicFr: "Le soleil 日 avec le faux 暇 donne du TEMPS LIBRE.",
    readingMnemonicFr: "KA - Le loisir apprécié.",
    levelId: 44,
  },
  {
    character: "暦",
    meaningsFr: ["calendrier"],
    readingsOn: ["レキ"],
    readingsKun: ["こよみ"],
    meaningMnemonicFr: "Le soleil 日 avec l'histoire 厤 forme le CALENDRIER.",
    readingMnemonicFr: "REKI - Le calendrier annuel.",
    levelId: 46,
  },
  {
    character: "朗",
    meaningsFr: ["clair", "joyeux"],
    readingsOn: ["ロウ"],
    readingsKun: ["ほが.らか"],
    meaningMnemonicFr: "Le bon 良 avec la lune 月 est JOYEUX.",
    readingMnemonicFr: "RŌ - La joie lumineuse.",
    levelId: 44,
  },
  {
    character: "枝",
    meaningsFr: ["branche"],
    readingsOn: ["シ"],
    readingsKun: ["えだ"],
    meaningMnemonicFr: "L'arbre 木 qui se divise 支 a des BRANCHES.",
    readingMnemonicFr: "SHI - La branche de l'arbre.",
    levelId: 42,
  },
  {
    character: "枠",
    meaningsFr: ["cadre", "limite"],
    readingsOn: [],
    readingsKun: ["わく"],
    meaningMnemonicFr: "L'arbre 木 avec neuf 九 et dix 十 forme un CADRE.",
    readingMnemonicFr: "WAKU - Le cadre délimité.",
    levelId: 46,
  },
  {
    character: "柄",
    meaningsFr: ["manche", "motif"],
    readingsOn: ["ヘイ"],
    readingsKun: ["がら", "え"],
    meaningMnemonicFr: "L'arbre 木 avec l'interne 丙 forme un MANCHE.",
    readingMnemonicFr: "HEI - Le manche en bois.",
    levelId: 45,
  },
  {
    character: "栄",
    meaningsFr: ["prospérité", "gloire"],
    readingsOn: ["エイ"],
    readingsKun: ["さか.える"],
    meaningMnemonicFr: "Le feu 火 sur l'arbre 木 symbolise la PROSPÉRITÉ.",
    readingMnemonicFr: "EI - La gloire brillante.",
    levelId: 43,
  },
  {
    character: "核",
    meaningsFr: ["noyau", "central"],
    readingsOn: ["カク"],
    readingsKun: [],
    meaningMnemonicFr: "L'arbre 木 avec le bébé 亥 a un NOYAU.",
    readingMnemonicFr: "KAKU - Le noyau central.",
    levelId: 44,
  },
  {
    character: "栓",
    meaningsFr: ["bouchon", "robinet"],
    readingsOn: ["セン"],
    readingsKun: [],
    meaningMnemonicFr: "L'arbre 木 complet 全 est un BOUCHON.",
    readingMnemonicFr: "SEN - Le bouchon en bois.",
    levelId: 47,
  },
  {
    character: "棄",
    meaningsFr: ["abandonner", "rejeter"],
    readingsOn: ["キ"],
    readingsKun: ["す.てる"],
    meaningMnemonicFr: "L'arbre 木 avec les deux mains 廾 et le bébé 亠厶 ABANDONNE.",
    readingMnemonicFr: "KI - L'abandon définitif.",
    levelId: 48,
  },
];

async function main() {
  console.log("Seeding FINAL kanji batch 9 to exceed 2000...");

  for (const kanji of kanjiData) {
    await prisma.kanji.upsert({
      where: { character: kanji.character },
      update: {
        meaningsFr: kanji.meaningsFr,
        readingsOn: kanji.readingsOn,
        readingsKun: kanji.readingsKun,
        meaningMnemonicFr: kanji.meaningMnemonicFr,
        readingMnemonicFr: kanji.readingMnemonicFr,
        levelId: kanji.levelId,
      },
      create: kanji,
    });
  }

  console.log(`Seeded ${kanjiData.length} kanji.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
