import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// LAST PUSH - targeting 35 unique kanji to exceed 2000

const kanjiData = [
  {
    character: "逮",
    meaningsFr: ["arrêter", "capturer"],
    readingsOn: ["タイ"],
    readingsKun: [],
    meaningMnemonicFr: "Marcher 辶 avec l'oreille 隶 ARRÊTE.",
    readingMnemonicFr: "TAI - L'arrestation réussie.",
    levelId: 47,
  },
  {
    character: "逸",
    meaningsFr: ["échapper", "excellent"],
    readingsOn: ["イツ"],
    readingsKun: [],
    meaningMnemonicFr: "Marcher 辶 avec le lapin 兔 ÉCHAPPE.",
    readingMnemonicFr: "ITSU - L'excellence qui s'échappe.",
    levelId: 48,
  },
  {
    character: "遂",
    meaningsFr: ["accomplir", "finalement"],
    readingsOn: ["スイ"],
    readingsKun: ["と.げる"],
    meaningMnemonicFr: "Marcher 辶 avec le cochon 㒸 ACCOMPLIT.",
    readingMnemonicFr: "SUI - L'accomplissement final.",
    levelId: 49,
  },
  {
    character: "遇",
    meaningsFr: ["rencontrer", "traiter"],
    readingsOn: ["グウ"],
    readingsKun: ["あ.う"],
    meaningMnemonicFr: "Marcher 辶 vers l'angle 禺 pour RENCONTRER.",
    readingMnemonicFr: "GŪ - La rencontre fortuite.",
    levelId: 47,
  },
  {
    character: "遍",
    meaningsFr: ["partout", "répandu"],
    readingsOn: ["ヘン"],
    readingsKun: ["あまね.く"],
    meaningMnemonicFr: "Marcher 辶 avec le plat 扁 est PARTOUT.",
    readingMnemonicFr: "HEN - La diffusion universelle.",
    levelId: 48,
  },
  {
    character: "遅",
    meaningsFr: ["tard", "lent"],
    readingsOn: ["チ"],
    readingsKun: ["おく.れる", "おそ.い"],
    meaningMnemonicFr: "Marcher 辶 avec le mouton 犀 est TARD.",
    readingMnemonicFr: "CHI - Le retard accumulé.",
    levelId: 44,
  },
  {
    character: "遠",
    meaningsFr: ["loin", "distant"],
    readingsOn: ["エン", "オン"],
    readingsKun: ["とお.い"],
    meaningMnemonicFr: "Marcher 辶 avec le vêtement 袁 va LOIN.",
    readingMnemonicFr: "EN - La distance lointaine.",
    levelId: 37,
  },
  {
    character: "避",
    meaningsFr: ["éviter", "fuir"],
    readingsOn: ["ヒ"],
    readingsKun: ["さ.ける"],
    meaningMnemonicFr: "Marcher 辶 avec le roi 辟 ÉVITE.",
    readingMnemonicFr: "HI - L'évitement prudent.",
    levelId: 46,
  },
  {
    character: "邦",
    meaningsFr: ["pays", "nation"],
    readingsOn: ["ホウ"],
    readingsKun: ["くに"],
    meaningMnemonicFr: "Le riche 丰 avec la ville 阝 est un PAYS.",
    readingMnemonicFr: "HŌ - La nation prospère.",
    levelId: 46,
  },
  {
    character: "郊",
    meaningsFr: ["banlieue", "environs"],
    readingsOn: ["コウ"],
    readingsKun: [],
    meaningMnemonicFr: "La croix 交 avec la ville 阝 est la BANLIEUE.",
    readingMnemonicFr: "KŌ - Les environs de la ville.",
    levelId: 45,
  },
  {
    character: "郎",
    meaningsFr: ["homme", "monsieur"],
    readingsOn: ["ロウ"],
    readingsKun: [],
    meaningMnemonicFr: "Le bon 良 avec la ville 阝 est un HOMME.",
    readingMnemonicFr: "RŌ - Le jeune homme.",
    levelId: 44,
  },
  {
    character: "郡",
    meaningsFr: ["district", "comté"],
    readingsOn: ["グン"],
    readingsKun: [],
    meaningMnemonicFr: "Le seigneur 君 avec la ville 阝 est un DISTRICT.",
    readingMnemonicFr: "GUN - Le comté administré.",
    levelId: 46,
  },
  {
    character: "郷",
    meaningsFr: ["village natal", "campagne"],
    readingsOn: ["キョウ", "ゴウ"],
    readingsKun: ["さと"],
    meaningMnemonicFr: "Les gens qui se saluent 卿 forment le VILLAGE NATAL.",
    readingMnemonicFr: "KYŌ - La campagne natale.",
    levelId: 47,
  },
  {
    character: "酔",
    meaningsFr: ["ivre", "enivré"],
    readingsOn: ["スイ"],
    readingsKun: ["よ.う"],
    meaningMnemonicFr: "L'alcool 酉 avec le neuf 卒 rend IVRE.",
    readingMnemonicFr: "SUI - L'ivresse légère.",
    levelId: 45,
  },
  {
    character: "釈",
    meaningsFr: ["expliquer", "libérer"],
    readingsOn: ["シャク"],
    readingsKun: [],
    meaningMnemonicFr: "La cueillette 采 qui change 尺 EXPLIQUE.",
    readingMnemonicFr: "SHAKU - L'explication claire.",
    levelId: 46,
  },
  {
    character: "鋭",
    meaningsFr: ["aigu", "pointu"],
    readingsOn: ["エイ"],
    readingsKun: ["するど.い"],
    meaningMnemonicFr: "Le métal 金 qui parle 兌 est AIGU.",
    readingMnemonicFr: "EI - La pointe acérée.",
    levelId: 45,
  },
  {
    character: "鋼",
    meaningsFr: ["acier"],
    readingsOn: ["コウ"],
    readingsKun: ["はがね"],
    meaningMnemonicFr: "Le métal 金 avec le filet 岡 est l'ACIER.",
    readingMnemonicFr: "KŌ - L'acier trempé.",
    levelId: 46,
  },
  {
    character: "錬",
    meaningsFr: ["forger", "tempérer"],
    readingsOn: ["レン"],
    readingsKun: ["ね.る"],
    meaningMnemonicFr: "Le métal 金 de l'est 東 se FORGE.",
    readingMnemonicFr: "REN - Le forgeage expert.",
    levelId: 47,
  },
  {
    character: "錯",
    meaningsFr: ["erreur", "mélange"],
    readingsOn: ["サク"],
    readingsKun: [],
    meaningMnemonicFr: "Le métal 金 du passé 昔 cause une ERREUR.",
    readingMnemonicFr: "SAKU - L'erreur commise.",
    levelId: 48,
  },
  {
    character: "録",
    meaningsFr: ["enregistrer", "copier"],
    readingsOn: ["ロク"],
    readingsKun: [],
    meaningMnemonicFr: "Le métal 金 avec l'eau 彔 ENREGISTRE.",
    readingMnemonicFr: "ROKU - L'enregistrement conservé.",
    levelId: 43,
  },
  {
    character: "鏡",
    meaningsFr: ["miroir"],
    readingsOn: ["キョウ"],
    readingsKun: ["かがみ"],
    meaningMnemonicFr: "Le métal 金 de la capitale 竟 est un MIROIR.",
    readingMnemonicFr: "KYŌ - Le miroir réfléchissant.",
    levelId: 44,
  },
  {
    character: "閉",
    meaningsFr: ["fermer"],
    readingsOn: ["ヘイ"],
    readingsKun: ["し.める", "と.じる"],
    meaningMnemonicFr: "La porte 門 avec le talent 才 se FERME.",
    readingMnemonicFr: "HEI - La fermeture définitive.",
    levelId: 42,
  },
  {
    character: "閑",
    meaningsFr: ["loisir", "tranquille"],
    readingsOn: ["カン"],
    readingsKun: [],
    meaningMnemonicFr: "La porte 門 avec l'arbre 木 apporte le LOISIR.",
    readingMnemonicFr: "KAN - La tranquillité appréciée.",
    levelId: 47,
  },
  {
    character: "閣",
    meaningsFr: ["cabinet", "pavillon"],
    readingsOn: ["カク"],
    readingsKun: [],
    meaningMnemonicFr: "La porte 門 avec chaque 各 forme un CABINET.",
    readingMnemonicFr: "KAKU - Le pavillon officiel.",
    levelId: 46,
  },
  {
    character: "閥",
    meaningsFr: ["clique", "faction"],
    readingsOn: ["バツ"],
    readingsKun: [],
    meaningMnemonicFr: "La porte 門 qui coupe 伐 forme une FACTION.",
    readingMnemonicFr: "BATSU - La clique politique.",
    levelId: 49,
  },
  {
    character: "闘",
    meaningsFr: ["combat", "lutter"],
    readingsOn: ["トウ"],
    readingsKun: ["たたか.う"],
    meaningMnemonicFr: "La porte 門 avec la louche 斗 COMBAT.",
    readingMnemonicFr: "TŌ - Le combat acharné.",
    levelId: 45,
  },
  {
    character: "阻",
    meaningsFr: ["empêcher", "bloquer"],
    readingsOn: ["ソ"],
    readingsKun: ["はば.む"],
    meaningMnemonicFr: "La colline 阝 avec l'ancêtre 且 EMPÊCHE.",
    readingMnemonicFr: "SO - L'obstacle bloquant.",
    levelId: 46,
  },
  {
    character: "附",
    meaningsFr: ["attacher", "joindre"],
    readingsOn: ["フ"],
    readingsKun: ["つ.ける"],
    meaningMnemonicFr: "La colline 阝 avec le plat 付 ATTACHE.",
    readingMnemonicFr: "FU - L'attachement solide.",
    levelId: 47,
  },
  {
    character: "陣",
    meaningsFr: ["formation", "camp"],
    readingsOn: ["ジン"],
    readingsKun: [],
    meaningMnemonicFr: "La colline 阝 avec le véhicule 車 forme une FORMATION.",
    readingMnemonicFr: "JIN - La formation militaire.",
    levelId: 45,
  },
  {
    character: "陥",
    meaningsFr: ["tomber", "piège"],
    readingsOn: ["カン"],
    readingsKun: ["おちい.る", "おとしい.れる"],
    meaningMnemonicFr: "La colline 阝 qui manque 臽 devient un PIÈGE.",
    readingMnemonicFr: "KAN - Le piège tendu.",
    levelId: 47,
  },
  {
    character: "隆",
    meaningsFr: ["prospère", "élevé"],
    readingsOn: ["リュウ"],
    readingsKun: [],
    meaningMnemonicFr: "La colline 阝 avec la marche 降 est PROSPÈRE.",
    readingMnemonicFr: "RYŪ - La prospérité croissante.",
    levelId: 46,
  },
  {
    character: "隔",
    meaningsFr: ["séparer", "intervalle"],
    readingsOn: ["カク"],
    readingsKun: ["へだ.てる"],
    meaningMnemonicFr: "La colline 阝 avec le client 鬲 SÉPARE.",
    readingMnemonicFr: "KAKU - L'intervalle entre deux.",
    levelId: 47,
  },
  {
    character: "隠",
    meaningsFr: ["cacher", "dissimuler"],
    readingsOn: ["イン", "オン"],
    readingsKun: ["かく.す", "かく.れる"],
    meaningMnemonicFr: "La colline 阝 avec le cœur 㥯 SE CACHE.",
    readingMnemonicFr: "IN - La dissimulation totale.",
    levelId: 46,
  },
  {
    character: "隣",
    meaningsFr: ["voisin", "adjacent"],
    readingsOn: ["リン"],
    readingsKun: ["となり", "とな.る"],
    meaningMnemonicFr: "La colline 阝 avec le riz 粦 est le VOISIN.",
    readingMnemonicFr: "RIN - Le voisin proche.",
    levelId: 45,
  },
  {
    character: "雅",
    meaningsFr: ["élégant", "raffiné"],
    readingsOn: ["ガ"],
    readingsKun: ["みや.び"],
    meaningMnemonicFr: "L'oiseau 牙 avec la dent 隹 est ÉLÉGANT.",
    readingMnemonicFr: "GA - L'élégance raffinée.",
    levelId: 47,
  },
];

async function main() {
  console.log("Seeding LAST PUSH kanji batch to exceed 2000...");

  for (const kanji of kanjiData) {
    await prisma.kanji.upsert({
      where: { character: kanji.character },
      update: {
        meaningsFr: kanji.meaningsFr,
        readingsOn: kanji.readingsOn,
        readingsKun: kanji.readingsKun,
        meaningMnemonicFr: kanji.meaningMnemonicFr,
        readingMnemonicFr: kanji.readingMnemonicFr,
        levelId: kanji.levelId,
      },
      create: kanji,
    });
  }

  console.log(`Seeded ${kanjiData.length} kanji.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
